<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Virtualmin.name'] = "virtualmin";
$lang['Virtualmin.module_row'] = "server";
$lang['Virtualmin.module_row_plural'] = "Server";
$lang['Virtualmin.module_group'] = "Gruppo di server";
$lang['Virtualmin.tab_stats'] = "statistiche";
$lang['Virtualmin.tab_client_actions'] = "Azioni";
$lang['Virtualmin.add_module_row'] = "Aggiungi server";
$lang['Virtualmin.add_module_group'] = "Aggiungi gruppo di server";
$lang['Virtualmin.manage.module_rows_title'] = "Server";
$lang['Virtualmin.manage.module_groups_title'] = "Gruppi di server";
$lang['Virtualmin.manage.module_rows_heading.name'] = "Etichetta del server";
$lang['Virtualmin.manage.module_rows_heading.hostname'] = "hostname";
$lang['Virtualmin.manage.module_rows_heading.port'] = "Porta";
$lang['Virtualmin.manage.module_rows_heading.accounts'] = "Conti";
$lang['Virtualmin.manage.module_rows_heading.options'] = "Opzioni";
$lang['Virtualmin.manage.module_groups_heading.name'] = "Nome del gruppo";
$lang['Virtualmin.manage.module_groups_heading.servers'] = "Conteggio server";
$lang['Virtualmin.manage.module_groups_heading.options'] = "Opzioni";
$lang['Virtualmin.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Virtualmin.manage.module_rows.edit'] = "Modificare";
$lang['Virtualmin.manage.module_groups.edit'] = "Modificare";
$lang['Virtualmin.manage.module_rows.delete'] = "Eliminare";
$lang['Virtualmin.manage.module_groups.delete'] = "Eliminare";
$lang['Virtualmin.manage.module_rows.confirm_delete'] = "Sei sicuro di voler eliminare questo server?";
$lang['Virtualmin.manage.module_groups.confirm_delete'] = "Sei sicuro di voler eliminare questo gruppo di server?";
$lang['Virtualmin.manage.module_rows_no_results'] = "Non ci sono server.";
$lang['Virtualmin.manage.module_groups_no_results'] = "Non sono presenti gruppi di server.";
$lang['Virtualmin.order_options.first'] = "Primo server non completo";
$lang['Virtualmin.add_row.box_title'] = "Aggiungi il server VirtualMin";
$lang['Virtualmin.add_row.basic_title'] = "Impostazioni di base";
$lang['Virtualmin.add_row.add_btn'] = "Aggiungi server";
$lang['Virtualmin.edit_row.box_title'] = "Modifica il server VirtualMin";
$lang['Virtualmin.edit_row.basic_title'] = "Impostazioni di base";
$lang['Virtualmin.edit_row.add_btn'] = "Modifica server";
$lang['Virtualmin.row_meta.server_name'] = "Etichetta del server";
$lang['Virtualmin.row_meta.host_name'] = "Nome host";
$lang['Virtualmin.row_meta.user_name'] = "Nome utente";
$lang['Virtualmin.row_meta.password'] = "Parola d'ordine";
$lang['Virtualmin.row_meta.port'] = "Porta";
$lang['Virtualmin.row_meta.use_ssl'] = "Utilizzare SSL quando ci si collega all'API (consigliato)";
$lang['Virtualmin.row_meta.account_limit'] = "Limite del conto";
$lang['Virtualmin.package_fields.plan'] = "Piano VirtualMin";
$lang['Virtualmin.package_fields.template'] = "Modello VirtualMin";
$lang['Virtualmin.service_field.domain'] = "Dominio";
$lang['Virtualmin.service_field.username'] = "Nome utente";
$lang['Virtualmin.service_field.password'] = "Parola d'ordine";
$lang['Virtualmin.service_field.confirm_password'] = "Conferma password";
$lang['Virtualmin.tab_client_actions.change_password'] = "Cambiare la password";
$lang['Virtualmin.tab_client_actions.field_virtualmin_password'] = "Parola d'ordine";
$lang['Virtualmin.tab_client_actions.field_virtualmin_confirm_password'] = "Conferma password";
$lang['Virtualmin.tab_client_actions.field_password_submit'] = "Aggiorna password";
$lang['Virtualmin.tab_stats.info_title'] = "Informazione";
$lang['Virtualmin.tab_stats.info_heading.field'] = "Campo";
$lang['Virtualmin.tab_stats.info_heading.value'] = "Valore";
$lang['Virtualmin.tab_stats.info.disk_used'] = "Disco utilizzato";
$lang['Virtualmin.tab_stats.info.databases_size'] = "Dimensioni del database";
$lang['Virtualmin.tab_stats.info.databases_count'] = "Conteggio database";
$lang['Virtualmin.tab_stats.info.maximum_databases'] = "Numero massimo di database";
$lang['Virtualmin.tab_stats.info.maximum_mailboxes'] = "Numero massimo di cassette postali";
$lang['Virtualmin.service_info.username'] = "Nome utente";
$lang['Virtualmin.service_info.password'] = "Parola d'ordine";
$lang['Virtualmin.service_info.server'] = "server";
$lang['Virtualmin.service_info.options'] = "Opzioni";
$lang['Virtualmin.service_info.option_login'] = "Login";
$lang['Virtualmin.service_field.tooltip.username'] = "Puoi lasciare vuoto il nome utente per generarne uno automaticamente.";
$lang['Virtualmin.service_field.tooltip.password'] = "Puoi lasciare vuota la password per generarne una automaticamente.";
$lang['Virtualmin.!error.server_name_valid'] = "È necessario inserire un'etichetta server.";
$lang['Virtualmin.!error.host_name_valid'] = "Il nome host sembra non essere valido.";
$lang['Virtualmin.!error.user_name_valid'] = "Il nome utente sembra non essere valido.";
$lang['Virtualmin.!error.port_valid'] = "La porta sembra non essere valida.";
$lang['Virtualmin.!error.password_valid'] = "La password sembra non essere valida.";
$lang['Virtualmin.!error.account_limit_valid'] = "Inserisci un limite di account valido.";
$lang['Virtualmin.!error.meta[plan].empty'] = "È richiesto un piano VirtualMin.";
$lang['Virtualmin.!error.meta[template].empty'] = "È richiesto un modello VirtualMin.";
$lang['Virtualmin.!error.api.internal'] = "Si è verificato un errore interno o il server non ha risposto alla richiesta.";
$lang['Virtualmin.!error.module_row.missing'] = "Si è verificato un errore interno. La riga del modulo non è disponibile.";
$lang['Virtualmin.!error.virtualmin_domain.format'] = "Inserisci un nome di dominio valido, ad es. domain.com.";
$lang['Virtualmin.!error.virtualmin_domain.test'] = "Il nome di dominio non può iniziare con \"test\".";
$lang['Virtualmin.!error.virtualmin_username.format'] = "Il nome utente può contenere solo lettere e numeri e non può iniziare con un numero.";
$lang['Virtualmin.!error.virtualmin_username.test'] = "Il nome utente non può iniziare con \"test\".";
$lang['Virtualmin.!error.virtualmin_username.length'] = "Il nome utente deve avere una lunghezza da 1 a 16 caratteri.";
$lang['Virtualmin.!error.virtualmin_password.valid'] = "La password deve contenere almeno 8 caratteri.";
$lang['Virtualmin.description'] = "Virtualmin è un pannello di controllo di hosting di domini e siti Web, che offre la possibilità di creare e gestire molti domini ed è disponibile sia in versione open source che commerciale. Si basa su Webmin.";
$lang['Virtualmin.!error.password_valid_connection'] = "Non è stato possibile stabilire una connessione al server. Verificare che il nome host, il nome utente, la password e la porta siano corretti.";
?>