<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Eway.!error.customer_id.empty'] = "Inserisci il tuo ID cliente eWAY.";
$lang['Eway.!error.customer_id.length'] = "L'ID cliente non può superare gli 8 caratteri.";
$lang['Eway.!error.developer_mode.valid'] = "La modalità sviluppatore deve essere impostata su \"true\" se fornita.";
$lang['Eway.!error.test_mode.valid'] = "La modalità test deve essere impostata su \"true\" se fornita.";
$lang['Eway.!error.refund_password.empty'] = "È necessario impostare una password per il rimborso per poter elaborare i rimborsi tramite eWAY.";
$lang['Eway.!error.libxml_required'] = "Per questo gateway sono richieste le estensioni libxml e simplexml.";
$lang['Eway.!error.invalid_xml'] = "Il gateway ha risposto con un XML non valido.";
$lang['Eway.name'] = "eWAY";
$lang['Eway.customer_id'] = "identificativo del cliente";
$lang['Eway.refund_password'] = "Recupero password";
$lang['Eway.developer_mode'] = "Modalità sviluppatore";
$lang['Eway.test_mode'] = "Modalità di test";
$lang['Eway.tooltip_refund_password'] = "Inserisci la password di rimborso che hai impostato nel tuo account eWAY. Questa non è la password del tuo account eWAY. È necessario impostare una password per il rimborso per poter elaborare i rimborsi tramite eWAY.";
$lang['Eway.tooltip_developer_mode'] = "Abilitando questa opzione le transazioni verranno registrate nell'ambiente sandbox eWAY. Per utilizzare questo ambiente è necessario disporre di un account di prova sandbox.";
$lang['Eway.tooltip_test_mode'] = "La modalità test utilizzerà un account di prova eWAY con un numero di carta di credito di prova indipendentemente da ciò che inserisci. Per ulteriori informazioni sulla modalità test in eWAY consultare il manuale.";
$lang['Eway.description'] = "eWAY rappresenta il 25% del mercato online australiano e commercia in 5 paesi. Elabora pagamenti per miliardi di dollari ogni anno in tutto il mondo per decine di migliaia di aziende";
?>