<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.service_updated'] = "Il prezzo del servizio è stato aggiornato con successo.";
$lang['AdminMain.!warning.reassign_pricing'] = "La Riassegnazione prezzi cambia solo il pacchetto e i prezzi associati a questo servizio. Non eseguire questa azione per gli aggiornamenti o downgrade.";
$lang['AdminMain.index.page_title'] = "Cliente n. %1\$s Riassegna i prezzi"; // %1$s is the client ID code
$lang['AdminMain.index.boxtitle_services'] = "Servizi per il cliente n.%1\$s"; // %1$s is the client ID code
$lang['AdminMain.index.link_client'] = "Torna al cliente n. %1\$s"; // %1$s is the client ID code
$lang['AdminMain.index.heading_package'] = "Pacchetto";
$lang['AdminMain.index.heading_label'] = "Etichetta";
$lang['AdminMain.index.heading_term'] = "Termine";
$lang['AdminMain.index.heading_date_created'] = "data di creazione";
$lang['AdminMain.index.heading_date_renews'] = "Data di rinnovo";
$lang['AdminMain.index.heading_options'] = "Opzioni";
$lang['AdminMain.index.recurring_term'] = "%1\$s %2\$s @ %3\$s"; // %1$s is the term, %2$s is the period, %3$s is the renewal price
$lang['AdminMain.index.text_never'] = "Mai";
$lang['AdminMain.index.no_results'] = "Non sono disponibili servizi da cui riassegnare i prezzi.";
$lang['AdminMain.index.option_service'] = "Riassegnare i prezzi";
$lang['AdminMain.service.term_onetime'] = "Una volta - %3\$s"; // %1$s is the pricing term, %2$s is the pricing period, and %3$s is the formatted price
$lang['AdminMain.service.term'] = "%1\$s %2\$s - %3\$s"; // %1$s is the pricing term, %2$s is the pricing period, and %3$s is the formatted price
$lang['AdminMain.service.boxtitle_pricing'] = "Riassegna prezzo per il servizio: %1\$s - %2\$s"; // %1$s is the package name, %2$s is the service name
$lang['AdminMain.service.heading_information'] = "Informazione Servizio";
$lang['AdminMain.service.text_package_name'] = "Nome del pacchetto:";
$lang['AdminMain.service.text_label'] = "Etichetta:";
$lang['AdminMain.service.text_qty'] = "Quantità:";
$lang['AdminMain.service.text_term'] = "Termine:";
$lang['AdminMain.service.text_status'] = "Nome del pacchetto:";
$lang['AdminMain.service.text_date_added'] = "Data aggiunta:";
$lang['AdminMain.service.text_date_renews'] = "Data di rinnovo:";
$lang['AdminMain.service.text_recurring_coupon'] = "Coupon ricorrente:";
$lang['AdminMain.service.text_coupon_percent'] = "%1\$s (%2\$s%%)"; // %1$s is the coupon code, %2$s is the coupon discount percentage. You MUST use two % signs to represent a single percent (i.e. %%)
$lang['AdminMain.service.text_coupon_amount'] = "%1\$s (%2\$s)"; // %1$s is the coupon code, %2$s is the formatted coupon amount
$lang['AdminMain.service.text_renewal_price'] = "Prezzo di rinnovo:";
$lang['AdminMain.service.heading_pricing'] = "Riassegnare i prezzi";
$lang['AdminMain.service.field_pricing'] = "Pacchetto/Durata";
$lang['AdminMain.service.field_cancel'] = "Cancella";
$lang['AdminMain.service.field_submit'] = "Salva";
$lang['AdminMain.service.field_group'] = "Gruppo di pacchetti";
?>