<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ImportManagerPlugin.name'] = "Responsabile delle importazioni";
$lang['ImportManagerPlugin.description'] = "Importa i tuoi dati da un altro sistema in Blesta.";
?>