<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cyberpanel.name'] = "CyberPanel";
$lang['Cyberpanel.module_row'] = "server";
$lang['Cyberpanel.module_row_plural'] = "Server";
$lang['Cyberpanel.module_group'] = "Gruppo di Server";
$lang['Cyberpanel.tab_client_actions'] = "Azioni";
$lang['Cyberpanel.add_module_row'] = "Aggiungi server";
$lang['Cyberpanel.add_module_group'] = "Aggiungi gruppo di server";
$lang['Cyberpanel.manage.module_rows_title'] = "Server";
$lang['Cyberpanel.manage.module_groups_title'] = "Gruppi di server";
$lang['Cyberpanel.manage.module_rows_heading.name'] = "Etichetta Server";
$lang['Cyberpanel.manage.module_rows_heading.hostname'] = "Nome host";
$lang['Cyberpanel.manage.module_rows_heading.options'] = "Opzioni";
$lang['Cyberpanel.manage.module_groups_heading.name'] = "Nome del gruppo";
$lang['Cyberpanel.manage.module_groups_heading.servers'] = "Conteggio server";
$lang['Cyberpanel.manage.module_groups_heading.options'] = "Opzioni";
$lang['Cyberpanel.manage.module_rows.edit'] = "Modifica";
$lang['Cyberpanel.manage.module_groups.edit'] = "Modificare";
$lang['Cyberpanel.manage.module_rows.delete'] = "Eliminare";
$lang['Cyberpanel.manage.module_groups.delete'] = "Eliminare";
$lang['Cyberpanel.manage.module_rows.confirm_delete'] = "Sei sicuro di voler eliminare questo server?";
$lang['Cyberpanel.manage.module_groups.confirm_delete'] = "Sei sicuro di voler eliminare questo gruppo di server?";
$lang['Cyberpanel.manage.module_rows_no_results'] = "Non ci sono server.";
$lang['Cyberpanel.manage.module_groups_no_results'] = "Non sono presenti gruppi di server.";
$lang['Cyberpanel.order_options.first'] = "Primo server non completo";
$lang['Cyberpanel.order_options.roundrobin'] = "Distribuire uniformemente tra i server";
$lang['Cyberpanel.add_row.box_title'] = "Aggiungi CyberPanel Server";
$lang['Cyberpanel.add_row.basic_title'] = "Impostazioni di base";
$lang['Cyberpanel.add_row.name_servers_title'] = "Server dei nomi";
$lang['Cyberpanel.add_row.notes_title'] = "Appunti";
$lang['Cyberpanel.add_row.name_server_btn'] = "Aggiungi ulteriore server dei nomi";
$lang['Cyberpanel.add_row.name_server_col'] = "Server dei nomi";
$lang['Cyberpanel.add_row.name_server_host_col'] = "Nome host";
$lang['Cyberpanel.add_row.name_server'] = "Server dei nomi %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Cyberpanel.add_row.remove_name_server'] = "Rimuovere";
$lang['Cyberpanel.add_row.add_btn'] = "Aggiungi server";
$lang['Cyberpanel.edit_row.box_title'] = "Modifica server CyberPanel";
$lang['Cyberpanel.edit_row.basic_title'] = "Impostazioni di base";
$lang['Cyberpanel.edit_row.name_servers_title'] = "Server dei nomi";
$lang['Cyberpanel.edit_row.notes_title'] = "Appunti";
$lang['Cyberpanel.edit_row.name_server_btn'] = "Aggiungi ulteriore server dei nomi";
$lang['Cyberpanel.edit_row.name_server_col'] = "Server dei nomi";
$lang['Cyberpanel.edit_row.name_server_host_col'] = "Nome host";
$lang['Cyberpanel.edit_row.name_server'] = "Server dei nomi %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Cyberpanel.edit_row.remove_name_server'] = "View the Google Translation";
$lang['Cyberpanel.edit_row.add_btn'] = "Modifica server";
$lang['Cyberpanel.row_meta.server_name'] = "Etichetta del server";
$lang['Cyberpanel.row_meta.host_name'] = "Nome host";
$lang['Cyberpanel.row_meta.admin_username'] = "Nome utente amministratore";
$lang['Cyberpanel.row_meta.admin_password'] = "Password dell'amministratore";
$lang['Cyberpanel.row_meta.use_ssl'] = "Usa SSL per la connessione all'API (consigliato)";
$lang['Cyberpanel.package_fields.package'] = "Nome del pacchetto";
$lang['Cyberpanel.service_field.domain'] = "Dominio";
$lang['Cyberpanel.service_field.username'] = "Nome utente";
$lang['Cyberpanel.service_field.password'] = "Parola d'ordine";
$lang['Cyberpanel.tab_client_actions.change_password'] = "Cambiare la password";
$lang['Cyberpanel.tab_client_actions.field_cyberpanel_password'] = "Parola d'ordine";
$lang['Cyberpanel.tab_client_actions.field_cyberpanel_confirm_password'] = "Conferma password";
$lang['Cyberpanel.tab_client_actions.field_password_submit'] = "Aggiorna password";
$lang['Cyberpanel.service_info.username'] = "Nome utente";
$lang['Cyberpanel.service_info.password'] = "Parola d'ordine";
$lang['Cyberpanel.service_info.server'] = "server";
$lang['Cyberpanel.service_info.options'] = "Opzioni";
$lang['Cyberpanel.service_info.option_login'] = "Login";
$lang['Cyberpanel.service_field.tooltip.username'] = "Puoi lasciare vuoto il nome utente per generarne uno automaticamente.";
$lang['Cyberpanel.service_field.tooltip.password'] = "Puoi lasciare vuota la password per generarne una automaticamente.";
$lang['Cyberpanel.!error.server_name_valid'] = "È necessario inserire un'etichetta server.";
$lang['Cyberpanel.!error.host_name_valid'] = "Il nome host sembra non essere valido.";
$lang['Cyberpanel.!error.remote_admin_username_valid'] = "Il nome utente amministratore sembra non essere valido.";
$lang['Cyberpanel.!error.remote_admin_password_valid'] = "La password dell'amministratore sembra non essere valida.";
$lang['Cyberpanel.!error.remote_admin_password_valid_connection'] = "Non è stato possibile stabilire una connessione al server. Verifica che il nome host e la password amministratore siano corretti.";
$lang['Cyberpanel.!error.name_servers_valid'] = "Uno o più server dei nomi inseriti non sono validi.";
$lang['Cyberpanel.!error.name_servers_count'] = "È necessario definire almeno 2 server dei nomi.";
$lang['Cyberpanel.!error.meta[package].empty'] = "È richiesto un pacchetto CyberPanel.";
$lang['Cyberpanel.!error.api.internal'] = "Si è verificato un errore interno oppure il server non ha risposto alla richiesta.";
$lang['Cyberpanel.!error.module_row.missing'] = "Si è verificato un errore interno. La riga del modulo non è disponibile.";
$lang['Cyberpanel.!error.cyberpanel_domain.format'] = "Inserisci un nome di dominio valido, ad es. dominio.com.";
$lang['Cyberpanel.!error.cyberpanel_domain.test'] = "Il nome di dominio non può iniziare con \"test\".";
$lang['Cyberpanel.!error.cyberpanel_username.format'] = "Il nome utente può contenere solo lettere e numeri e non può iniziare con un numero.";
$lang['Cyberpanel.!error.cyberpanel_username.test'] = "Il nome utente non può iniziare con \"test\".";
$lang['Cyberpanel.!error.cyberpanel_username.length'] = "Il nome utente deve avere una lunghezza compresa tra 1 e 16 caratteri.";
$lang['Cyberpanel.!error.cyberpanel_password.valid'] = "La password deve contenere almeno 8 caratteri.";
$lang['Cyberpanel.!error.cyberpanel_password.matches'] = "Password e Conferma password non corrispondono.";
$lang['Cyberpanel.description'] = "CyberPanel è un pannello di controllo hosting di nuova generazione basato su OpenLiteSpeed. Costruito per velocità, sicurezza e affidabilità.";
?>