<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Blesta2_5.!error.host.invalid'] = "L'host del database è obbligatorio.";
$lang['Blesta2_5.!error.database.invalid'] = "Il nome del database è obbligatorio.";
$lang['Blesta2_5.!error.user.invalid'] = "L'utente del database è obbligatorio.";
$lang['Blesta2_5.!error.pass.invalid'] = "È richiesta la password del database.";
$lang['Blesta2_5.!error.key.invalid'] = "È richiesta una AESKEY valida.";
$lang['Blesta2_5.settings.host'] = "Host della banca dati";
$lang['Blesta2_5.settings.database'] = "Nome del database";
$lang['Blesta2_5.settings.user'] = "Utente del database";
$lang['Blesta2_5.settings.pass'] = "Password del database";
$lang['Blesta2_5.settings.key'] = "AESKEY";
$lang['Blesta2_5.settings.key.info'] = "Immettere il valore di AESKEY definito in / inc/config.php. Questo dovrebbe avere una lunghezza di 32 caratteri.";
$lang['Blesta2_5.configuration.create_packages_true'] = "Crea automaticamente tutti i pacchetti necessari durante l'importazione";
$lang['Blesta2_5.configuration.create_packages_false'] = "Mappare manualmente i pacchetti";
$lang['Blesta2_5.configuration.local_package'] = "Pacchetto locale";
$lang['Blesta2_5.configuration.remote_package'] = "Pacchetto remoto";
$lang['Blesta2_5.configuration.no_local_packages'] = "È necessario creare pacchetti prima di poterli mappare.";
?>