<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Pagseguro.name'] = "PagSeguro";
$lang['Pagseguro.email_id'] = "E-mail";
$lang['Pagseguro.email_note'] = "Inserisci l'indirizzo email del tuo account PagSeguro.";
$lang['Pagseguro.token'] = "Gettone";
$lang['Pagseguro.token_note'] = "Inserisci il token di sicurezza creato nel tuo account PagSeguro.";
$lang['Pagseguro.buildprocess.submit'] = "Paga con PagSeguro";
$lang['Pagseguro.!error.libxml_required'] = "Per questo gateway sono richieste le estensioni libxml e simplexml.";
$lang['Pagseguro.!error.dom_required'] = "Per questo gateway è richiesta l'estensione dom.";
$lang['Pagseguro.!error.email.format'] = "Si prega di inserire un indirizzo email valido.Si prega di inserire un indirizzo email valido.";
$lang['Pagseguro.!error.notification.type'] = "Tipo di notifica sconosciuto:";
$lang['Pagseguro.!error.notification.invalid'] = "Parametri di notifica non validi.";
$lang['Pagseguro.!error.token.empty'] = "Inserisci il tuo token di sicurezza.";
$lang['Pagseguro.description'] = "PagSeguro è un servizio di e-commerce brasiliano basato su pagamenti online o mobili per operazioni commerciali. Nel 2015 è stato riconosciuto come il \"Miglior metodo di pagamento\" dal Congresso Afiliados Brasil";
?>