<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerFiles.!error.category_id.exists'] = "Seleziona una categoria valida.";
$lang['DownloadManagerFiles.!error.company_id.exists'] = "ID azienda non valido.";
$lang['DownloadManagerFiles.!error.name.empty'] = "Inserisci un nome per questo file.";
$lang['DownloadManagerFiles.!error.file_name.format'] = "Carica un file o inserisci un percorso valido per il file.";
$lang['DownloadManagerFiles.!error.public.format'] = "L'opzione di disponibilità pubblica è in un formato non valido.";
$lang['DownloadManagerFiles.!error.public.assignment'] = "Il file deve essere disponibile pubblicamente, per gruppi di clienti o pacchetti.";
$lang['DownloadManagerFiles.!error.permit_client_groups.format'] = "L'opzione di disponibilità del gruppo client è in un formato non valido.";
$lang['DownloadManagerFiles.!error.file_groups.format'] = "Impossibile aggiungere almeno un gruppo di clienti selezionato perché non esiste.";
$lang['DownloadManagerFiles.!error.permit_packages.format'] = "L'opzione di disponibilità del pacchetto è in un formato non valido.";
$lang['DownloadManagerFiles.!error.file_packages.format'] = "Impossibile aggiungere almeno un pacchetto selezionato perché non esiste.";
$lang['DownloadManagerFiles.!error.file_id.exists'] = "Il file in aggiornamento non esiste.";
?>