<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerUrls.!error.company_id.exists'] = "ID azienda non valido.";
$lang['DownloadManagerUrls.!error.url.exists'] = "Questo URL esiste già.";
$lang['DownloadManagerUrls.!error.url.match'] = "Questo URL non corrisponde all'estensione del file.";
$lang['DownloadManagerUrls.!error.url.format'] = "Il formato dell'URL non è valido, può contenere solo lettere, numeri e trattini.";
$lang['DownloadManagerUrls.!error.category_id.exists'] = "La categoria selezionata non esiste.";
$lang['DownloadManagerUrls.!error.file_id.exists'] = "Il file selezionato non esiste.";
?>