<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['GenericDomains.name'] = "Domini generici";
$lang['GenericDomains.description'] = "Un modulo generico per la registrazione del dominio.";
$lang['GenericDomains.module_row'] = "Riga del modulo";
$lang['GenericDomains.module_row_plural'] = "Righe del modulo";
$lang['GenericDomains.domain.domain'] = "Dominio";
$lang['GenericDomains.transfer.domain'] = "Dominio";
$lang['GenericDomains.transfer.transfer_key'] = "Codice PPE";
$lang['GenericDomains.manage.text'] = "Il personale può ricevere copie BCC delle e-mail di creazione, sospensione e cancellazione del servizio se il proprio gruppo di personale ha impostato questi avvisi BCC e il membro dello staff li sottoscrive nella sezione [Le mie informazioni] -> [Avvisi].";
$lang['GenericDomains.package_fields.tld_options'] = "TLD";
?>