<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Clientexec5_5.!error.host.invalid'] = "L'host del database è obbligatorio.";
$lang['Clientexec5_5.!error.database.invalid'] = "Il nome del database è obbligatorio.";
$lang['Clientexec5_5.!error.user.invalid'] = "L'utente del database è richiesto.";
$lang['Clientexec5_5.!error.pass.invalid'] = "È richiesta la password del database.";
$lang['Clientexec5_5.!error.passphrase.invalid'] = "La passphrase CC è obbligatoria.";
$lang['Clientexec5_5.!error.import'] = "L'importazione è stata completata ma si sono verificati i seguenti errori:";
$lang['Clientexec5_5.settings.host'] = "Host della banca dati";
$lang['Clientexec5_5.settings.database'] = "Nome del database";
$lang['Clientexec5_5.settings.user'] = "Utente del database";
$lang['Clientexec5_5.settings.pass'] = "Password della banca dati";
$lang['Clientexec5_5.settings.passphrase'] = "Passphrase CC";
$lang['Clientexec5_5.settings.enable_debug'] = "Abilita debug";
$lang['Clientexec5_5.configuration.create_packages_true'] = "Crea automaticamente tutti i pacchetti necessari durante l'importazione";
$lang['Clientexec5_5.configuration.create_packages_false'] = "Mappare manualmente i pacchetti";
$lang['Clientexec5_5.configuration.local_package'] = "Pacchetto locale";
$lang['Clientexec5_5.configuration.remote_package'] = "Pacchetto remoto";
$lang['Clientexec5_5.configuration.no_local_packages'] = "È necessario creare pacchetti prima di poterli mappare.";
?>