<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Whmcs5_2.!error.host.invalid'] = "L'host del database è obbligatorio.";
$lang['Whmcs5_2.!error.database.invalid'] = "Il nome del database è obbligatorio.";
$lang['Whmcs5_2.!error.user.invalid'] = "L'utente del database è obbligatorio.";
$lang['Whmcs5_2.!error.pass.invalid'] = "È richiesta la password del database.";
$lang['Whmcs5_2.!error.key.invalid'] = "Città";
$lang['Whmcs5_2.!error.import'] = "L'importazione è stata completata ma si sono verificati i seguenti errori:";
$lang['Whmcs5_2.!notice.gmp'] = "Impossibile trovare l'estensione \"gmp\". Questa estensione è consigliata per migliorare le prestazioni e migliorare il processo di importazione. Puoi continuare senza questa estensione ma il processo di importazione potrebbe essere molto più lento.";
$lang['Whmcs5_2.settings.host'] = "Host della banca dati";
$lang['Whmcs5_2.settings.database'] = "Nome del database";
$lang['Whmcs5_2.settings.user'] = "Utente del database";
$lang['Whmcs5_2.settings.pass'] = "Password della banca dati";
$lang['Whmcs5_2.settings.key'] = "Hash di crittografia CC";
$lang['Whmcs5_2.settings.key.info'] = "Questa è la chiave di crittografia utilizzata da WHMCS per crittografare vari bit di dati. Può essere trovato nel file Configuration.php di WHMCS.";
$lang['Whmcs5_2.settings.balance_credit'] = "Transazioni di bilanciamento automatico per abbinare i crediti dei clienti in WHMCS";
$lang['Whmcs5_2.settings.balance_credit.info'] = "Se selezionato, genererà una transazione o una fattura per garantire che il credito del cliente in Blesta corrisponda a quello impostato per il cliente in WHMCS. Ciò è necessario perché WHMCS non tiene conto correttamente dei crediti dei clienti.";
$lang['Whmcs5_2.settings.enable_debug'] = "Abilita debug";
$lang['Whmcs5_2.configuration.create_packages_true'] = "Crea automaticamente tutti i pacchetti necessari durante l'importazione";
$lang['Whmcs5_2.configuration.create_packages_false'] = "Mappare manualmente i pacchetti";
$lang['Whmcs5_2.configuration.local_package'] = "Pacchetto locale";
$lang['Whmcs5_2.configuration.remote_package'] = "Pacchetto remoto";
$lang['Whmcs5_2.configuration.no_local_packages'] = "È necessario creare pacchetti prima di poterli mappare.";
?>