<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminManagePlugin.!success.settings_saved'] = "Le impostazioni sono state salvate.";
$lang['AdminManagePlugin.index.page_title'] = "Annullamento Automatico";
$lang['AdminManagePlugin.index.boxtitle_auto_cancel'] = "Annullamento automatico";
$lang['AdminManagePlugin.index.heading_settings'] = "Impostazioni";
$lang['AdminManagePlugin.index.field.schedule_days'] = "Pianifica i giorni di cancellazione dopo la sospensione";
$lang['AdminManagePlugin.index.field.cancel_days'] = "Annulla i servizi giorni dopo la sospensione";
$lang['AdminManagePlugin.index.field.submit'] = "Salva";
$lang['AdminManagePlugin.getDays.never'] = "Mai";
$lang['AdminManagePlugin.getDays.text_day'] = "%1\$s Giorno";
$lang['AdminManagePlugin.getDays.text_days'] = "%1\$s Giorni"; // %1$s is the number of days
?>