<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AutoCancelPlugin.getCronTasks.schedule_cancellation_name'] = "Cancellazione automatica della pianificazione";
$lang['AutoCancelPlugin.getCronTasks.schedule_cancellation_desc'] = "Pianifica automaticamente la cancellazione dei servizi sospesi.";
$lang['AutoCancelPlugin.name'] = "Annullamento automatico";
$lang['AutoCancelPlugin.description'] = "Pianifica automaticamente i servizi per la cancellazione.";
?>