<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Config.index.header_configuration'] = "Configurazione";
$lang['Config.index.header_configure_service'] = "Configura %1\$s"; // %1$s is the service name to configure
$lang['Config.index.config_notes'] = "Seleziona le opzioni desiderate e continua con il pagamento.";
$lang['Config.index.header_term'] = "Durata e prezzo";
$lang['Config.index.header_module'] = "Opzioni configurabili";
$lang['Config.index.header_addons'] = "Componenti aggiuntivi disponibili";
$lang['Config.index.addons_notes'] = "Tutti i componenti aggiuntivi selezionati verranno configurati nel passaggio successivo.";
$lang['Config.index.continue_btn'] = "Continua";
?>