<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Main.index.heading'] = "Selezione del pacchetto";
$lang['Main.index.subheading'] = "Seleziona un gruppo di pacchetti qui sotto per continuare.";
$lang['Main.index.group_heading'] = "Seleziona un pacchetto qui sotto.";
$lang['Main.index.field_pricing_id'] = "Scegli il tuo ciclo di fatturazione.";
$lang['Main.index.button_order'] = "Ordina adesso";
$lang['Main.index.sold_out'] = "Esaurito";
$lang['Main.index.field_currency'] = "Valuta:";
$lang['Main.index.show_cart_btn'] = "Mostra carrello";
$lang['Main.packages.subheading'] = "Seleziona un pacchetto e configuralo nel passaggio successivo.";
$lang['Main.packages.select_note'] = "Trascina per selezionare un pacchetto diverso.";
$lang['Main.packages.price_start'] = "A partire da";
$lang['Main.packages.field_pricing_id'] = "Scegli il tuo ciclo di fatturazione.";
$lang['Main.packages.box_select'] = "Selezionare";
$lang['Main.packages.box_selected'] = "Selezionato";
$lang['Main.packages.box_sold_out'] = "Esaurito";
$lang['Main.packages.button_order'] = "Ordina adesso";
$lang['Main.packages.continue_btn'] = "Continua";
$lang['Main.packages.continue_note'] = "Continua con la configurazione e il checkout.";
$lang['Main.index.client_limit'] = "Limite raggiunto";
$lang['Main.packages.box_client_limit'] = "Limite raggiunto";
$lang['Main.index.currency_unavailable'] = "Valuta non disponibile";
$lang['Main.packages.show_cart_btn'] = "Mostra carrello";
?>