<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Summary.index.have_coupon'] = "Utilizza un codice coupon";
$lang['Summary.index.coupon'] = "Buono";
$lang['Summary.index.coupon_btn'] = "Riscattare";
$lang['Summary.index.heading_summary'] = "Riepilogo dell'ordine";
$lang['Summary.index.summary_note'] = "Eventuali tasse applicabili verranno calcolate dopo la registrazione o l'accesso.";
$lang['Summary.index.table_description'] = "Descrizione";
$lang['Summary.index.table_price'] = "Prezzo";
$lang['Summary.index.empty_cart'] = "Carrello vuoto";
$lang['Summary.index.heading_paymethods'] = "Metodo di pagamento";
$lang['Summary.index.paymethods_note'] = "Seleziona il metodo di pagamento desiderato.";
?>