<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['BtcpayServer.name'] = "BTCPay (Bitcoin)";
$lang['BtcpayServer.description'] = "BTCPayServer è un gateway di pagamento Bitcoin self-hosted senza costi.";
$lang['BtcpayServer.!error.server_url.valid'] = "URL del server non valido.";
$lang['BtcpayServer.!error.transaction_speed.valid'] = "Seleziona una velocità di transazione valida.";
$lang['BtcpayServer.!error.store_id.valid'] = "ID negozio non valido.";
$lang['BtcpayServer.!error.api_key.valid'] = "Chiave API non valida.";
$lang['BtcpayServer.!error.failed.response'] = "Impossibile elaborare la transazione.";
$lang['BtcpayServer.!error.payment.invalid'] = "La transazione non è valida e non è stato possibile elaborarla.";
$lang['BtcpayServer.!error.payment.expired'] = "La transazione è scaduta e non è stato possibile elaborarla.";
$lang['BtcpayServer.!error.webhook_secret.valid'] = "È necessario inserire un segreto webhook valido.";
$lang['BtcpayServer.meta.server_url'] = "URL del server";
$lang['BtcpayServer.meta.store_id'] = "ID del negozio";
$lang['BtcpayServer.meta.api_key'] = "Chiave API";
$lang['BtcpayServer.meta.transaction_speed'] = "Velocità di transazione";
$lang['BtcpayServer.meta.webhook_secret'] = "View the Google Translation";
$lang['BtcpayServer.transaction.speed.high'] = "Alto";
$lang['BtcpayServer.transaction.speed.medium'] = "medio";
$lang['BtcpayServer.transaction.speed.low'] = "Basso";
$lang['BtcpayServer.webhook'] = "Webhook del server BTCPay";
$lang['BtcpayServer.webhook_note'] = "Prima di iniziare a utilizzare questo gateway devi configurare il seguente URL come Webhook nel tuo server BTCPay.";
$lang['BtcpayServer.buildprocess.submit'] = "Inviare pagamento";
?>