<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TransactionsReceived.name'] = "Transazioni ricevute";
$lang['TransactionsReceived.option.any'] = "Qualunque";
$lang['TransactionsReceived.options.field_start_date'] = "Data d'inizio";
$lang['TransactionsReceived.options.field_end_date'] = "Data di fine";
$lang['TransactionsReceived.options.field_gateway'] = "Gateway";
$lang['TransactionsReceived.options.field_status'] = "Stato";
$lang['TransactionsReceived.options.field_payment_type'] = "Modalità di pagamento";
$lang['TransactionsReceived.heading.id'] = "Transazione n.";
$lang['TransactionsReceived.heading.transaction_id'] = "ID della transazione";
$lang['TransactionsReceived.heading.reference_id'] = "Identificativo di riferimento";
$lang['TransactionsReceived.heading.client_id_code'] = "Cliente #";
$lang['TransactionsReceived.heading.gateway_name'] = "Casello stradale";
$lang['TransactionsReceived.heading.type_name'] = "Modalità di pagamento";
$lang['TransactionsReceived.heading.amount'] = "Importo del pagamento";
$lang['TransactionsReceived.heading.currency'] = "Moneta";
$lang['TransactionsReceived.heading.status'] = "Stato";
$lang['TransactionsReceived.heading.date_added'] = "Data aggiunta";
$lang['TransactionsReceived.heading.income_type'] = "Tipo di transazione";
?>