<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FeedReaderFeeds.!error.url.valid'] = "L'URL fornito non è valido.";
$lang['FeedReaderFeeds.!error.company_id.exists'] = "L'azienda specificata non esiste";
$lang['FeedReaderFeeds.!error.updated.valid'] = "È necessario specificare una data di aggiornamento valida.";
$lang['FeedReaderFeeds.!error.feed_id.exists'] = "Il feed fornito non esiste.";
$lang['FeedReaderFeeds.!error.staff_id.exists'] = "Il membro dello staff specificato non esiste.";
$lang['FeedReaderFeeds.!error.date.valid'] = "I dati specificati non sono validi.";
?>