<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FeedReaderPlugin.!error.libxml_required'] = "Per questo plugin è richiesta l'estensione libxml.";
$lang['FeedReaderPlugin.!error.dom_required'] = "Per questo plugin è richiesta l'estensione dom.";
$lang['FeedReaderPlugin.name'] = "Lettore di feed";
$lang['FeedReaderPlugin.description'] = "Visualizza qualsiasi feed RSS/Atom direttamente sulla tua dashboard.";
?>