<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Whmsonic.name'] = "WHMSonic";
$lang['Whmsonic.module_row'] = "server";
$lang['Whmsonic.module_row_plural'] = "Server";
$lang['Whmsonic.module_group'] = "Gruppo di server";
$lang['Whmsonic.tab_stats'] = "Informazioni sul servizio";
$lang['Whmsonic.tab_client_actions'] = "Actions";
$lang['Whmsonic.submit'] = "Invia";
$lang['Whmsonic.tab_stats.info_heading.field'] = "Campo";
$lang['Whmsonic.tab_stats.info_heading.value'] = "Valore";
$lang['Whmsonic.tab_stats.info.client_type'] = "Tipo di cliente";
$lang['Whmsonic.tab_stats.info.bitrate'] = "Limite della velocità in bit";
$lang['Whmsonic.tab_stats.info.bandwidth'] = "Limite di larghezza di banda (in MB)";
$lang['Whmsonic.tab_stats.info.hspace'] = "Spazio di hosting (in MB)";
$lang['Whmsonic.tab_stats.info.listeners'] = "Limite degli ascoltatori";
$lang['Whmsonic.tab_stats.info.autodj'] = "Accesso AutoDJ";
$lang['Whmsonic.tab_stats.info.username'] = "Nome utente";
$lang['Whmsonic.tab_stats.info.password'] = "Parola d'ordine";
$lang['Whmsonic.tab_stats.info.whmsonic_ftp'] = "Accesso FTP";
$lang['Whmsonic.tab_stats.info.whmsonic_radio_ip'] = "IP radiofonico";
$lang['Whmsonic.tab_stats.info.whmsonic_radio_password'] = "Password radiofonica";
$lang['Whmsonic.tab_client_actions.change_password'] = "Cambia password";
$lang['Whmsonic.tab_client_actions.password'] = "Password del cPanel";
$lang['Whmsonic.tab_client_actions.radio_password'] = "Password radiofonica";
$lang['Whmsonic.add_module_row'] = "Aggiungi server";
$lang['Whmsonic.add_module_group'] = "Aggiungi gruppo di server";
$lang['Whmsonic.manage.module_rows_title'] = "Server";
$lang['Whmsonic.manage.module_groups_title'] = "Gruppi di server";
$lang['Whmsonic.manage.module_rows_heading.name'] = "Etichetta del server";
$lang['Whmsonic.manage.module_rows_heading.ip_address'] = "Indirizzo IP";
$lang['Whmsonic.manage.module_rows_heading.options'] = "Opzioni";
$lang['Whmsonic.manage.module_groups_heading.name'] = "Nome del gruppo";
$lang['Whmsonic.manage.module_groups_heading.servers'] = "Conteggio server";
$lang['Whmsonic.manage.module_groups_heading.options'] = "Opzioni";
$lang['Whmsonic.manage.module_rows.edit'] = "Modificare";
$lang['Whmsonic.manage.module_groups.edit'] = "Modificare";
$lang['Whmsonic.manage.module_rows.delete'] = "Eliminare";
$lang['Whmsonic.manage.module_groups.delete'] = "Elimina";
$lang['Whmsonic.manage.module_rows.confirm_delete'] = "Sei sicuro di voler eliminare questo server?";
$lang['Whmsonic.manage.module_groups.confirm_delete'] = "Sei sicuro di voler eliminare questo gruppo di server?";
$lang['Whmsonic.manage.module_rows_no_results'] = "Non ci sono server.";
$lang['Whmsonic.manage.module_groups_no_results'] = "Non sono presenti gruppi di server.";
$lang['Whmsonic.order_options.first'] = "Primo server non completo
";
$lang['Whmsonic.add_row.box_title'] = "Aggiungi il server WHMSonic";
$lang['Whmsonic.add_row.basic_title'] = "Impostazioni di base";
$lang['Whmsonic.add_row.add_btn'] = "Aggiungi server";
$lang['Whmsonic.edit_row.box_title'] = "Modifica il server WHMSonic";
$lang['Whmsonic.edit_row.basic_title'] = "Impostazioni di base";
$lang['Whmsonic.edit_row.add_btn'] = "Modifica server";
$lang['Whmsonic.row_meta.server_name'] = "Etichetta del server";
$lang['Whmsonic.row_meta.ip_address'] = "Indirizzo IP";
$lang['Whmsonic.row_meta.password'] = "Parola d'ordine";
$lang['Whmsonic.row_meta.use_ssl'] = "Usa SSL per le connessioni all'API (consigliato)";
$lang['Whmsonic.package_fields.client_type'] = "Tipo di cliente";
$lang['Whmsonic.package_fields.client_type.external'] = "Esterno";
$lang['Whmsonic.package_fields.client_type.internal'] = "Interno";
$lang['Whmsonic.package_fields.bitrate'] = "Limite della velocità in bit";
$lang['Whmsonic.package_fields.hspace'] = "Spazio di hosting (in MB)";
$lang['Whmsonic.package_fields.bandwidth'] = "Limite di larghezza di banda (in MB)";
$lang['Whmsonic.package_fields.listeners'] = "Limite degli ascoltatori";
$lang['Whmsonic.package_fields.autodj'] = "Accesso AutoDJ";
$lang['Whmsonic.package_fields.autodj.yes'] = "Si";
$lang['Whmsonic.package_fields.autodj.no'] = "NO";
$lang['Whmsonic.service_field.cpanel_username'] = "Nome utente cPanel";
$lang['Whmsonic.service_field.username'] = "Nome utente radiofonico";
$lang['Whmsonic.service_field.radio_password'] = "Password radiofonica";
$lang['Whmsonic.service_field.password'] = "Password del cPanel";
$lang['Whmsonic.service_field.username.tooltip'] = "Il nome utente verrà aggiornato solo localmente all'interno di Blesta";
$lang['Whmsonic.service_field.password.tooltip'] = "La password verrà aggiornata solo localmente all'interno di Blesta";
$lang['Whmsonic.service_info.ip_address'] = "Indirizzo IP";
$lang['Whmsonic.service_info.username'] = "Nome utente";
$lang['Whmsonic.service_info.password'] = "Parola d'ordine";
$lang['Whmsonic.service_info.options'] = "Opzioni";
$lang['Whmsonic.service_info.option_login'] = "Login";
$lang['Whmsonic.!error.server_name_valid'] = "È necessario inserire un'etichetta server.";
$lang['Whmsonic.!error.ip_address_valid'] = "L'indirizzo IP sembra non essere valido.";
$lang['Whmsonic.!error.password_valid'] = "Le credenziali API sembrano non essere valide.";
$lang['Whmsonic.!error.api.internal'] = "Si è verificato un errore interno oppure il server non ha risposto alla richiesta.";
$lang['Whmsonic.!error.module_row.missing'] = "Si è verificato un errore interno. La riga del modulo non è disponibile.";
$lang['Whmsonic.!error.meta[client_type].valid'] = "Seleziona un tipo di cliente valido.";
$lang['Whmsonic.!error.meta[bitrate].valid'] = "

Seleziona un limite di bitrate valido.
";
$lang['Whmsonic.!error.meta[hspace].empty'] = "Inserisci lo spazio di hosting (in MB), ad esempio: 1000.";
$lang['Whmsonic.!error.meta[bandwidth].empty'] = "Inserisci il limite di larghezza di banda (in MB), ad esempio 1000.";
$lang['Whmsonic.!error.meta[listeners].empty'] = "Inserisci il limite di ascoltatori.";
$lang['Whmsonic.!error.meta[autodj].valid'] = "Seleziona un'opzione di accesso AutoDJ valida.";
$lang['Whmsonic.!error.user_name.empty'] = "Il nome utente non può essere vuoto.";
$lang['Whmsonic.!error.user_password.valid'] = "La password deve contenere almeno 8 caratteri.";
$lang['Whmsonic.description'] = "Ti consente di offrire Shoutcast, Icecast, hosting multimediale in streaming, AutoDJ, rivenditore radio dal tuo server dedicato o VPS.";
?>