<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientMain.index.page_title'] = "Cliente #%1\$s Domini"; // %1$s is the client ID number
$lang['ClientMain.index.boxtitle_domains'] = "Domini";
$lang['ClientMain.index.category_active'] = "Attivo";
$lang['ClientMain.index.category_pending'] = "In attesa di";
$lang['ClientMain.index.category_suspended'] = "Sospeso";
$lang['ClientMain.index.category_deleted'] = "Eliminato";
$lang['ClientMain.index.heading_addons'] = "Componenti aggiuntivi";
$lang['ClientMain.index.heading_status'] = "Stato";
$lang['ClientMain.index.heading_term'] = "Termine";
$lang['ClientMain.index.heading_registration_date'] = "Data di registrazione";
$lang['ClientMain.index.heading_expiration_date'] = "Data di scadenza";
$lang['ClientMain.index.heading_suspension_date'] = "Data di sospensione";
$lang['ClientMain.index.heading_deletion_date'] = "Data di eliminazione";
$lang['ClientMain.index.heading_options'] = "Opzioni";
$lang['ClientMain.index.heading_domain'] = "Dominio";
$lang['ClientMain.index.option_manage'] = "

Maneggio
";
$lang['ClientMain.index.recurring_term'] = "%1\$s %2\$s @ %3\$s"; // %1$s is the service term length (number), %2$s is the service period, %3$s is the formatted service renewal price
$lang['ClientMain.index.text_never'] = "Mai";
$lang['ClientMain.index.no_results'] = "Non hai domini %1\$s."; // %1$s is the language for the domains category type (e.g. Active, Pending)
$lang['ClientMain.serviceinfo.no_results'] = "Questo dominio non ha dettagli.";
$lang['ClientMain.serviceinfo.cancellation_reason'] = "Motivo dell'annullamento: %1\$s"; // %1$s is the reason this service was canceled
$lang['ClientMain.getfilters.any'] = "Qualunque";
$lang['ClientMain.getfilters.field_module_id'] = "Moduli di registrazione";
$lang['ClientMain.getfilters.field_package_name'] = "TLD";
$lang['ClientMain.getfilters.field_service_meta'] = "Nome del dominio";
$lang['ClientMain.index.heading_renewal_date'] = "Data di rinnovo";
?>