<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DomainsTlds.!error.tld.empty'] = "Inserisci un TLD.";
$lang['DomainsTlds.!error.tld.exists'] = "Il TLD esiste già in azienda.";
$lang['DomainsTlds.!error.tld.length'] = "Il TLD deve contenere almeno 3 caratteri.";
$lang['DomainsTlds.!error.package_id.exists'] = "ID pacchetto non valido.";
$lang['DomainsTlds.!error.package_group_id.exists'] = "ID gruppo di pacchetti non valido.";
$lang['DomainsTlds.!error.module_id.exists'] = "ID modulo non valido.";
$lang['DomainsTlds.!error.commpany_id.exists'] = "ID azienda non valido.";
$lang['DomainsTlds.!error.dns_management.valid'] = "Valore non valido per la gestione DNS, deve essere 0 o 1.";
$lang['DomainsTlds.!error.email_forwarding.valid'] = "Valore non valido per l'inoltro e-mail. Deve essere 0 o 1.";
$lang['DomainsTlds.!error.id_protection.valid'] = "Valore non valido per la protezione ID, deve essere 0 o 1.";
$lang['DomainsTlds.!error.epp_code.valid'] = "Valore non valido per il codice EPP, deve essere 0 o 1.";
$lang['DomainsTlds.!error.package_pricing.count'] = "Il prezzo non può essere disabilitato, il TLD deve avere almeno un prezzo.";
$lang['DomainsTlds.!error.package_pricing.service'] = "Non è stato possibile disattivare il prezzo perché un servizio lo sta attualmente utilizzando.";
$lang['DomainsTlds.!error.tld.supported'] = "Il TLD fornito non è supportato dal modulo registrar selezionato.";
$lang['DomainsTlds.!error.feature.unsupported'] = "La funzione %1\$s non è supportata dal modulo registrar selezionato."; // %1$s is the feature name
$lang['DomainsTlds.getTldFields.group'] = "Gruppo";
$lang['DomainsTlds.!error.tld.not_exists'] = "Il TLD non esiste in azienda.";
$lang['DomainsTlds.!error.tld_id.exists'] = "ID TLD non valido.";
?>