<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.document_uploaded'] = "Il documento è stato caricato.";
$lang['AdminMain.!success.document_deleted'] = "Il documento è stato eliminato.";
$lang['AdminMain.index.page_title'] = "Documenti";
$lang['AdminMain.add.page_title'] = "Documenti > Aggiungi";
$lang['AdminMain.index.categorylink_adddocument'] = "Aggiungi documento";
$lang['AdminMain.index.boxtitle_client'] = "Cliente #%1\$s - %2\$s %3\$s";
$lang['AdminMain.index.boxtitle_documents'] = "Documenti";
$lang['AdminMain.index.no_results'] = "Non sono presenti documenti impostati per questo cliente.";
$lang['AdminMain.index.heading_name'] = "Nome";
$lang['AdminMain.index.heading_description'] = "Descrizione";
$lang['AdminMain.index.heading_date_added'] = "Data aggiunta";
$lang['AdminMain.index.heading_date_options'] = "Opzioni";
$lang['AdminMain.index.option_delete'] = "Eliminare";
$lang['AdminMain.index.option_download'] = "Scaricamento";
$lang['AdminMain.modal.delete_document'] = "Eliminare davvero questo documento?";
$lang['AdminMain.add.boxtitle_adddocument'] = "Carica documento";
$lang['AdminMain.add.field_name'] = "Nome";
$lang['AdminMain.add.field_document'] = "Documento";
$lang['AdminMain.add.field_description'] = "Descrizione";
$lang['AdminMain.add.field_submit'] = "Carica documento";
?>