<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientMain.index.page_title'] = "Documenti";
$lang['ClientMain.index.boxtitle_documents'] = "Documenti";
$lang['ClientMain.index.no_results'] = "Non ci sono documenti disponibili per il download.";
$lang['ClientMain.index.heading_name'] = "Nome";
$lang['ClientMain.index.heading_description'] = "Descrizione";
$lang['ClientMain.index.heading_date_added'] = "Data aggiunta";
$lang['ClientMain.index.heading_options'] = "Opzioni";
$lang['ClientMain.index.option_download'] = "Scaricamento";
?>