<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Authorize_net.name'] = "Autorize.net";
$lang['Authorize_net.login_id'] = "Utente";
$lang['Authorize_net.transaction_key'] = "Chiave di transazione";
$lang['Authorize_net.api'] = "API di pagamento";
$lang['Authorize_net.test_mode'] = "Modalità di prova";
$lang['Authorize_net.apis_aim'] = "SCOPO (predefinito)";
$lang['Authorize_net.apis_cim'] = "CIM (deve essere abilitato da Authorize.Net)";
$lang['Authorize_net.validation_mode'] = "Modalità di convalida del conto di pagamento";
$lang['Authorize_net.validation_note'] = "Controlla quale tipo di convalida viene eseguita quando un conto di pagamento viene archiviato utilizzando CIM. 'Nessuno' non esegue alcuna convalida aggiuntiva. \"Test\" emette una transazione di prova che non appare sull'estratto conto del cliente ma genererà un'e-mail al commerciante. 'Live' elabora una transazione da \$ 0,00 o \$ 0,01 che viene immediatamente annullata. Consulta il fornitore del tuo account commerciante prima di impostare questo valore su \"In vigore\", poiché potresti essere soggetto a commissioni.";
$lang['Authorize_net.validation_modes_none'] = "Nessuno";
$lang['Authorize_net.validation_modes_test'] = "Test";
$lang['Authorize_net.validation_modes_live'] = "Vivere";
$lang['Authorize_net.!error.login_id.format'] = "L'ID di accesso non deve contenere più di 20 caratteri e non può essere vuoto.";
$lang['Authorize_net.!error.transaction_key.format'] = "La chiave della transazione deve contenere 16 caratteri.";
$lang['Authorize_net.!error.test_mode.valid'] = "La modalità test deve essere impostata su \"true\" se fornita.";
$lang['Authorize_net.test_mode_note'] = "La funzionalità della modalità test è supportata solo da AIM. Per testare le transazioni CIM è necessario abilitare la modalità test dal tuo account Authorize.net.";
$lang['Authorize_net.dev_mode'] = "Modalità sviluppatore";
$lang['Authorize_net.dev_mode_note'] = "L'abilitazione di questa opzione pubblicherà le transazioni nell'ambiente di sviluppo Authorize.net. È necessario disporre di un account di prova sviluppatore per poter utilizzare questo ambiente.";
$lang['Authorize_net.!error.dev_mode.valid'] = "La modalità sviluppatore deve essere impostata su \"true\" se fornita.";
$lang['Authorize_net.!error.card_number.missing'] = "La data di scadenza non può essere aggiornata senza il numero completo della carta.";
$lang['Authorize_net.description'] = "Elaborazione di carte di credito e ACH affidabile e veloce";
?>