<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.options_updated'] = "Le opzioni di Fatturazione a colpo d'occhio sono state aggiornate con successo!";
$lang['AdminMain.index.boxtitle_overview'] = "Fatturazione in un colpo d'occhio";
$lang['AdminMain.index.statistic.revenue_today'] = "Entrate oggi";
$lang['AdminMain.index.statistic.revenue_month'] = "Entrate questo mese";
$lang['AdminMain.index.statistic.invoiced_today'] = "Fatturato oggi";
$lang['AdminMain.index.statistic.invoiced_month'] = "Fatturato questo mese";
$lang['AdminMain.index.statistic.balance_outstanding'] = "Saldo dovuto";
$lang['AdminMain.index.statistic.balance_overdue'] = "Saldo scaduto";
$lang['AdminMain.index.statistic.scheduled_cancelation'] = "Cancellazioni programmate";
$lang['AdminMain.index.statistic.services_active'] = "Servizi attivi";
$lang['AdminMain.index.statistic.services_added_today'] = "Servizi aggiunti oggi";
$lang['AdminMain.index.statistic.services_canceled_today'] = "Servizi annullati oggi";
$lang['AdminMain.settings.text_options'] = "Controlla le opzioni che appariranno nella Panoramica fatturazione.";
$lang['AdminMain.settings.heading_statistics'] = "Statistiche";
$lang['AdminMain.settings.heading_graphs'] = "Grafici";
$lang['AdminMain.settings.heading_graph_settings'] = "Impostazioni del grafico";
$lang['AdminMain.settings.revenue_today'] = "Entrate oggi";
$lang['AdminMain.settings.revenue_month'] = "Entrate questo mese";
$lang['AdminMain.settings.invoiced_today'] = "Fatturato oggi";
$lang['AdminMain.settings.invoiced_month'] = "Fatturato questo mese";
$lang['AdminMain.settings.balance_outstanding'] = "Saldo eccezionale";
$lang['AdminMain.settings.balance_overdue'] = "Saldo scaduto";
$lang['AdminMain.settings.scheduled_cancelation'] = "Cancellazioni programmate";
$lang['AdminMain.settings.services_active'] = "Servizi attivi";
$lang['AdminMain.settings.services_added_today'] = "Servizi aggiunti oggi";
$lang['AdminMain.settings.services_canceled_today'] = "Servizi annullati oggi";
$lang['AdminMain.settings.text_graphs'] = "Controlla quali grafici dovrebbero apparire nella Panoramica fatturazione.";
$lang['AdminMain.settings.graph_invoiced'] = "Grafico importo fatturato";
$lang['AdminMain.settings.text_graph_settings'] = "Gestisci le impostazioni del grafico per i grafici che appariranno nella Panoramica fatturazione.";
$lang['AdminMain.settings.show_legend'] = "Mostra legenda sui grafici";
$lang['AdminMain.settings.date_range'] = "Intervallo di date del grafico";
$lang['AdminMain.settings.submit_settings'] = "Aggiorna impostazioni";
$lang['AdminMain.settings.submit_cancel'] = "Torna alla panoramica";
$lang['AdminMain.date_range.days'] = "giorni";
$lang['AdminMain.graph_name.graph_invoiced'] = "Importo Fatturato";
$lang['AdminMain.graph_line_name.total'] = "Totale";
$lang['AdminMain.graph_line_name.credit'] = "Carta di credito";
$lang['AdminMain.graph_line_name.ach'] = "ACH";
$lang['AdminMain.graph_line_name.other'] = "Altro";
$lang['AdminMain.index.statistic.revenue_year'] = "Entrate quest'anno";
$lang['AdminMain.settings.revenue_year'] = "Entrate quest'anno";
$lang['AdminMain.settings.graph_revenue_year'] = "Grafico delle entrate (da inizio anno)";
$lang['AdminMain.graph_name.graph_revenue_year'] = "Entrate (da inizio anno)";
$lang['AdminMain.settings.graph_revenue'] = "Grafico Entrate (Range)";
$lang['AdminMain.graph_name.graph_revenue'] = "Entrate (intervallo)";
$lang['AdminMain.index.statistic.credits_today'] = "Crediti oggi";
$lang['AdminMain.index.statistic.credits_month'] = "Crediti questo mese";
$lang['AdminMain.index.statistic.credits_year'] = "Crediti quest'anno";
$lang['AdminMain.settings.credits_today'] = "Credits Oggi";
$lang['AdminMain.settings.credits_month'] = "Crediti questo mese";
$lang['AdminMain.settings.credits_year'] = "Crediti quest'anno";
$lang['AdminMain.graph_line_name.credits'] = "Crediti";
$lang['AdminMain.index.statistic.invoiced_today_proforma'] = "Fatturato oggi (Proforma)";
$lang['AdminMain.index.statistic.invoiced_month_proforma'] = "Fatturato questo mese (Proforma)";
$lang['AdminMain.settings.invoiced_today_proforma'] = "Fatturato oggi (Proforma)";
$lang['AdminMain.settings.invoiced_month_proforma'] = "Fatturato questo mese (Proforma)";
?>