<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['BillingOverviewPlugin.name'] = "Fatturazione veloce";
$lang['BillingOverviewPlugin.description'] = "Visualizza le statistiche di fatturazione in un widget nella pagina Panoramica fatturazione.";
?>