<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderTypeRegistration.name'] = "Registrazione del cliente";
$lang['OrderTypeRegistration.!success.signup'] = "Grazie per aver registrato un account con noi.";
$lang['OrderTypeRegistration.!error.template.valid'] = "La registrazione del cliente supporta solo il modello Standard.";
?>