<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TaxLiability.name'] = "Responsabilità fiscale";
$lang['TaxLiability.options.field_start_date'] = "Data d'inizio";
$lang['TaxLiability.options.field_end_date'] = "Data di fine";
$lang['TaxLiability.options.field_cascade_true'] = "Si";
$lang['TaxLiability.options.field_cascade_false'] = "NO";
$lang['TaxLiability.heading.id_code'] = "Fattura #


";
$lang['TaxLiability.heading.client_id_code'] = "Cliente #";
$lang['TaxLiability.heading.subtotal'] = "totale parziale";
$lang['TaxLiability.heading.taxable_amount'] = "Importo tassabile";
$lang['TaxLiability.heading.level1_tax_rate'] = "Aliquota fiscale di livello 1 (%)";
$lang['TaxLiability.heading.level1_tax_amount'] = "Importo fiscale di livello 1";
$lang['TaxLiability.heading.level2_tax_rate'] = "Aliquota fiscale di livello 2 (%)";
$lang['TaxLiability.heading.level2_tax_amount'] = "Importo fiscale di livello 2";
$lang['TaxLiability.heading.cascade'] = "Tassa a cascata";
$lang['TaxLiability.heading.currency'] = "Moneta";
$lang['TaxLiability.heading.date_closed'] = "Data di chiusura";
$lang['TaxLiability.heading.level1_tax_country'] = "Paese di livello 1";
$lang['TaxLiability.heading.level1_tax_state'] = "Livello 1 Stato/Provincia";
$lang['TaxLiability.heading.level2_tax_country'] = "Paese di livello 2";
$lang['TaxLiability.heading.level2_tax_state'] = "Livello 2 Stato/Provincia";
?>