<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cart.index.header_cart'] = "Riepilogo dell'ordine";
$lang['Cart.index.header_note'] = "Eventuali tasse applicabili verranno calcolate dopo la registrazione o l'accesso.";
$lang['Cart.index.table_description'] = "Descrizione";
$lang['Cart.index.table_term'] = "Termine";
$lang['Cart.index.table_qty'] = "Quantità";
$lang['Cart.index.table_price'] = "Prezzo";
$lang['Cart.index.edit_item'] = "Modificare";
$lang['Cart.index.remove_item'] = "Rimuovere";
$lang['Cart.index.have_coupon'] = "Utilizza un codice coupon";
$lang['Cart.index.coupon'] = "Buono";
$lang['Cart.index.order_more_btn'] = "Fare clic per ordinare più articoli";
$lang['Cart.index.order_more_note'] = "Oppure registrati/accedi e continua ad effettuare il pagamento.";
?>