<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Domain.lookup.title'] = "Controlla la disponibilità del dominio";
$lang['Domain.lookup.description'] = "View the Google Translation";
$lang['Domain.lookup.domain_placeholder'] = "tuodominio.com";
$lang['Domain.lookup.transfer_btn'] = "Trasferimento";
$lang['Domain.lookup.lookup_btn'] = "Verificare la disponibilità";
$lang['Domain.lookup.other_btn'] = "Salta, ordina altri articoli";
$lang['Domain.lookup.domains_header_available'] = "Congratulazioni, quel dominio è disponibile.";
$lang['Domain.lookup.domains_header_unavailable'] = "Siamo spiacenti, quel dominio non è disponibile.";
$lang['Domain.lookup.domains_domain_name'] = "Nome del dominio";
$lang['Domain.lookup.domains_status'] = "Stato";
$lang['Domain.lookup.domains_term'] = "Termine";
$lang['Domain.lookup.domain_available'] = "Disponibile";
$lang['Domain.lookup.domain_unavailable'] = "Non disponibile";
$lang['Domain.lookup.order_btn'] = "Ordine selezionato";
$lang['Domain.lookup.term'] = "%1\$s %2\$s @ %3\$s"; // %1$s is the term, %2$s is the period, %3$s is the currency price
$lang['Domain.lookup.term_onetime'] = "%1\$s @ %2\$s"; // %1$s is the period, %2$s is the currency price
$lang['Domain.lookup.term_recurring'] = "%1\$s %2\$s @ %3\$s (rinnova @ %4\$s)"; // %1$s is the term, %2$s is the period, %3$s is the initial price, %4$s is the renewal price
$lang['Domain.lookup.show_all'] = "Mostra tutto";
$lang['Domain.lookup.hide_all'] = "

Nascondi tutto


Nascondi tutto
";
$lang['Domain.lookup.heading_tld'] = "TLD";
$lang['Domain.lookup.heading_price'] = "Prezzo";
$lang['Domain.lookup.heading_transfer_price'] = "Prezzo di trasferimento";
$lang['Domain.lookup.heading_renew_price'] = "Rinnova prezzo";
$lang['Domain.lookup.term_year'] = "%1\$s Anno"; // %1$s is the term
$lang['Domain.lookup.term_years'] = "%1\$s Anni"; // %1$s is the term
$lang['Domain.lookup.loading'] = "Caricamento...";
?>