<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Util.filters.client_filters.any'] = "Qualunque";
$lang['Util.filters.client_filters.field_contact_name'] = "Nome";
$lang['Util.filters.client_filters.field_contact_email'] = "E-mail";
$lang['Util.filters.client_filters.field_contact_company'] = "Azienda";
$lang['Util.filters.client_filters.field_contact_country'] = "Paese";
$lang['Util.filters.client_filters.field_client_group_id'] = "Gruppo clienti";
$lang['Util.filters.client_filters.field_invoice_method'] = "Metodo di fatturazione";
$lang['Util.filters.client_filters.field_last_seen'] = "Ultima visualizzazione";
$lang['Util.filters.client_filters.field_last_seen_start_date'] = "Data d'inizio";
$lang['Util.filters.client_filters.field_last_seen_end_date'] = "Data di fine";
?>