<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Util.filters.package_filters.any'] = "Qualunque";
$lang['Util.filters.package_filters.services.na'] = "N / A";
$lang['Util.filters.package_filters.services.any'] = "Qualsiasi servizio";
$lang['Util.filters.package_filters.services.canceled'] = "Solo servizi annullati";
$lang['Util.filters.package_filters.services.none'] = "Nessun servizio";
$lang['Util.filters.package_filters.options.hidden'] = "Mostra pacchetti nascosti";
$lang['Util.filters.package_filters.field_module_id'] = "Modulo";
$lang['Util.filters.package_filters.field_name'] = "Nome del pacchetto";
$lang['Util.filters.package_filters.field_assigned_services'] = "Servizi assegnati";
$lang['Util.filters.package_filters.field_options'] = "Opzioni";
?>