<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Util.filters.quotation_filters.any'] = "Qualunque";
$lang['Util.filters.quotation_filters.field_quotation_number'] = "Quotazione #";
$lang['Util.filters.quotation_filters.field_currency'] = "Valuta";
$lang['Util.filters.quotation_filters.field_quotation_line'] = "Contenuto dell'elemento pubblicitario";
?>