<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Util.filters.transaction_filters.any'] = "Qualunque";
$lang['Util.filters.transaction_filters.fully_applied'] = "Completamente applicato";
$lang['Util.filters.transaction_filters.partially_applied'] = "Parzialmente applicato";
$lang['Util.filters.transaction_filters.not_applied'] = "Non applicato";
$lang['Util.filters.transaction_filters.field_payment_type'] = "Modalità di pagamento";
$lang['Util.filters.transaction_filters.field_transaction_id'] = "Numero";
$lang['Util.filters.transaction_filters.field_reference_id'] = "Riferimento";
$lang['Util.filters.transaction_filters.field_applied_status'] = "Stato applicato";
$lang['Util.filters.transaction_filters.field_date'] = "Data";
$lang['Util.filters.transaction_filters.field_start_date'] = "Data d'inizio";
$lang['Util.filters.transaction_filters.field_end_date'] = "Data di fine";
$lang['Util.filters.transaction_filters.field_amount'] = "Quantità";
$lang['Util.filters.transaction_filters.field_minimum_amount'] = "Quantità minima";
$lang['Util.filters.transaction_filters.field_maximum_amount'] = "Importo massimo";
?>