<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CmsPages.!error.uri.empty'] = "Inserisci il percorso URI della pagina.";
$lang['CmsPages.!error.company_id.exists'] = "ID azienda non valido.";
$lang['CmsPages.!error.title.empty'] = "Perfavore inserisci un titolo della pagina.";
$lang['CmsPages.!error.content.valid'] = "Errore di analisi del contenuto: %1\$s"; // %1$s is the parse error
?>