<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CmsPlugin.name'] = "Portale";
$lang['CmsPlugin.index.title'] = "Portale clienti";
$lang['CmsPlugin.description'] = "Il portale consente di impostare il contenuto della pagina da visualizzare nell'URL della home page di Blesta.";
?>