<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['HCaptcha.name'] = "hCaptcha";
$lang['HCaptcha.options.field_hcaptcha_site_key'] = "Chiave del sito hCaptcha";
$lang['HCaptcha.options.field_hcaptcha_secret_key'] = "hChiave segreta Captcha";
?>