<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ReCaptcha.name'] = "reCaptcha";
$lang['ReCaptcha.options.field_recaptcha_pub_key'] = "Chiave del sito reCaptcha";
$lang['ReCaptcha.options.field_recaptcha_shared_key'] = "Chiave condivisa reCaptcha";
?>