<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Braintree.name'] = "Braintree";
$lang['Braintree.merchant_id'] = "ID Commerciante";
$lang['Braintree.public_key'] = "Chiave pubblica";
$lang['Braintree.private_key'] = "Chiave privata";
$lang['Braintree.live_mode'] = "Modalità dal vivo";
$lang['Braintree.environment'] = "Ambiente";
$lang['Braintree.environment.sandbox'] = "Sabbiera";
$lang['Braintree.environment.production'] = "Produzione";
$lang['Braintree.!error.live_mode.valid'] = "La modalità live deve essere impostata su \"true\" se fornita.";
$lang['Braintree.!error.merchant_id'] = "Inserisci il tuo ID commerciante.";
$lang['Braintree.!error.public_key'] = "Per piacere inserisci la tua chiave pubblica.";
$lang['Braintree.!error.private_key'] = "Inserisci la tua chiave privata.";
$lang['Braintree.!error.environment'] = "Seleziona un ambiente valido.";
$lang['Braintree.description'] = "I commercianti in più di 45 paesi/regioni in tutto il mondo possono accettare, dividere e abilitare pagamenti in più di 130 valute utilizzando Braintree";
?>