<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Hubtel.name'] = "Hubtel";
$lang['Hubtel.client_id'] = "Identificativo cliente";
$lang['Hubtel.client_secret'] = "Segreto del cliente";
$lang['Hubtel.buildprocess.submit'] = "Paga con Hubtel";
$lang['Hubtel.!error.client_id.valid'] = "È necessario inserire un ID cliente valido.";
$lang['Hubtel.!error.client_secret.valid'] = "È necessario inserire un segreto client valido.";
$lang['Hubtel.description'] = "Hubtel è la principale piattaforma mobile di aggregazione e pagamenti a valore aggiunto del Ghana";
?>