<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MaxmindV2.!error.reject.private_ip'] = "Non vengono accettati ordini provenienti da IP privati.";
$lang['MaxmindV2.!error.review.private_ip'] = "Gli ordini provenienti da IP privati sono in fase di revisione.";
$lang['MaxmindV2.!error.reject.reject_score'] = "Il tuo ordine non può essere elaborato in questo momento.";
$lang['MaxmindV2.!error.review.review_score'] = "Il tuo ordine deve essere rivisto manualmente.";
$lang['MaxmindV2.!error.reject.free_email'] = "Non vengono accettati ordini con account di posta elettronica gratuiti.";
$lang['MaxmindV2.!error.review.free_email'] = "Gli ordini con account e-mail gratuiti sono in fase di revisione.";
$lang['MaxmindV2.!error.reject.country_mismatch'] = "Gli ordini con mancate corrispondenze nazionali non vengono accettati.";
$lang['MaxmindV2.!error.review.country_mismatch'] = "Gli ordini con mancate corrispondenze nazionali sono in fase di revisione.";
$lang['MaxmindV2.!error.reject.risky_country'] = "Non vengono accettati ordini provenienti da paesi a rischio.";
$lang['MaxmindV2.!error.review.risky_country'] = "Gli ordini provenienti da paesi a rischio sono in fase di revisione.";
$lang['MaxmindV2.!error.reject.anon_proxy'] = "Non vengono accettati ordini provenienti da proxy anonimi.";
$lang['MaxmindV2.!error.review.anon_proxy'] = "Gli ordini provenienti da proxy anonimi sono in fase di revisione.";
$lang['MaxmindV2.settings.tooltip.enable_js'] = "Questa opzione inserisce un codice JavaScript in tutti i moduli d'ordine, che consente a MaxMind di raccogliere e monitorare ulteriori informazioni dell'utente. L'abilitazione di questa opzione migliora la precisione dei risultati.";
$lang['MaxmindV2.settings.field_server'] = "server";
$lang['MaxmindV2.settings.field_account_id'] = "Account ID";
$lang['MaxmindV2.settings.field_key'] = "Chiave di licenza";
$lang['MaxmindV2.settings.field_minfraud_api'] = "API minFraud";
$lang['MaxmindV2.settings.field_reject_score'] = "Punteggio minimo per rifiutare";
$lang['MaxmindV2.settings.field_review_score'] = "Punteggio minimo per la revisione";
$lang['MaxmindV2.settings.field_free_email'] = "E-mail gratuita";
$lang['MaxmindV2.settings.field_country_mismatch'] = "Mancata corrispondenza del paese";
$lang['MaxmindV2.settings.field_risky_country'] = "View the Google Translation";
$lang['MaxmindV2.settings.field_anon_proxy'] = "proxy anonimo";
$lang['MaxmindV2.settings.field_private_ip'] = "IP privato";
$lang['MaxmindV2.settings.field_enable_js'] = "Abilita il componente aggiuntivo di monitoraggio JavaScript";
$lang['MaxmindV2.settings.option_score'] = "minPunteggio frode";
$lang['MaxmindV2.settings.option_insights'] = "minInformazioni sulle frodi";
$lang['MaxmindV2.settings.option_factors'] = "minFattori di frode";
$lang['MaxmindV2.settings.option_allow'] = "Permettere";
$lang['MaxmindV2.settings.option_review'] = "Revisione";
$lang['MaxmindV2.settings.option_reject'] = "Respingi";
$lang['MaxmindV2.settings.option_enable'] = "Abilitare";
$lang['MaxmindV2.settings.option_disable'] = "disattivare";
?>