<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AgingInvoices.name'] = "Fatture invecchiate";
$lang['AgingInvoices.options.field_status'] = "Stato";
$lang['AgingInvoices.option.any'] = "Qualunque";
$lang['AgingInvoices.heading.id_code'] = "Fattura #";
$lang['AgingInvoices.heading.client_id_code'] = "Cliente #";
$lang['AgingInvoices.heading.subtotal'] = "View the Google Translation";
$lang['AgingInvoices.heading.total'] = "Totale";
$lang['AgingInvoices.heading.paid'] = "Pagato";
$lang['AgingInvoices.heading.currency'] = "Valuta";
$lang['AgingInvoices.heading.status'] = "Stato";
$lang['AgingInvoices.heading.date_billed'] = "Data di fatturazione";
$lang['AgingInvoices.heading.date_due'] = "Data di scadenza";
$lang['AgingInvoices.heading.past30'] = "30";
$lang['AgingInvoices.heading.past60'] = "60";
$lang['AgingInvoices.heading.past90'] = "90+";
$lang['AgingInvoices.heading.client_first_name'] = "Nome del cliente";
$lang['AgingInvoices.heading.client_last_name'] = "Cognome del cliente";
$lang['AgingInvoices.heading.client_email'] = "E-mail del cliente";
$lang['AgingInvoices.heading.client_numbers'] = "Numeri di telefono dei clienti";
?>