<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Util.Tax.united_kingdom_tax.tax_provider_name'] = "IVA HMRC del Regno Unito";
$lang['Util.Tax.united_kingdom_tax.tax_name'] = "I.V.A.";
$lang['Util.Tax.united_kingdom_tax.tax_id_name'] = "Partita IVA";
$lang['Util.Tax.united_kingdom_tax.tax_note'] = "%1\$s (%2\$s%%)"; // %1$s is the name of the tax and %2$s the amount of the tax
$lang['Util.Tax.united_kingdom_tax.tax_deduction_note'] = "%1\$s Detrazione (%2\$s%%)"; // %1$s is the name of the tax and %2$s the amount of the tax
$lang['Util.Tax.united_kingdom_tax.tax_note_domestic_reverse_charge'] = "Si applica la sezione 55A della legge sull'IVA del 1994 sull'addebito inverso. Il cliente deve rendere conto dell'IVA all'HMRC all'aliquota indicata.";
$lang['Util.Tax.united_kingdom_tax.fields.country_uk'] = "Regno Unito";
$lang['Util.Tax.united_kingdom_tax.fields.enable_uk_vat'] = "Abilita la convalida dell'IVA nel Regno Unito";
$lang['Util.Tax.united_kingdom_tax.fields.note_enable_uk_vat'] = "Seleziona questa opzione per abilitare la convalida della partita IVA nel Regno Unito per questa azienda.";
$lang['Util.Tax.united_kingdom_tax.fields.tax_exempt_uk_vat'] = "Impostato automaticamente come esentasse";
$lang['Util.Tax.united_kingdom_tax.fields.note_tax_exempt_uk_vat'] = "Imposta automaticamente un cliente come esente da tasse se il suo numero di partita IVA è valido.";
$lang['Util.Tax.united_kingdom_tax.fields.tax_intra_eu_uk_vat'] = "Trattare le transazioni come scambi intra-UE";
$lang['Util.Tax.united_kingdom_tax.fields.note_tax_intra_eu_uk_vat'] = "A causa della Brexit, il Regno Unito non è più membro dell'UE e tutte le transazioni effettuate al di fuori del Regno Unito saranno trattate come transazioni estere. L'abilitazione di questa opzione tratterà tutte le transazioni effettuate all'interno di un membro dell'UE come un'operazione intra-UE e verrà applicato il principio dell'inversione contabile.";
?>