<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Stripe_gateway.!error.auth'] = "Il gateway non è riuscito ad autenticarsi.";
$lang['Stripe_gateway.!error.api_key.empty'] = "Inserisci una chiave API.";
$lang['Stripe_gateway.!error.json_required'] = "Per questo gateway è richiesta l'estensione JSON.";
$lang['Stripe_gateway.name'] = "Striscia";
$lang['Stripe_gateway.api_key'] = "Chiave segreta dell'API";
$lang['Stripe_gateway.tooltip_api'] = "La tua chiave segreta API è specifica per la modalità live o test. Assicurati di utilizzare la chiave corretta.";
$lang['Stripe_gateway.stored'] = "Memorizza le informazioni sulla carta fuori sede";
$lang['Stripe_gateway.tooltip_stored'] = "Seleziona questa casella per archiviare i dati della carta del conto di pagamento con Stripe anziché in Blesta.";
$lang['Stripe_gateway.charge_description'] = "Addebito per %1\$s"; // Where %1$s is a comma seperated list of invoice ID display codes
$lang['Stripe_gateway.description'] = "Questo è il gateway Stripe legacy che utilizza Stripe Checkout. Richiede che il tuo account Stripe sia aggiornato a \"Elabora i pagamenti in modo non sicuro\". Ti consigliamo invece di utilizzare il gateway Stripe Payments in Blesta";
?>