<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PayJunction.name'] = "PayJunction";
$lang['PayJunction.api_key'] = "Chiave API";
$lang['PayJunction.user_name'] = "Nome utente";
$lang['PayJunction.password'] = "Parola d'ordine";
$lang['PayJunction.test_mode'] = "Modalità sviluppatore";
$lang['PayJunction.api_key_note'] = "Inserisci la chiave API dal tuo account PayJunction.";
$lang['PayJunction.user_name_note'] = "Inserisci il nome utente del tuo account PayJunction.";
$lang['PayJunction.password_note'] = "Inserisci la password del tuo account PayJunction.";
$lang['PayJunction.test_mode_note'] = "L'abilitazione della modalità sviluppatore pubblicherà le transazioni nell'ambiente demo di PayJunction Labs. Per utilizzare la modalità sviluppatore è necessario utilizzare il nome utente e la password della demo, nonché la chiave API Labs.";
$lang['PayJunction.!error.api_key.empty'] = "Inserisci una chiave API valida.";
$lang['PayJunction.!error.user_name.empty'] = "Inserisci il nome utente del tuo account.";
$lang['PayJunction.!error.password.empty'] = "Inserisci la password del tuo account.";
$lang['PayJunction.!error.test_mode.valid'] = "Modalità sviluppatore deve essere impostata su 'true' se dato.";
$lang['PayJunction.description'] = "PayJunction elabora 4 miliardi di dollari all'anno e sta crescendo rapidamente. La sua tecnologia è ideale per le aziende con più sedi e più dipartimenti che elaborano un volume mensile di carte di credito pari o superiore a 10.000 dollari";
?>