<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.apply_payments.attempt'] = "Tentativo di applicare crediti alle fatture aperte.";
$lang['Automation.task.apply_payments.completed'] = "L'attività di applicazione dei crediti è stata completata.";
$lang['Automation.task.apply_payments.attempt_group'] = "Tentativo di applicare crediti per il gruppo clienti %1\$s."; // %1$s is the name of the client group
$lang['Automation.task.apply_payments.completed_group'] = "Applicazione dei crediti per il gruppo di clienti %1\$s completata."; // %1$s is the name of the client group
$lang['Automation.task.apply_payments.apply_failed'] = "Impossibile applicare crediti in sospeso per il cliente #%1\$s."; // %1$s is the client ID
$lang['Automation.task.apply_payments.apply_success'] = "Crediti in sospeso applicati con successo dalla transazione %1\$s per il cliente #%2\$s alla fattura #%3\$s per un importo di %4\$s."; // %1$s is the transaction number, %2$s is the client ID, %3$s is the invoice ID, and %4$s is the amount applied
$lang['Automation.task.apply_payments.apply_none'] = "Non ci sono fatture a cui possono essere applicati crediti.";
?>