<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.autodebit.attempt'] = "Tentativo di addebito automatico delle fatture aperte.";
$lang['Automation.task.autodebit.completed'] = "L'attività di addebito automatico delle fatture è stata completata.";
$lang['Automation.task.autodebit.charge_attempt'] = "Tentativo di addebito automatico al cliente #%1\$s per tutte le fatture aperte per un importo di %2\$s."; // %1$s is the client ID, %2$s is the amount due
$lang['Automation.task.autodebit.charge_failed'] = "Impossibile elaborare il pagamento.";
$lang['Automation.task.autodebit.charge_success'] = "Pagamento elaborato con successo.";
?>