<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.backups_amazons3.attempt'] = "Tentativo di eseguire il backup del database su AmazonS3.";
$lang['Automation.task.backups_amazons3.completed'] = "L'attività di backup del database AmazonS3 è stata completata.";
$lang['Automation.task.backups_amazons3.success'] = "Il backup è stato completato con successo.";
?>