<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.card_expiration_reminders.attempt'] = "Tentativo di inviare promemoria di scadenza della carta.";
$lang['Automation.task.card_expiration_reminders.completed'] = "L'attività di promemoria della scadenza della carta è stata completata.";
$lang['Automation.task.card_expiration_reminders.failed'] = "Impossibile inviare il promemoria di scadenza per il contatto %1\$s %2\$s dal client #%3\$s."; // %1$s is the contact's first name, %2$s is the contact's last name, %3$s is the client ID
$lang['Automation.task.card_expiration_reminders.success'] = "Promemoria di scadenza consegnato con successo per il contatto %1\$s %2\$s dal cliente #%3\$s."; // %1$s is the contact's first name, %2$s is the contact's last name, %3$s is the client ID
?>