<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.cleanup_logs.attempt'] = "Tentativo di ripulire i vecchi registri.";
$lang['Automation.task.cleanup_logs.completed'] = "L'attività di pulizia dei registri è stata completata.";
$lang['Automation.task.cleanup_logs.logs_gateway_deleted'] = "%1\$s vecchi log del gateway sono stati eliminati."; // %1$s is the number of logs deleted
$lang['Automation.task.cleanup_logs.logs_module_deleted'] = "%1\$s vecchi log del modulo sono stati eliminati."; // %1$s is the number of logs deleted
$lang['Automation.task.cleanup_logs.logs_accountaccess_deleted'] = "%1\$s vecchi registri di accesso all'account sono stati eliminati."; // %1$s is the number of logs deleted
$lang['Automation.task.cleanup_logs.logs_contact_deleted'] = "%1\$s vecchi registri dei contatti sono stati eliminati."; // %1$s is the number of logs deleted
$lang['Automation.task.cleanup_logs.logs_email_deleted'] = "%1\$s vecchi registri email sono stati eliminati."; // %1$s is the number of logs deleted
$lang['Automation.task.cleanup_logs.logs_messenger_deleted'] = "%1\$s vecchi log di Messenger sono stati eliminati."; // %1$s is the number of logs deleted
$lang['Automation.task.cleanup_logs.logs_user_deleted'] = "%1\$s vecchi registri utente sono stati eliminati."; // %1$s is the number of logs deleted
$lang['Automation.task.cleanup_logs.logs_client_settings_deleted'] = "%1\$s vecchi registri delle impostazioni del client sono stati eliminati."; // %1$s is the number of logs deleted
$lang['Automation.task.cleanup_logs.logs_service_deleted'] = "%1\$s vecchi log di servizio sono stati eliminati."; // %1$s is the number of logs deleted
$lang['Automation.task.cleanup_logs.logs_transaction_deleted'] = "%1\$s vecchi log delle transazioni sono stati eliminati."; // %1$s is the number of logs deleted
$lang['Automation.task.cleanup_logs.logs_cron_deleted'] = "%1\$s vecchi registri Cron sono stati eliminati."; // %1$s is the number of logs deleted
?>