<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.create_invoices.attempt'] = "Tentativo di rinnovare i servizi e creare fatture.";
$lang['Automation.task.create_invoices.completed'] = "L'attività di creazione delle fatture è stata completata.";
$lang['Automation.task.create_invoices.recurring_invoice_failed'] = "Impossibile creare una nuova fattura dalla fattura ricorrente #%1\$s per il cliente #%2\$s."; // %1$s is the recurring invoice number, %2$s is the client ID
$lang['Automation.task.create_invoices.recurring_invoice_success'] = "Creazione di una nuova fattura dalla fattura ricorrente #%1\$s per il cliente #%2\$s riuscita."; // %1$s is the recurring invoice number, %2$s is the client ID
$lang['Automation.task.create_invoices.service_invoice_success'] = "Creazione della fattura n. %1\$s per il cliente n. %2\$s contenente i servizi %3\$s riuscita."; // %1$s is the invoice ID, %2$s is the client ID, %3$s is a comma-separated list of service IDs
$lang['Automation.task.create_invoices.service_invoice_error'] = "Impossibile generare la fattura per il client #%2\$s contenente i servizi %3\$s perché: %1\$s"; // %1$s is a dump of all errors, %2$s is the client ID, %3$s is a comma-separated list of service IDs
?>