<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.exchange_rates.attempt'] = "Tentativo di aggiornare i tassi di cambio.";
$lang['Automation.task.exchange_rates.completed'] = "L'attività sui tassi di cambio è stata completata.";
$lang['Automation.task.exchange_rates.success'] = "I tassi di cambio sono stati aggiornati con successo.";
$lang['Automation.task.exchange_rates.failed'] = "Impossibile aggiornare i tassi di cambio.";
?>