<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.module.attempt'] = "Tentativo di cron del modulo per %1\$s %2\$s."; // %1$s is the module class, %2$s is the module cron task key
$lang['Automation.task.module.completed'] = "Modulo cron terminato per %1\$s %2\$s."; // %1$s is the module class, %2$s is the module cron task key
?>