<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.payment_reminders.attempt'] = "Tentativo di invio di solleciti di pagamento.";
$lang['Automation.task.payment_reminders.completed'] = "The payment reminders task has completed.";
$lang['Automation.task.payment_reminders.failed'] = "Impossibile inviare l'avviso di sollecito per la fattura #%4\$s al contatto %1\$s %2\$s dal cliente #%3\$s."; // %1$s is the contact's first name, %2$s is the contact's last name, %3$s is the client ID, %4$s is the invoice ID
$lang['Automation.task.payment_reminders.success'] = "Inviato con successo l'avviso di sollecito per la fattura n. %4\$s per contattare %1\$s %2\$s dal cliente n. %3\$s."; // %1$s is the contact's first name, %2$s is the contact's last name, %3$s is the client ID, %4$s is the invoice ID
$lang['Automation.task.payment_reminders.autodebit_failed'] = "Impossibile inviare l'avviso di promemoria dell'addebito automatico per la fattura #%4\$s al contatto %1\$s %2\$s dal cliente #%3\$s."; // %1$s is the contact's first name, %2$s is the contact's last name, %3$s is the client ID, %4$s is the invoice ID
$lang['Automation.task.payment_reminders.autodebit_success'] = "Inviato con successo l'avviso di promemoria dell'addebito automatico per la fattura n. %4\$s al contatto %1\$s %2\$s dal cliente n. %3\$s."; // %1$s is the contact's first name, %2$s is the contact's last name, %3$s is the client ID, %4$s is the invoice ID
?>