<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.process_renewing_services.attempt'] = "Tentativo di elaborare il rinnovo dei servizi.";
$lang['Automation.task.process_renewing_services.completed'] = "L'attività di rinnovo dei servizi del processo è stata completata.";
$lang['Automation.task.process_renewing_services.renew_success'] = "Servizio rinnovato #%1\$s per il client %2\$s."; // %1$s is the service ID, %2$s is the client ID
$lang['Automation.task.process_renewing_services.renew_error'] = "Impossibile rinnovare il servizio #%1\$s per il client %2\$s."; // %1$s is the service ID, %2$s is the client ID
?>