<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Vesta.name'] = "Vesta";
$lang['Vesta.module_row'] = "server";
$lang['Vesta.module_row_plural'] = "Server";
$lang['Vesta.module_group'] = "Gruppo di server";
$lang['Vesta.tab_stats'] = "Statistiche";
$lang['Vesta.tab_client_actions'] = "Azioni";
$lang['Vesta.submit'] = "Invia";
$lang['Vesta.tab_stats.info.WEB_DOMAINS'] = "Domini";
$lang['Vesta.tab_stats.info.WEB_ALIASES'] = "Alias";
$lang['Vesta.tab_stats.info.DNS_DOMAINS'] = "Domini DNS";
$lang['Vesta.tab_stats.info.DNS_RECORDS'] = "Record DNS";
$lang['Vesta.tab_stats.info.MAIL_DOMAINS'] = "Domini di posta";
$lang['Vesta.tab_stats.info.MAIL_ACCOUNTS'] = "Account di posta";
$lang['Vesta.tab_stats.info.DATABASES'] = "Banche dati";
$lang['Vesta.tab_stats.info.CRON_JOBS'] = "Lavori Cron";
$lang['Vesta.tab_stats.info.DISK_QUOTA'] = "Uso del disco";
$lang['Vesta.tab_stats.info.BANDWIDTH'] = "Utilizzo della larghezza di banda";
$lang['Vesta.tab_stats.info.BACKUPS'] = "Backup";
$lang['Vesta.add_module_row'] = "Aggiungi server";
$lang['Vesta.add_module_group'] = "Aggiungi gruppo di server";
$lang['Vesta.manage.module_rows_title'] = "server";
$lang['Vesta.manage.module_groups_title'] = "Gruppi di server";
$lang['Vesta.manage.module_rows_heading.name'] = "Etichetta del server";
$lang['Vesta.manage.module_rows_heading.hostname'] = "hostname";
$lang['Vesta.manage.module_rows_heading.port'] = "Porta";
$lang['Vesta.manage.module_rows_heading.accounts'] = "Conti";
$lang['Vesta.manage.module_rows_heading.options'] = "Opzioni";
$lang['Vesta.manage.module_groups_heading.name'] = "Nome del gruppo";
$lang['Vesta.manage.module_groups_heading.servers'] = "Conteggio server";
$lang['Vesta.manage.module_groups_heading.options'] = "Opzioni";
$lang['Vesta.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Vesta.manage.module_rows.edit'] = "Modificare";
$lang['Vesta.manage.module_groups.edit'] = "Modificare";
$lang['Vesta.manage.module_rows.delete'] = "Eliminare";
$lang['Vesta.manage.module_groups.delete'] = "Eliminare";
$lang['Vesta.manage.module_rows.confirm_delete'] = "Sei sicuro di voler eliminare questo server?";
$lang['Vesta.manage.module_groups.confirm_delete'] = "Sei sicuro di voler eliminare questo gruppo di server?";
$lang['Vesta.manage.module_rows_no_results'] = "Non ci sono server.";
$lang['Vesta.manage.module_groups_no_results'] = "Non sono presenti gruppi di server.";
$lang['Vesta.order_options.first'] = "Primo server non completo";
$lang['Vesta.add_row.box_title'] = "Aggiungi Vesta Server";
$lang['Vesta.add_row.basic_title'] = "Impostazioni di base";
$lang['Vesta.add_row.remove_name_server'] = "Rimuovere";
$lang['Vesta.add_row.add_btn'] = "Aggiungi server";
$lang['Vesta.edit_row.box_title'] = "Modifica il server Vesta";
$lang['Vesta.edit_row.basic_title'] = "Impostazioni di base";
$lang['Vesta.edit_row.remove_name_server'] = "Rimuovere";
$lang['Vesta.edit_row.add_btn'] = "Modifica server";
$lang['Vesta.row_meta.server_name'] = "Etichetta del server";
$lang['Vesta.row_meta.host_name'] = "Nome host";
$lang['Vesta.row_meta.user_name'] = "Nome utente";
$lang['Vesta.row_meta.password'] = "Parola d'ordine";
$lang['Vesta.row_meta.port'] = "Porta";
$lang['Vesta.row_meta.use_ssl'] = "Utilizza SSL quando ti connetti all'API (consigliato)";
$lang['Vesta.package_fields.package_name'] = "Nome del pacchetto Vesta";
$lang['Vesta.package_fields.package_name_how_to'] = "Puoi ottenere il nome del pacchetto accedendo al tuo Pannello di controllo Vesta > Pacchetti";
$lang['Vesta.service_field.domain'] = "Nome del dominio";
$lang['Vesta.service_field.username'] = "Nome utente";
$lang['Vesta.service_field.password'] = "Parola d'ordine";
$lang['Vesta.stored_locally_only'] = "Questo campo verrà aggiornato solo localmente";
$lang['Vesta.service_info.hostname'] = "Nome host";
$lang['Vesta.service_info.username'] = "Nome utente";
$lang['Vesta.service_info.password'] = "Parola d'ordine";
$lang['Vesta.service_info.server'] = "server";
$lang['Vesta.service_info.options'] = "Opzioni";
$lang['Vesta.service_info.option_login'] = "Login";
$lang['Vesta.tab_client_actions.change_password'] = "Cambia Password";
$lang['Vesta.tab_client_actions.password'] = "Parola d'ordine";
$lang['Vesta.tab_client_actions.confirm_password'] = "Conferma password";
$lang['Vesta.tab_stats.info_heading.field'] = "Campo";
$lang['Vesta.tab_stats.info_heading.value'] = "Valore";
$lang['Vesta.!error.server_name_valid'] = "È necessario inserire un'etichetta server.";
$lang['Vesta.!error.host_name_valid'] = "Il nome host sembra non essere valido.";
$lang['Vesta.!error.user_name_valid'] = "Il nome utente sembra non essere valido.";
$lang['Vesta.!error.port_valid'] = "La porta sembra non essere valida.";
$lang['Vesta.!error.password_valid'] = "La password sembra non essere valida.";
$lang['Vesta.!error.meta[package_name].empty'] = "Inserisci il nome del pacchetto Vesta.";
$lang['Vesta.!error.api.internal'] = "Si è verificato un errore interno oppure il server non ha risposto alla richiesta.";
$lang['Vesta.!error.module_row.missing'] = "Si è verificato un errore interno. La riga del modulo non è disponibile.";
$lang['Vesta.!error.domain.format'] = "Inserisci un nome di dominio valido, ad es. dominio.com.";
$lang['Vesta.!error.domain.test'] = "Il nome di dominio non può iniziare con \"test\".";
$lang['Vesta.!error.user_name.empty'] = "Il nome utente non può essere vuoto.";
$lang['Vesta.!error.password.valid'] = "La password deve contenere almeno 8 caratteri.";
$lang['Vesta.!error.actions_password.valid'] = "I campi Password e Conferma password non possono essere vuoti.";
$lang['Vesta.description'] = "Vesta, o VestaCP, è un pannello di controllo web open source considerato un'ottima alternativa a cPanel. Non solo la sua sicurezza e i suoi aggiornamenti frequenti corrispondono in termini di qualità a quelli di cPanel, ma è anche completamente gratuito.";
?>