<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMerchant.getsupportedfeatures.cc'] = "Carta di credito";
$lang['AdminMerchant.getsupportedfeatures.cc_offsite'] = "Carta di credito fuori sede";
$lang['AdminMerchant.getsupportedfeatures.cc_form'] = "Modulo personalizzato per carta di credito";
$lang['AdminMerchant.getsupportedfeatures.ach'] = "ACH";
$lang['AdminMerchant.getsupportedfeatures.ach_offsite'] = "ACH fuori sede";
$lang['AdminMerchant.getsupportedfeatures.tooltip_cc'] = "Elaborazione della carta di credito utilizzando credenziali non memorizzate o archiviate in Blesta.";
$lang['AdminMerchant.getsupportedfeatures.tooltip_cc_offsite'] = "Elaborazione della carta di credito utilizzando credenziali archiviate fuori sede dal processore.";
$lang['AdminMerchant.getsupportedfeatures.tooltip_cc_form'] = "Ciò consente a un gateway di fornire codice HTML personalizzato per i moduli delle carte di credito. Questo ha lo scopo di supportare le carte di credito esterne che possono utilizzare iframe o richiedere campi aggiuntivi.";
$lang['AdminMerchant.getsupportedfeatures.tooltip_ach'] = "Elaborazione automatizzata della stanza di compensazione utilizzando credenziali non archiviate o archiviate in Blesta.";
$lang['AdminMerchant.getsupportedfeatures.tooltip_ach_offsite'] = "Elaborazione automatizzata della stanza di compensazione utilizzando le credenziali archiviate fuori sede dal processore.";
$lang['AdminMerchant.index.page_title'] = "Generatore di estensioni - %1\$s"; // %1$s is the plugin name
$lang['AdminMerchant.index.boxtitle_extension_generator'] = "Generatore di estensioni - Gateway commerciante";
$lang['AdminMerchant.basic.heading_basic'] = "Informazioni di base";
$lang['AdminMerchant.basic.heading_authors'] = "Autori";
$lang['AdminMerchant.basic.description'] = "Descrizione";
$lang['AdminMerchant.basic.logo'] = "Logo";
$lang['AdminMerchant.basic.signup_url'] = "URL di registrazione";
$lang['AdminMerchant.basic.currencies'] = "Valute";
$lang['AdminMerchant.basic.author_name'] = "Nome dell'autore";
$lang['AdminMerchant.basic.author_url'] = "URL dell'autore";
$lang['AdminMerchant.basic.text_options'] = "Opzioni";
$lang['AdminMerchant.basic.author_row_add'] = "Aggiungi autore";
$lang['AdminMerchant.basic.text_remove'] = "Rimuovere";
$lang['AdminMerchant.basic.tooltip_description'] = "La descrizione mostrata nell'elenco dei plugin";
$lang['AdminMerchant.basic.tooltip_logo'] = "Il logo visualizzato nell'elenco dei plugin. Le immagini non vengono ridimensionate, quindi le dimensioni ideali sono 150x70";
$lang['AdminMerchant.basic.tooltip_signup_url'] = "L'URL della pagina di registrazione del gateway";
$lang['AdminMerchant.basic.tooltip_currencies'] = "Un elenco separato da virgole delle valute supportate (ad esempio USD, JPY, EUR)";
$lang['AdminMerchant.basic.placeholder_signup_url'] = "per esempio. https://dashboard.stripe.com/register";
$lang['AdminMerchant.basic.placeholder_currencies'] = "per esempio. USD,EUR,JPY";
$lang['AdminMerchant.basic.placeholder_author_name'] = "per esempio. Blesta";
$lang['AdminMerchant.basic.placeholder_author_url'] = "per esempio. https://blesta.com/";
$lang['AdminMerchant.basic.fields'] = "Successivo: Campi di configurazione";
$lang['AdminMerchant.basic.features'] = "Successivo - Funzionalità supportate";
$lang['AdminMerchant.fields.heading_fields'] = "Campi di configurazione";
$lang['AdminMerchant.fields.name'] = "Nome";
$lang['AdminMerchant.fields.label'] = "Etichetta";
$lang['AdminMerchant.fields.type'] = "Tipo";
$lang['AdminMerchant.fields.tooltip'] = "Testo della descrizione comando";
$lang['AdminMerchant.fields.encryptable'] = "Crittografabile";
$lang['AdminMerchant.fields.tooltip_name'] = "Il nome del campo nel codebase";
$lang['AdminMerchant.fields.tooltip_label'] = "Il nome visualizzato del campo";
$lang['AdminMerchant.fields.tooltip_type'] = "Il tipo di campo da creare (casella di controllo, testo, ecc.)";
$lang['AdminMerchant.fields.tooltip_tooltip'] = "Il testo del tooltip da visualizzare a lato del campo (lasciare vuoto per non avere tooltip)";
$lang['AdminMerchant.fields.tooltip_encryptable'] = "Se crittografare questo campo nel database";
$lang['AdminMerchant.fields.placeholder_name'] = "per esempio. campo_configurazione";
$lang['AdminMerchant.fields.placeholder_label'] = "per esempio. Campo di configurazione";
$lang['AdminMerchant.fields.field_row_add'] = "Aggiungi campo di configurazione";
$lang['AdminMerchant.fields.text_options'] = "Opzioni";
$lang['AdminMerchant.fields.text_remove'] = "Rimuovere";
$lang['AdminMerchant.fields.features'] = "Successivo - Funzionalità supportate";
$lang['AdminMerchant.features.heading_supported_features'] = "Funzionalità supportate";
$lang['AdminMerchant.features.confirm'] = "Avanti: Conferma";
?>