<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ExtensionGeneratorPlugin.name'] = "Generatore di estensioni";
$lang['ExtensionGeneratorPlugin.description'] = "Questo è un plugin per generare automaticamente file per le nuove estensioni Blesta";
$lang['ExtensionGeneratorPlugin.nav_secondary_staff.admin_main'] = "Generatore di estensioni";
?>