<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FormRules.general.name.format'] = "I nomi delle estensioni possono contenere solo caratteri alfa_numerici, trattini bassi e spazi.";
$lang['FormRules.modulebasic.module_row.empty'] = "Inserisci il nome della riga del modulo.";
$lang['FormRules.modulebasic.module_row_plural.empty'] = "Aggiungi un nome di riga del modulo plurale.";
$lang['FormRules.modulebasic.module_group.empty'] = "Inserisci un'etichetta per il gruppo di moduli.";
$lang['FormRules.modulebasic.authors[][name].empty'] = "Inserisci un nome per ogni autore.";
$lang['FormRules.modulefields.module_rows[][name].format'] = "Inserisci un nome per ogni campo della riga del modulo nel formato nome_caso_serpente.";
$lang['FormRules.modulefields.module_rows[][label].empty'] = "Inserisci un'etichetta per ogni campo della riga del modulo.";
$lang['FormRules.modulefields.module_rows[][type].valid'] = "Una o più righe del modulo hanno un tipo non valido.";
$lang['FormRules.modulefields.module_rows[][name_key].valid'] = "Se impostare un campo della riga del modulo come chiave del nome deve essere impostato su true o false.";
$lang['FormRules.modulefields.service_fields[][name].format'] = "Inserisci un nome per ciascun campo del servizio nel formato nome_caso_serpente.";
$lang['FormRules.modulefields.service_fields[][label].empty'] = "Inserisci un'etichetta per ciascun campo del servizio.";
$lang['FormRules.modulefields.service_fields[][type].valid'] = "Uno o più campi del servizio hanno un tipo non valido.";
$lang['FormRules.modulefields.service_fields[][name_key].valid'] = "Se impostare un campo del servizio come chiave del nome deve essere impostato su true o false.";
$lang['FormRules.modulefields.package_fields[][name].format'] = "Inserisci un nome per ciascun campo del pacchetto nel formato nome_custodia_serpente.";
$lang['FormRules.modulefields.package_fields[][label].empty'] = "Inserisci un'etichetta per ciascun campo del pacco.";
$lang['FormRules.modulefields.package_fields[][type].valid'] = "Uno o più campi del pacchetto hanno un tipo non valido.";
$lang['FormRules.modulefields.package_fields[][name_key].valid'] = "Se impostare un campo del pacchetto come chiave del nome deve essere impostato su true o false.";
$lang['FormRules.modulefeatures.service_tabs[][method_name].format'] = "Inserisci un nome di metodo per ciascuna scheda di servizio nel formato camelCaseName.";
$lang['FormRules.modulefeatures.service_tabs[][label].empty'] = "Inserisci un'etichetta per ciascuna scheda di servizio.";
$lang['FormRules.modulefeatures.service_tabs[][level].valid'] = "Una o più schede di servizio hanno un livello non valido.";
$lang['FormRules.modulefeatures.cron_tasks[][name].format'] = "Inserisci un nome di metodo per ciascuna attività cron nel formato nome_caso_serpente.";
$lang['FormRules.modulefeatures.cron_tasks[][label].empty'] = "Inserisci un'etichetta per ogni attività cron.";
$lang['FormRules.modulefeatures.cron_tasks[][type].valid'] = "Una o più attività cron hanno un tipo non valido.";
$lang['FormRules.modulefeatures.cron_tasks[][time].format'] = "Inserisci un'ora nel formato 00:00 o un intervallo numerico.";
$lang['FormRules.pluginbasic.authors[][name].empty'] = "Inserisci un nome per ogni autore.";
$lang['FormRules.plugindatabase.tables[][name].format'] = "Inserisci un nome di metodo per ciascuna tabella nel formato nome_caso_serpente.";
$lang['FormRules.plugindatabase.tables[][columns][][name].format'] = "Inserisci un nome di metodo per ciascuna colonna nel formato nome_caso_serpente.";
$lang['FormRules.plugindatabase.tables[][columns][][type].valid'] = "Una o più colonne hanno un tipo non valido.";
$lang['FormRules.plugindatabase.tables[][columns][][length].empty'] = "La lunghezza deve essere nel formato \"a\", \"b\", \"c\" per le colonne enum, vuota per le colonne testo e data/ora e numerica per tutte le altre.";
$lang['FormRules.plugindatabase.tables[][columns][][nullable].valid'] = "Nullable deve essere impostato su true o false per ogni colonna.";
$lang['FormRules.plugindatabase.tables[][columns][][primary].valid'] = "Il primario deve essere impostato su true o false per ogni colonna.";
$lang['FormRules.pluginintegrations.actions[][controller].format'] = "Inserisci un controller per ogni azione nel formato nome_caso_serpente.";
$lang['FormRules.pluginintegrations.actions[][action].format'] = "Inserisci un'azione per ciascuna azione tutta in lettere minuscole.";
$lang['FormRules.pluginintegrations.actions[][name].empty'] = "Inserisci un nome per ciascuna azione.";
$lang['FormRules.pluginintegrations.events[][event].empty'] = "Inserisci un nome evento per ciascun evento.";
$lang['FormRules.pluginintegrations.events[][callback].format'] = "Inserisci un metodo di richiamata per ogni evento nel formato camelCaseName.";
$lang['FormRules.pluginintegrations.cards[][level].valid'] = "Una o più carte hanno un livello non valido.";
$lang['FormRules.pluginintegrations.cards[][callback].format'] = "Inserisci un metodo di richiamata per ciascuna carta nel formato camelCaseName.";
$lang['FormRules.pluginintegrations.cards[][label].empty'] = "Inserisci un'etichetta per ciascuna carta.";
$lang['FormRules.merchantbasic.authors[][name].empty'] = "Inserisci un nome per ogni autore.";
$lang['FormRules.merchantbasic.currencies.format'] = "Inserisci le valute nel formato di tre caratteri separati da virgole (ad esempio USD, EUR, JPY).";
$lang['FormRules.merchantfields.fields[][name].format'] = "Inserisci un nome per ciascun campo nel formato nome_caso_serpente.";
$lang['FormRules.merchantfields.fields[][label].empty'] = "Inserisci un'etichetta per ciascun campo.";
$lang['FormRules.merchantfields.fields[][type].valid'] = "Uno o più campi hanno un tipo non valido.";
$lang['FormRules.nonmerchantbasic.authors[][name].empty'] = "Inserisci un nome per ogni autore.";
$lang['FormRules.nonmerchantbasic.currencies.format'] = "Inserisci le valute nel formato di tre caratteri separati da virgole (ad esempio USD, EUR, JPY).";
$lang['FormRules.nonmerchantfields.fields[][name].format'] = "Inserisci un nome per ciascun campo nel formato nome_caso_serpente.";
$lang['FormRules.nonmerchantfields.fields[][label].empty'] = "Inserisci un'etichetta per ciascun campo.";
$lang['FormRules.nonmerchantfields.fields[][type].valid'] = "View the Google Translation";
$lang['FormRules.pluginintegrations.actions[][location].valid'] = "Inserisci un luogo di azione valido.";
?>