<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DirectAdmin.!error.server_name.empty'] = "È necessario inserire un'etichetta server.";
$lang['DirectAdmin.!error.host_name.format'] = "Il nome host sembra non essere valido.";
$lang['DirectAdmin.!error.user_name.empty'] = "È necessario immettere un nome utente.";
$lang['DirectAdmin.!error.password.format'] = "È necessario inserire una password.";
$lang['DirectAdmin.!error.use_ssl.format'] = "View the Google Translation";
$lang['DirectAdmin.!error.account_limit.valid'] = "Il limite dell'account deve essere lasciato vuoto (per account illimitati) o impostato su un valore intero.";
$lang['DirectAdmin.!error.name_servers.valid'] = "Uno o più server dei nomi inseriti non sono validi.";
$lang['DirectAdmin.!error.name_servers.count'] = "È necessario definire almeno 2 server dei nomi.";
$lang['DirectAdmin.!error.api.internal'] = "Si è verificato un errore interno oppure il server non ha risposto alla richiesta.";
$lang['DirectAdmin.!error.meta[type].format'] = "Il tipo di account deve essere utente o rivenditore.";
$lang['DirectAdmin.!error.meta[package].empty'] = "È richiesto un pacchetto DirectAdmin.";
$lang['DirectAdmin.!error.meta[ip].empty'] = "È richiesto un indirizzo IP.";
$lang['DirectAdmin.!error.direct_admin_domain.format'] = "Inserisci un nome di dominio valido nel modulo: dominio.com";
$lang['DirectAdmin.!error.direct_admin_username.format'] = "Il nome utente può contenere solo caratteri alfanumerici.";
$lang['DirectAdmin.!error.direct_admin_username.length'] = "Il nome utente deve avere una lunghezza compresa tra 4 e 8 caratteri.";
$lang['DirectAdmin.!error.direct_admin_password.format'] = "Assicurati che la password contenga quanto segue: Almeno 12 caratteri, almeno 1 carattere maiuscolo A-Z, almeno 1 carattere minuscolo a-z, almeno 1 numero 0-9 e almeno 1 carattere speciale dal set: ! \"#\$%&'()*+,-./:;<=>?@[]^_` {|}";
$lang['DirectAdmin.!error.direct_admin_email.format'] = "Si prega di inserire un indirizzo email valido.";
$lang['DirectAdmin.!error.change_package.type'] = "Il modulo non supporta il passaggio tra i pacchetti utente e rivenditore.";
$lang['DirectAdmin.name'] = "Amministrazione diretta";
$lang['DirectAdmin.module_row'] = "server";
$lang['DirectAdmin.module_row_plural'] = "Server";
$lang['DirectAdmin.module_group'] = "Gruppo di server";
$lang['DirectAdmin.tab_stats'] = "Statistiche";
$lang['DirectAdmin.servers.no_results'] = "Non ci sono i server.";
$lang['DirectAdmin.server_groups.no_results'] = "Non sono presenti gruppi di server.";
$lang['DirectAdmin.service_field.domain'] = "Dominio";
$lang['DirectAdmin.service_field.username'] = "Nome utente";
$lang['DirectAdmin.service_field.password'] = "Parola d'ordine";
$lang['DirectAdmin.service_field.email'] = "E-mail";
$lang['DirectAdmin.service_info.username'] = "Nome utente";
$lang['DirectAdmin.service_info.password'] = "Password";
$lang['DirectAdmin.service_info.server'] = "server";
$lang['DirectAdmin.service_info.options'] = "Opzioni";
$lang['DirectAdmin.service_info.option_login'] = "Login";
$lang['DirectAdmin.package_fields.type'] = "Tipo di account";
$lang['DirectAdmin.package_fields.type_user'] = "Utente";
$lang['DirectAdmin.package_fields.type_reseller'] = "Rivenditore";
$lang['DirectAdmin.package_fields.package'] = "Pacchetto DirectAdmin";
$lang['DirectAdmin.package_fields.ip'] = "Indirizzo IP";
$lang['DirectAdmin.package_fields.ip_shared'] = "Condiviso";
$lang['DirectAdmin.package_fields.ip_assign'] = "Assegna";
$lang['DirectAdmin.add_module_row'] = "Aggiungi server";
$lang['DirectAdmin.add_module_group'] = "Aggiungi gruppo di server";
$lang['DirectAdmin.manage.module_rows_title'] = "Server";
$lang['DirectAdmin.manage.module_groups_title'] = "Gruppi di server";
$lang['DirectAdmin.manage.module_rows_heading.name'] = "Etichetta del server";
$lang['DirectAdmin.manage.module_rows_heading.host_name'] = "Nome host";
$lang['DirectAdmin.manage.module_rows_heading.accounts'] = "Conti";
$lang['DirectAdmin.manage.module_rows_heading.options'] = "Opzioni";
$lang['DirectAdmin.manage.module_groups_heading.name'] = "Nome del gruppo";
$lang['DirectAdmin.manage.module_groups_heading.servers'] = "Conteggio server";
$lang['DirectAdmin.manage.module_groups_heading.options'] = "Opzioni";
$lang['DirectAdmin.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['DirectAdmin.manage.module_rows.edit'] = "Modifica";
$lang['DirectAdmin.manage.module_groups.edit'] = "Modificare";
$lang['DirectAdmin.manage.module_rows.delete'] = "Eliminare";
$lang['DirectAdmin.manage.module_groups.delete'] = "Elimina";
$lang['DirectAdmin.manage.module_rows.confirm_delete'] = "Sei sicuro di voler eliminare questo server?";
$lang['DirectAdmin.manage.module_groups.confirm_delete'] = "Sei sicuro di voler eliminare questo gruppo di server?";
$lang['DirectAdmin.row_meta.server_name'] = "Etichetta del server";
$lang['DirectAdmin.row_meta.host_name'] = "Nome host";
$lang['DirectAdmin.row_meta.user_name'] = "Nome utente";
$lang['DirectAdmin.row_meta.password'] = "Parola d'ordine";
$lang['DirectAdmin.row_meta.use_ssl'] = "Utilizzare il protocollo SSL quando ci si collega all'API (consigliato)";
$lang['DirectAdmin.row_meta.account_limit'] = "Limite account";
$lang['DirectAdmin.row_meta.name_server'] = "Nome del server %1\$s"; // %1$s is the name server number (e.g. 2)
$lang['DirectAdmin.add_row.box_title'] = "Aggiungi il server DirectAdmin";
$lang['DirectAdmin.add_row.basic_title'] = "Impostazioni di base";
$lang['DirectAdmin.add_row.name_servers_title'] = "Server dei nomi";
$lang['DirectAdmin.add_row.name_server_btn'] = "Aggiungere ulteriori Name Server";
$lang['DirectAdmin.add_row.name_server_col'] = "Server dei nomi";
$lang['DirectAdmin.add_row.name_server_host_col'] = "Nome host";
$lang['DirectAdmin.add_row.remove_name_server'] = "Rimuovere";
$lang['DirectAdmin.add_row.notes_title'] = "Appunti";
$lang['DirectAdmin.add_row.add_btn'] = "Aggiungi server";
$lang['DirectAdmin.edit_row.box_title'] = "Modifica il server DirectAdmin";
$lang['DirectAdmin.edit_row.basic_title'] = "Impostazioni di base";
$lang['DirectAdmin.edit_row.name_servers_title'] = "Nome server";
$lang['DirectAdmin.edit_row.name_server_btn'] = "Aggiungi ulteriore server dei nomi";
$lang['DirectAdmin.edit_row.name_server_col'] = "Nameserver";
$lang['DirectAdmin.edit_row.name_server_host_col'] = "Hostname";
$lang['DirectAdmin.edit_row.remove_name_server'] = "Rimuovere";
$lang['DirectAdmin.edit_row.notes_title'] = "Appunti";
$lang['DirectAdmin.edit_row.add_btn'] = "Modifica server";
$lang['DirectAdmin.tab_client_stats'] = "Statistiche";
$lang['DirectAdmin.tab_client_stats.info_title'] = "Informazione";
$lang['DirectAdmin.tab_client_stats.info_heading.field'] = "Campo";
$lang['DirectAdmin.tab_client_stats.info_heading.value'] = "Valore";
$lang['DirectAdmin.tab_client_stats.no_results'] = "Le informazioni statistiche non sono attualmente disponibili.";
$lang['DirectAdmin.order_options.roundrobin'] = "Distribuire uniformemente tra i server";
$lang['DirectAdmin.!error.direct_admin_password.matches'] = "Password e password di conferma non corrispondono.";
$lang['DirectAdmin.tab_client_actions'] = "Azioni";
$lang['DirectAdmin.order_options.first'] = "[object HTMLCollection]";
$lang['DirectAdmin.tab_client_actions.change_password'] = "Cambiare la password";
$lang['DirectAdmin.tab_client_actions.field_direct_admin_password'] = "Parola d'ordine";
$lang['DirectAdmin.tab_client_actions.field_direct_admin_confirm_password'] = "Conferma password";
$lang['DirectAdmin.tab_client_actions.field_password_submit'] = "Update Password";
$lang['DirectAdmin.!error.port.format'] = "La porta deve essere un numero.";
$lang['DirectAdmin.service_field.text_generate_password'] = "Genera password";
$lang['DirectAdmin.row_meta.port'] = "Porta";
$lang['DirectAdmin.row_meta.default_port'] = "2222";
$lang['DirectAdmin.tab_client_actions.text_generate_password'] = "Genera password";
$lang['DirectAdmin.description'] = "DirectAdmin è un pannello di controllo grafico di hosting web basato sul web progettato per semplificare l'amministrazione dei siti web.";
?>