<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Kassacompleet.!error.api_key.empty'] = "Inserisci una chiave API";
$lang['Kassacompleet.!error.api_key.valid'] = "La chiave API non è valida";
$lang['Kassacompleet.name'] = "Carta di credito/debito (Kassa Complete)";
$lang['Kassacompleet.api_key'] = "Chiave API";
$lang['Kassacompleet.tooltip.api_key'] = "Per utilizzare la modalità test, inserisci semplicemente una chiave API da un account di prova";
$lang['Kassacompleet.buildprocess.submit'] = "Paga con Kassa Compleet";
$lang['Kassacompleet.description'] = "Integrazione Kassa Compleet per il tipo di pagamento con carta di credito.";
?>