<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Apnscp.module_row.name'] = "server";
$lang['Apnscp.module_row_plural.name'] = "Server";
$lang['Apnscp.module_group.name'] = "Gruppo di server";
$lang['Apnscp.tab_stats'] = "Statistiche";
$lang['Apnscp.tab_client_stats'] = "Statistiche";
$lang['Apnscp.tab_client_actions'] = "Azioni";
$lang['Apnscp.add_module_row'] = "Aggiungi server";
$lang['Apnscp.add_module_group'] = "Aggiungi gruppo di server";
$lang['Apnscp.manage.module_rows_title'] = "Server";
$lang['Apnscp.manage.module_groups_title'] = "Gruppi di server";
$lang['Apnscp.manage.module_rows_heading.name'] = "Etichetta del server";
$lang['Apnscp.manage.module_rows_heading.hostname'] = "Nome host";
$lang['Apnscp.manage.module_rows_heading.accounts'] = "Conti";
$lang['Apnscp.manage.module_rows_heading.options'] = "Opzioni";
$lang['Apnscp.manage.module_groups_heading.name'] = "Nome del gruppo";
$lang['Apnscp.manage.module_groups_heading.servers'] = "Conteggio server";
$lang['Apnscp.manage.module_groups_heading.options'] = "Opzioni";
$lang['Apnscp.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Apnscp.manage.module_rows.edit'] = "Modificare";
$lang['Apnscp.manage.module_groups.edit'] = "Modificare";
$lang['Apnscp.manage.module_rows.delete'] = "Eliminare";
$lang['Apnscp.manage.module_groups.delete'] = "Eliminare";
$lang['Apnscp.manage.module_rows.confirm_delete'] = "Sei sicuro di voler eliminare questo server?";
$lang['Apnscp.manage.module_groups.confirm_delete'] = "Sei sicuro di voler eliminare questo gruppo di server?";
$lang['Apnscp.manage.module_rows_no_results'] = "Non ci sono server.";
$lang['Apnscp.manage.module_groups_no_results'] = "Non sono presenti gruppi di server.";
$lang['Apnscp.order_options.first'] = "Primo server non completo";
$lang['Apnscp.order_options.roundrobin'] = "Distribuire uniformemente tra i server";
$lang['Apnscp.add_row.basic_title'] = "Impostazioni di base";
$lang['Apnscp.add_row.name_servers_title'] = "Server dei nomi";
$lang['Apnscp.add_row.notes_title'] = "Appunti";
$lang['Apnscp.add_row.name_server_btn'] = "Aggiungi ulteriore server dei nomi";
$lang['Apnscp.add_row.name_server_col'] = "Server dei nomi";
$lang['Apnscp.add_row.name_server_host_col'] = "Nome host";
$lang['Apnscp.add_row.name_server'] = "Server dei nomi %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Apnscp.add_row.remove_name_server'] = "Rimuovere";
$lang['Apnscp.add_row.add_btn'] = "Aggiungi server";
$lang['Apnscp.edit_row.basic_title'] = "Impostazioni di base";
$lang['Apnscp.edit_row.name_servers_title'] = "Server dei nomi";
$lang['Apnscp.edit_row.notes_title'] = "Appunti";
$lang['Apnscp.edit_row.name_server_btn'] = "Aggiungi ulteriore server dei nomi";
$lang['Apnscp.edit_row.name_server_col'] = "Server dei nomi";
$lang['Apnscp.edit_row.name_server_host_col'] = "Nome host";
$lang['Apnscp.edit_row.name_server'] = "Server dei nomi %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Apnscp.edit_row.remove_name_server'] = "Rimuovere";
$lang['Apnscp.edit_row.add_btn'] = "Modifica server";
$lang['Apnscp.row_meta.server_name'] = "Etichetta del server";
$lang['Apnscp.row_meta.host_name'] = "Nome host";
$lang['Apnscp.row_meta.port'] = "Porta";
$lang['Apnscp.row_meta.default_port'] = "2083";
$lang['Apnscp.row_meta.api_key'] = "Chiave API";
$lang['Apnscp.row_meta.use_ssl'] = "Utilizza SSL quando ti connetti all'API (consigliato)";
$lang['Apnscp.row_meta.account_limit'] = "Limite del conto";
$lang['Apnscp.service_field.domain'] = "Dominio";
$lang['Apnscp.service_field.username'] = "Nome utente";
$lang['Apnscp.service_field.password'] = "Parola d'ordine";
$lang['Apnscp.tab_stats.info_title'] = "Informazione";
$lang['Apnscp.tab_stats.info_heading.field'] = "Campo";
$lang['Apnscp.tab_stats.info_heading.value'] = "Valore";
$lang['Apnscp.tab_stats.info.disk'] = "Quota disco";
$lang['Apnscp.tab_stats.info.bandwidth'] = "Quota di larghezza di banda";
$lang['Apnscp.tab_client_actions.change_password'] = "Cambia la password";
$lang['Apnscp.tab_client_actions.field_apnscp_password'] = "Parola d'ordine";
$lang['Apnscp.tab_client_actions.field_password_submit'] = "Aggiorna password";
$lang['Apnscp.tab_client_stats.info_title'] = "Informazione";
$lang['Apnscp.tab_client_stats.bandwidth_title'] = "Utilizzo della larghezza di banda (da mese a oggi)";
$lang['Apnscp.tab_client_stats.disk_title'] = "Uso del disco";
$lang['Apnscp.tab_client_stats.usage'] = "(%1\$s MB/%2\$s MB)"; // %1$s is the amount of resource usage, %2$s is the resource usage limit
$lang['Apnscp.tab_client_stats.usage_unlimited'] = "(%1\$s MB/∞)"; // %1$s is the amount of resource usage
$lang['Apnscp.service_info.username'] = "Nome utente";
$lang['Apnscp.service_info.password'] = "Parola d'ordine";
$lang['Apnscp.service_info.server'] = "server";
$lang['Apnscp.service_info.options'] = "Opzioni";
$lang['Apnscp.service_info.option_login'] = "Login";
$lang['Apnscp.service_field.tooltip.username'] = "Puoi lasciare vuoto il nome utente per generarne uno automaticamente.";
$lang['Apnscp.service_field.tooltip.password'] = "Puoi lasciare vuota la password per generarne una automaticamente.";
$lang['Apnscp.!error.server_name_valid'] = "È necessario inserire un'etichetta server.";
$lang['Apnscp.!error.host_name_valid'] = "Il nome host sembra non essere valido.";
$lang['Apnscp.!error.port_format'] = "La porta deve essere un numero.";
$lang['Apnscp.!error.api_key_valid'] = "La chiave API sembra non essere valida.";
$lang['Apnscp.!error.api_key_valid_connection'] = "Non è stato possibile stabilire una connessione al server. Verifica che il nome host, la chiave API e la porta siano corretti.";
$lang['Apnscp.!error.account_limit_valid'] = "Il limite dell'account deve essere lasciato vuoto (per account illimitati) o impostato su un valore intero.";
$lang['Apnscp.!error.name_servers_valid'] = "Uno o più server dei nomi inseriti non sono validi.";
$lang['Apnscp.!error.name_servers_count'] = "È necessario definire almeno 2 server dei nomi.";
$lang['Apnscp.!error.api.internal'] = "Si è verificato un errore interno oppure il server non ha risposto alla richiesta.";
$lang['Apnscp.!error.module_row.missing'] = "Si è verificato un errore interno. La riga del modulo non è disponibile.";
$lang['Apnscp.!error.apnscp_domain.format'] = "Inserisci un nome di dominio valido, ad es. dominio.com.";
$lang['Apnscp.!error.apnscp_domain.test'] = "Il nome di dominio non può iniziare con \"test\".";
$lang['Apnscp.!error.apnscp_username.format'] = "Il nome utente può contenere solo lettere e numeri e non può iniziare con un numero.";
$lang['Apnscp.!error.apnscp_username.test'] = "Il nome utente non può iniziare con \"test\".";
$lang['Apnscp.!error.apnscp_username.length'] = "Il nome utente deve avere una lunghezza compresa tra 1 e 16 caratteri.";
$lang['Apnscp.!error.apnscp_password.valid'] = "La password deve contenere almeno 8 caratteri.";
$lang['Apnscp.!error.apnscp_password.matches'] = "Password e Conferma password non corrispondono.";
$lang['Apnscp.description'] = "Precedentemente chiamato APNSCP.";
$lang['Apnscp.name'] = "ApisCP";
$lang['Apnscp.add_row.box_title'] = "Aggiungi il server ApisCP";
$lang['Apnscp.edit_row.box_title'] = "Modifica il server ApisCP";
$lang['Apnscp.package_fields.package'] = "Pacchetto ApisCP";
$lang['Apnscp.!error.meta[package].empty'] = "È richiesto un pacchetto ApisCP.";
?>