<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OvhDomains.name'] = "Domini OVH";
$lang['OvhDomains.module_row'] = "Account";
$lang['OvhDomains.module_row_plural'] = "Conti";
$lang['OvhDomains.module_group'] = "Gruppo di conti";
$lang['OvhDomains.add_module_row'] = "Aggiungi account";
$lang['OvhDomains.add_module_group'] = "Aggiungi gruppo di account";
$lang['OvhDomains.manage.module_rows_title'] = "Conti";
$lang['OvhDomains.manage.module_rows_heading.application_key'] = "Chiave dell'applicazione";
$lang['OvhDomains.manage.module_rows_heading.secret_key'] = "Chiave segreta";
$lang['OvhDomains.manage.module_rows_heading.consumer_key'] = "Chiave del consumatore";
$lang['OvhDomains.manage.module_rows_heading.endpoint'] = "Punto finale";
$lang['OvhDomains.manage.module_rows_heading.options'] = "Opzioni";
$lang['OvhDomains.manage.module_rows.edit'] = "Modificare";
$lang['OvhDomains.manage.module_rows.delete'] = "Eliminare";
$lang['OvhDomains.manage.module_rows.confirm_delete'] = "Sei sicuro di voler eliminare questo account?";
$lang['OvhDomains.manage.module_rows_no_results'] = "Non ci sono conti.";
$lang['OvhDomains.manage.module_groups_title'] = "Gruppi";
$lang['OvhDomains.manage.module_groups_heading.name'] = "Nome";
$lang['OvhDomains.manage.module_groups_heading.module_rows'] = "Conti";
$lang['OvhDomains.manage.module_groups_heading.options'] = "Opzioni";
$lang['OvhDomains.manage.module_groups.edit'] = "Modificare";
$lang['OvhDomains.manage.module_groups.delete'] = "Eliminare";
$lang['OvhDomains.manage.module_groups.confirm_delete'] = "Sei sicuro di voler eliminare questo account?";
$lang['OvhDomains.manage.module_groups.no_results'] = "Non esiste un gruppo di account";
$lang['OvhDomains.add_row.box_title'] = "Domini OVH - Aggiungi Account";
$lang['OvhDomains.add_row.add_btn'] = "Aggiungi account";
$lang['OvhDomains.edit_row.box_title'] = "Domini OVH - Modifica Account";
$lang['OvhDomains.edit_row.edit_btn'] = "Aggiorna conto";
$lang['OvhDomains.row_meta.application_key'] = "Chiave dell'applicazione";
$lang['OvhDomains.row_meta.secret_key'] = "Chiave segreta";
$lang['OvhDomains.row_meta.consumer_key'] = "Chiave del consumatore";
$lang['OvhDomains.row_meta.endpoint'] = "Punto finale";
$lang['OvhDomains.!error.application_key.valid'] = "Chiave dell'applicazione non valida";
$lang['OvhDomains.!error.secret_key.valid'] = "Chiave segreta non valida";
$lang['OvhDomains.!error.consumer_key.valid'] = "Chiave consumatore non valida";
$lang['OvhDomains.!error.endpoint.valid'] = "Endpoint non valido";
$lang['OvhDomains.!error.module_row.missing'] = "Si è verificato un errore interno. La riga del modulo non è disponibile.";
$lang['OvhDomains.!error.domain.valid'] = "Dominio non valido";
$lang['OvhDomains.!error.epp_code.valid'] = "Il codice EPP deve essere 1 o 0.";
$lang['OvhDomains.!error.ns_count'] = "Sono richiesti almeno 2 server dei nomi.";
$lang['OvhDomains.!error.ns_valid'] = "Uno o più server dei nomi non sono validi.";
$lang['OvhDomains.tab_whois'] = "CHI È";
$lang['OvhDomains.tab_whois.heading'] = "CHI È";
$lang['OvhDomains.tab_whois.field_submit'] = "Aggiorna WHOIS";
$lang['OvhDomains.tab_nameservers'] = "Server dei nomi";
$lang['OvhDomains.tab_nameservers.heading'] = "Server dei nomi";
$lang['OvhDomains.tab_nameservers.field_submit'] = "Aggiorna i server dei nomi";
$lang['OvhDomains.tab_dns'] = "Record DNS";
$lang['OvhDomains.tab_dns.heading'] = "Record DNS";
$lang['OvhDomains.tab_dns.heading_add'] = "Aggiungi registrazione";
$lang['OvhDomains.tab_dns.record_type'] = "Tipo di registrazione";
$lang['OvhDomains.tab_dns.host'] = "Ospite";
$lang['OvhDomains.tab_dns.value'] = "Valore";
$lang['OvhDomains.tab_dns.ttl'] = "TTL";
$lang['OvhDomains.tab_dns.options'] = "Opzioni";
$lang['OvhDomains.tab_dns.field_delete'] = "Eliminare";
$lang['OvhDomains.tab_dns.field_add'] = "Aggiungi registrazione";
$lang['OvhDomains.tab_settings'] = "Impostazioni";
$lang['OvhDomains.tab_settings.heading'] = "Impostazioni";
$lang['OvhDomains.tab_settings.field_submit'] = "Salva le impostazioni";
$lang['OvhDomains.tab_client_whois'] = "CHI È";
$lang['OvhDomains.tab_client_whois.heading'] = "CHI È";
$lang['OvhDomains.tab_client_whois.field_submit'] = "Aggiorna WHOIS";
$lang['OvhDomains.tab_client_nameservers'] = "Server dei nomi";
$lang['OvhDomains.tab_client_nameservers.heading'] = "Server dei nomi";
$lang['OvhDomains.tab_client_nameservers.field_submit'] = "Aggiorna i server dei nomi";
$lang['OvhDomains.tab_client_dns'] = "Record DNS";
$lang['OvhDomains.tab_client_dns.heading'] = "Record DNS";
$lang['OvhDomains.tab_client_dns.record_type'] = "Tipo di registrazione";
$lang['OvhDomains.tab_client_dns.host'] = "Ospite";
$lang['OvhDomains.tab_client_dns.value'] = "Valore";
$lang['OvhDomains.tab_client_dns.ttl'] = "TTL";
$lang['OvhDomains.tab_client_dns.options'] = "Opzioni";
$lang['OvhDomains.tab_client_dns.field_delete'] = "Eliminare";
$lang['OvhDomains.tab_client_dns.field_add'] = "Aggiungi registrazione";
$lang['OvhDomains.tab_client_settings'] = "Impostazioni";
$lang['OvhDomains.tab_client_settings.heading'] = "Impostazioni";
$lang['OvhDomains.tab_client_settings.heading_auth_code'] = "codice di autorizzazione";
$lang['OvhDomains.tab_client_settings.field_registrar_lock'] = "Blocco del cancelliere";
$lang['OvhDomains.tab_client_settings.field_registrar_lock_yes'] = "Imposta il blocco del registrar. Consigliato per impedire trasferimenti non autorizzati.";
$lang['OvhDomains.tab_client_settings.field_registrar_lock_no'] = "Rilascia il blocco del registrar in modo che il dominio possa essere trasferito.";
$lang['OvhDomains.tab_client_settings.text_auth_code'] = "Utilizza questo codice di autorizzazione per trasferire il tuo dominio ad un altro provider.";
$lang['OvhDomains.tab_client_settings.field_submit'] = "Salva le impostazioni";
$lang['OvhDomains.transfer.domain'] = "Dominio";
$lang['OvhDomains.transfer.auth_info'] = "codice di autorizzazione";
$lang['OvhDomains.domain.domain'] = "Dominio";
$lang['OvhDomains.nameserver.ns1'] = "Server dei nomi 1";
$lang['OvhDomains.nameserver.ns2'] = "Server dei nomi 2";
$lang['OvhDomains.nameserver.ns3'] = "Server dei nomi 3";
$lang['OvhDomains.nameserver.ns4'] = "Server dei nomi 4";
$lang['OvhDomains.nameserver.ns5'] = "Server dei nomi 5";
$lang['OvhDomains.contact.first_name'] = "Nome di battesimo";
$lang['OvhDomains.contact.last_name'] = "Cognome";
$lang['OvhDomains.contact.email'] = "Indirizzo e-mail";
$lang['OvhDomains.contact.address1'] = "Indirizzo 1";
$lang['OvhDomains.contact.address2'] = "Indirizzo 2";
$lang['OvhDomains.contact.city'] = "Città";
$lang['OvhDomains.contact.state'] = "Stato";
$lang['OvhDomains.contact.zip'] = "Cap";
$lang['OvhDomains.contact.country'] = "Paese";
$lang['OvhDomains.contact.phone'] = "Telefono";
$lang['OvhDomains.service_fields.domain'] = "Dominio";
$lang['OvhDomains.package_fields.epp_code'] = "Codice PPE";
$lang['OvhDomains.package_fields.ns1'] = "Server dei nomi 1";
$lang['OvhDomains.package_fields.ns2'] = "Server dei nomi 2";
$lang['OvhDomains.package_fields.ns3'] = "Server dei nomi 3";
$lang['OvhDomains.package_fields.ns4'] = "Server dei nomi 4";
$lang['OvhDomains.package_fields.ns5'] = "Server dei nomi 5";
$lang['OvhDomains.package_field.tooltip.epp_code'] = "Se consentire agli utenti di richiedere un codice EPP tramite l'interfaccia del servizio Blesta.";
$lang['OvhDomains.package_fields.tld_options'] = "TLD";
?>