<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TransactionsApplied.name'] = "Transazioni applicate";
$lang['TransactionsApplied.option.any'] = "Qualunque";
$lang['TransactionsApplied.options.field_start_date'] = "Data d'inizio";
$lang['TransactionsApplied.options.field_end_date'] = "Data di fine";
$lang['TransactionsApplied.options.field_gateway'] = "Porta";
$lang['TransactionsApplied.options.field_status'] = "Stato";
$lang['TransactionsApplied.options.field_payment_type'] = "Modalità di pagamento";
$lang['TransactionsApplied.heading.id'] = "Transazione n.";
$lang['TransactionsApplied.heading.transaction_id'] = "ID Transazione";
$lang['TransactionsApplied.heading.reference_id'] = "Identificativo di riferimento";
$lang['TransactionsApplied.heading.client_id_code'] = "Cliente #";
$lang['TransactionsApplied.heading.invoice_id_code'] = "Fattura #";
$lang['TransactionsApplied.heading.gateway_name'] = "Casello stradale";
$lang['TransactionsApplied.heading.type_name'] = "Tipo di Pagamento";
$lang['TransactionsApplied.heading.applied_amount'] = "Importo applicato";
$lang['TransactionsApplied.heading.amount'] = "Importo del pagamento";
$lang['TransactionsApplied.heading.currency'] = "Valuta";
$lang['TransactionsApplied.heading.status'] = "Stato";
$lang['TransactionsApplied.heading.applied_date'] = "Data applicata";
$lang['TransactionsApplied.heading.income_type'] = "Tipo di transazione";
?>