<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Discount.description.coupon.amount'] = "Buono %1\$s"; // %1$s is the coupon code
$lang['Discount.description.coupon.percent'] = "Coupon %1\$s (%2\$s%%)"; // %1$s is the coupon code, %2$s is the coupon discount percentage - the two percent symbols (%%) must both be used together to display a single percent symbol
?>