<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Domain.description.domain.item'] = "Registrazione del dominio - %2\$s"; // %1$s is the name of the tld, %2$s is the name of the domain
$lang['Domain.description.domain.item.date'] = "Registrazione del dominio - %2\$s (%3\$s - %4\$s)"; // %1$s is the name of the tld, %2$s is the name of the domain, %3$s is the start date, %4$s is the end date
$lang['Domain.description.domain.item.updated'] = "Passa da %1\$s a %2\$s - %3\$s"; // %1$s is the name of the old package, %2$s is the name of the tld, %3$s is the name of the domain
$lang['Domain.description.domain.item.updated.date'] = "Passa da %1\$s a %2\$s - %3\$s (%4\$s - %5\$s)"; // %1$s is the name of the old package, %2$s is the name of the tld, %3$s is the name of the domain, %4$s is the start date, %5$s is the end date
$lang['Domain.description.domain.item.transferred'] = "Trasferimento dominio - %2\$s"; // %1$s is the name of the tld, %2$s is the name of the domain
$lang['Domain.description.domain.item.date.transferred'] = "Trasferimento dominio - %2\$s (%3\$s - %4\$s)"; // %1$s is the name of the tld, %2$s is the name of the domain, %3$s is the start date, %4$s is the end date
$lang['Domain.description.domain.item.updated.transferred'] = "Passa da %1\$s a %2\$s - %3\$s"; // %1$s is the name of the old package, %2$s is the name of the tld, %3$s is the name of the domain
$lang['Domain.description.domain.item.updated.date.transferred'] = "Passa da %1\$s a %2\$s - %3\$s (%4\$s - %5\$s)"; // %1$s is the name of the old package, %2$s is the name of the tld, %3$s is the name of the domain, %4$s is the start date, %5$s is the end date
$lang['Domain.description.domain.setup'] = "%1\$s - %2\$s Commissione di installazione"; // %1$s is the name of the tld, %2$s is the name of the domain
$lang['Domain.description.domain.cancel'] = "%1\$s - %2\$s Commissione di cancellazione"; // %1$s is the name of the tld, %2$s is the name of the domain
$lang['Domain.description.domain.item.prorate'] = "%1\$s - %2\$s proporzionale (%3\$s - %4\$s)"; // %1$s is the name of the tld, %2$s is the name of the domain, %3$s is the prorated start date, %4$s is the prorated end date
$lang['Domain.description.domain.item.updated.prorate'] = "Modifica proporzionale da %1\$s a %2\$s - %3\$s (%4\$s - %5\$s)"; // %1$s is the name of the old package, %2$s is the name of the tld, %3$s is the name of the domain, %4$s is the prorated start date, %5$s is the prorated end date
$lang['Domain.description.package.item'] = "%1\$s"; // %1$s is the name of the tld
$lang['Domain.description.package.item.date'] = "%1\$s (%2\$s - %3\$s)"; // %1$s is the name of the tld, %2$s is the start date, %3$s is the end date
$lang['Domain.description.package.item.updated'] = "Passa da %1\$s a %2\$s"; // %1$s is the name of the old package, %2$s is the name of the tld
$lang['Domain.description.package.item.updated.date'] = "Passa da %1\$s a %2\$s (%3\$s - %4\$s)"; // %1$s is the name of the old package, %2$s is the name of the tld, %3$s is the start date, %4$s is the end date
$lang['Domain.description.package.setup'] = "%1\$s Commissione di installazione"; // %1$s is the name of the tld
$lang['Domain.description.package.cancel'] = "%1\$s Commissione di cancellazione"; // %1$s is the name of the tld
$lang['Domain.description.package.item.prorate'] = "%1\$s proporzionale (%2\$s - %3\$s)"; // %1$s is the name of the tld, %2$s is the prorated start date, %3$s is the prorated end date
$lang['Domain.description.package.item.updated.prorate'] = "Modifica proporzionale da %1\$s a %2\$s (%3\$s - %4\$s)"; // %1$s is the name of the old package, %2$s is the name of the tld, %3$s is the prorated start date, %4$s is the prorated end date
$lang['Domain.description.domain.item.renewed'] = "Rinnovo dominio - %2\$s"; // %1$s is the name of the tld, %2$s is the name of the domain
$lang['Domain.description.domain.item.date.renewed'] = "Rinnovo dominio - %2\$s (%3\$s - %4\$s)"; // %1$s is the name of the tld, %2$s is the name of the domain, %3$s is the start date, %4$s is the end date
$lang['Domain.description.domain.item.updated.renewed'] = "Passa da %1\$s a %2\$s - %3\$s"; // %1$s is the name of the old package, %2$s is the name of the tld, %3$s is the name of the domain
$lang['Domain.description.domain.item.updated.date.renewed'] = "Passa da %1\$s a %2\$s - %3\$s (%4\$s - %5\$s)"; // %1$s is the name of the old package, %2$s is the name of the tld, %3$s is the name of the domain, %4$s is the start date, %5$s is the end date
?>