<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Maxmind.!error.reject.reject_score'] = "Il tuo ordine non può essere elaborato in questo momento.";
$lang['Maxmind.!error.review.review_score'] = "Il tuo ordine deve essere rivisto manualmente.";
$lang['Maxmind.!error.reject.free_email'] = "Non vengono accettati ordini con account di posta elettronica gratuiti.";
$lang['Maxmind.!error.review.free_email'] = "Gli ordini con account e-mail gratuiti sono in fase di revisione.";
$lang['Maxmind.!error.reject.country_mismatch'] = "Gli ordini con mancate corrispondenze nazionali non vengono accettati.";
$lang['Maxmind.!error.review.country_mismatch'] = "Gli ordini con mancate corrispondenze nazionali sono in fase di revisione.";
$lang['Maxmind.!error.reject.risky_country'] = "Non vengono accettati ordini provenienti da paesi a rischio.";
$lang['Maxmind.!error.review.risky_country'] = "Gli ordini provenienti da paesi a rischio sono in fase di revisione.";
$lang['Maxmind.!error.reject.anon_proxy'] = "Non vengono accettati ordini provenienti da proxy anonimi.";
$lang['Maxmind.!error.review.anon_proxy'] = "Gli ordini provenienti da proxy anonimi sono in fase di revisione.";
$lang['Maxmind.settings.field_server'] = "server";
$lang['Maxmind.settings.field_key'] = "Chiave di licenza";
$lang['Maxmind.settings.field_reject_score'] = "Punteggio minimo per rifiutare";
$lang['Maxmind.settings.field_review_score'] = "Punteggio minimo per la revisione";
$lang['Maxmind.settings.field_free_email'] = "E-mail gratuita";
$lang['Maxmind.settings.field_country_mismatch'] = "Mancata corrispondenza del paese";
$lang['Maxmind.settings.field_risky_country'] = "Paese rischioso";
$lang['Maxmind.settings.field_anon_proxy'] = "proxy anonimo";
$lang['Maxmind.settings.option_allow'] = "Permettere";
$lang['Maxmind.settings.option_review'] = "Revisione";
$lang['Maxmind.settings.option_reject'] = "Rifiutare";
?>