<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Vpsdotnet.name'] = "VPS.NET";
$lang['Vpsdotnet.module_row'] = "Server principale VPS.NET";
$lang['Vpsdotnet.module_row_plural'] = "Server";
$lang['Vpsdotnet.module_group'] = "VPS.NET Master Group";
$lang['Vpsdotnet.order_options.first'] = "Primo server non completo";
$lang['Vpsdotnet.please_wait'] = "Attendere prego...";
$lang['Vpsdotnet.add_module_row'] = "Aggiungi server";
$lang['Vpsdotnet.add_module_group'] = "Aggiungi gruppo di server";
$lang['Vpsdotnet.manage.module_rows_title'] = "Server principali VPS.NET";
$lang['Vpsdotnet.manage.module_rows_heading.server_label'] = "Etichetta Server";
$lang['Vpsdotnet.manage.module_rows_heading.email'] = "E-mail";
$lang['Vpsdotnet.manage.module_rows_heading.options'] = "Opzioni";
$lang['Vpsdotnet.manage.module_rows.edit'] = "Modificare";
$lang['Vpsdotnet.manage.module_rows.delete'] = "Elimina";
$lang['Vpsdotnet.manage.module_rows.confirm_delete'] = "Sei sicuro di voler cancellare questo server?";
$lang['Vpsdotnet.manage.module_rows_no_results'] = "Non ci sono server.";
$lang['Vpsdotnet.manage.module_groups_title'] = "Gruppi di server principali VPS.NET";
$lang['Vpsdotnet.manage.module_groups_heading.name'] = "Nome Gruppo";
$lang['Vpsdotnet.manage.module_groups_heading.servers'] = "Conteggio server";
$lang['Vpsdotnet.manage.module_groups_heading.options'] = "Opzioni";
$lang['Vpsdotnet.manage.module_groups.edit'] = "Modificare";
$lang['Vpsdotnet.manage.module_groups.delete'] = "Eliminare";
$lang['Vpsdotnet.manage.module_groups.confirm_delete'] = "Sei sicuro di voler eliminare questo gruppo di server?";
$lang['Vpsdotnet.manage.module_groups_no_results'] = "Non sono presenti gruppi di server.";
$lang['Vpsdotnet.service_info.vpsdotnet_primary_ip_address'] = "Indirizzo IP primario";
$lang['Vpsdotnet.service_info.vpsdotnet_password'] = "Parola d'ordine";
$lang['Vpsdotnet.add_row.box_title'] = "Aggiungi il server VPS.NET";
$lang['Vpsdotnet.add_row.basic_title'] = "Impostazioni di base";
$lang['Vpsdotnet.row_meta.server_name'] = "Etichetta del server";
$lang['Vpsdotnet.row_meta.email'] = "E-mail";
$lang['Vpsdotnet.row_meta.key'] = "Chiave API";
$lang['Vpsdotnet.add_row.add_btn'] = "Aggiungi Server";
$lang['Vpsdotnet.edit_row.box_title'] = "Modifica il server VPS.NET";
$lang['Vpsdotnet.edit_row.basic_title'] = "Impostazioni di base";
$lang['Vpsdotnet.edit_row.add_btn'] = "Aggiorna server";
$lang['Vpsdotnet.package_fields.number_of_nodes'] = "Numero di nodi";
$lang['Vpsdotnet.package_fields.client_set_cloud'] = "Consenti al client di impostare Cloud/Zona, Sistema operativo e Modello";
$lang['Vpsdotnet.package_fields.admin_set_cloud'] = "Seleziona una nuvola/zona";
$lang['Vpsdotnet.package_fields.cloud'] = "Nuvola/Zona";
$lang['Vpsdotnet.package_fields.client_set_template_group'] = "Consenti al client di impostare il sistema operativo e il modello";
$lang['Vpsdotnet.package_fields.admin_set_template_group'] = "Selezionare Sistema Operativo";
$lang['Vpsdotnet.package_fields.template_group'] = "Sistema operativo";
$lang['Vpsdotnet.package_fields.client_set_template'] = "Lascia che il client imposti il modello";
$lang['Vpsdotnet.package_fields.admin_set_template'] = "Seleziona Template";
$lang['Vpsdotnet.package_fields.template'] = "Modello";
$lang['Vpsdotnet.service_field.vpsdotnet_hostname'] = "Nome host";
$lang['Vpsdotnet.service_field.vpsdotnet_label'] = "Etichetta VPS";
$lang['Vpsdotnet.service_field.vpsdotnet_cloud'] = "Nuvola/Zona";
$lang['Vpsdotnet.service_field.vpsdotnet_template_group'] = "Sistema Operativo";
$lang['Vpsdotnet.service_field.vpsdotnet_template'] = "Modello";
$lang['Vpsdotnet.tab_actions'] = "Azioni del server";
$lang['Vpsdotnet.tab_console'] = "Consolle";
$lang['Vpsdotnet.tab_client_actions'] = "Azioni Server";
$lang['Vpsdotnet.tab_client_console'] = "consolle";
$lang['Vpsdotnet.!actions.boot'] = "Stivale";
$lang['Vpsdotnet.!actions.reboot'] = "Riavviare";
$lang['Vpsdotnet.!actions.shutdown'] = "Fermare";
$lang['Vpsdotnet.!actions.reinstall'] = "Reinstalla";
$lang['Vpsdotnet.!actions.hostname'] = "Cambia nome host";
$lang['Vpsdotnet.!actions.password'] = "Resetta la password";
$lang['Vpsdotnet.tab_actions.status_online'] = "in linea";
$lang['Vpsdotnet.tab_actions.status_offline'] = "disconnesso";
$lang['Vpsdotnet.tab_actions.status_pending'] = "In sospeso";
$lang['Vpsdotnet.tab_actions.status_unknown'] = "Sconosciuto";
$lang['Vpsdotnet.tab_actions.heading_actions'] = "Azioni";
$lang['Vpsdotnet.tab_actions.server_status'] = "Stato del server";
$lang['Vpsdotnet.tab_actions.heading_reinstall'] = "Reinstallare";
$lang['Vpsdotnet.tab_actions.field_vpsdotnet_template_group'] = "Sistema operativo";
$lang['Vpsdotnet.tab_actions.field_vpsdotnet_template'] = "Modello";
$lang['Vpsdotnet.tab_actions.field_confirm'] = "Comprendo che con la reinstallazione tutti i dati sul server verranno eliminati definitivamente e il sistema operativo e il modello selezionati verranno installati.";
$lang['Vpsdotnet.tab_actions.field_reinstall_submit'] = "reinstallare";
$lang['Vpsdotnet.tab_actions.heading_hostname'] = "Cambia nome host";
$lang['Vpsdotnet.tab_actions.field_vpsdotnet_hostname'] = "Nome host";
$lang['Vpsdotnet.tab_actions.field_hostname_submit'] = "Cambia nome host";
$lang['Vpsdotnet.tab_actions.heading_password'] = "Resetta la password";
$lang['Vpsdotnet.tab_actions.field_password_submit'] = "Reset Password";
$lang['Vpsdotnet.tab_client_actions.heading_server_status'] = "Stato del server";
$lang['Vpsdotnet.tab_client_actions.status_online'] = "in linea";
$lang['Vpsdotnet.tab_client_actions.status_offline'] = "disconnesso";
$lang['Vpsdotnet.tab_client_actions.status_pending'] = "In attesa di";
$lang['Vpsdotnet.tab_client_actions.status_unknown'] = "Sconosciuto";
$lang['Vpsdotnet.tab_client_actions.heading_reinstall'] = "Reinstallare";
$lang['Vpsdotnet.tab_client_actions.field_vpsdotnet_template_group'] = "Sistema operativo";
$lang['Vpsdotnet.tab_client_actions.field_vpsdotnet_template'] = "Modello";
$lang['Vpsdotnet.tab_client_actions.field_confirm'] = "Comprendo che con la reinstallazione tutti i dati sul server verranno eliminati definitivamente e il sistema operativo e il modello selezionati verranno installati.";
$lang['Vpsdotnet.tab_client_actions.field_reinstall_submit'] = "reinstallare";
$lang['Vpsdotnet.tab_client_actions.heading_hostname'] = "Cambia nome host";
$lang['Vpsdotnet.tab_client_actions.field_vpsdotnet_hostname'] = "Nome host";
$lang['Vpsdotnet.tab_client_actions.field_hostname_submit'] = "Cambia nome host";
$lang['Vpsdotnet.tab_client_actions.heading_password'] = "Resetta la password";
$lang['Vpsdotnet.tab_client_actions.field_password_submit'] = "Reset Password";
$lang['Vpsdotnet.tab_console.heading_console'] = "Consolle";
$lang['Vpsdotnet.tab_console.root_password'] = "Parola d'ordine:";
$lang['Vpsdotnet.tab_client_console.heading_console'] = "Consolle";
$lang['Vpsdotnet.!error.server_name.empty'] = "Inserisci un'etichetta per questo server.";
$lang['Vpsdotnet.!error.email.format'] = "Si prega di inserire un indirizzo email valido.";
$lang['Vpsdotnet.!error.key.empty'] = "Inserisci la tua chiave API.";
$lang['Vpsdotnet.!error.key.valid_connection'] = "Non è stato possibile stabilire una connessione al server. Verifica che l'indirizzo email e la chiave API siano corretti.";
$lang['Vpsdotnet.!error.nodes.add_failed'] = "Impossibile aggiungere i nodi richiesti.";
$lang['Vpsdotnet.!error.vps.update_failed'] = "Si è verificato un errore e non è stato possibile aggiornare la macchina virtuale.";
$lang['Vpsdotnet.!error.vps.action_failed'] = "Si è verificato un errore e non è stato possibile eseguire l'azione.";
$lang['Vpsdotnet.!error.vps.cancel_failed'] = "Si è verificato un errore e il servizio non può essere annullato.";
$lang['Vpsdotnet.!error.vps.reinstall_failed'] = "Si è verificato un errore e il template non può essere reinstallato.
";
$lang['Vpsdotnet.!error.vpsdotnet_template.valid'] = "Seleziona un template valido.";
$lang['Vpsdotnet.!error.confirm.valid'] = "È necessario confermare di aver compreso l'azione di reinstallazione per poter eseguire la reinstallazione del modello.";
$lang['Vpsdotnet.!error.meta[number_of_nodes].format'] = "Inserisci il numero di nodi da allocare.";
$lang['Vpsdotnet.!error.meta[set_cloud].format'] = "Si prega di scegliere se consentire a un cliente di impostare una cloud.";
$lang['Vpsdotnet.!error.meta[cloud].format'] = "Seleziona un cloud valido.";
$lang['Vpsdotnet.!error.meta[set_template_group].format'] = "Seleziona se consentire a un client di impostare il sistema operativo.";
$lang['Vpsdotnet.!error.meta[template_group].format'] = "Seleziona un sistema operativo valido.";
$lang['Vpsdotnet.!error.meta[set_template].format'] = "Scegli se autorizzare il cliente a impostare il template";
$lang['Vpsdotnet.!error.meta[template].format'] = "Seleziona un modello valido.";
$lang['Vpsdotnet.!error.vpsdotnet_hostname.format'] = "Il nome host sembra non essere valido.";
$lang['Vpsdotnet.!error.vpsdotnet_label.empty'] = "Inserisci un'etichetta.";
$lang['Vpsdotnet.!error.vpsdotnet_label.format'] = "L'etichetta non può contenere caratteri speciali.";
$lang['Vpsdotnet.!error.vpsdotnet_cloud.format'] = "Si prega di selezionare un cloud valido";
$lang['Vpsdotnet.!error.vpsdotnet_template_group.format'] = "Seleziona un sistema operativo valido.";
$lang['Vpsdotnet.!error.vpsdotnet_template.format'] = "Si prega di selezionare un template valido";
$lang['Vpsdotnet.tab_client_actions.heading_actions'] = "Azioni del server";
$lang['Vpsdotnet.tab_client_console.root_password'] = "Parola d'ordine";
$lang['Vpsdotnet.description'] = "VPS.NET fornisce hosting di server virtualizzati.";
?>