<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Pagination.next'] = "Prossimo";
$lang['Pagination.prev'] = "Prec";
$lang['Pagination.first'] = "← Primo";
$lang['Pagination.last'] = "Ultimo →";
?>