<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cart.index.header_cart'] = "Revisione dell'ordine";
$lang['Cart.index.table_description'] = "Descrizione";
$lang['Cart.index.table_term'] = "Termine";
$lang['Cart.index.table_qty'] = "Quantità";
$lang['Cart.index.table_price'] = "Prezzo";
$lang['Cart.index.checkout_btn'] = "Guardare";
$lang['Cart.index.order_more_btn'] = "Ordina più articoli";
$lang['Cart.index.edit_item'] = "Modificare";
$lang['Cart.index.remove_item'] = "Rimuovere";
$lang['Cart.index.empty_cart'] = "Il tuo carrello è vuoto. Inizia <a href=\"%1\$s\">scegliendo un piano »</a>"; // %1$s is the URI to the order home page
?>