<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Checkout.index.header_checkout'] = "Guardare";
$lang['Checkout.index.header_paymethod'] = "Scegli il tuo metodo di pagamento";
$lang['Checkout.index.field_useaccount'] = "Utilizza il conto di pagamento";
$lang['Checkout.index.field_newdetails'] = "Nuovi dettagli di pagamento";
$lang['Checkout.index.heading_other_payment_options'] = "Altre opzioni di pagamento";
$lang['Checkout.index.heading_payment_options'] = "Opzioni di pagamento";
$lang['Checkout.index.apply_credit'] = "Applica credito (%1\$s disponibile)"; // %1$s is the amount of credit available
$lang['Checkout.index.pay_btn'] = "Inviare ordine";
$lang['Checkout.index.pay_credit_btn'] = "Applica credito e invia ordine";
$lang['Checkout.index.continue_btn'] = "Continua";
$lang['Checkout.index.no_options'] = "Non sono disponibili opzioni di pagamento.";
$lang['Checkout.contact_info.heading_contact'] = "Informazioni sui contatti";
$lang['Checkout.contact_info.field_contact_id'] = "Copia le informazioni di contatto da";
$lang['Checkout.contact_info.text_select_contact'] = "Puoi selezionare un contatto esistente per precompilare questo modulo.";
$lang['Checkout.cc_info.heading_cc'] = "Informazioni sulla carta di credito";
$lang['Checkout.ach_info.heading_ach'] = "Informazioni sul conto bancario";
$lang['Checkout.complete.header_complete'] = "Ordine completo";
$lang['Checkout.complete.header_almost_complete'] = "Quasi lì...";
$lang['Checkout.complete.order_more_btn'] = "Effettua un altro ordine";
?>