<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Summary.index.box_heading'] = "Il tuo carrello";
$lang['Summary.index.login_customer'] = "Cliente esistente?";
$lang['Summary.index.login_link'] = "Login";
$lang['Summary.index.link_resetpassword'] = "Reimposta la mia password";
$lang['Summary.index.field_username'] = "Nome utente";
$lang['Summary.index.field_password'] = "Parola d'ordine";
$lang['Summary.index.login_btn'] = "Accesso";
$lang['Summary.index.checkout_btn'] = "Guardare";
$lang['Summary.index.have_coupon'] = "Hai un buono?";
$lang['Summary.index.coupon'] = "Buono";
$lang['Summary.index.coupon_btn'] = "Riscattare";
$lang['Summary.index.cart_empty'] = "Non ci sono articoli nel carrello.";
?>