<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CustomReport.name'] = "Rapporto personalizzato";
$lang['CustomReports.options.field_report'] = "Rapporto";
$lang['CustomReports.options.field_report_select'] = "-- Please Select --";
$lang['CustomReport.!error.field'] = "%1\$s non è valido."; // %1$s is the field label
?>