<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TheSSLStorePlugin.name'] = "Il plugin SSLStore";
$lang['TheSSLStorePlugin.getCronTasks.tss_expiration_reminder_name'] = "Promemoria scadenza certificato SSL";
$lang['TheSSLStorePlugin.getCronTasks.tss_expiration_reminder_desc'] = "Un promemoria verrà inviato 30 giorni prima della data di scadenza del certificato.";
?>