<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Bitpay.name'] = "BitPay";
$lang['Bitpay.transaction_speed'] = "Velocità di transazione";
$lang['Bitpay.transaction.speed.high'] = "Alto";
$lang['Bitpay.transaction.speed.medium'] = "medio";
$lang['Bitpay.transaction.speed.low'] = "Basso";
$lang['Bitpay.transaction_speed_note'] = "La velocità di operazione determina la rapidità con la quale una fattura (in Bitpay) può essere considerata 'confermata'.";
$lang['Bitpay.buildprocess.submit'] = "Paga utilizzando Bitcoin";
$lang['Bitpay.!error.transaction_speed.valid'] = "Seleziona una velocità di transazione valida.";
$lang['Bitpay.!error.failed.response'] = "Impossibile elaborare la transazione.";
$lang['Bitpay.!error.payment.invalid'] = "La transazione non è valida e non è stato possibile elaborarla.";
$lang['Bitpay.!error.payment.expired'] = "La transazione è scaduta e non può essere processata";
$lang['Bitpay.description'] = "Un fornitore di servizi di pagamento in Bitcoin e criptovaluta";
$lang['Bitpay.pairing_code'] = "Codice di abbinamento";
$lang['Bitpay.pairing_code_note'] = "Vai alla dashboard di BitPay nella sezione \"Strumenti di pagamento > Token API\" e approva il token generato utilizzando questo codice di abbinamento \"%1\$s\", quindi salva le impostazioni del gateway facendo clic su \"Aggiorna impostazioni\"."; // %1$s is the paring code
$lang['Bitpay.test_mode'] = "Modalità di prova";
$lang['Bitpay.test_mode_note'] = "Se selezionato, il gateway invierà richieste di pagamento all'URL di prova. La modifica di questo disconnetterà BitPay e verrà generato un nuovo token.";
$lang['Bitpay.connect.button'] = "Connettiti con BitPay";
$lang['Bitpay.disconnect.button'] = "Disconnettiti da BitPay";
$lang['Bitpay.!error.token.valid'] = "Il token non è valido o il codice di abbinamento non è stato autorizzato in BitPay.";
?>