<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FraudLabsPro.!error.reject.reject_score'] = "Il tuo ordine non può essere elaborato in questo momento.";
$lang['FraudLabsPro.!error.review.review_score'] = "Il tuo ordine deve essere rivisto manualmente.";
$lang['FraudLabsPro.!error.reject.fraudlabspro'] = "Il tuo ordine è stato contrassegnato come frode da FraudLabs Pro.";
$lang['FraudLabsPro.!error.review.fraudlabspro'] = "Il tuo ordine è stato contrassegnato come potenzialmente fraudolento da FraudLabs Pro. Verrà rivisto manualmente.";
$lang['FraudLabsPro.settings.field_api_key'] = "Chiave API";
$lang['FraudLabsPro.settings.label_description'] = "Ottieni gratuitamente il piano FraudLabs Pro Micro (500 query al mese) da http://www.fraudlabspro.com/plan";
$lang['FraudLabsPro.settings.field_reject_score'] = "Punteggio minimo da respingere
";
$lang['FraudLabsPro.settings.field_review_score'] = "Punteggio minimo per la revisione";
$lang['FraudLabsPro.settings.field_follow_flp_result'] = "Rifiuta / Revisiona automaticamente in base alla raccomandazione di FraudLabs Pro";
$lang['FraudLabsPro.settings.option_yes'] = "si";
$lang['FraudLabsPro.settings.option_no'] = "NO";
?>