<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.Phpids.email_alert_name'] = "Avviso di intrusione PHPIDS";
$lang['AdminCompanyEmails.templates.Phpids.email_alert_desc'] = "E-mail di avviso di rilevamento di intrusioni PHPIDS, inviata agli indirizzi configurati nel plug-in PHPIDS.";
?>