<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PhpidsPlugin.name'] = "PHPIDS";
$lang['PhpidsPlugin.description'] = "Sistema di rilevamento delle intrusioni per aiutare a identificare attività sospette.";
?>