<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MulticraftPackage.!error.meta[server_name].format'] = "Imposta un nome per il server.";
$lang['MulticraftPackage.!error.meta[players].format'] = "Imposta il numero massimo di slot giocatore da consentire.";
$lang['MulticraftPackage.!error.meta[memory].format'] = "Imposta la quantità massima di memoria come numero intero in MB.";
$lang['MulticraftPackage.!error.meta[jardir].format'] = "Seleziona una directory JAR valida.";
$lang['MulticraftPackage.!error.meta[user_jar].format'] = "Se il proprietario può selezionare il JAR deve essere impostato su 1 o 0.";
$lang['MulticraftPackage.!error.meta[user_name].format'] = "Se il proprietario può impostare un nome deve essere impostato su 1 o 0.";
$lang['MulticraftPackage.!error.meta[user_schedule].format'] = "Se il proprietario può pianificare le attività deve essere impostato su 1 o 0.";
$lang['MulticraftPackage.!error.meta[user_ftp].format'] = "Se il proprietario può concedere l'accesso FTP ad altri deve essere impostato su 1 o 0.";
$lang['MulticraftPackage.!error.meta[user_visibility].format'] = "Se il proprietario può modificare la visibilità del server deve essere impostato su 1 o 0.";
$lang['MulticraftPackage.!error.meta[default_level].format'] = "Seleziona un ruolo predefinito valido.";
$lang['MulticraftPackage.!error.meta[autostart].format'] = "Se il server deve avviarsi automaticamente deve essere impostato su 1 o 0.";
$lang['MulticraftPackage.!error.meta[create_ftp].format'] = "Se creare un account FTP deve essere impostato su 1 o 0.";
$lang['MulticraftPackage.!error.meta[server_visibility].format'] = "Seleziona una visibilità server valida.";
$lang['MulticraftPackage.package_fields.server_name'] = "Nome del server";
$lang['MulticraftPackage.package_fields.players'] = "Slot per i giocatori";
$lang['MulticraftPackage.package_fields.memory'] = "RAM del server";
$lang['MulticraftPackage.package_fields.tooltip.memory'] = "Imposta la memoria in MB o lascia vuoto per utilizzare la quantità predefinita.";
$lang['MulticraftPackage.package_fields.jarfile'] = "File JAR";
$lang['MulticraftPackage.package_fields.tooltip.jarfile'] = "Lascia vuoto per utilizzare il file JAR predefinito.";
$lang['MulticraftPackage.package_fields.jardir'] = "Cerca i JAR nella seguente directory";
$lang['MulticraftPackage.package_fields.tooltip.jardir'] = "Se non si utilizza la directory JAR del demone, Multicraft dovrebbe essere eseguito in modalità multiutente.";
$lang['MulticraftPackage.package_fields.jardir_daemon'] = "Directory JAR del demone";
$lang['MulticraftPackage.package_fields.jardir_server'] = "Directory JAR del server";
$lang['MulticraftPackage.package_fields.jardir_server_base'] = "Directory di base del server";
$lang['MulticraftPackage.package_fields.user_jar'] = "JAR selezionabile dal proprietario";
$lang['MulticraftPackage.package_fields.user_name'] = "Il proprietario può impostare il nome";
$lang['MulticraftPackage.package_fields.tooltip.user_name'] = "Imposta se il proprietario può definire o modificare il nome del server.";
$lang['MulticraftPackage.package_fields.user_schedule'] = "Il proprietario può pianificare le attività";
$lang['MulticraftPackage.package_fields.tooltip.user_schedule'] = "Imposta se il proprietario può creare attività pianificate e modificare l'impostazione di salvataggio automatico.";
$lang['MulticraftPackage.package_fields.user_ftp'] = "Il proprietario può gestire FTP";
$lang['MulticraftPackage.package_fields.tooltip.user_ftp'] = "Imposta se il proprietario può concedere l'accesso FTP ad altri utenti.";
$lang['MulticraftPackage.package_fields.user_visibility'] = "Il proprietario può impostare la visibilità";
$lang['MulticraftPackage.package_fields.tooltip.user_visibility'] = "Imposta se il proprietario può modificare la visibilità del server e il ruolo predefinito.";
$lang['MulticraftPackage.package_fields.default_level'] = "Ruolo predefinito";
$lang['MulticraftPackage.package_fields.tooltip.default_level'] = "Seleziona il ruolo che i giocatori verranno assegnati al momento della prima connessione. Usa Nessun accesso per l'elenco in bianco.";
$lang['MulticraftPackage.package_fields.default_level_0'] = "Nessun accesso";
$lang['MulticraftPackage.package_fields.default_level_10'] = "Ospite";
$lang['MulticraftPackage.package_fields.default_level_20'] = "Utente";
$lang['MulticraftPackage.package_fields.default_level_30'] = "Moderatore";
$lang['MulticraftPackage.package_fields.autostart'] = "Avvia Server";
$lang['MulticraftPackage.package_fields.tooltip.autostart'] = "Avvia automaticamente il server al riavvio di Multicraft.";
$lang['MulticraftPackage.package_fields.create_ftp'] = "Crea un account FTP";
$lang['MulticraftPackage.package_fields.tooltip.create_ftp'] = "Crea automaticamente un account FTP.";
$lang['MulticraftPackage.package_fields.server_visibility'] = "Visibilità del server";
$lang['MulticraftPackage.package_fields.tooltip.server_visibility'] = "Imposta la visibilità del server nell'elenco dei server Multicraft.";
$lang['MulticraftPackage.package_fields.server_visibility_0'] = "Solo proprietario";
$lang['MulticraftPackage.package_fields.server_visibility_1'] = "Per ruolo predefinito";
$lang['MulticraftPackage.package_fields.server_visibility_2'] = "Solo utenti con ruoli";
?>