<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SoftaculousPlugin.name'] = "Programma di installazione automatica morbido";
$lang['SoftaculousPlugin.library_error'] = "Impossibile caricare la libreria.";
$lang['SoftaculousPlugin.remote_error'] = "Impossibile accedere al server remoto.";
$lang['SoftaculousPlugin.remote_error_message'] = "Impossibile accedere al server remoto. Errore: %1\$s"; // %1$s is the error
$lang['SoftaculousPlugin.remote_curl_error'] = "Impossibile accedere al server remoto. Errore cURL: %1\$s"; // %1$s is the curl error
$lang['SoftaculousPlugin.remote_firewall_error'] = "Impossibile determinare la posizione di Softaculous sul server remoto. Potrebbe esserci un firewall che impedisce l'accesso.";
$lang['SoftaculousPlugin.script_selected_error'] = "Impossibile determinare lo script da installare. Assicurati che il nome dello script sia corretto. Nome dello script: %1\$s"; // %1$s is the script
$lang['SoftaculousPlugin.script_installed'] = "Script installato con successo";
$lang['SoftaculousPlugin.script_no_installed'] = "Impossibile installare lo script: %1\$s"; // %1$s is the script
$lang['SoftaculousPlugin.admin_fname'] = "Sistema";
$lang['SoftaculousPlugin.admin_lname'] = "Amministratore";
$lang['SoftaculousPlugin.installation_success'] = "Script installato correttamente per il servizio con ID %1\$s"; // %1$s is the script
$lang['SoftaculousPlugin.cron.script_installation_name'] = "Fornitura di script di servizio";
$lang['SoftaculousPlugin.cron.script_installation_desc'] = "Installa gli script in sospeso per i servizi.";
?>