<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminExcludedPackages.!success.packages_updated'] = "I pacchetti esclusi sono stati aggiornati correttamente.";
$lang['AdminExcludedPackages.index.boxtitle_excluded_packages'] = "Pacchetti esclusi";
$lang['AdminExcludedPackages.index.heading_available_packages'] = "Pacchetti disponibili";
$lang['AdminExcludedPackages.index.field_updatesubmit'] = "Aggiorna impostazioni";
$lang['AdminExcludedPackages.index.text_no_packages'] = "Non ci sono pacchetti attivi disponibili.";
?>