<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminPaymentMethods.!success.payment_method_added'] = "Il metodo di pagamento è stato aggiunto con successo.";
$lang['AdminPaymentMethods.!success.payment_method_deleted'] = "Il metodo di pagamento è stato eliminato con successo.";
$lang['AdminPaymentMethods.!success.payment_method_updated'] = "Il metodo di pagamento è stato aggiornato con successo.";
$lang['AdminPaymentMethods.index.page_title'] = "Metodi di pagamento degli affiliati";
$lang['AdminPaymentMethods.index.boxtitle_payment_methods'] = "Metodi di pagamento degli affiliati";
$lang['AdminPaymentMethods.index.affiliate_payment_method_add'] = "Aggiungi il metodo di pagamento dell'affiliato";
$lang['AdminPaymentMethods.index.no_results'] = "Non sono presenti metodi di pagamento in questo momento.";
$lang['AdminPaymentMethods.index.heading_name'] = "Nome";
$lang['AdminPaymentMethods.index.heading_options'] = "Opzioni";
$lang['AdminPaymentMethods.index.option_edit'] = "Modificare";
$lang['AdminPaymentMethods.index.option_delete'] = "Eliminare";
$lang['AdminPaymentMethods.index.confirm_delete'] = "Sei sicuro di voler eliminare questo metodo di pagamento?";
$lang['AdminPaymentMethods.add.boxtitle_add_payment_method'] = "Aggiungi il metodo di pagamento dell'affiliato";
$lang['AdminPaymentMethods.add.field_name'] = "Nome";
$lang['AdminPaymentMethods.add.field_payment_methodsubmit'] = "Aggiungi metodo di pagamento";
$lang['AdminPaymentMethods.edit.boxtitle_edit_payment_method'] = "Modifica il metodo di pagamento dell'affiliato";
$lang['AdminPaymentMethods.edit.field_name'] = "Nome";
$lang['AdminPaymentMethods.edit.field_payment_methodsubmit'] = "Aggiorna metodo di pagamento";
?>