<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.Order.received_name'] = "Ordine Ricevuto";
$lang['AdminCompanyEmails.templates.Order.received_desc'] = "L'avviso verrà inviato quando viene ricevuto un ordine.";
$lang['AdminCompanyEmails.templates.Order.received_mobile_name'] = "Ordine Ricevuto (Mobile)";
$lang['AdminCompanyEmails.templates.Order.received_mobile_desc'] = "Avviso inviato alla ricezione di un ordine destinato a dispositivi mobili.";
$lang['AdminCompanyEmails.templates.Order.affiliate_payout_request_name'] = "Richiesta di pagamento dell'affiliato";
$lang['AdminCompanyEmails.templates.Order.affiliate_payout_request_desc'] = "Avviso inviato al personale quando viene presentata una richiesta di pagamento.";
$lang['AdminCompanyEmails.templates.Order.affiliate_payout_request_received_name'] = "Pagamento dell'affiliato ricevuto";
$lang['AdminCompanyEmails.templates.Order.affiliate_payout_request_received_desc'] = "Avviso inviato a un cliente quando viene inviata la richiesta di pagamento.";
$lang['AdminCompanyEmails.templates.Order.affiliate_monthly_report_name'] = "Rapporto di affiliazione (mensile)";
$lang['AdminCompanyEmails.templates.Order.affiliate_monthly_report_desc'] = "Riporta l'elenco delle iscrizioni e i dati associati per l'ultimo mese.";
$lang['AdminCompanyEmails.templates.Order.abandoned_cart_first_name'] = "Giorni di ordine abbandonato (1° avviso)";
$lang['AdminCompanyEmails.templates.Order.abandoned_cart_first_desc'] = "Primo avviso inviato a un cliente, dopo aver abbandonato un ordine non pagato.";
$lang['AdminCompanyEmails.templates.Order.abandoned_cart_second_name'] = "Giorni per ordini abbandonati (2° avviso)";
$lang['AdminCompanyEmails.templates.Order.abandoned_cart_second_desc'] = "Secondo avviso inviato a un cliente, dopo aver abbandonato un ordine non pagato.";
$lang['AdminCompanyEmails.templates.Order.abandoned_cart_third_name'] = "Giorni per ordini abbandonati (3° avviso)";
$lang['AdminCompanyEmails.templates.Order.abandoned_cart_third_desc'] = "Terzo e ultimo avviso inviato a un cliente, dopo aver abbandonato un ordine non pagato.";
?>