<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.status_updated'] = "Gli ordini selezionati sono stati aggiornati con successo.";
$lang['AdminMain.!success.settings_updated'] = "Le impostazioni del tuo ordine sono state aggiornate con successo.";
$lang['AdminMain.index.boxtitle_order'] = "Ordini";
$lang['AdminMain.index.no_results'] = "Non esistono ordini di questo tipo.";
$lang['AdminMain.index.category_accepted'] = "Accettato";
$lang['AdminMain.index.category_fraud'] = "Frode";
$lang['AdminMain.index.heading_order_number'] = "Ordine #";
$lang['AdminMain.index.heading_client_id_code'] = "Identificativo cliente";
$lang['AdminMain.index.heading_invoice_id_code'] = "Fattura #";
$lang['AdminMain.index.heading_total'] = "Totale";
$lang['AdminMain.index.heading_paid'] = "Pagato";
$lang['AdminMain.index.heading_date_added'] = "Data dell'ordine";
$lang['AdminMain.index.field_ordersubmit'] = "Aggiorna Ordini";
$lang['AdminMain.orderinfo.fraudreport_heading'] = "Rapporto sulle frodi";
$lang['AdminMain.orderinfo.fraudreport_heading_key'] = "Chiave";
$lang['AdminMain.orderinfo.fraudreport_heading_value'] = "Valore";
$lang['AdminMain.orderinfo.applied_heading'] = "Transazioni";
$lang['AdminMain.orderinfo.applied_heading_paymenttype'] = "Modalità di pagamento";
$lang['AdminMain.orderinfo.applied_heading_amount'] = "Quantità";
$lang['AdminMain.orderinfo.applied_heading_applied'] = "Applicato";
$lang['AdminMain.orderinfo.applied_heading_appliedon'] = "Applicato";
$lang['AdminMain.orderinfo.applied_heading_options'] = "Opzioni";
$lang['AdminMain.orderinfo.applied_option_edit'] = "Modificare";
$lang['AdminMain.orderinfo.applied_no_results'] = "Non ci sono transazioni applicate a questo ordine.";
$lang['AdminMain.orderinfo.services_heading'] = "Servizi";
$lang['AdminMain.orderinfo.services_heading_package'] = "Pacchetto";
$lang['AdminMain.orderinfo.services_heading_label'] = "Etichetta";
$lang['AdminMain.orderinfo.services_heading_term'] = "Termine";
$lang['AdminMain.orderinfo.services_heading_dateadded'] = "Data aggiunta";
$lang['AdminMain.orderinfo.services_heading_daterenews'] = "Data di rinnovo";
$lang['AdminMain.orderinfo.services_heading_options'] = "Opzioni";
$lang['AdminMain.orderinfo.services_option_manage'] = "Maneggio";
$lang['AdminMain.orderinfo.services_text_never'] = "Mai";
$lang['AdminMain.orderinfo.services_no_results'] = "Non ci sono servizi in questo ordine.";
$lang['AdminMain.settings.heading_notifications'] = "Notifiche sugli ordini";
$lang['AdminMain.settings.field_email_notice'] = "E-mail";
$lang['AdminMain.settings.field_email_notice_never'] = "Non inviare";
$lang['AdminMain.settings.field_email_notice_manual'] = "Inviare solo se è richiesta l'approvazione manuale";
$lang['AdminMain.settings.field_email_notice_always'] = "Invia sempre";
$lang['AdminMain.settings.field_mobile_notice'] = "Mobile";
$lang['AdminMain.settings.field_mobile_notice_never'] = "Non inviare";
$lang['AdminMain.settings.field_mobile_notice_manual'] = "Inviare solo se è richiesta l'approvazione manuale";
$lang['AdminMain.settings.field_mobile_notice_always'] = "Invia sempre";
$lang['AdminMain.settings.submit_settings'] = "Aggiorna impostazioni";
$lang['AdminMain.settings.submit_cancel'] = "Torna all'elenco degli ordini";
$lang['AdminMain.index.category_canceled'] = "Annullato";
$lang['AdminMain.index.field_markas'] = "Segna come:";
$lang['AdminMain.index.text_location'] = "Posizione";
$lang['AdminMain.index.category_pending'] = "In revisione";
$lang['AdminMain.search.page_title'] = "Risultati della ricerca per \"%1\$s\""; // %1$s is the search keywords
$lang['AdminMain.search.boxtitle_order'] = "Ordini di ricerca per \"%1\$s\""; // %1$s is the search keywords
$lang['AdminMain.!success.affiliate_settings_updated'] = "Le impostazioni di affiliazione sono state aggiornate.";
$lang['AdminMain.settings.heading_affiliate_notifications'] = "Notifiche di affiliazione";
$lang['AdminMain.settings.field_payout_notice'] = "Pagamento";
$lang['AdminMain.settings.field_payout_notice_never'] = "Mai";
$lang['AdminMain.settings.field_payout_notice_always'] = "Sempre";
$lang['AdminMain.affiliates.page_title'] = "Panoramica degli affiliati";
$lang['AdminMain.affiliates.boxtitle_affiliates'] = "Panoramica degli affiliati";
$lang['AdminMain.affiliates.inactive'] = "Questo affiliato è stato contrassegnato come inattivo.";
$lang['AdminMain.affiliates.activate'] = "Clicca qui per riattivare";
$lang['AdminMain.affiliates.no_results'] = "Nessun affiliato è associato a questo cliente. Clicca qui per registrarti.";
$lang['AdminMain.affiliates.title_details'] = "Dettagli";
$lang['AdminMain.affiliates.title_referral'] = "Link di riferimento";
$lang['AdminMain.affiliates.visits'] = "Clic";
$lang['AdminMain.affiliates.monthly_visits'] = "%1\$s/mese in media"; // %1$s is the number of average monthly visits
$lang['AdminMain.affiliates.sales'] = "Vendite totali";
$lang['AdminMain.affiliates.monthly_sales'] = "%1\$s/mese in media"; // %1$s is the number of average monthly sales
$lang['AdminMain.affiliates.conversion_rate'] = "Tasso di conversione";
$lang['AdminMain.affiliates.conversion_fraction'] = "%1\$s/%2\$s in media"; // %1$s 1 or 0 if there are no sales, %2$s is the average number of visits per sale
$lang['AdminMain.affiliates.commission_type'] = "Livello di pagamento";
$lang['AdminMain.affiliates.min_withdrawal_amount'] = "Importo minimo del pagamento";
$lang['AdminMain.affiliates.maturity_days'] = "Giorni per maturare";
$lang['AdminMain.affiliates.available_payout'] = "Disponibile per il pagamento";
$lang['AdminMain.affiliates.field.commission_fixed'] = "%1\$s una volta per ogni referral maturato"; // %1$s is the commission amount
$lang['AdminMain.affiliates.field.commission_percentage'] = "%1\$s di ogni referral maturato"; // %1$s is the commission percentage
$lang['AdminMain.affiliates.request_payout'] = "Richiedi pagamento";
$lang['AdminMain.affiliates.boxtitle_client'] = "Cliente #%1\$s - %2\$s %3\$s";
$lang['AdminMain.affiliates.heading_affiliates'] = "Impostazioni di affiliazione";
$lang['AdminMain.affiliates.heading_referral_link'] = "Link di riferimento";
$lang['AdminMain.affiliates.field_commission_type'] = "Tipo di commissione";
$lang['AdminMain.affiliates.tooltip_commission_type'] = "Il metodo di calcolo utilizzato per determinare la commissione di riferimento. Un valore fisso per ordine o una percentuale del totale dell'ordine.";
$lang['AdminMain.affiliates.field_commission_amount'] = "Importo della commissione";
$lang['AdminMain.affiliates.field_order_frequency'] = "Frequenza degli ordini";
$lang['AdminMain.affiliates.tooltip_order_frequency'] = "Primo per pagare i referral solo per il primo ordine che un cliente effettua utilizzando un link di referral oppure Qualsiasi per pagare i referral per ogni ordine che un cliente effettua utilizzando un link di referral.";
$lang['AdminMain.affiliates.field_order_recurring'] = "Ordine ricorrente";
$lang['AdminMain.affiliates.tooltip_order_recurring'] = "Se i referral verranno pagati per i servizi ordinati che si rinnovano.";
$lang['AdminMain.affiliates.field_maturity_days'] = "Giorni di maturità";
$lang['AdminMain.affiliates.tooltip_maturity_days'] = "Il numero di giorni dopo il pagamento in cui un referral matura e diventa disponibile per il pagamento.";
$lang['AdminMain.affiliates.field_min_withdrawal_amount'] = "Importo minimo di prelievo";
$lang['AdminMain.affiliates.field_max_withdrawal_amount'] = "Importo massimo di prelievo";
$lang['AdminMain.affiliates.field_withdrawal_currency'] = "Valuta di prelievo";
$lang['AdminMain.affiliates.text_code_order_form'] = "Puoi anche collegarti a una particolare pagina del modulo d'ordine come affiliato aggiungendo alla fine ?a=%1\$s a un collegamento senza parametri di ricerca o &a=%1\$s a un collegamento con parametri di ricerca.";
$lang['AdminMain.affiliates.heading_statistics'] = "Statistiche";
$lang['AdminMain.affiliates.graph_referrals'] = "Referral";
$lang['AdminMain.affiliates.graph_visits'] = "Visite";
$lang['AdminMain.affiliates.graph_sales'] = "Saldi";
$lang['AdminMain.affiliates.submit_settings'] = "Salva le impostazioni";
$lang['AdminMain.affiliates.submit_cancel'] = "Annulla";
$lang['AdminMain.settings.field_messenger_notice'] = "Messaggeri";
$lang['AdminMain.settings.field_messenger_notice_never'] = "Non inviare";
$lang['AdminMain.settings.field_messenger_notice_manual'] = "Inviare solo se è richiesta l'approvazione manuale";
$lang['AdminMain.settings.field_messenger_notice_always'] = "Invia sempre";
$lang['AdminMain.getfilters.field_order_number'] = "Ordine #";
?>