<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cart.!success.coupon_applied'] = "Il coupon è stato applicato con successo.";
$lang['Cart.!success.item_removed'] = "L'articolo è stato rimosso dal tuo carrello";
$lang['Cart.!success.all_items_removed'] = "Tutti gli articoli sono stati rimossi dal tuo carrello.";
$lang['Cart.!error.coupon_applied'] = "Non è stato possibile applicare il coupon.";
$lang['Cart.index.quantity'] = "%1\$s @"; // %1\$s is the quantity value being ordered
$lang['Cart.index.totals.discount'] = "Sconto:";
$lang['Cart.index.totals.subtotal'] = "Totale parziale:";
$lang['Cart.index.totals.total'] = "Totale dovuto oggi:";
$lang['Cart.index.totals.tax'] = "%1\$s:"; // %1$s is the tax name
$lang['Cart.index.totals.total_recurring'] = "Totale al rinnovo:";
$lang['Cart.index.totals.total_recurring_amount'] = "%1\$s %2\$s @ %3\$s"; // %1$s is the term, %2$s is the period, %3$s is the amount
?>