<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Config.!error.invalid_pricing_id'] = "Il pacchetto dato non è stato trovato.";
$lang['Config.!error.invalid_module'] = "Il pacchetto non è al momento disponibile.";
$lang['Config.index.package_price'] = "%1\$s @ %2\$s"; // %1$s is the term, %2$s is the price
$lang['Config.index.field_default_addon'] = "Nessuno";
$lang['Config.index.field_addon_label'] = "%1\$s (%2\$s @ %3\$s)"; // %1$s is the addon on name, %2$s is the term, %3$s is the price
$lang['Config.index.package_price_recurring'] = "%1\$s @ %2\$s (rinnova @ %3\$s)"; // %1$s is the term, %2$s is the initial price, %3$s is the renewal price
$lang['Config.index.field_addon_label_recurring'] = "%1\$s (%2\$s @ %3\$s, rinnova @ %4\$s)"; // %1$s is the addon on name, %2$s is the term, %3$s is the initial price, %4$s is the addon renewal price
$lang['Config.!error.domain_duplicated'] = "Il dominio \"%1\$s\" è già nel tuo carrello."; // %1$s is the domain name
$lang['Config.!error.invalid_domain_term'] = "Il termine selezionato per il dominio \"%1\$s\" non è valido."; // %1$s is the domain name
?>