<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderAffiliates.!error.affiliate_id.exists'] = "ID affiliato non valido.";
$lang['OrderAffiliates.!error.client_id.exists'] = "ID cliente non valido.";
$lang['OrderAffiliates.!error.client_id.unique'] = "L'ID cliente è già associato a un altro affiliato.";
$lang['OrderAffiliates.!error.code.empty'] = "Inserisci un codice affiliato.";
$lang['OrderAffiliates.!error.code.unique'] = "Questo codice è già preso da un altro affiliato.";
$lang['OrderAffiliates.!error.status.valid'] = "Seleziona uno stato di affiliazione valido.";
$lang['OrderAffiliates.!error.date_added.format'] = "La data aggiunta è in un formato data non valido.";
$lang['OrderAffiliates.!error.date_updated.format'] = "La data aggiornata è in un formato data non valido.";
$lang['OrderAffiliates.getStatuses.active'] = "Attivo";
$lang['OrderAffiliates.getStatuses.inactive'] = "Inattivo";
?>