<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderAffiliatePaymentMethods.!error.payment_method_id.exists'] = "Ungültige Zahlungsmethoden-ID.";
$lang['OrderAffiliatePaymentMethods.!error.company_id.exists'] = "ID azienda non valido.";
$lang['OrderAffiliatePaymentMethods.!error.names[][lang].format'] = "Il codice della lingua non è formattato correttamente.";
$lang['OrderAffiliatePaymentMethods.!error.names[][name].empty'] = "Inserisci il nome del metodo di pagamento.";
?>