<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderForms.!error.name.empty'] = "View the Google Translation";
$lang['OrderForms.!error.label.empty'] = "Devi inserire un'etichetta per il modulo.";
$lang['OrderForms.!error.label.unique'] = "Esiste già un modulo d'ordine con quell'etichetta.";
$lang['OrderForms.!error.template.supported'] = "Il modello selezionato non supporta quel tipo di ordine.";
$lang['OrderForms.!error.client_group_id.valid'] = "Quel gruppo di clienti non esiste.";
$lang['OrderForms.!error.require_tos.valid'] = "Se è necessario accettare i termini di servizio, è necessario fornire un URL ai termini.";
$lang['OrderForms.!error.order_form_id.exists'] = "Il modulo d'ordine non può essere eliminato perché sono presenti ordini in sospeso per quel modulo.";
$lang['OrderForms.!error.date_added.valid'] = "La data aggiunta deve essere una data valida.";
$lang['OrderForms.!error.visibility.valid'] = "La visibilità fornita non è supportata.";
$lang['OrderForms.getVisibilities.public'] = "Pubblico";
$lang['OrderForms.getVisibilities.shared'] = "Condiviso";
$lang['OrderForms.getVisibilities.client'] = "Solo cliente";
$lang['OrderForms.!error.label.length'] = "La lunghezza dell'etichetta non deve superare i 32 caratteri.";
$lang['OrderForms.!error.abandoned_cart_first.valid'] = "I giorni del primo sollecito devono essere un valore numerico.";
$lang['OrderForms.!error.abandoned_cart_second.valid'] = "I giorni per il secondo sollecito devono essere un valore numerico.";
$lang['OrderForms.!error.abandoned_cart_third.valid'] = "I giorni per il terzo sollecito devono essere un valore numerico.";
$lang['OrderForms.!error.field_abandoned_cart_cancellation.valid'] = "I giorni per l'annullamento dell'ordine abbandonato devono essere un valore numerico.";
$lang['OrderForms.!error.inactive_after_cancellation'] = "Disattivare i clienti con ordine singolo deve essere 1 o 0.";
$lang['OrderOrders.getNoticeIntervals.hour'] = "1 ora";
$lang['OrderOrders.getNoticeIntervals.hours'] = "%1\$s Ore"; // %1$s is the number of hours
$lang['OrderOrders.getNoticeIntervals.day'] = "1 giorno";
$lang['OrderOrders.getNoticeIntervals.days'] = "%1\$s Giorni"; // %1$s is the number of days
$lang['OrderForms.!error.label.format'] = "L'etichetta non corrisponde al formato richiesto. Sono accettati solo lettere, numeri, trattini bassi e trattini.";
?>