<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderAffiliateCompanySettings.!error.company_id.exists'] = "ID azienda non valido.";
$lang['OrderAffiliateCompanySettings.getcommissiontypes.fixed'] = "Fisso";
$lang['OrderAffiliateCompanySettings.getcommissiontypes.percentage'] = "Percentuale";
$lang['OrderAffiliateCompanySettings.getorderfrequencies.first'] = "Primo";
$lang['OrderAffiliateCompanySettings.getorderfrequencies.any'] = "Qualunque";
?>