<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderSettings.!error.embed_code.parse'] = "

Errore di analisi del codice di incorporamento: %1\$s
}"; // %1$s is the parse error
$lang['OrderSettings.getantifraud.fraudlabspro'] = "FraudLabs Pro";
$lang['OrderSettings.getantifraud.maxmind'] = "Eredità di MaxMind";
$lang['OrderSettings.getantifraud.maxmind_v2'] = "MaxMind v2";
?>