<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderAffiliatePayouts.!error.payout_id.exists'] = "ID pagamento non valido.";
$lang['OrderAffiliatePayouts.!error.affiliate_id.exists'] = "ID affiliato non valido.";
$lang['OrderAffiliatePayouts.!error.payment_method_id.exists'] = "

ID metodo di pagamento non valido.
";
$lang['OrderAffiliatePayouts.!error.status.valid'] = "Seleziona uno stato di pagamento valido.";
$lang['OrderAffiliatePayouts.!error.requested_amount.format'] = "L'importo richiesto deve essere un numero.";
$lang['OrderAffiliatePayouts.!error.requested_amount.valid'] = "L'importo richiesto non rientra nei limiti di pagamento.";
$lang['OrderAffiliatePayouts.!error.requested_currency.length'] = "Il codice valuta richiesto deve contenere 3 caratteri.";
$lang['OrderAffiliatePayouts.!error.paid_amount.format'] = "L'importo pagato deve essere un numero.";
$lang['OrderAffiliatePayouts.!error.paid_amount.valid'] = "L'importo pagato non rientra nei limiti di pagamento.";
$lang['OrderAffiliatePayouts.!error.paid_currency.length'] = "Il codice valuta pagato deve contenere 3 caratteri.";
$lang['OrderAffiliatePayouts.getStatuses.pending'] = "In attesa di";
$lang['OrderAffiliatePayouts.getStatuses.approved'] = "Approvato";
$lang['OrderAffiliatePayouts.getStatuses.declined'] = "Rifiutato";
?>