<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Payouts.!success.payout_requested'] = "Il tuo pagamento è stato richiesto.";
$lang['Payouts.!error.exceeded_payout_requests'] = "Hai superato il limite massimo di richieste di pagamento in sospeso.";
$lang['Payouts.!error.insufficient_funds_payout_request'] = "Non ci sono fondi sufficienti per elaborare la richiesta di pagamento.";
$lang['Payouts.!error.minimum_payout_not_available'] = "I fondi disponibili non raggiungono l'importo minimo per i pagamenti.";
$lang['Payouts.index.boxtitle_payouts'] = "Pagamenti";
$lang['Payouts.index.category_approved'] = "Approvato";
$lang['Payouts.index.category_pending'] = "In attesa di";
$lang['Payouts.index.category_declined'] = "Rifiutato";
$lang['Payouts.index.categorylink_request_payout'] = "Richiedi pagamento";
$lang['Payouts.index.no_results'] = "Al momento non sono presenti pagamenti con questo stato.";
$lang['Payouts.index.heading_id'] = "ID pagamento";
$lang['Payouts.index.heading_requested_amount'] = "Importo richiesto";
$lang['Payouts.index.heading_requested_currency'] = "Valuta richiesta";
$lang['Payouts.index.heading_payment_method'] = "Metodo di pagamento";
$lang['Payouts.index.heading_date_requested'] = "Data richiesta";
$lang['Payouts.add.boxtitle_request_payout'] = "Richiedi pagamento";
$lang['Payouts.add.title_payout_request'] = "Richiesta di pagamento";
$lang['Payouts.add.field_requested_amount'] = "Importo del prelievo";
$lang['Payouts.add.field_requested_currency'] = "Valuta richiesta";
$lang['Payouts.add.field_payment_method'] = "Metodo di pagamento";
$lang['Payouts.add.min_withdrawal_amount'] = "Importo minimo del pagamento";
$lang['Payouts.add.max_withdrawal_amount'] = "Importo massimo del pagamento";
$lang['Payouts.add.available_payout'] = "Disponibile per il pagamento";
$lang['Payouts.add.request_payout'] = "Richiedi pagamento";
?>