<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Summary.index.totals.discount'] = "Sconto:";
$lang['Summary.index.totals.subtotal'] = "Totale parziale:";
$lang['Summary.index.totals.total'] = "Totale dovuto oggi:";
$lang['Summary.index.price'] = "@ %1\$s"; // %1$s is the price per term
$lang['Summary.index.totals.tax'] = "%1\$s:"; // %1$s is the tax name
$lang['Summary.index.totals.total_recurring'] = "Totale al rinnovo:";
$lang['Summary.index.totals.total_recurring_amount'] = "%1\$s %2\$s @ %3\$s"; // %1$s is the term, %2$s is the period, %3$s is the amount
?>