<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientDataPortability.name'] = "Portabilità dei dati del cliente";
$lang['ClientDataPortability.options.field_client_id'] = "Identificativo cliente";
$lang['ClientDataPortability.!error.client_id'] = "L'ID cliente non è valido.";
$lang['ClientDataPortability.!tooltip.client_id'] = "Questo è l'ID cliente interno mostrato nell'URL quando visualizzi un profilo cliente.";
?>