<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Coingate.name'] = "CoinGate.com";
$lang['Coingate.app_id'] = "ID DELL'APP";
$lang['Coingate.api_key'] = "Chiave API";
$lang['Coingate.api_secret'] = "Segreto API";
$lang['Coingate.coingate_environment'] = "Ambiente CoinGate";
$lang['Coingate.environment.sandbox'] = "sabbiera";
$lang['Coingate.environment.live'] = "Live";
$lang['Coingate.receive_currency'] = "Valuta di pagamento";
$lang['Coingate.receive_currency_note'] = "Valuta che desideri ricevere quando effettui un prelievo su CoinGate. Ti preghiamo di notare che se scegli EUR o USD ti verrà chiesto di verificare la tua attività prima di effettuare un prelievo su CoinGate.";
$lang['Coingate.environment_note'] = "Abilita \"sandbox\" per testare su sandbox.coingate.com. Tieni presente che per la modalità sandbox devi generare credenziali API separate su sandbox.coingate.com. Le credenziali API generate su coingate.com non funzioneranno per la modalità sandbox.";
$lang['Coingate.buildprocess.submit'] = "CoinGate.com";
$lang['Coingate.receive_currency.usd'] = "Dollari americani \$";
$lang['Coingate.receive_currency.btc'] = "Bitcoin฿";
$lang['Coingate.receive_currency.eur'] = "Euro €";
$lang['Coingate.!error.app_id.empty'] = "L'ID APP non può essere vuoto.";
$lang['Coingate.!error.api_key.empty'] = "La chiave API non può essere vuota";
$lang['Coingate.!error.api_secret.empty'] = "L'API Secret non può essere vuota";
$lang['Coingate.!error.payment.invalid'] = "La transazione non è valida e non è stato possibile elaborarla.";
$lang['Coingate.!error.payment.canceled'] = "La transazione è stata annullata e non è stato possibile elaborarla.";
$lang['Coingate.!error.payment.expired'] = "La transazione è scaduta e non è stato possibile elaborarla.";
$lang['Coingate.!error.failed.response'] = "Impossibile elaborare la transazione.";
$lang['Coingate.description'] = "Paga con Bitcoin o Altcoin tramite CoinGate.com";
?>