<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CoinPayments.name'] = "CoinPayments.net";
$lang['CoinPayments.merchant_id'] = "ID commerciante CoinPayments";
$lang['CoinPayments.ipn_secret'] = "Segreto IPN";
$lang['CoinPayments.buildprocess.submit'] = "Paga con CoinPayments";
$lang['CoinPayments.description'] = "Un sistema di pagamento per criptovalute come Bitcoin e Litecoin con commissioni basse";
?>