<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AuthorizeNetAcceptjs.!error.auth'] = "Il gateway non è riuscito ad autenticarsi.";
$lang['AuthorizeNetAcceptjs.!error.transaction_key.empty'] = "Inserisci una chiave di transazione.";
$lang['AuthorizeNetAcceptjs.!error.login_id.empty'] = "Inserisci un ID di accesso.";
$lang['AuthorizeNetAcceptjs.!error.login_id.valid'] = "Impossibile connettersi all'API Authorize.net utilizzando l'ID di accesso fornito.";
$lang['AuthorizeNetAcceptjs.!error.sandbox.valid'] = "Sandbox deve essere impostato su \"true\" se fornito.";
$lang['AuthorizeNetAcceptjs.name'] = "Autorizza.Net Accept.js";
$lang['AuthorizeNetAcceptjs.description'] = "Invia dati di pagamento sicuri direttamente ad Authorize.net. Accept.js acquisisce i dati di pagamento e li invia direttamente ad Authorize.net.";
$lang['AuthorizeNetAcceptjs.field_number'] = "Numero";
$lang['AuthorizeNetAcceptjs.field_security'] = "Codice di sicurezza";
$lang['AuthorizeNetAcceptjs.field_expiration'] = "Data di scadenza";
$lang['AuthorizeNetAcceptjs.login_id'] = "Utente";
$lang['AuthorizeNetAcceptjs.transaction_key'] = "Chiave di transazione";
$lang['AuthorizeNetAcceptjs.sandbox'] = "Sabbiera";
$lang['AuthorizeNetAcceptjs.sandbox_note'] = "Abilitando questa opzione le transazioni verranno pubblicate nell'ambiente Authorize.Net Sandbox. Abilita questa opzione solo se stai testando con un account Authorize.Net Sandbox.";
$lang['AuthorizeNetAcceptjs.charge_description_default'] = "View the Google Translation";
$lang['AuthorizeNetAcceptjs.charge_description'] = "Addebito per %1\$s"; // Where %1$s is a comma seperated list of invoice ID display codes
?>