<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PterodactylRule.!error.required'] = "Il campo %1\$s è obbligatorio."; // %1$s is the name of the required field
$lang['PterodactylRule.!error.regex'] = "Il campo %1\$s deve corrispondere alla regex %2\$s."; // %1$s is the name of the field, %2$s is the regex to match
$lang['PterodactylRule.!error.numeric'] = "Il campo %1\$s deve contenere un numero."; // %1$s is the name of the field
$lang['PterodactylRule.!error.integer'] = "Il campo %1\$s deve contenere un numero intero."; // %1$s is the name of the field
$lang['PterodactylRule.!error.string'] = "Il campo %1\$s deve contenere una stringa."; // %1$s is the name of the field
$lang['PterodactylRule.!error.alphaNum'] = "Il campo %1\$s deve contenere solo i seguenti caratteri a-z, A-Z o 0-9."; // %1$s is the name of the field
$lang['PterodactylRule.!error.alphaDash'] = "Il campo %1\$s deve contenere solo i seguenti caratteri a-z, A-Z, 0-9, - o _."; // %1$s is the name of the field
$lang['PterodactylRule.!error.url'] = "Il campo %1\$s deve contenere un URL valido (ad esempio www.domain.com)."; // %1$s is the name of the field
$lang['PterodactylRule.!error.min'] = "Il campo %1\$s deve contenere almeno %2\$s."; // %1$s is the name of the field, %2$s is the minimum value/length
$lang['PterodactylRule.!error.max'] = "Il campo %1\$s ha un massimo di %2\$s."; // %1$s is the name of the field, %2$s is the maximum value/length
$lang['PterodactylRule.!error.between'] = "Il campo %1\$s deve contenere un valore compreso tra %2\$s e %3\$s."; // %1$s is the name of the field, %2$s is the minimum value/length, %3$s is the maximum value/length
$lang['PterodactylRule.!error.digitsBetween'] = "Il campo %1\$s deve contenere un valore compreso tra %2\$s e %3\$s cifre."; // %1$s is the name of the field, %2$s is the minimum value/length, %3$s is the maximum value/length
?>