<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminResponses.!success.category_added'] = "La categoria %1\$s è stata aggiunta con successo."; // %1$s is the name of the category
$lang['AdminResponses.!success.category_updated'] = "La categoria %1\$s è stata aggiornata con successo."; // %1$s is the name of the category
$lang['AdminResponses.!success.category_deleted'] = "La categoria %1\$s è stata eliminata con successo."; // %1$s is the name of the category
$lang['AdminResponses.!success.response_added'] = "La risposta %1\$s è stata aggiunta correttamente."; // %1$s is the name of the predefined response
$lang['AdminResponses.!success.response_updated'] = "La risposta %1\$s è stata aggiornata con successo."; // %1$s is the name of the predefined response
$lang['AdminResponses.!success.response_deleted'] = "La risposta %1\$s è stata cancellata con successo."; // %1$s is the name of the predefined response
$lang['AdminResponses.index.page_title'] = "Gestione supporto > Risposte predefinite";
$lang['AdminResponses.add.page_title'] = "Gestione supporto > Aggiungi risposta predefinita";
$lang['AdminResponses.edit.page_title'] = "Gestione supporto > Modifica risposta predefinita";
$lang['AdminResponses.addcategory.page_title'] = "Supporto Gestione > Aggiungi Categoria";
$lang['AdminResponses.editcategory.page_title'] = "Support Manger > Modifica Categoria";
$lang['AdminResponses.!text.open_parenthesis'] = "(";
$lang['AdminResponses.!text.forward_slash'] = "/";
$lang['AdminResponses.!text.closed_parenthesis'] = ")";
$lang['AdminResponses.index.boxtitle_responses'] = "Risposte predefinite";
$lang['AdminResponses.index.add_response'] = "Aggiungi risposta qui";
$lang['AdminResponses.index.add_category'] = "Aggiungi categoria qui";
$lang['AdminResponses.index.text_up_level'] = "Sali di un livello";
$lang['AdminResponses.index.edit'] = "Modificare";
$lang['AdminResponses.index.delete'] = "Eliminare";
$lang['AdminResponses.index.no_responses'] = "Non ci sono risposte in questa sezione.";
$lang['AdminResponses.modal.delete_category'] = "Sei sicuro di voler cancellare questa categoria? Tutte le sottocategorie e le risposte predefinite all'interno di questa categoria saranno spostati alla categoria superiore";
$lang['AdminResponses.modal.delete_response'] = "Sei sicuro di voler cancellare questa risposta predefinita?";
$lang['AdminResponses.add.boxtitle_add'] = "Aggiungi risposta predefinita alla categoria [%1\$s]"; // %1$s is the name of the category
$lang['AdminResponses.add.field_name'] = "Nome";
$lang['AdminResponses.add.field_details'] = "Dettagli della risposta";
$lang['AdminResponses.add.field_submit'] = "Crea risposta";
$lang['AdminResponses.edit.boxtitle_edit'] = "Modifica risposta predefinita"; // %1$s is the name of the category
$lang['AdminResponses.edit.field_name'] = "Nome";
$lang['AdminResponses.edit.field_details'] = "Dettagli di risposta";
$lang['AdminResponses.edit.field_submit'] = "Risposta all'aggiornamento";
$lang['AdminResponses.addcategory.boxtitle_root'] = "Aggiungi categoria";
$lang['AdminResponses.addcategory.boxtitle_addcategory'] = "Aggiungi Categoria per categoria [%1\$s]"; // %1$s is the name of the parent category
$lang['AdminResponses.addcategory.field_name'] = "Nome";
$lang['AdminResponses.addcategory.field_submit'] = "Crea Categoria";
$lang['AdminResponses.editcategory.boxtitle_root'] = "Modifica categoria";
$lang['AdminResponses.editcategory.boxtitle_editcategory'] = "Aggiorna categoria";
$lang['AdminResponses.editcategory.field_name'] = "Nome";
$lang['AdminResponses.editcategory.field_submit'] = "Aggiorna categoria";
?>