<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyMessengers.templates.SupportManager.staff_ticket_updated_name'] = "Biglietto del personale aggiornato";
$lang['AdminCompanyMessengers.templates.SupportManager.staff_ticket_updated_desc'] = "Avviso inviato a un membro dello staff quando un ticket viene aggiornato.";
$lang['AdminCompanyMessengers.templates.SupportManager.staff_ticket_assigned_name'] = "Biglietto del personale assegnato";
$lang['AdminCompanyMessengers.templates.SupportManager.staff_ticket_assigned_desc'] = "Avviso inviato a un membro dello staff quando gli è stato assegnato un ticket.";
?>