<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminStaff.!success.staff_added'] = "Il membro dello staff è stato aggiunto con successo.";
$lang['AdminStaff.!success.staff_updated'] = "Il membro dello staff è stato aggiornato con successo.";
$lang['AdminStaff.!success.staff_deleted'] = "Il membro dello staff è stato cancellato con successo.";
$lang['AdminStaff.!tooltip.all_day'] = "Seleziona questa casella per rendere il membro dello staff disponibile tutto il giorno.";
$lang['AdminStaff.!tooltip.ticket_emails'] = "Seleziona la casella di ciascuna priorità del ticket per cui lo staff dovrebbe ricevere un email";
$lang['AdminStaff.!tooltip.mobile_ticket_emails'] = "Seleziona la casella di ciascuna priorità del biglietto per la quale il personale deve ricevere e-mail di biglietti mobili.";
$lang['AdminStaff.index.page_title'] = "Responsabile dell'assistenza > Personale";
$lang['AdminStaff.add.page_title'] = "Gestione supporto > Aggiungi personale";
$lang['AdminStaff.edit.page_title'] = "Gestione supporto > Modifica personale";
$lang['AdminStaff.index.categorylink_addstaff'] = "Aggiungi personale";
$lang['AdminStaff.index.boxtitle_staff'] = "Staff";
$lang['AdminStaff.index.heading_first_name'] = "Nome";
$lang['AdminStaff.index.heading_email'] = "Email";
$lang['AdminStaff.index.heading_ticket_emails'] = "Ricevi e-mail sui biglietti";
$lang['AdminStaff.index.heading_mobile_ticket_emails'] = "Ricevi e-mail di biglietti mobili";
$lang['AdminStaff.index.heading_options'] = "Opzioni";
$lang['AdminStaff.index.option_edit'] = "Modificare";
$lang['AdminStaff.index.option_delete'] = "Elimina";
$lang['AdminStaff.index.confirm_delete'] = "L'eliminazione di questo membro dello staff annullerà l'assegnazione di tutti i biglietti attualmente assegnati a questo membro dello staff. Sei sicuro di voler eliminare questo membro dello staff?";
$lang['AdminStaff.index.no_results'] = "Al momento non vi è personale assegnato al sistema di supporto.";
$lang['AdminStaff.add.boxtitle_addstaff'] = "Aggiungi personale";
$lang['AdminStaff.add.heading_staff'] = "Staff";
$lang['AdminStaff.add.heading_schedule'] = "Programma";
$lang['AdminStaff.add.heading_settings'] = "Impostazioni";
$lang['AdminStaff.add.heading_departments'] = "Dipartimenti";
$lang['AdminStaff.add.field_staff_group_id'] = "Gruppo del personale";
$lang['AdminStaff.add.field_staff_id'] = "Membro del personale";
$lang['AdminStaff.add.heading_day'] = "Giorno";
$lang['AdminStaff.add.heading_all_day'] = "Tutto il giorno";
$lang['AdminStaff.add.heading_start_time'] = "Ora di inizio";
$lang['AdminStaff.add.heading_end_time'] = "Tempo scaduto";
$lang['AdminStaff.add.ticket_emails'] = "Ricevi e-mail sui biglietti";
$lang['AdminStaff.add.mobile_ticket_emails'] = "Ricevi e-mail di biglietti mobili";
$lang['AdminStaff.add.text_assigneddepartments'] = "Dipartimenti assegnati";
$lang['AdminStaff.add.text_availabledepartments'] = "Dipartimenti disponibili";
$lang['AdminStaff.add.field_addsubmit'] = "Aggiungi personale";
$lang['AdminStaff.edit.boxtitle_editstaff'] = "Modifica rigo %1\$s %2\$s"; // %1$s is the staff member's first name, %2$s is the staff member's last name
$lang['AdminStaff.edit.heading_schedule'] = "Programma";
$lang['AdminStaff.edit.heading_settings'] = "Impostazioni";
$lang['AdminStaff.edit.heading_departments'] = "Dipartimenti";
$lang['AdminStaff.edit.heading_day'] = "Giorno";
$lang['AdminStaff.edit.heading_all_day'] = "Tutto il giorno";
$lang['AdminStaff.edit.heading_start_time'] = "Ora di inizio";
$lang['AdminStaff.edit.heading_end_time'] = "Tempo scaduto";
$lang['AdminStaff.edit.ticket_emails'] = "Ricevi e-mail sui biglietti";
$lang['AdminStaff.edit.mobile_ticket_emails'] = "Ricevi e-mail di biglietti mobili";
$lang['AdminStaff.edit.text_assigneddepartments'] = "Dipartimenti assegnati";
$lang['AdminStaff.edit.text_availabledepartments'] = "Dipartimenti disponibili";
$lang['AdminStaff.edit.field_editsubmit'] = "Modifica personale";
$lang['AdminStaff.staff.name'] = "%1\$s %2\$s"; // %1$s is the staff member's first name, %2$s is the staff member's last name
$lang['AdminStaff.schedule_list.heading_schedule'] = "Programma";
$lang['AdminStaff.schedule_list.heading_day'] = "Giorno";
$lang['AdminStaff.schedule_list.heading_start_time'] = "Ora di inizio";
$lang['AdminStaff.schedule_list.heading_end_time'] = "Tempo scaduto";
$lang['AdminStaff.schedule_list.no_results'] = "Questo membro dello staff non è previsto per nessun giorno.";
$lang['AdminStaff.schedule_list.heading_departments'] = "Dipartimenti";
$lang['AdminStaff.schedule_list.heading_department'] = "Dipartimento";
$lang['AdminStaff.schedule_list.heading_description'] = "Descrizione";
$lang['AdminStaff.schedule_list.no_department_results'] = "Questo membro dello staff non è assegnato a nessun dipartimento.";
$lang['AdminStaff.text.no_time'] = "--";
$lang['AdminStaff.!tooltip.title'] = "L'immissione di un titolo per questo membro del personale sovrascrive il titolo predefinito: %1\$s"; // %1$s is the language for the default title
$lang['AdminStaff.!tooltip.signature'] = "Inserisci una firma per renderla automaticamente disponibile quando rispondi ai ticket.";
$lang['AdminStaff.add.title'] = "titolo";
$lang['AdminStaff.add.signature'] = "Firma";
$lang['AdminStaff.edit.title'] = "Titolo";
$lang['AdminStaff.edit.signature'] = "Firma";
$lang['AdminStaff.!tooltip.ticket_messenger_notifications'] = "Seleziona la casella di ciascuna priorità del biglietto per la quale il personale deve ricevere le notifiche del ticket messenger.";
$lang['AdminStaff.index.heading_ticket_messenger_notifications'] = "Ricevi notifiche di Ticket Messenger";
$lang['AdminStaff.add.ticket_messenger_notifications'] = "Ricevi notifiche di Ticket Messenger";
$lang['AdminStaff.edit.ticket_messenger_notifications'] = "Ricevi notifiche di Ticket Messenger";
?>