<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminTickets.!success.ticket_created'] = "Il ticket #%1\$s è stato aperto con successo."; // %1$s is the ticket number
$lang['AdminTickets.!success.ticket_updated'] = "Il ticket #%1\$s è stato aggiornato con successo."; // %1$s is the ticket number
$lang['AdminTickets.!notice.no_departments_staff'] = "Non è stato ancora creato personale e/o dipartimento. Fai clic su %1\$s qui sopra per creare un dipartimento o su %2\$s per assegnare un membro dello staff."; // %1$s is the language definition for the Departments navigation item, %2$s is the language definition for the Staff navigation item
$lang['AdminTickets.index.page_title'] = "Gestione supporto > Ticket";
$lang['AdminTickets.add.page_title'] = "Gestione supporto > Apri ticket";
$lang['AdminTickets.reply.page_title'] = "Gestore supporto > Ticket n.%1\$s"; // %1$s is the ticket number
$lang['AdminTickets.search.page_title'] = "Risultati della ricerca per \"%1\$s\""; // %1$s is the search keywords
$lang['AdminTickets.text.unassigned'] = "Non assegnato";
$lang['AdminTickets.index.category_open'] = "In attesa di risposta da parte del personale";
$lang['AdminTickets.index.category_awaiting_reply'] = "In attesa della risposta del cliente";
$lang['AdminTickets.index.category_in_progress'] = "In corso";
$lang['AdminTickets.index.category_closed'] = "Chiuso";
$lang['AdminTickets.index.categorylink_createticket'] = "Apri un ticket";
$lang['AdminTickets.index.boxtitle_tickets'] = "Biglietti";
$lang['AdminTickets.index.heading_code'] = "Numero Ticket";
$lang['AdminTickets.index.heading_priority'] = "Priorità";
$lang['AdminTickets.index.heading_department_name'] = "Dipartimento";
$lang['AdminTickets.index.heading_summary'] = "Riepilogo";
$lang['AdminTickets.index.heading_last_reply_date'] = "Ultima risposta";
$lang['AdminTickets.index.no_results'] = "Al momento non ci sono biglietti con questo stato.";
$lang['AdminTickets.add.boxtitle_add'] = "Apri un ticket";
$lang['AdminTickets.add.heading_search_client'] = "Cerca il cliente";
$lang['AdminTickets.add.text_no_clients'] = "Nessun cliente è stato trovato. Prova di nuovo la ricerca.";
$lang['AdminTickets.add.heading_summary'] = "Riepilogo";
$lang['AdminTickets.add.heading_client'] = "Cliente";
$lang['AdminTickets.add.heading_department'] = "Dipartimento";
$lang['AdminTickets.add.heading_staff_id'] = "Assegnato a";
$lang['AdminTickets.add.heading_priority'] = "Priorità";
$lang['AdminTickets.add.heading_status'] = "Stato";
$lang['AdminTickets.add.field_attachments'] = "Allegati";
$lang['AdminTickets.add.field_details'] = "Dettagli";
$lang['AdminTickets.add.text_add_attachment'] = "Aggiungi allegato";
$lang['AdminTickets.add.field_addsubmit'] = "Apri un ticket";
$lang['AdminTickets.add.text_add_response'] = "Inserisci una risposta predefinita";
$lang['AdminTickets.reply.boxtitle_reply'] = "Biglietto n.%1\$s"; // %1$s is the ticket number
$lang['AdminTickets.reply.heading_summary'] = "Riepilogo";
$lang['AdminTickets.reply.heading_client'] = "Cliente";
$lang['AdminTickets.reply.heading_department'] = "Dipartimento";
$lang['AdminTickets.reply.heading_staff_id'] = "Assegnato a";
$lang['AdminTickets.reply.heading_priority'] = "Priorità";
$lang['AdminTickets.reply.heading_status'] = "Stato";
$lang['AdminTickets.reply.heading_date_added'] = "Data di apertura";
$lang['AdminTickets.reply.text_add_response'] = "Inserisci una risposta predefinita";
$lang['AdminTickets.reply.heading_reply'] = "Aggiungi risposta";
$lang['AdminTickets.reply.field_reply'] = "Rispondere";
$lang['AdminTickets.reply.field_note'] = "Nota";
$lang['AdminTickets.reply.field_attachments'] = "Allegati";
$lang['AdminTickets.reply.text_add_attachment'] = "Aggiungi allegato";
$lang['AdminTickets.reply.field_replysubmit'] = "Aggiorna biglietto";
$lang['AdminTickets.reply.reply_date'] = "

Il %1\$s %2\$s %3\$s ha risposto
"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['AdminTickets.reply.log_date'] = "%1\$s di %2\$s %3\$s"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['AdminTickets.reply.system'] = "Sistema";
$lang['AdminTickets.reply.staff_title'] = "Personale di supporto";
$lang['AdminTickets.client.category_open'] = "View the Google Translation";
$lang['AdminTickets.client.category_awaiting_reply'] = "In attesa della risposta del cliente";
$lang['AdminTickets.client.category_in_progress'] = "In corso";
$lang['AdminTickets.client.category_closed'] = "Chiuso";
$lang['AdminTickets.client.categorylink_createticket'] = "Apri Ticket";
$lang['AdminTickets.client.boxtitle_tickets'] = "Tickets";
$lang['AdminTickets.client.heading_code'] = "Ticket Numero";
$lang['AdminTickets.client.heading_priority'] = "Priorità";
$lang['AdminTickets.client.heading_department_name'] = "Dipartimento";
$lang['AdminTickets.client.heading_summary'] = "Riepilogo";
$lang['AdminTickets.client.heading_last_reply_date'] = "Ultima risposta";
$lang['AdminTickets.client.no_results'] = "Non ci sono tickets disponibili non questo status";
$lang['AdminTickets.search.boxtitle_tickets'] = "Cerca biglietti per \"%1\$s\""; // %1$s is the search criteria
$lang['AdminTickets.search.heading_code'] = "Numero del biglietto";
$lang['AdminTickets.search.heading_priority'] = "Priorità";
$lang['AdminTickets.search.heading_status'] = "Stato";
$lang['AdminTickets.search.heading_department_name'] = "Dipartimento";
$lang['AdminTickets.search.heading_summary'] = "Riepilogo";
$lang['AdminTickets.search.heading_last_reply_date'] = "Ultima risposta";
$lang['AdminTickets.search.no_results'] = "Non ci sono tickets che corrispondono ai criteri di ricerca.";
$lang['AdminTickets.index.last_reply_by'] = "di";
$lang['Admintickets.add.client_placeholder'] = "ID cliente o nome";
$lang['AdminTickets.!success.ticket_split'] = "Il ticket #%1\$s è stato suddiviso correttamente nel ticket #%2\$s."; // %1$s is the ticket number of the ticket being split, %2$s is the ticket number of the split ticket
$lang['AdminTickets.!success.ticket_merge'] = "I ticket selezionati sono stati uniti con successo nel ticket #%1\$s."; // %1$s is the ticket number
$lang['AdminTickets.!success.ticket_update_status'] = "Il ticket selezionati sono stati aggiornati con successo.";
$lang['AdminTickets.index.heading_assigned_staff'] = "Assegnato a";
$lang['AdminTickets.index.unassigned'] = "Non assegnato";
$lang['AdminTickets.index.text_with_selected'] = "Con i biglietti selezionati, esegui:";
$lang['AdminTickets.index.text_into_ticket'] = "Nel ticket";
$lang['AdminTickets.index.text_to_status'] = "Cambia in:";
$lang['AdminTickets.index.ticket_number_placeholder'] = "Ticket nr.";
$lang['AdminTickets.index.text_no_tickets'] = "View the Google Translation";
$lang['AdminTickets.index.field_actionsubmit'] = "Invia";
$lang['AdminTickets.index.ticket_name'] = "#%1\$s %2\$s %3\$s"; // %1$s is the ticket number, %2$s is the client's first name, %3$s is the client's last name
$lang['AdminTickets.index.ticket_email'] = "#%1\$s %2\$s"; // %1$s is the ticket number, %2$s is the client's email address
$lang['AdminTickets.reply.text_with_selected'] = "Con le risposte selezionate, esegui:";
$lang['AdminTickets.reply.field_actionsubmit'] = "Andare";
$lang['AdminTickets.index.heading_client'] = "Cliente";
$lang['AdminTickets.!success.ticket_delete'] = "I ticket selezionati sono stati eliminati con successo.";
$lang['AdminTickets.index.category_on_hold'] = "In attesa";
$lang['AdminTickets.index.category_trash'] = "Spazzatura";
$lang['AdminTickets.client.category_on_hold'] = "In attesa";
$lang['AdminTickets.client.category_trash'] = "Spazzatura";
$lang['AdminTickets.reply.refresh'] = "Sono presenti nuove risposte o cambiamenti di stato.";
$lang['AdminTickets.reply.refresh_link'] = "Fare clic per visualizzare.";
$lang['AdminTickets.!success.ticket_reassign'] = "I biglietti selezionati sono stati riassegnati con successo.";
$lang['AdminTickets.index.text_to_client'] = "Al cliente:";
$lang['AdminTickets.index.any'] = "Qualunque";
$lang['AdminTickets.index.minutes'] = "%1\$s minuti"; // %1$s is the elapsed minutes
$lang['AdminTickets.index.hour'] = "1 ora";
$lang['AdminTickets.index.hours'] = "%1\$s ore"; // %1$s is the elapsed hours
$lang['AdminTickets.index.field_ticket_number'] = "Numero del biglietto";
$lang['AdminTickets.index.field_priority'] = "Priorità";
$lang['AdminTickets.index.field_department_id'] = "Dipartimento";
$lang['AdminTickets.index.field_summary'] = "Riepilogo";
$lang['AdminTickets.index.field_assigned_staff'] = "Assegnato a";
$lang['AdminTickets.index.field_last_reply'] = "Ultima risposta";
$lang['AdminTickets.add.dropzone_drop_files_here'] = "Trascina qui i file da caricare o fai clic per selezionare i file";
$lang['AdminTickets.add.dropzone_remove_file'] = "Rimuovi il file";
$lang['AdminTickets.reply.dropzone_drop_files_here'] = "Trascina qui i file da caricare o fai clic per selezionare i file";
$lang['AdminTickets.reply.dropzone_remove_file'] = "Rimuovi il file";
?>