<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientTickets.!success.ticket_created'] = "Il ticket #%1\$s è stato creato con successo."; // %1$s is the ticket number
$lang['ClientTickets.!success.ticket_updated'] = "Il ticket #%1\$s è stato aggiornato con successo."; // %1$s is the ticket number
$lang['ClientTickets.!success.ticket_closed'] = "Il ticket #%1\$s è stato chiuso con successo."; // %1$s is the ticket number
$lang['ClientTickets.!notice.no_departments'] = "Non sono disponibili dipartimenti di supporto.";
$lang['ClientTickets.index.page_title'] = "Supporto > Ticket";
$lang['ClientTickets.add.page_title'] = "Supporto > Apri Ticket";
$lang['ClientTickets.reply.page_title'] = "Supporto > Aggiorna ticket";
$lang['ClientTickets.index.category_open'] = "Aprire";
$lang['ClientTickets.index.category_closed'] = "Chiuso";
$lang['ClientTickets.index.categorylink_createticket'] = "Apri un ticket";
$lang['ClientTickets.index.boxtitle_tickets'] = "Biglietti";
$lang['ClientTickets.index.heading_code'] = "Numero del biglietto";
$lang['ClientTickets.index.heading_priority'] = "Priorità";
$lang['ClientTickets.index.heading_department_name'] = "Dipartimento";
$lang['ClientTickets.index.heading_summary'] = "Riepilogo";
$lang['ClientTickets.index.heading_last_reply_date'] = "Ultima risposta";
$lang['ClientTickets.index.heading_status'] = "Stato";
$lang['ClientTickets.index.heading_options'] = "Opzioni";
$lang['ClientTickets.index.option_close'] = "Vicino";
$lang['ClientTickets.add.text_add_attachment'] = "Aggiungi allegato";
$lang['ClientTickets.index.no_results'] = "Al momento non ci sono biglietti con questo stato.";
$lang['ClientTickets.index.confirm_close'] = "Sei sicuro di voler chiudere questo ticket?";
$lang['ClientTickets.add.boxtitle_add'] = "Apri un ticket";
$lang['ClientTickets.add.field_email'] = "E-mail";
$lang['ClientTickets.add.field_summary'] = "Riassunto";
$lang['ClientTickets.add.field_priority'] = "Priorità";
$lang['ClientTickets.add.field_details'] = "Dettagli";
$lang['ClientTickets.add.field_attachments'] = "Allegati";
$lang['ClientTickets.add.field_addsubmit'] = "Apri un ticket";
$lang['ClientTickets.reply.boxtitle_reply'] = "Ticket #%1\$s"; // %1$s is the ticket number
$lang['ClientTickets.reply.heading_summary'] = "Riepilogo";
$lang['ClientTickets.reply.heading_department'] = "Dipartimento";
$lang['ClientTickets.reply.heading_priority'] = "Priorità";
$lang['ClientTickets.reply.heading_status'] = "Stato";
$lang['ClientTickets.reply.heading_date_added'] = "View the Google Translation";
$lang['ClientTickets.reply.heading_reply'] = "Aggiungi risposta";
$lang['ClientTickets.reply.field_details'] = "Dettagli";
$lang['ClientTickets.reply.field_attachments'] = "Allegati";
$lang['ClientTickets.reply.text_add_attachment'] = "Aggiungi allegato";
$lang['ClientTickets.reply.reply_date'] = "Il %1\$s %2\$s %3\$s ha risposto"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['ClientTickets.reply.log_date'] = "%1\$s di %2\$s %3\$s"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['ClientTickets.reply.system'] = "Sistema";
$lang['ClientTickets.reply.staff_title'] = "Personale di supporto";
$lang['ClientTickets.departments.boxtitle_departments'] = "Servizio di assistenza";
$lang['ClientTickets.index.option_reply'] = "Rispondere";
$lang['ClientTickets.add.placeholder_summary'] = "Inserisci il riepilogo";
$lang['ClientTickets.add.placeholder_details'] = "Inserisci i dettagli";
$lang['ClientTickets.reply.placeholder_reply'] = "Inserisci Dettagli";
$lang['ClientTickets.reply.field_closesubmit'] = "Vicino";
$lang['ClientTickets.reply.confirm_close'] = "Sei sicuro di voler chiudere questo ticket?";
$lang['ClientTickets.reply.field_replysubmit'] = "Rispondere";
$lang['ClientTickets.index.any'] = "Qualunque";
$lang['ClientTickets.index.minutes'] = "%1\$s minuti"; // %1$s is the elapsed minutes
$lang['ClientTickets.index.hour'] = "1 ora";
$lang['ClientTickets.index.hours'] = "%1\$s ore"; // %1$s is the elapsed hours
$lang['ClientTickets.index.field_ticket_number'] = "Numero del biglietto";
$lang['ClientTickets.index.field_priority'] = "Priorità";
$lang['ClientTickets.index.field_summary'] = "Riepilogo";
$lang['ClientTickets.index.field_last_reply'] = "Ultima risposta";
$lang['ClientTickets.add.dropzone_drop_files_here'] = "Trascina qui i file da caricare o fai clic per selezionare i file";
$lang['ClientTickets.add.dropzone_remove_file'] = "Rimuovi il file";
$lang['ClientTickets.reply.dropzone_drop_files_here'] = "Trascina qui i file da caricare o fai clic per selezionare i file";
$lang['ClientTickets.reply.dropzone_remove_file'] = "Rimuovi il file";
$lang['ClientTickets.!error.captcha.invalid'] = "Il captcha inserito non è valido. Per favore riprova.";
$lang['ClientTickets.formatDepartmentCustomFields.encrypted_field'] = "Questi dati sono crittografati e non possono essere visualizzati.";
?>