<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientMain.index.page_title'] = "Supporto > Ticket";
$lang['ClientMain.index.category_open'] = "Aprire";
$lang['ClientMain.index.category_closed'] = "Chiuso";
$lang['ClientMain.index.categorylink_createticket'] = "Apri un ticket";
$lang['ClientMain.index.boxtitle_tickets'] = "Biglietti";
$lang['ClientMain.index.heading_code'] = "Numero del biglietto";
$lang['ClientMain.index.heading_priority'] = "Priorità";
$lang['ClientMain.index.heading_department_name'] = "Dipartimento";
$lang['ClientMain.index.heading_summary'] = "Riepilogo";
$lang['ClientMain.index.heading_last_reply_date'] = "Ultima risposta";
$lang['ClientMain.index.heading_status'] = "Stato";
$lang['ClientMain.index.heading_options'] = "Opzioni";
$lang['ClientMain.index.option_close'] = "Vicino";
$lang['ClientMain.index.option_reply'] = "Rispondere";
$lang['ClientMain.index.any'] = "Qualunque";
$lang['ClientMain.index.minutes'] = "%1\$s minuti"; // %1$s is the elapsed minutes
$lang['ClientMain.index.hour'] = "1 ora";
$lang['ClientMain.index.hours'] = "%1\$s ore"; // %1$s is the elapsed hours
$lang['ClientMain.index.field_ticket_number'] = "Numero del biglietto";
$lang['ClientMain.index.field_priority'] = "Priorità";
$lang['ClientMain.index.field_summary'] = "Riepilogo";
$lang['ClientMain.index.field_last_reply'] = "Ultima risposta";
$lang['ClientMain.index.no_results'] = "Al momento non ci sono biglietti con questo stato.";
$lang['ClientMain.index.confirm_close'] = "Sei sicuro di voler chiudere questo ticket?";
?>