<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Global.time_since.day'] = "%1\$s d"; // %1$s is the number of days
$lang['Global.time_since.hour'] = "%1\$s ore"; // %1$s is the number of hours
$lang['Global.time_since.minute'] = "%1\$s min"; // %1$s is the number of minutes
$lang['Global.select.never'] = "-- Mai --";
$lang['Global.action.split'] = "Dividi";
$lang['Global.action.merge'] = "Unisci";
$lang['Global.action.update_status'] = "Aggiorna stato";
$lang['Global.action.quote'] = "Citazione";
$lang['Global.action.delete'] = "Eliminare";
$lang['Global.action.reassign'] = "Riassegnare";
?>