<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Knowledgebase.index.page_title'] = "base di conoscenza";
$lang['Knowledgebase.view.page_title'] = "%1\$s"; // %1\$s is the title of the knowledge base article
$lang['Knowledgebase.search.placeholder'] = "Avete una domanda? Ricerca nella Knowledge Base qui.";
$lang['Knowledgebase.search.form_submit'] = "Ricerca";
$lang['Knowledgebase.index.heading_categories'] = "Categorie";
$lang['Knowledgebase.index.heading_subcategories'] = "Sottocategorie";
$lang['Knowledgebase.index.category_items'] = "(%1\$s)"; // %1$s is the number of items within this category
$lang['Knowledgebase.index.categories_description'] = "Sfoglia la nostra Knowledge Base per categoria.";
$lang['Knowledgebase.index.categories_no_results'] = "Non ci sono categorie disponibili.";
$lang['Knowledgebase.index.heading_popular'] = "Articoli popolari";
$lang['Knowledgebase.index.popular_description'] = "Le persone hanno trovato questi articoli i più utili.";
$lang['Knowledgebase.index.heading_articles'] = "Articoli";
$lang['Knowledgebase.index.articles_description'] = "Articoli per %1\$s."; // %1$s is the name of the category
$lang['Knowledgebase.search.heading_articles'] = "Articoli corrispondenti a '%1\$s'"; // %1$s is the search criteria
$lang['Knowledgebase.search.articles_no_results'] = "Non ci sono articoli che corrispondono ai criteri di ricerca.";
$lang['Knowledgebase.view.text_rate'] = "Valuta questo articolo per aiutarci a migliorare la nostra Knowledge Base.";
$lang['Knowledgebase.view.edit'] = "Modifica";
$lang['Knowledgebase.view.text_voted'] = "Hai già votato questo articolo.
";
$lang['Knowledgebase.view.text_vote_thanks'] = "Grazie per aver votato questo articolo!";
$lang['Knowledgebase.!text.root_directory'] = "Home";
$lang['Knowledgebase.!text.ellipsis'] = "...";
?>