<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerResponses.!error.company_id.exists'] = "ID azienda non valido.";
$lang['SupportManagerResponses.!error.parent_id.exists'] = "ID categoria principale non valido.";
$lang['SupportManagerResponses.!error.parent_id.company'] = "

e.g. module_field
";
$lang['SupportManagerResponses.!error.name.empty'] = "Inserisci un nome di categoria.";
$lang['SupportManagerResponses.!error.name.length'] = "Il nome della categoria non può superare i 64 caratteri di lunghezza.";
$lang['SupportManagerResponses.!error.category_id.exists'] = "ID categoria non valido.";
$lang['SupportManagerResponses.!error.name.response_empty'] = "Inserisci un nome per questa risposta.";
$lang['SupportManagerResponses.!error.name.response_length'] = "La categoria non può essere superiore a 64 caratteri";
$lang['SupportManagerResponses.!error.details.empty'] = "Inserisci i dettagli della risposta.";
$lang['SupportManagerResponses.!error.category_id.root_responses'] = "La categoria non può essere eliminata perché contiene risposte predefinite.";
?>