<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerDepartments.!error.company_id.exists'] = "ID azienda non valido.";
$lang['SupportManagerDepartments.!error.name.empty'] = "Inserisci un nome per questo dipartimento.";
$lang['SupportManagerDepartments.!error.description.empty'] = "Inserisci una descrizione.";
$lang['SupportManagerDepartments.!error.email.format'] = "Si prega di inserire un indirizzo email valido.";
$lang['SupportManagerDepartments.!error.method.format'] = "Tipo di metodo non valido.";
$lang['SupportManagerDepartments.!error.method.imap'] = "L'estensione PHP IMAP è necessaria per il download di messaggi tramite POP3 o IMAP.";
$lang['SupportManagerDepartments.!error.method.mailparse'] = "L'estensione PHP Mailparse PECL è necessaria per l'analisi dei ticket e-mail.";
$lang['SupportManagerDepartments.!error.default_priority.format'] = "Tipo di priorità predefinito non valido.";
$lang['SupportManagerDepartments.!error.host.format'] = "Si prega di inserire un nome host valido.";
$lang['SupportManagerDepartments.!error.host.length'] = "Il nome host non può superare i 128 caratteri di lunghezza.";
$lang['SupportManagerDepartments.!error.user.format'] = "Perfavore inserisci un username.";
$lang['SupportManagerDepartments.!error.user.length'] = "Il nome utente non può superare i 64 caratteri di lunghezza.";
$lang['SupportManagerDepartments.!error.password.format'] = "Per favore inserire una password.";
$lang['SupportManagerDepartments.!error.port.format'] = "Inserisci un numero di porta.";
$lang['SupportManagerDepartments.!error.port.length'] = "La porta non può superare le 6 cifre di lunghezza.";
$lang['SupportManagerDepartments.!error.service.format'] = "Si prega di selezionare un tipo di servizio valido.";
$lang['SupportManagerDepartments.!error.security.format'] = "Seleziona un tipo di sicurezza valido.";
$lang['SupportManagerDepartments.!error.mark_messages.format'] = "Per favore seleziona un valido tipo di messaggio per contrassegnare i messaggi.";
$lang['SupportManagerDepartments.!error.mark_messages.valid'] = "I messaggi che utilizzano POP3 possono essere contrassegnati solo come eliminati.";
$lang['SupportManagerDepartments.!error.status.format'] = "Tipo di stato non valido.";
$lang['SupportManagerDepartments.!error.department_id.exists'] = "ID reparto non valido.";
$lang['SupportManagerDepartments.!error.department_id.has_tickets'] = "Non è stato possibile eliminare il reparto perché attualmente gli sono assegnati dei ticket.";
$lang['SupportManagerDepartments.methods.none'] = "Nessuno";
$lang['SupportManagerDepartments.methods.pipe'] = "Piping";
$lang['SupportManagerDepartments.methods.pop3'] = "POP3";
$lang['SupportManagerDepartments.methods.imap'] = "IMAP";
$lang['SupportManagerDepartments.statuses.hidden'] = "Nascosto";
$lang['SupportManagerDepartments.statuses.visible'] = "Visibile";
$lang['SupportManagerDepartments.priorities.emergency'] = "Emergenza";
$lang['SupportManagerDepartments.priorities.critical'] = "Critico";
$lang['SupportManagerDepartments.priorities.high'] = "Alto";
$lang['SupportManagerDepartments.priorities.medium'] = "medio";
$lang['SupportManagerDepartments.priorities.low'] = "Basso";
$lang['SupportManagerDepartments.security_types.none'] = "Nessuno";
$lang['SupportManagerDepartments.security_types.ssl'] = "SSL";
$lang['SupportManagerDepartments.security_types.tls'] = "TLS";
$lang['SupportManagerDepartments.message_types.read'] = "Leggere";
$lang['SupportManagerDepartments.message_types.deleted'] = "Eliminato";
$lang['SupportManagerDepartments.!error.clients_only.format'] = "Se consentire ai client di aprire o rispondere ai ticket deve essere impostato su 0 o 1.";
$lang['SupportManagerDepartments.!error.override_from_email.format'] = "Per consentire a questa email di dipartimento di essere usata come indirizzo email da nei template il valore deve essere impostato su 0 o 1.";
$lang['SupportManagerDepartments.!error.close_ticket_interval.format'] = "Si prega di selezionare uno intervallo di ticket valido.";
$lang['SupportManagerDepartments.!error.response_id.format'] = "Seleziona una risposta di chiusura automatica valida.";
$lang['SupportManagerDepartments.ticket_intervals.day'] = "1 giorno";
$lang['SupportManagerDepartments.ticket_intervals.days'] = "%1\$s Giorni"; // %1$s is the number of days
$lang['SupportManagerDepartments.!error.send_ticket_received.format'] = "Se inviare e-mail di conferma del ticket per questo reparto deve essere impostato su 0 o 1.";
$lang['SupportManagerDepartments.!error.delete_ticket_interval.format'] = "Seleziona un intervallo valido per l'eliminazione del ticket.";
$lang['SupportManagerDepartments.!error.require_captcha.format'] = "Se richiedere la verifica umana deve essere impostato su 0 o 1.";
$lang['SupportManagerDepartments.!error.reminder_ticket_interval.format'] = "Seleziona un intervallo di ticket promemoria valido.";
$lang['SupportManagerDepartments.!error.reminder_ticket_status.format'] = "Seleziona uno stato di promemoria del biglietto valido.";
$lang['SupportManagerDepartments.!error.reminder_ticket_priority.format'] = "Seleziona una priorità valida per il promemoria del biglietto.";
$lang['SupportManagerDepartments.!error.include_attachments.format'] = "Se includere gli allegati del ticket deve essere impostato su 0 o 1.";
$lang['SupportManagerDepartments.!error.attachment_types.length'] = "L'elenco dei tipi di allegati non può superare i 255 caratteri di lunghezza.";
$lang['SupportManagerDepartments.!error.max_attachment_size.format'] = "La dimensione massima dell'allegato deve essere un valore numerico.";
$lang['SupportManagerDepartments.reminder_intervals.hour'] = "1 ora";
$lang['SupportManagerDepartments.reminder_intervals.hours'] = "%1\$s Ore"; // %1$s is the number of hours
$lang['SupportManagerDepartments.reminder_intervals.minutes'] = "%1\$s Minuti"; // %1$s is the number of minutes
$lang['SupportManagerDepartments.!error.label.empty'] = "Inserisci un'etichetta.";
$lang['SupportManagerDepartments.!error.visibility.format'] = "Seleziona uno stato di visibilità valido.";
$lang['SupportManagerDepartments.!error.type.format'] = "Seleziona un tipo di campo valido.";
$lang['SupportManagerDepartments.!error.client_add.format'] = "Se consentire al client di aggiungere deve essere impostato su 0 o 1.";
$lang['SupportManagerDepartments.!error.encrypted.format'] = "Se crittografare i dati del campo deve essere impostato su 0 o 1.";
$lang['SupportManagerDepartments.!error.auto_delete.format'] = "Se eliminare automaticamente i dati del campo dopo la chiusura di un ticket deve essere impostato su 0 o 1.";
$lang['SupportManagerDepartments.field_types.checkbox'] = "Casella di controllo";
$lang['SupportManagerDepartments.field_types.radio'] = "Radio";
$lang['SupportManagerDepartments.field_types.select'] = "Cadere in picchiata";
$lang['SupportManagerDepartments.field_types.quantity'] = "Quantità";
$lang['SupportManagerDepartments.field_types.text'] = "Testo";
$lang['SupportManagerDepartments.field_types.textarea'] = "Area di testo";
$lang['SupportManagerDepartments.field_types.password'] = "Parola d'ordine";
$lang['SupportManagerDepartments.visibility_options.client'] = "Cliente e personale";
$lang['SupportManagerDepartments.visibility_options.staff'] = "Solo per il personale";
?>