<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerStaff.!error.staff_id.exists'] = "Il membro dello staff da aggiungere non esiste.";
$lang['SupportManagerStaff.!error.staff_id.belongs'] = "Il dipendente non appartiene all'azienda a cui è assegnato.";
$lang['SupportManagerStaff.!error.staff_id.duplicate'] = "Il membro dello staff selezionato esiste già nel sistema di supporto.";
$lang['SupportManagerStaff.!error.company_id.exists'] = "L'ID dell'azienda non è valido.";
$lang['SupportManagerStaff.!error.departments.exists'] = "Almeno uno dei reparti impostati non esiste.";
$lang['SupportManagerStaff.!error.schedules.minimum'] = "Imposta un'ora di inizio e fine programmata per almeno un giorno.";
$lang['SupportManagerStaff.!error.schedules.unique_days'] = "Ogni giorno programmato deve essere unico.";
$lang['SupportManagerStaff.!error.schedules[][day].format'] = "Giorno programmato non valido.";
$lang['SupportManagerStaff.!error.schedules[][start_time].format'] = "Si prega di selezionare un'ora di inizio per ogni giorno programmato";
$lang['SupportManagerStaff.!error.schedules[][end_time].format'] = "Seleziona un'ora di fine per ogni giorno programmato.";
$lang['SupportManagerStaff.days.sun'] = "Domenica";
$lang['SupportManagerStaff.days.mon'] = "Lunedi";
$lang['SupportManagerStaff.days.tue'] = "Martedì";
$lang['SupportManagerStaff.days.wed'] = "Mercoledì";
$lang['SupportManagerStaff.days.thu'] = "Giovedì";
$lang['SupportManagerStaff.days.fri'] = "Venerdì";
$lang['SupportManagerStaff.days.sat'] = "Sabato";
?>