<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerKbCategories.!error.parent_id.exists'] = "ID genitore non valido.";
$lang['SupportManagerKbCategories.!error.parent_id.valid_company'] = "Questa categoria non può essere assegnata a una società madre di una società separata.";
$lang['SupportManagerKbCategories.!error.parent_id.valid_parent'] = "Questa categoria non può essere un livello a se stesso.";
$lang['SupportManagerKbCategories.!error.company_id.exists'] = "ID azienda non valido.";
$lang['SupportManagerKbCategories.!error.name.empty'] = "Inserisci il nome di una categoria.";
$lang['SupportManagerKbCategories.!error.name.length'] = "Il nome della categoria non può superare i 255 caratteri di lunghezza.";
$lang['SupportManagerKbCategories.!error.access.type'] = "Tipo di accesso non valido.";
$lang['SupportManagerKbCategories.!error.category_id.exists'] = "ID categoria non valido.";
$lang['SupportManagerKbCategories.access_types.public'] = "Pubblico";
$lang['SupportManagerKbCategories.access_types.private'] = "Privato";
$lang['SupportManagerKbCategories.access_types.hidden'] = "Nascosto";
$lang['SupportManagerKbCategories.!error.articles.parent'] = "La categoria non può essere eliminata a meno che tutti gli articoli al suo interno non appartengano a un'altra categoria.";
$lang['SupportManagerKbCategories.access_types.staff'] = "Personale";
?>