<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['InvoiceDelivery.!error.libxml_required'] = "Per l'invio delle fatture sono necessarie le estensioni libxml e simplexml.";
$lang['InvoiceDelivery.deliverinvoices.interfax_subject'] = "Fattura #%1\$s"; // %1$s is the invoice number (or the first invoice number in a group of several)
$lang['InvoiceDelivery.deliverinvoices.postalmethods_description'] = "Fattura n.%1\$s"; // %1$s is the invoice number (or the first invoice number in a group of several);
?>