<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.options_updated'] = "Le impostazioni della Panoramica del sistema sono state aggiornate con successo!";
$lang['AdminMain.index.boxtitle_overview'] = "panoramica del sistema";
$lang['AdminMain.overview.statistic.clients_active'] = "Clienti attivi";
$lang['AdminMain.overview.statistic.services_active'] = "Servizi attivi";
$lang['AdminMain.overview.statistic.active_users_today'] = "Utenti attivi oggi";
$lang['AdminMain.overview.statistic.recurring_invoices'] = "Fatture ricorrenti";
$lang['AdminMain.overview.statistic.pending_orders'] = "Ordini in attesa";
$lang['AdminMain.overview.statistic.open_tickets'] = "Apri i biglietti";
$lang['AdminMain.overview.heading_users'] = "Utenti recenti";
$lang['AdminMain.overview.tab_all'] = "Grafici";
$lang['AdminMain.overview.tab_clients'] = "Clienti";
$lang['AdminMain.overview.tab_services'] = "Servizi";
$lang['AdminMain.overview.tooltip_activity'] = "L'ultima attività";
$lang['AdminMain.overview.tooltip_location'] = "Posizione";
$lang['AdminMain.overview.tooltip_last_activity_now'] = "Proprio adesso";
$lang['AdminMain.overview.tooltip_last_activity_minute'] = "1 minuto fa";
$lang['AdminMain.date_range.days'] = "%1\$s Giorni"; // %1$s is the number of days (more than 1)
$lang['AdminMain.settings.heading_statistics'] = "Statistiche";
$lang['AdminMain.settings.text_options'] = "Controlla le opzioni che appariranno nella Panoramica del sistema.";
$lang['AdminMain.settings.clients_active'] = "Clienti attivi";
$lang['AdminMain.settings.services_active'] = "Servizi attivi";
$lang['AdminMain.settings.active_users_today'] = "Utenti attivi oggi";
$lang['AdminMain.settings.recurring_invoices'] = "Fatture ricorrenti";
$lang['AdminMain.settings.open_tickets'] = "Biglietti aperti";
$lang['AdminMain.settings.pending_orders'] = "Ordini in attesa";
$lang['AdminMain.settings.heading_clients'] = "Scheda Clienti";
$lang['AdminMain.settings.text_graphs_clients'] = "Controlla quali grafici dovrebbero apparire nella scheda Clienti.";
$lang['AdminMain.settings.graph_clients'] = "Grafico dei clienti";
$lang['AdminMain.settings.heading_services'] = "Scheda Servizi";
$lang['AdminMain.settings.text_graphs_services'] = "Controlla quali grafici dovrebbero apparire nella scheda Servizi.";
$lang['AdminMain.settings.graph_services'] = "Grafico dei servizi";
$lang['AdminMain.settings.heading_settings'] = "Impostazioni";
$lang['AdminMain.settings.show_one_tab'] = "Mostra solo una scheda";
$lang['AdminMain.settings.tooltip_show_one_tab'] = "Non separa più i grafici in schede, ma li mostra tutti in un'unica scheda.";
$lang['AdminMain.settings.show_legend'] = "Mostra legenda";
$lang['AdminMain.settings.date_range'] = "Intervallo di date del grafico";
$lang['AdminMain.settings.submit_cancel'] = "Ritorna al sommario";
$lang['AdminMain.settings.submit_settings'] = "Aggiorna impostazioni";
$lang['AdminMain.graph_name.graph_services'] = "Servizi";
$lang['AdminMain.graph_name.graph_clients'] = "Clienti";
$lang['AdminMain.graph_line_name.active'] = "Attivo";
$lang['AdminMain.graph_line_name.canceled'] = "Annullato";
$lang['AdminMain.graph_line_name.new'] = "Nuovo";
$lang['AdminMain.overview.statistic.services_scheduled_cancellation'] = "Servizi previsti per la cancellazione";
$lang['AdminMain.settings.services_scheduled_cancellation'] = "Servizi previsti per la cancellazione";
$lang['AdminMain.overview.tooltip_last_activity_minutes'] = "%1\$s minuti fa"; // %1$s is the number of minutes since the user's last activity
$lang['AdminMain.graph_line_name.suspended'] = "Sospeso";
?>