<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['IpUnblockerPlugin.name'] = "Sblocco IP";
$lang['IpUnblockerPlugin.description'] = "Un plugin per Blesta che si integra con cPanel e DirectAdmin per sbloccare gli IP nella lista nera";
$lang['IpUnblockerPlugin.unblock_ip'] = "Sblocca IP";
$lang['IpUnblockerPlugin.!success.unblock_ip'] = "Richiesta di sblocco inviata.";
$lang['IpUnblockerPlugin.!error.remote_curl'] = "Impossibile connettersi al server remoto. Errore cURL: %1\$s"; // %1$s is the curl error
?>