<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Perfectmoney.name'] = "Soldi perfetti";
$lang['Perfectmoney.payee_account'] = "Conto del beneficiario";
$lang['Perfectmoney.passphrase'] = "Passphrase alternativa";
$lang['Perfectmoney.passphrase_note'] = "The alternative passphrase is used for the calculation of the MD5 hash to validate payments.";
$lang['Perfectmoney.buildprocess.submit'] = "Paga con Perfect Money";
$lang['Perfectmoney.!error.payee_account.valid'] = "È necessario inserire un account valido.";
$lang['Perfectmoney.!error.passphrase.valid'] = "Devi inserire una passphrase valida.";
?>