<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['404.heading_error'] = "404";
$lang['404.text_error'] = "Spiacenti, la pagina che si sta tentando di accedere non esiste o è stata spostata.";
$lang['404.text_go_to_home'] = "Vai alla Home";
?>