<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['_PaymentTypes.cash'] = "Contanti";
$lang['_PaymentTypes.check'] = "Verifica";
$lang['_PaymentTypes.money_order'] = "Vaglia";
$lang['_PaymentTypes.in_house_credit'] = "In House Credit";
?>