<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Accounts.!error.contact_id.exists'] = "Id Contatto non corretto";
$lang['Accounts.!error.first_name.empty'] = "Si prega di specificare un Nome";
$lang['Accounts.!error.last_name.empty'] = "Si prega di specificare un Cognome";
$lang['Accounts.!error.state.length'] = "Lunghezza Stato non può superare i 3 caratteri.";
$lang['Accounts.!error.country.length'] = "La lunghezza paese non può superare i 3 caratteri";
$lang['Accounts.!error.state.country_exists'] = "Si prega di selezionare il paese che corrisponde allo stato selezionato.";
$lang['Accounts.!error.account.length'] = "Si prega di specificare un numero di conto";
$lang['Accounts.!error.routing.empty'] = "Si prega di specificare un numero di routing";
$lang['Accounts.!error.last4.empty_ach'] = "Inserisci le ultime quattro cifre del numero di conto.";
$lang['Accounts.!error.type.ach_format'] = "Tipo non valido.";
$lang['Accounts.!error.ach_account_id.exists'] = "Account ID Invalido";
$lang['Accounts.!error.number.valid'] = "Il numero di carta fornito non è valido";
$lang['Accounts.!error.expiration.empty'] = "Si prega di inserire la data di scadenza della carta di credito";
$lang['Accounts.!error.expiration.valid'] = "La data di scadenza è già decaduta.";
$lang['Accounts.!error.last4.empty_cc'] = "Inserisci le ultime quattro cifre del numero della carta di credito.";
$lang['Accounts.!error.type.cc_format'] = "Il tipo di carta non è valido o non è stato possibile determinarlo";
$lang['Accounts.!error.cc_account_id.exists'] = "Account ID non Valido";
$lang['Accounts.getTypes.cc'] = "Carta di Credito";
$lang['Accounts.getTypes.ach'] = "Automated Clearing House";
$lang['Accounts.getTypes.other'] = "Altro";
$lang['Accounts.getAchTypes.checking'] = "Verifica";
$lang['Accounts.getAchTypes.savings'] = "Salvataggio";
$lang['Accounts.getCcTypes.amex'] = "American Express";
$lang['Accounts.getCcTypes.bc'] = "Bancomat";
$lang['Accounts.getCcTypes.cup'] = "China Union Pay";
$lang['Accounts.getCcTypes.dc-cb'] = "Diners Club Carte Blanche";
$lang['Accounts.getCcTypes.dc-er'] = "Diners Club EnRoute";
$lang['Accounts.getCcTypes.dc-int'] = "Diners Club International";
$lang['Accounts.getCcTypes.dc-uc'] = "Diners Club US and Canada";
$lang['Accounts.getCcTypes.disc'] = "Scoprire";
$lang['Accounts.getCcTypes.ipi'] = "InstaPayment";
$lang['Accounts.getCcTypes.jcb'] = "Japan Credit Bureau";
$lang['Accounts.getCcTypes.lasr'] = "Laser";
$lang['Accounts.getCcTypes.maes'] = "Maestro";
$lang['Accounts.getCcTypes.mc'] = "Master Card";
$lang['Accounts.getCcTypes.solo'] = "Solo";
$lang['Accounts.getCcTypes.switch'] = "Cambia";
$lang['Accounts.getCcTypes.visa'] = "Visa";
$lang['Accounts.getCcTypes.other'] = "Altro..";
$lang['Accounts.!error.currency.format'] = "La valuta non è valida.";
?>