<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyGroups.!success.add_created'] = "%1\$s è stato creato con successo!"; // %1$s is the name of the client group
$lang['AdminCompanyGroups.!success.edit_updated'] = "%1\$s è stato modificato con successo!"; // %1$s is the name of the client group
$lang['AdminCompanyGroups.!success.delete_deleted'] = "%1\$s è stato eliminato con successo!"; // %1$s is the name of the client group
$lang['AdminCompanyGroups.!error.delete_failed'] = "%1\$s è il gruppo predefinito e non può essere eliminato."; // %1$s is the name of the client group
$lang['AdminCompanyGroups.index.boxtitle_groups'] = "Gruppi di clienti";
$lang['AdminCompanyGroups.index.categorylink_addgroup'] = "Crea un gruppo";
$lang['AdminCompanyGroups.index.text_name'] = "Nome";
$lang['AdminCompanyGroups.index.text_description'] = "Descrizione";
$lang['AdminCompanyGroups.index.text_clients'] = "Numero di Clienti";
$lang['AdminCompanyGroups.index.text_options'] = "Opzioni";
$lang['AdminCompanyGroups.index.option_edit'] = "Modificare";
$lang['AdminCompanyGroups.index.option_delete'] = "Cancella";
$lang['AdminCompanyGroups.index.no_results'] = "Non ci sono gruppi di clienti.";
$lang['AdminCompanyGroups.index.confirm_delete'] = "Sei sicuro di voler eliminare questo gruppo di clienti? Tutti i client in questo gruppo verranno spostati nel gruppo predefinito.";
$lang['AdminCompanyGroups.add.boxtitle_addgroup'] = "Creare un gruppo";
$lang['AdminCompanyGroups.add.heading_basic'] = "Opzioni di base";
$lang['AdminCompanyGroups.add.heading_invoice'] = "Opzioni di fatturazione e addebito";
$lang['AdminCompanyGroups.add.heading_delivery'] = "Consegna della fattura";
$lang['AdminCompanyGroups.add.field_name'] = "Nome";
$lang['AdminCompanyGroups.add.field_color'] = "Colore";
$lang['AdminCompanyGroups.add.field_description'] = "Descrizione";
$lang['AdminCompanyGroups.add.field_delivery_methods'] = "Metodi di consegna delle fatture";
$lang['AdminCompanyGroups.add.field_company_settings'] = "Utilizza le impostazioni aziendali (deseleziona per specificare di seguito)";
$lang['AdminCompanyGroups.add.text_addsubmit'] = "Crea un gruppo";
$lang['AdminCompanyGroups.edit.boxtitle_editgroup'] = "Modifica Gruppo";
$lang['AdminCompanyGroups.edit.heading_basic'] = "Opzioni di base";
$lang['AdminCompanyGroups.edit.heading_invoice'] = "Opzioni di fatturazione e addebito";
$lang['AdminCompanyGroups.edit.heading_delivery'] = "Consegna della fattura";
$lang['AdminCompanyGroups.edit.field_name'] = "Nome";
$lang['AdminCompanyGroups.edit.field_color'] = "Colore";
$lang['AdminCompanyGroups.edit.field_description'] = "Descrizione";
$lang['AdminCompanyGroups.edit.field_delivery_methods'] = "Metodi di consegna delle fatture";
$lang['AdminCompanyGroups.edit.field_company_settings'] = "

Utilizza le impostazioni dell'azienda (deseleziona per specificare di seguito)
";
$lang['AdminCompanyGroups.edit.text_editsubmit'] = "Modifica gruppo";
$lang['AdminCompanyGroups.index.page_title'] = "Impostazioni > Azienda > Gruppi di clienti";
$lang['AdminCompanyGroups.add.page_title'] = "Impostazioni> Azienda> Gruppi client> Crea gruppo";
$lang['AdminCompanyGroups.edit.page_title'] = "Impostazioni > Azienda > Gruppi di clienti > Modifica gruppo";
$lang['AdminCompanyGroups.add.heading_client_fields'] = "Campi cliente obbligatori";
$lang['AdminCompanyGroups.edit.heading_client_fields'] = "Campi cliente obbligatori";
$lang['AdminCompanyGroups.add.heading_payment'] = "Avvisi";
$lang['AdminCompanyGroups.edit.heading_payment'] = "Avvisi";
$lang['AdminCompanyGroups.add.heading_late_fees'] = "Commissioni per ritardo";
$lang['AdminCompanyGroups.edit.heading_late_fees'] = "Commissioni per ritardo";
$lang['AdminCompanyGroups.!tooltip.force_email_usernames'] = "Rimuove la possibilità per i client di definire il proprio nome utente.";
$lang['AdminCompanyGroups.add.heading_client_settings'] = "Impostazioni generali del cliente";
$lang['AdminCompanyGroups.add.field_force_email_usernames'] = "Applica gli indirizzi email come nomi utente";
$lang['AdminCompanyGroups.edit.heading_client_settings'] = "Impostazioni generali del cliente";
$lang['AdminCompanyGroups.edit.field_force_email_usernames'] = "Applica gli indirizzi email come nomi utente";
$lang['AdminCompanyGroups.!tooltip.email_verification'] = "Selezionare per inviare un'e-mail di verifica e-mail quando viene creato un nuovo accesso o un cliente modifica la propria e-mail. Un avviso apparirà sul profilo dei clienti finché non saranno verificati.";
$lang['AdminCompanyGroups.add.field_email_verification'] = "Abilita la verifica e-mail";
?>