<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyGateways.!success.manage_updated'] = "Il gateway è stato aggiornato con successo.";
$lang['AdminCompanyGateways.!success.upgraded'] = "Il gateway è stato aggiornato con successo.";
$lang['AdminCompanyGateways.!success.uninstalled'] = "Il gateway è stato disinstallato correttamente.";
$lang['AdminCompanyGateways.!success.installed'] = "Il gateway è stato installato correttamente.";
$lang['AdminCompanyGateways.available.heading_merchant'] = "Mercante";
$lang['AdminCompanyGateways.available.heading_nonmerchant'] = "Non commerciante";
$lang['AdminCompanyGateways.available.text_author'] = "Autore:";
$lang['AdminCompanyGateways.available.text_author_url'] = "URL dell'autore";
$lang['AdminCompanyGateways.available.text_supports'] = "Supporta:";
$lang['AdminCompanyGateways.available.text_merchantach'] = "ACH";
$lang['AdminCompanyGateways.available.text_merchantachoffsite'] = "ACH fuori sede";
$lang['AdminCompanyGateways.available.text_merchantcc'] = "Carta di credito";
$lang['AdminCompanyGateways.available.text_merchantccoffsite'] = "Carta di credito fuori sede";
$lang['AdminCompanyGateways.available.text_merchant_none'] = "Non sono disponibili gateway commerciante.";
$lang['AdminCompanyGateways.available.text_nonmerchant_none'] = "Non sono disponibili gateway non commerciali.";
$lang['AdminCompanyGateways.available.btn_install'] = "Installare";
$lang['AdminCompanyGateways.installed.heading_merchant'] = "Mercante";
$lang['AdminCompanyGateways.installed.heading_nonmerchant'] = "Non commerciante";
$lang['AdminCompanyGateways.installed.text_author'] = "Autore:";
$lang['AdminCompanyGateways.installed.text_author_url'] = "URL dell'autore";
$lang['AdminCompanyGateways.installed.text_supports'] = "Supporto:";
$lang['AdminCompanyGateways.installed.text_merchantach'] = "ACH";
$lang['AdminCompanyGateways.installed.text_merchantachoffsite'] = "ACH fuori sede";
$lang['AdminCompanyGateways.installed.text_merchantcc'] = "Carta di credito";
$lang['AdminCompanyGateways.installed.text_merchantccoffsite'] = "Credit Card offsite";
$lang['AdminCompanyGateways.installed.text_merchant_none'] = "View the Google Translation";
$lang['AdminCompanyGateways.installed.text_nonmerchant_none'] = "Non sono installati gateway non commerciali.";
$lang['AdminCompanyGateways.installed.btn_uninstall'] = "Disinstallare";
$lang['AdminCompanyGateways.installed.btn_manage'] = "Gestire";
$lang['AdminCompanyGateways.installed.btn_upgrade'] = "Aggiornamento";
$lang['AdminCompanyGateways.installed.confirm_uninstall'] = "Sei sicuro di voler disinstallare questo gateway?";
$lang['AdminCompanyGateways.manage.boxtitle_manage'] = "Gestisci %1\$s"; // %1$s is the name of the gateway
$lang['AdminCompanyGateways.manage.heading_gateway'] = "Opzioni del gateway";
$lang['AdminCompanyGateways.manage.heading_currencies'] = "Valute accettate";
$lang['AdminCompanyGateways.manage.text_addcurrency'] = "aggiungere valuta";
$lang['AdminCompanyGateways.manage.update_settings'] = "Aggiorna impostazioni";
$lang['AdminCompanyGateways.available.page_title'] = "Impostazioni > Azienda > Gateway > Disponibile";
$lang['AdminCompanyGateways.available.signup_url'] = "Registrati";
$lang['AdminCompanyGateways.installed.page_title'] = "Impostazioni > Azienda > Gateway > Installato";
$lang['AdminCompanyGateways.installed.signup_url'] = "Iscrizione";
$lang['AdminCompanyGateways.manage.page_title'] = "Impostazioni > Azienda > Gateway > Gestisci %1\$s"; // %1$s is the name of the gateway
$lang['AdminCompanyGateways.available.text_version'] = "(versione %1\$s)"; // %1$s is the version number of this gateway
$lang['AdminCompanyGateways.installed.text_version'] = "(versione %1\$s)"; // %1$s is the version number of this gateway
$lang['AdminCompanyGateways.manage.text_in_use_by'] = "in uso da";
$lang['AdminCompanyGateways.!tab.installed'] = "installato";
$lang['AdminCompanyGateways.!tab.available'] = "A disposizione";
$lang['AdminCompanyGateways.available.boxtitle_gateway'] = "Gateway";
$lang['AdminCompanyGateways.installed.boxtitle_gateway'] = "Gateway";
$lang['AdminCompanyGateways.available.text_merchantccform'] = "Modulo personalizzato per carta di credito";
$lang['AdminCompanyGateways.installed.text_merchantccform'] = "Modulo personalizzato per carta di credito";
$lang['AdminCompanyGateways.available.text_merchantachform'] = "Modulo personalizzato ACH";
$lang['AdminCompanyGateways.installed.text_merchantachform'] = "Modulo personalizzato ACH";
?>