<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyAutomation.!success.automation_updated'] = "Le impostazioni di automazione sono state aggiornate con successo!";
$lang['AdminCompanyAutomation.index.boxtitle_automation'] = "Automazione";
$lang['AdminCompanyAutomation.index.field_automationsubmit'] = "Aggiorna le impostazioni";
$lang['AdminCompanyAutomation.index.field_enabled'] = "Abilitato";
$lang['AdminCompanyAutomation.index.text_interval'] = "Intervallo";
$lang['AdminCompanyAutomation.index.text_starttime'] = "Ora di inizio";
$lang['AdminCompanyAutomation.index.text_task_lastran'] = "Ultimo avvio task";
$lang['AdminCompanyAutomation.index.no_results'] = "Non ci sono attività cron.";
$lang['AdminCompanyAutomation.index.no_cron_lastran'] = "Mai";
$lang['AdminCompanyAutomation.index.text_cron_last_ran'] = "L'ultima volta il cron è stato eseguito su %1\$s."; // %1$s is the date that the cron last ran
$lang['AdminCompanyAutomation.index.text_cron_never_ran'] = "Il cron non è mai stato eseguito.";
$lang['AdminCompanyAutomation.getintervals.text_minutes'] = "minuti";
$lang['AdminCompanyAutomation.getintervals.text_hour'] = "ora";
$lang['AdminCompanyAutomation.getintervals.text_hours'] = "ore";
$lang['AdminCompanyAutomation.index.page_title'] = "Impostazioni> Azienda> Automazione";
$lang['AdminCompanyAutomation.!success.task_cleared'] = "L'attività cron è stata cancellata.";
$lang['AdminCompanyAutomation.index.option_clear_task'] = "Cancella Blocco attività";
$lang['AdminCompanyAutomation.index.confirm_clear_task'] = "Sei sicuro di voler cancellare questo blocco dell'attività cron? Se questa attività si blocca continuamente, potrebbe esserci un problema più serio. Prova a eseguire il cron manualmente o controlla la presenza di errori nel registro cron per determinarne la causa.";
?>