<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyFeeds.!success.datafeeds_updated'] = "Le impostazioni dei feed di dati sono state aggiornate con successo.";
$lang['AdminCompanyFeeds.!success.settings_updated'] = "Le impostazioni del feed sono state aggiornate con successo.";
$lang['AdminCompanyFeeds.index.page_title'] = "Impostazioni > Azienda > Feed di dati";
$lang['AdminCompanyFeeds.index.boxtitle_data_feeds'] = "Feed di dati";
$lang['AdminCompanyFeeds.index.data_feeds_description'] = "I feed di dati consentono di incorporare i contenuti di Blesta su siti Web esterni, come nomi di pacchetti, prezzi e altro.";
$lang['AdminCompanyFeeds.index.field_enable_data_feeds'] = "Abilita feed di dati";
$lang['AdminCompanyFeeds.index.field_submit'] = "Aggiorna impostazioni";
$lang['AdminCompanyFeeds.settings.page_title'] = "Impostazioni > Azienda > Feed di dati > Impostazioni feed";
$lang['AdminCompanyFeeds.settings.boxtitle_feed_settings'] = "Impostazioni del feed";
$lang['AdminCompanyFeeds.settings.header_endpoints'] = "Endpoint";
$lang['AdminCompanyFeeds.settings.field_submit'] = "Aggiorna impostazioni";
?>