<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSettings.company.category_company'] = "Azienda";
$lang['AdminSettings.company.category_system'] = "Sistema";
$lang['AdminSettings.company.boxtitle_settings'] = "Impostazioni";
$lang['AdminSettings.company.heading_general'] = "Generale";
$lang['AdminSettings.company.heading_billing'] = "Fatturazione/Pagamento";
$lang['AdminSettings.company.text_billing'] = "Configura opzioni e personalizzazione della fattura, pagamenti automatici, avvisi di pagamento e coupon.";
$lang['AdminSettings.company.heading_emails'] = "Messaggi di posta elettronica";
$lang['AdminSettings.company.text_emails'] = "Configura le impostazioni di posta, modifica i modelli di posta elettronica e crea e gestisci firme di posta elettronica.";
$lang['AdminSettings.company.heading_currencies'] = "Valute";
$lang['AdminSettings.company.heading_clientgroups'] = "Gruppi di clienti";
$lang['AdminSettings.company.text_clientgroups'] = "Tutti i client appartengono a un gruppo, che determina quando quel client è fatturato, addebitato e altro. Creare e gestire gruppi di clienti e impostazioni.";
$lang['AdminSettings.company.heading_automation'] = "Automazione";
$lang['AdminSettings.company.text_automation'] = "Accedi e controlla le attività automatizzate in Blesta.";
$lang['AdminSettings.company.heading_modules'] = "moduli";
$lang['AdminSettings.company.text_modules'] = "Installare e gestire moduli, che vengono utilizzati per l'approvvigionamento e gestione di servizi.";
$lang['AdminSettings.company.heading_gateways'] = "Gateway di pagamento";
$lang['AdminSettings.company.text_gateways'] = "Abilita e disabilita i processori di pagamento di commercianti e non commercianti per l'accettazione del pagamento.";
$lang['AdminSettings.company.heading_taxes'] = "Le tasse";
$lang['AdminSettings.company.text_taxes'] = "Abilita o disabilita le tasse, imposta un ID fiscale/IVA e crea regole fiscali a livello singolo o multilivello.";
$lang['AdminSettings.company.heading_plugins'] = "plugin";
$lang['AdminSettings.company.text_plugins'] = "Installa, disinstalla e gestisci plugin che estendono e personalizzano le funzionalità principali di Blesta.";
$lang['AdminSettings.system.category_company'] = "Azienda";
$lang['AdminSettings.system.category_system'] = "Sistema";
$lang['AdminSettings.system.boxtitle_settings'] = "Impostazioni";
$lang['AdminSettings.system.heading_general'] = "Generale";
$lang['AdminSettings.system.text_general'] = "Configura le impostazioni a livello di sistema, inclusa l'attivazione della modalità di manutenzione, il database GeoIP o l'aggiornamento della chiave di licenza.";
$lang['AdminSettings.system.heading_companies'] = "Aziende";
$lang['AdminSettings.system.text_companies'] = "Aggiungi o aggiorna le aziende.";
$lang['AdminSettings.system.heading_backup'] = "Backup";
$lang['AdminSettings.system.heading_api'] = "Accesso all'API";
$lang['AdminSettings.system.text_api'] = "Controllare l'accesso alle API di questa installazione.";
$lang['AdminSettings.system.heading_marketplace'] = "Mercato";
$lang['AdminSettings.system.text_marketplace'] = "Sfoglia e scarica i plugin, moduli, gateway e altro dal Marketplace Blesta.";
$lang['AdminSettings.system.heading_automation'] = "Automazione";
$lang['AdminSettings.system.text_automation'] = "Determinare il Cron";
$lang['AdminSettings.system.heading_staff'] = "Staff";
$lang['AdminSettings.system.text_staff'] = "Crea o modifica gli account e le autorizzazioni dello staff. Il personale ha accesso all'area amministrativa di Blesta.";
$lang['AdminSettings.system.heading_upgrade'] = "Opzioni di aggiornamento";
$lang['AdminSettings.system.text_upgrade'] = "Visualizza informazioni sull'aggiornamento e download.";
$lang['AdminSettings.system.heading_help'] = "Aiuto";
$lang['AdminSettings.system.text_help'] = "Visualizza le risorse di aiuto per l'installazione di Blesta.";
$lang['AdminSettings.company.page_title'] = "Impostazioni";
$lang['AdminSettings.system.page_title'] = "Impostazioni";
$lang['AdminSettings.company.text_currencies'] = "Aggiorna e aggiungi valute, imposta la valuta predefinita, configura multivaluta e configura i tassi di cambio.";
$lang['AdminSettings.system.text_backup'] = "Configura backup automatici utilizzando SFTP o Amazon S3 oppure scarica un backup sul tuo computer locale.";
$lang['AdminSettings.company.heading_lookandfeel'] = "Guardare e sentire";
$lang['AdminSettings.company.text_lookandfeel'] = "Personalizza l'aspetto di Blesta gestendo i temi colore o aggiornando il modello dell'interfaccia client.";
$lang['AdminSettings.company.text_general'] = "Configurare localizzazione, opzioni di internazionalizzazione e tipi di contatto cliente.";
$lang['AdminSettings.company.heading_clientoptions'] = "Opzioni cliente";
$lang['AdminSettings.company.text_clientoptions'] = "Crea e gestisci campi cliente personalizzati e seleziona i campi cliente richiesti.";
$lang['AdminSettings.company.heading_messengers'] = "Messaggeri";
$lang['AdminSettings.company.text_messengers'] = "Installa e gestisci i messenger, utilizzati per notifiche e comunicazioni.";
$lang['AdminSettings.company.heading_feeds'] = "Feed di dati";
$lang['AdminSettings.company.text_feeds'] = "I feed di dati consentono di incorporare facilmente prezzi, nomi e descrizioni dei pacchetti in un sito Web esterno.";
?>