<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminTools.getlognames.text_module'] = "Modulo";
$lang['AdminTools.getlognames.text_gateway'] = "

Portale
";
$lang['AdminTools.getlognames.text_email'] = "E-mail";
$lang['AdminTools.getlognames.text_users'] = "Login utente";
$lang['AdminTools.getlognames.text_contacts'] = "Contatti";
$lang['AdminTools.getlognames.text_accountaccess'] = "Accesso all'account";
$lang['AdminTools.getlognames.text_cron'] = "Cron";
$lang['AdminTools.convertcurrency.boxtitle_currency'] = "Converti valuta";
$lang['AdminTools.convertcurrency.field_amount'] = "Quantità";
$lang['AdminTools.convertcurrency.field_from'] = "Da";
$lang['AdminTools.convertcurrency.field_to'] = "A";
$lang['AdminTools.convertcurrency.field_currencysubmit'] = "Converti valuta";
$lang['AdminTools.logs.boxtitle_logs'] = "Registri";
$lang['AdminTools.logmodule.text_name'] = "Nome";
$lang['AdminTools.logmodule.text_staffname'] = "Staff";
$lang['AdminTools.logmodule.text_date'] = "Data";
$lang['AdminTools.logmodule.no_results'] = "Non sono presenti registri dei moduli.";
$lang['AdminTools.moduleloglist.text_direction'] = "Direzione";
$lang['AdminTools.moduleloglist.text_data'] = "Dati";
$lang['AdminTools.moduleloglist.text_date'] = "Data";
$lang['AdminTools.moduleloglist.text_status'] = "Stato";
$lang['AdminTools.moduleloglist.text_input'] = "Ingresso";
$lang['AdminTools.moduleloglist.text_output'] = "Produzione";
$lang['AdminTools.moduleloglist.text_error'] = "Errore";
$lang['AdminTools.moduleloglist.text_success'] = "Successo";
$lang['AdminTools.moduleloglist.no_results'] = "Non ci sono dati per questo registro del modulo.";
$lang['AdminTools.loggateway.text_name'] = "Nome";
$lang['AdminTools.loggateway.text_staffname'] = "Personale";
$lang['AdminTools.loggateway.text_date'] = "Data";
$lang['AdminTools.loggateway.no_results'] = "Non sono presenti registri del gateway.";
$lang['AdminTools.gatewayloglist.text_direction'] = "Direzione";
$lang['AdminTools.gatewayloglist.text_data'] = "Dati";
$lang['AdminTools.gatewayloglist.text_date'] = "Data";
$lang['AdminTools.gatewayloglist.text_status'] = "Stato";
$lang['AdminTools.gatewayloglist.text_input'] = "Ingresso";
$lang['AdminTools.gatewayloglist.text_output'] = "Produzione";
$lang['AdminTools.gatewayloglist.text_error'] = "Errore";
$lang['AdminTools.gatewayloglist.text_success'] = "Successo";
$lang['AdminTools.gatewayloglist.no_results'] = "Non sono presenti dati per questo registro del gateway.";
$lang['AdminTools.logemail.text_date'] = "Data";
$lang['AdminTools.logemail.text_subject'] = "Soggetto";
$lang['AdminTools.logemail.text_summary'] = "Riassunto";
$lang['AdminTools.logemail.text_status'] = "Stato";
$lang['AdminTools.logemail.text_to'] = "A";
$lang['AdminTools.logemail.text_cc'] = "CC";
$lang['AdminTools.logemail.text_from'] = "Da";
$lang['AdminTools.logemail.text_resend'] = "Invia nuovamente";
$lang['AdminTools.logemail.text_sent'] = "Inviato";
$lang['AdminTools.logemail.text_unsent'] = "Non inviato";
$lang['AdminTools.logemail.no_results'] = "Non ci sono registri di posta elettronica.";
$lang['AdminTools.logusers.text_name'] = "Nome";
$lang['AdminTools.logusers.text_username'] = "Nome utente";
$lang['AdminTools.logusers.text_type'] = "Tipo";
$lang['AdminTools.logusers.text_ipaddress'] = "Indirizzo IP";
$lang['AdminTools.logusers.text_date'] = "Data";
$lang['AdminTools.logusers.text_staff'] = "Staff";
$lang['AdminTools.logusers.text_client'] = "Cliente";
$lang['AdminTools.logusers.no_results'] = "Non sono presenti registri di accesso degli utenti.";
$lang['AdminTools.logaccountaccess.name'] = "Personale";
$lang['AdminTools.logaccountaccess.type'] = "Tipo";
$lang['AdminTools.logaccountaccess.date'] = "data";
$lang['AdminTools.logaccountaccess.text_cc'] = "Carta di credito";
$lang['AdminTools.logaccountaccess.text_ach'] = "ACH";
$lang['AdminTools.logaccountaccess.no_results'] = "Non sono presenti registri di accesso all'account.";
$lang['AdminTools.accountaccess.name'] = "Nome";
$lang['AdminTools.accountaccess.type'] = "Genere";
$lang['AdminTools.accountaccess.last4'] = "Ultimo 4";
$lang['AdminTools.accountaccess.type_cc'] = "%1\$s - %2\$s"; // %1$s is the account type (Credit Card) and %2$s is the type of account (MasterCard, Visa, etc.)
$lang['AdminTools.accountaccess.type_ach'] = "%1\$s - %2\$s"; // %1$s is the account type (ACH) and %2$s is the type of account (Checking or Savings)
$lang['AdminTools.accountaccess.no_results'] = "View the Google Translation";
$lang['AdminTools.logcron.task'] = "Compito";
$lang['AdminTools.logcron.start_date'] = "Data d'inizio";
$lang['AdminTools.logcron.end_date'] = "Data di fine";
$lang['AdminTools.logcron.output'] = "Output";
$lang['AdminTools.logcron.no_output'] = "Nessun output registrato per questo registro.";
$lang['AdminTools.logcron.no_results'] = "Non ci sono registri cron.";
$lang['AdminTools.!success.currency_converted'] = "%1\$s = %2\$s"; // %1$s is the from currency code and amount, %2$s is the to currency code and amount
$lang['AdminTools.getlognames.text_transactions'] = "Transazioni";
$lang['AdminTools.convertcurrency.page_title'] = "Strumenti Conversione valuta";
$lang['AdminTools.logs.page_title'] = "Registri degli strumenti";
$lang['AdminTools.logmodule.page_title'] = "Registri degli strumenti";
$lang['AdminTools.loggateway.page_title'] = "Registri degli strumenti";
$lang['AdminTools.logemail.page_title'] = "Registri degli strumenti";
$lang['AdminTools.logusers.page_title'] = "Registri degli strumenti";
$lang['AdminTools.logcontacts.page_title'] = "Registri degli strumenti";
$lang['AdminTools.logcontacts.text_name'] = "Nome";
$lang['AdminTools.logcontacts.text_date'] = "Data";
$lang['AdminTools.logcontacts.text_field'] = "Campo";
$lang['AdminTools.logcontacts.text_previous'] = "Valore precedente";
$lang['AdminTools.logcontacts.text_new'] = "Nuovo valore";
$lang['AdminTools.logcontacts.no_results'] = "Non ci sono registri dei contatti.";
$lang['AdminTools.logtransactions.page_title'] = "Registri degli strumenti";
$lang['AdminTools.logtransactions.text_client_name'] = "Cliente";
$lang['AdminTools.logtransactions.text_staff_name'] = "Personale";
$lang['AdminTools.logtransactions.text_date'] = "Data";
$lang['AdminTools.logtransactions.text_field'] = "Campo";
$lang['AdminTools.logtransactions.text_previous'] = "Valore precedente";
$lang['AdminTools.logtransactions.text_new'] = "Nuovo valore";
$lang['AdminTools.logtransactions.no_results'] = "Non ci sono log delle transazioni.
";
$lang['AdminTools.logaccountaccess.page_title'] = "Registri degli strumenti";
$lang['AdminTools.logcron.page_title'] = "Registri";
$lang['AdminTools.getlognames.text_invoice_delivery'] = "Consegna della fattura";
$lang['AdminTools.loginvoicedelivery.page_title'] = "Log di strumenti";
$lang['AdminTools.loginvoicedelivery.invoice_id_code'] = "Fattura #";
$lang['AdminTools.loginvoicedelivery.first_name'] = "Cliente";
$lang['AdminTools.loginvoicedelivery.method'] = "metodo di consegna";
$lang['AdminTools.loginvoicedelivery.date_sent'] = "Data di invio";
$lang['AdminTools.loginvoicedelivery.no_results'] = "Non sono presenti registri di consegna delle fatture.";
$lang['AdminTools.logusers.text_location'] = "Posizione";
$lang['AdminTools.logusers.text_result'] = "Risultato";
$lang['AdminTools.logusers.text_success'] = "Successo";
$lang['AdminTools.logusers.text_failure'] = "Fallimento";
$lang['AdminTools.logusers.text_contact'] = "Contatto";
$lang['AdminTools.getlognames.text_client_settings'] = "Impostazioni Utente";
$lang['AdminTools.logclientsettings.page_title'] = "Registri degli strumenti";
$lang['AdminTools.logclientsettings.text_client'] = "Cliente";
$lang['AdminTools.logclientsettings.text_user'] = "Eseguito da";
$lang['AdminTools.logclientsettings.text_ip_address'] = "Indirizzo IP";
$lang['AdminTools.logclientsettings.text_date'] = "Data";
$lang['AdminTools.logclientsettings.text_field'] = "Campo";
$lang['AdminTools.logclientsettings.text_previous'] = "Valore precedente";
$lang['AdminTools.logclientsettings.text_new'] = "Nuovo valore";
$lang['AdminTools.logclientsettings.no_results'] = "Non sono presenti registri delle impostazioni del client.";
$lang['AdminTools.getlognames.text_messenger'] = "Messaggero";
$lang['AdminTools.logmessenger.page_title'] = "Registri degli strumenti";
$lang['AdminTools.logmessenger.text_name'] = "Nome";
$lang['AdminTools.logmessenger.text_recipient'] = "Destinatario";
$lang['AdminTools.logmessenger.text_date'] = "Data";
$lang['AdminTools.logmessenger.no_results'] = "Non ci sono registri di messaggistica.";
$lang['AdminTools.messengerloglist.text_direction'] = "Direzione";
$lang['AdminTools.messengerloglist.text_data'] = "Dati";
$lang['AdminTools.messengerloglist.text_date'] = "Data";
$lang['AdminTools.messengerloglist.text_status'] = "Stato";
$lang['AdminTools.messengerloglist.text_input'] = "Ingresso";
$lang['AdminTools.messengerloglist.text_output'] = "Produzione";
$lang['AdminTools.messengerloglist.text_error'] = "Errore";
$lang['AdminTools.messengerloglist.text_success'] = "Successo";
$lang['AdminTools.messengerloglist.no_results'] = "Non ci sono dati per questo registro di Messenger.";
$lang['AdminTools.!success.collation_updated'] = "Le regole di confronto del database sono state aggiornate correttamente.";
$lang['AdminTools.utilities.page_title'] = "Strumenti Utilità";
$lang['AdminTools.utilities.boxtitle_utilities'] = "Utilità";
$lang['AdminTools.utilities.heading_utility'] = "Utilità";
$lang['AdminTools.utilities.heading_description'] = "Descrizione";
$lang['AdminTools.utilities.heading_options'] = "Opzioni";
$lang['AdminTools.utilities.update_collation'] = "Aggiorna la raccolta dei database";
$lang['AdminTools.utilities.field_update_to_utf8mb4'] = "Aggiorna a utf8mb4";
$lang['AdminTools.utilities.text_update_to_utf8mb4'] = "Aggiorna il set di caratteri e le regole di confronto del database, delle tabelle e delle colonne a utf8mb4 per supportare caratteri a 4 byte come gli emoji. Questo potrebbe richiedere vari minuti.";
$lang['AdminTools.utilities.text_update_to_utf8mb4_requirements'] = "Effettua l'aggiornamento a MySQL alla versione 5.7+ o MariaDB alla versione 10.2.2+ per supportare i caratteri utf8mb4 come gli emoji.";
$lang['AdminTools.utilities.text_update_to_utf8mb4_supported'] = "Il database supporta già utf8mb4.";
$lang['AdminTools.utilities.text_update_to_utf8mb4_config'] = "Per inserire e recuperare i caratteri utf8mb4 aggiorna il tuo file di configurazione blesta.php per utilizzare 'charset_query' => \"SET NAMES 'utf8mb4'\".";
$lang['AdminTools.!success.max_updated'] = "Il numero massimo di tentativi di rinnovo è stato aggiornato con successo.";
$lang['AdminTools.!success.dequeue'] = "Il servizio è stato rimosso con successo dalla coda di rinnovo.";
$lang['AdminTools.renewals.page_title'] = "Rinnovo coda";
$lang['AdminTools.renewals.boxtitle_renewals'] = "Coda di rinnovo del servizio";
$lang['AdminTools.renewals.heading_client'] = "Cliente";
$lang['AdminTools.renewals.heading_service_id'] = "Identificativo del servizio";
$lang['AdminTools.renewals.heading_failed_attempts'] = "Tentativi falliti";
$lang['AdminTools.renewals.heading_maximum_attempts'] = "Tentativi massimi";
$lang['AdminTools.renewals.heading_invoice'] = "Fattura";
$lang['AdminTools.renewals.heading_options'] = "Opzioni";
$lang['AdminTools.renewals.confirm_dequeue'] = "Sei sicuro di voler rimuovere questo servizio dalla coda di rinnovo?";
$lang['AdminTools.renewals.option_view'] = "Visualizza fattura";
$lang['AdminTools.renewals.option_dequeue'] = "Decoda";
$lang['AdminTools.renewals.option_change_max'] = "Cambia massimo";
$lang['AdminTools.renewals.no_results'] = "Al momento non ci sono servizi in coda per il rinnovo.";
$lang['AdminTools.change_max_attempts.boxtitle_change_max_attempts'] = "Modifica numero massimo di tentativi";
$lang['AdminTools.change_max_attempts.field_max_attempts'] = "Tentativi massimi";
$lang['AdminTools.change_max_attempts.field_cancel'] = "Annulla";
$lang['AdminTools.change_max_attempts.btn_save'] = "Salva";
?>