<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemCompanies.!success.company_added'] = "L'azioenda %1\$s è stata creata con successo!"; // %1$s is the name of the company
$lang['AdminSystemCompanies.!success.company_edited'] = "L'azienda %1\$s è stata aggiornata con successo!"; // %1$s is the name of the company
$lang['AdminSystemCompanies.index.boxtitle_companies'] = "Aziende";
$lang['AdminSystemCompanies.index.categorylink_addcompany'] = "Aggiungi azienda";
$lang['AdminSystemCompanies.index.no_results'] = "Non ci sono aziende.";
$lang['AdminSystemCompanies.index.text_name'] = "Nome";
$lang['AdminSystemCompanies.index.text_address'] = "Indirizzo";
$lang['AdminSystemCompanies.index.text_phone'] = "Telefono";
$lang['AdminSystemCompanies.index.text_options'] = "Opzioni";
$lang['AdminSystemCompanies.index.option_edit'] = "modificare";
$lang['AdminSystemCompanies.add.boxtitle_addcompany'] = "Aggiungi azienda";
$lang['AdminSystemCompanies.add.field_company'] = "Importa impostazioni aziendali da";
$lang['AdminSystemCompanies.add.field_name'] = "Nome";
$lang['AdminSystemCompanies.add.field_hostname'] = "Nome host";
$lang['AdminSystemCompanies.add.field_address'] = "Indirizzo";
$lang['AdminSystemCompanies.add.field_phone'] = "Telefono";
$lang['AdminSystemCompanies.add.field_fax'] = "Fax";
$lang['AddSystemCompanies.add.field_companysubmit'] = "Crea Azienda";
$lang['AdminSystemCompanies.edit.boxtitle_editcompany'] = "Modifica società";
$lang['AdminSystemCompanies.edit.field_name'] = "Nome";
$lang['AdminSystemCompanies.edit.field_hostname'] = "Nome host";
$lang['AdminSystemCompanies.edit.field_address'] = "Indirizzo";
$lang['AdminSystemCompanies.edit.field_phone'] = "Telefono";
$lang['AdminSystemCompanies.edit.field_fax'] = "Fax";
$lang['AddSystemCompanies.edit.field_companysubmit'] = "Modifica Azienda";
$lang['AdminSystemCompanies.index.page_title'] = "Impostazioni > Sistema > Aziende";
$lang['AdminSystemCompanies.index.text_hostname'] = "Nome host";
$lang['AdminSystemCompanies.add.page_title'] = "Impostazioni > Sistema > Aziende > Aggiungi azienda";
$lang['AdminSystemCompanies.edit.page_title'] = "Impostazioni > Sistema > Aziende > Modifica azienda";
$lang['AdminSystemCompanies.!success.company_deleted'] = "La società %1\$s è stata rimossa con successo!"; // %1$s is the name of the company
$lang['AdminSystemCompanies.index.option_delete'] = "Eliminare";
$lang['AdminSystemCompanies.index.confirm_delete'] = "Eliminare davvero questa azienda? Tutto ciò che riguarda questa azienda scomparirà.";
$lang['AdminSystemCompanies.!tooltip.hostname'] = "Il nome host deve contenere solo il nome di dominio, il TLD e il numero di porta opzionale. Ad esempio, \"dominio.com\" o \"sottodominio.dominio.com:8080\".";
?>