<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyClientOptions.!success.field_updated'] = "Il campo personalizzato del cliente è stato aggiornato con successo.";
$lang['AdminCompanyClientOptions.!success.field_created'] = "Il campo personalizzato del cliente è stato creato con successo.";
$lang['AdminCompanyClientOptions.!success.field_deleted'] = "Il campo personalizzato del cliente è stato eliminato con successo.";
$lang['AdminCompanyClientOptions.!success.requiredfields_updated'] = "I campi obbligatori sono stati aggiornati con successo.";
$lang['AdminCompanyClientoptions.customfields.page_title'] = "Impostazioni> Azienda> Opzioni client> Campi personalizzati client> Sfoglia";
$lang['AdminCompanyClientOptions.customfields.boxtitle_browse'] = "Sfoglia i campi personalizzati del cliente";
$lang['AdminCompanyClientOptions.customfields.categorylink_addfield'] = "Crea campo";
$lang['AdminCompanyClientOptions.customfields.text_name'] = "Nome";
$lang['AdminCompanyClientOptions.customfields.text_type'] = "Tipo";
$lang['AdminCompanyClientOptions.customfields.text_required'] = "Necessario";
$lang['AdminCompanyClientOptions.customfields.text_visible'] = "Visibile ai clienti";
$lang['AdminCompanyClientOptions.customfields.text_read_only'] = "Sola lettura per i client";
$lang['AdminCompanyClientOptions.customfields.text_options'] = "Opzioni";
$lang['AdminCompanyClientOptions.customfields.option_edit'] = "Modificare";
$lang['AdminCompanyClientOptions.customfields.option_delete'] = "Eliminare";
$lang['AdminCompanyClientOptions.customfields.confirm_delete'] = "L'eliminazione di questo campo personalizzato eliminerà tutti i dati archiviati per esso per ciascun client all'interno di questo gruppo. Sei sicuro di voler eliminare questo campo personalizzato?";
$lang['AdminCompanyClientOptions.customfields.no_results'] = "Non sono presenti campi personalizzati.";
$lang['AdminCompanyClientoptions.addcustomfield.page_title'] = "Impostazioni > Azienda > Opzioni cliente > Campi personalizzati cliente > Aggiungi campo personalizzato";
$lang['AdminCompanyClientOptions.addcustomfield.boxtitle_add'] = "Aggiungi campo personalizzato";
$lang['AdminCompanyClientOptions.addcustomfield.categorylink_select'] = "Aggiungi opzione aggiuntiva";
$lang['AdminCompanyClientOptions.addcustomfield.heading_select_value'] = "Valore";
$lang['AdminCompanyClientOptions.addcustomfield.heading_select_option'] = "Nome dell'opzione";
$lang['AdminCompanyClientOptions.addcustomfield.text_remove'] = "Rimuovere";
$lang['AdminCompanyClientoptions.editcustomfield.page_title'] = "Impostazioni > Azienda > Opzioni cliente > Campi personalizzati cliente > Modifica campo personalizzato";
$lang['AdminCompanyClientOptions.editcustomfield.boxtitle_edit'] = "Modifica campo personalizzato";
$lang['AdminCompanyClientOptions.editcustomfield.categorylink_select'] = "Aggiungi opzione aggiuntiva";
$lang['AdminCompanyClientOptions.editcustomfield.heading_select_value'] = "Valore";
$lang['AdminCompanyClientOptions.editcustomfield.heading_select_option'] = "Nome dell'opzione";
$lang['AdminCompanyClientOptions.editcustomfield.text_remove'] = "Rimuovere";
$lang['AdminCompanyClientOptions.getRequired.no'] = "NO";
$lang['AdminCompanyClientOptions.getRequired.yes'] = "SÌ";
$lang['AdminCompanyClientOptions.getRequired.regex'] = "Regex personalizzata";
$lang['AdminCompanyClientoptions.requiredfields.page_title'] = "Impostazioni > Azienda > Opzioni cliente > Campi personalizzati cliente > Campi cliente obbligatori";
$lang['AdminCompanyClientOptions.requiredfields.boxtitle'] = "Campi cliente obbligatori";
$lang['AdminCompanyClientOptions.requiredfields.description'] = "Controlla i campi che dovrebbero essere richiesti durante la creazione o l'aggiornamento di un cliente o contatto.";
$lang['AdminCompanyClientOptions.requiredfields.field_company'] = "Azienda/Org.";
$lang['AdminCompanyClientOptions.requiredfields.field_title'] = "Titolo";
$lang['AdminCompanyClientOptions.requiredfields.field_address1'] = "Indirizzo 1";
$lang['AdminCompanyClientOptions.requiredfields.field_address2'] = "Indirizzo 2";
$lang['AdminCompanyClientOptions.requiredfields.field_city'] = "Città";
$lang['AdminCompanyClientOptions.requiredfields.field_country'] = "Paese";
$lang['AdminCompanyClientOptions.requiredfields.field_state'] = "Stato/Provincia";
$lang['AdminCompanyClientOptions.requiredfields.field_zip'] = "Zip / Codice postale";
$lang['AdminCompanyClientOptions.requiredfields.field_email'] = "E-mail";
$lang['AdminCompanyClientOptions.requiredfields.text_submit'] = "Aggiorna impostazioni";
$lang['AdminCompanyClientOptions.requiredfields.field_first_name'] = "Nome di battesimo";
$lang['AdminCompanyClientOptions.requiredfields.field_last_name'] = "Cognome";
$lang['AdminCompanyClientOptions.!notice.group_settings'] = "NOTA: queste impostazioni si applicano solo ai gruppi di clienti che ereditano le proprie impostazioni dalla Società.";
$lang['AdminCompanyClientOptions.!tooltip.state'] = "Prestare attenzione quando si richiede la selezione di uno Stato/Provincia. Alcuni paesi non hanno stati. I clienti in questi paesi non sarebbero in grado di salvare i propri dettagli di contatto. Si consiglia di non richiedere questo campo.";
$lang['AdminCompanyClientOptions.!success.general_updated'] = "Le impostazioni generali sono state aggiornate con successo.";
$lang['AdminCompanyClientOptions.!tooltip.unique_contact_emails'] = "Limita gli indirizzi email per i contatti. Contatti primari significa che non possono essere presenti due contatti primari (ovvero clienti) con lo stesso indirizzo email. Tutti i contatti significa che nessun contatto di alcun tipo può avere lo stesso indirizzo email di un altro contatto.";
$lang['AdminCompanyClientoptions.general.page_title'] = "Impostazioni > Azienda > Opzioni cliente > Generale";
$lang['AdminCompanyClientOptions.general.boxtitle'] = "Impostazioni generali del cliente";
$lang['AdminCompanyClientOptions.general.field_unique_contact_emails'] = "Applica indirizzi email di contatto univoci";
$lang['AdminCompanyClientOptions.general.field_unique_contact_emails_none'] = "-- Nessuno --";
$lang['AdminCompanyClientOptions.general.field_unique_contact_emails_primary'] = "Contatti primari";
$lang['AdminCompanyClientOptions.general.field_unique_contact_emails_all'] = "Tutti i contatti";
$lang['AdminCompanyClientOptions.general.text_submit'] = "Invia";
$lang['AdminCompanyClientOptions.addcustomfield.configuration_warning'] = "Richiedere questo campo senza renderlo visibile ai clienti comporterà l'impossibilità per i clienti di registrarsi o aggiornare le informazioni del proprio account.";
$lang['AdminCompanyClientOptions.!tooltip.client_group_id'] = "Il campo personalizzato verrà applicato solo ai membri del gruppo di clienti selezionato.";
$lang['AdminCompanyClientOptions.!tooltip.name'] = "Questo è il nome visualizzato per questo campo. Potrebbe essere una definizione linguistica.";
$lang['AdminCompanyClientOptions.!tooltip.is_lang'] = "Seleziona questa casella solo se hai aggiunto una definizione di lingua per questo campo personalizzato nel file della lingua personalizzata.";
$lang['AdminCompanyClientOptions.!tooltip.type'] = "Il campo personalizzato verrà visualizzato come tipo di modulo selezionato.";
$lang['AdminCompanyClientOptions.!tooltip.show_client'] = "Seleziona per consentire ai clienti di vedere e aggiornare questo campo.";
$lang['AdminCompanyClientOptions.!tooltip.read_only'] = "Selezionando questa casella il cliente renderà questo campo personalizzato non modificabile. I campi di sola lettura verranno impostati automaticamente sul valore predefinito assegnato.";
$lang['AdminCompanyClientOptions.!tooltip.required'] = "Selezionare \"Sì\" per garantire che venga fornito un valore per questo campo, per i tipi a discesa l'opzione deve apparire nell'elenco delle opzioni. Seleziona \"No\" per accettare qualsiasi valore per questo campo. Seleziona \"Regex personalizzato\" per utilizzare un'espressione regolare personalizzata per convalidare questo campo.";
$lang['AdminCompanyClientOptions.!tooltip.regex'] = "Questa opzione verrà visualizzata se \"Richiesto\" è impostato su \"Regex personalizzato\". Inserisci qui l'espressione regolare personalizzata da convalidare per questo campo.";
$lang['AdminCompanyClientOptions.!tooltip.encrypted'] = "Seleziona questa casella per memorizzare il valore crittografato. Questo è altamente raccomandato se si memorizzano informazioni sensibili o di identificazione personale.";
$lang['AdminCompanyClientOptions.!tooltip.checkbox_value'] = "Il valore inviato quando la casella di controllo è selezionata.";
$lang['AdminCompanyClientOptions.!tooltip.default_text'] = "Il testo inserito qui sarà il valore predefinito impostato per questa opzione quando questo campo personalizzato viene aggiunto per un cliente.";
$lang['AdminCompanyClientOptions.!tooltip.default_checkbox'] = "Se selezionata, questa casella di controllo verrà selezionata per impostazione predefinita quando questo campo personalizzato viene aggiunto per un cliente.";
$lang['AdminCompanyClientOptions.!tooltip.select_default'] = "Il valore dell'opzione selezionata sarà il valore predefinito selezionato quando questa opzione viene aggiunta per un client.";
$lang['AdminCompanyClientOptions.addcustomfield.field.client_group_id'] = "Gruppo clienti";
$lang['AdminCompanyClientOptions.addcustomfield.field.name'] = "Nome";
$lang['AdminCompanyClientOptions.addcustomfield.field.is_lang'] = "Il nome è una definizione linguistica";
$lang['AdminCompanyClientOptions.addcustomfield.field.type'] = "Tipo";
$lang['AdminCompanyClientOptions.addcustomfield.field.show_client'] = "Visibile ai clienti";
$lang['AdminCompanyClientOptions.addcustomfield.field.read_only'] = "Sola lettura per i client";
$lang['AdminCompanyClientOptions.addcustomfield.field.required'] = "Necessario";
$lang['AdminCompanyClientOptions.addcustomfield.field.regex'] = "Regex personalizzata";
$lang['AdminCompanyClientOptions.addcustomfield.field.encrypted'] = "Crittografare i valori";
$lang['AdminCompanyClientOptions.addcustomfield.field.addsubmit'] = "Aggiungi campo personalizzato";
$lang['AdminCompanyClientOptions.addcustomfield.field.checkbox_value'] = "Valore";
$lang['AdminCompanyClientOptions.addcustomfield.field.default_checkbox'] = "Valore predefinito selezionato";
$lang['AdminCompanyClientOptions.addcustomfield.field.default_text'] = "Valore testo predefinito";
$lang['AdminCompanyClientOptions.addcustomfield.heading_select_default'] = "Predefinito";
$lang['AdminCompanyClientOptions.editcustomfield.field.name'] = "Nome";
$lang['AdminCompanyClientOptions.editcustomfield.field.is_lang'] = "Il nome è una definizione linguistica";
$lang['AdminCompanyClientOptions.editcustomfield.field.type'] = "Tipo";
$lang['AdminCompanyClientOptions.editcustomfield.field.show_client'] = "Visibile ai clienti";
$lang['AdminCompanyClientOptions.editcustomfield.field.read_only'] = "Sola lettura per i client";
$lang['AdminCompanyClientOptions.editcustomfield.field.required'] = "Necessario";
$lang['AdminCompanyClientOptions.editcustomfield.field.regex'] = "Regex personalizzata";
$lang['AdminCompanyClientOptions.editcustomfield.field.encrypted'] = "Crittografare i valori";
$lang['AdminCompanyClientOptions.editcustomfield.field.editsubmit'] = "Modifica campo personalizzato";
$lang['AdminCompanyClientOptions.editcustomfield.field.checkbox_value'] = "Valore";
$lang['AdminCompanyClientOptions.editcustomfield.field.default_checkbox'] = "Valore predefinito selezionato";
$lang['AdminCompanyClientOptions.editcustomfield.field.default_text'] = "Valore testo predefinito";
$lang['AdminCompanyClientOptions.editcustomfield.heading_select_default'] = "Predefinito";
$lang['AdminCompanyClientOptions.!tooltip.force_email_usernames'] = "I clienti devono utilizzare il proprio indirizzo e-mail come nome utente anziché definirne uno proprio. I clienti esistenti possono ancora accedere con il loro nome utente attuale.";
$lang['AdminCompanyClientOptions.general.field_force_email_usernames'] = "Forza i nomi utente e-mail";
$lang['AdminCompanyClientOptions.!tooltip.email_verification'] = "Selezionare per inviare un'e-mail di verifica e-mail quando viene creato un nuovo accesso o un cliente modifica il proprio indirizzo e-mail. Un avviso apparirà sul profilo dei clienti finché non saranno verificati.";
$lang['AdminCompanyClientOptions.general.field_email_verification'] = "Abilita la verifica e-mail";
$lang['AdminCompanyClientOptions.general.prevent_unverified_payments'] = "Impedisci pagamenti da clienti non verificati";
$lang['AdminCompanyClientOptions.!error.clients_format'] = "Il formato dell'ID cliente deve contenere {num}.";
$lang['AdminCompanyClientOptions.!tooltip.clients_format'] = "Formato ID cliente è il formato dell'ID cliente. Un valore di ABC-{num} risulterà in un ID cliente di ABC-1500 dove 1500 è il valore dell'ID cliente.";
$lang['AdminCompanyClientOptions.!tooltip.clients_start'] = "Inizio ID cliente è il valore iniziale per gli ID cliente. I nuovi clienti avranno questo valore, a meno che non sia inferiore al valore del cliente creato più recentemente.";
$lang['AdminCompanyClientOptions.!tooltip.clients_increment'] = "I successivi numeri degli ID cliente aumenteranno di questo valore.";
$lang['AdminCompanyClientOptions.general.field_clients_format'] = "Formato ID cliente";
$lang['AdminCompanyClientOptions.general.field_clients_start'] = "Valore iniziale dell'ID cliente";
$lang['AdminCompanyClientOptions.general.field_clients_increment'] = "Valore di incremento dell'ID client";
$lang['AdminCompanyClientOptions.requiredfields.heading_field'] = "Campo";
$lang['AdminCompanyClientOptions.requiredfields.heading_required'] = "Necessario";
$lang['AdminCompanyClientOptions.requiredfields.heading_show'] = "Spettacolo";
$lang['AdminCompanyClientOptions.requiredfields.field_phone'] = "Telefono";
$lang['AdminCompanyClientOptions.requiredfields.field_fax'] = "Fax";
?>