<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminDialog.confirm.text_yes'] = "Si";
$lang['AdminDialog.confirm.text_no'] = "No";
$lang['AdminDialog.password.field_modal_password'] = "Parola d'ordine";
$lang['AdminDialog.password.field_modal_password_copied'] = "Ho copiato questa password in un posto sicuro";
$lang['AdminDialog.password.btn_generate'] = "creare";
$lang['AdminDialog.password.btn_modal_password'] = "Password";
$lang['AdminDialog.password.btn_cancel'] = "Annulla";
$lang['AdminDialog.password.btn_use_password'] = "Usa password";
?>