<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyLookandfeel.template.page_title'] = "Impostazioni > Azienda > Aspetto > Modello";
$lang['AdminCompanyLookandfeel.template.box_title'] = "Modello";
$lang['AdminCompanyLookandfeel.template.text_client_view_dir'] = "Modello cliente";
$lang['AdminCompanyLookandfeel.template.text_submit'] = "Salva";
$lang['AdminCompanyLookandfeel.template.text_admin_view_dir'] = "Modello di amministrazione";
$lang['AdminCompanyLookandfeel.!success.template_updated'] = "I modelli sono stati aggiornati con successo.";
$lang['AdminCompanyLookandfeel.!success.layout_updated'] = "Il layout è stato aggiornato con successo.";
$lang['AdminCompanyLookandfeel.layout.page_title'] = "Impostazioni > Azienda > Aspetto > Layout";
$lang['AdminCompanyLookandfeel.layout.box_title'] = "Disposizione";
$lang['AdminCompanyLookandfeel.layout.field.background_url'] = "URL di sfondo";
$lang['AdminCompanyLookandfeel.layout.text_html_generated'] = "Generato da HTML";
$lang['AdminCompanyLookandfeel.layout.text_cards_note'] = "Trascina le carte per modificare l'ordine, fai clic su di esse per cambiare il colore e fai clic sulla casella di controllo per abilitare o disabilitare una carta. Il colore delle carte generate da HTML non può essere modificato.";
$lang['AdminCompanyLookandfeel.layout.text_submit'] = "Salva";
$lang['AdminCompanyLookandfeel.!success.navigation_updated'] = "La navigazione è stata aggiornata con successo.";
$lang['AdminCompanyLookandfeel.!success.action_created'] = "L'azione è stata creata correttamente e può essere aggiunta in Aspetto > Navigazione.";
$lang['AdminCompanyLookandfeel.!success.action_updated'] = "L'azione è stata aggiornata con successo.";
$lang['AdminCompanyLookandfeel.!success.action_deleted'] = "L'azione è stata eliminata con successo.";
$lang['AdminCompanyLookandfeel.!success.logo_updated'] = "Il logo personalizzato è stato aggiornato con successo.";
$lang['AdminCompanyLookandfeel.!tooltip.action_name'] = "Per creare azioni multilingue è possibile specificare una definizione di lingua nel file di lingua _global.php. Se necessario, rinomina _global-example.php in _global.php. Questi file possono essere trovati in %1\$s e nella directory di ogni altra lingua. Codice di esempio per la definizione:"; // %1$s is the path to the language files
$lang['AdminCompanyLookandfeel.!tooltip.action_name_language'] = "Collegamento testo";
$lang['AdminCompanyLookandfeel.!tooltip.action_url'] = "Questo percorso può essere relativo (ad esempio client/add) o assoluto (ad esempio %1\$sclients/add/ o https://blesta.com). I percorsi relativi saranno basati sull'interfaccia visualizzata. Ad esempio, client/add si collegherà a %1\$sclients/add"; // %1$s is the admin uri for this company
$lang['AdminCompanyLookandfeel.!tooltip.disabled_location'] = "La posizione di un'azione non può essere modificata dopo la creazione.";
$lang['AdminCompanyLookandfeel.layout.field.text_color'] = "Colore del testo";
$lang['AdminCompanyLookandfeel.customize.page_title'] = "Impostazioni > Azienda > Aspetto > Personalizza";
$lang['AdminCompanyLookandfeel.customize.box_title'] = "personalizzare";
$lang['AdminCompanyLookandfeel.customize.heading_custom_logo'] = "Logo personalizzato";
$lang['AdminCompanyLookandfeel.customize.field.admin_type_logo'] = "Carica logo";
$lang['AdminCompanyLookandfeel.customize.field.admin_type_url'] = "Imposta l'URL del logo";
$lang['AdminCompanyLookandfeel.customize.field.admin_logo'] = "Logo dell'intestazione";
$lang['AdminCompanyLookandfeel.customize.field.admin_url'] = "Logo dell'intestazione";
$lang['AdminCompanyLookandfeel.customize.field.client_type_logo'] = "Carica logo";
$lang['AdminCompanyLookandfeel.customize.field.client_type_url'] = "Imposta l'URL del logo";
$lang['AdminCompanyLookandfeel.customize.field.client_logo'] = "Logo dell'intestazione";
$lang['AdminCompanyLookandfeel.customize.field.client_url'] = "Logo dell'intestazione";
$lang['AdminCompanyLookandfeel.customize.text_submit'] = "Salva";
$lang['AdminCompanyLookandfeel.navigation.page_title'] = "Impostazioni > Azienda > Aspetto > Navigazione";
$lang['AdminCompanyLookandfeel.navigation.boxtitle_navigation'] = "Navigazione";
$lang['AdminCompanyLookandfeel.navigation.category_nav_staff'] = "Navigazione del personale";
$lang['AdminCompanyLookandfeel.navigation.category_nav_client'] = "Navigazione del cliente";
$lang['AdminCompanyLookandfeel.navigation.category_nav_public'] = "Navigazione pubblica";
$lang['AdminCompanyLookandfeel.navigation.heading_navigation'] = "Menu di navigazione";
$lang['AdminCompanyLookandfeel.navigation.heading_action'] = "Azione";
$lang['AdminCompanyLookandfeel.navigation.heading_options'] = "Opzioni";
$lang['AdminCompanyLookandfeel.actions.option_add'] = "Aggiungere";
$lang['AdminCompanyLookandfeel.actions.option_remove'] = "Rimuovere";
$lang['AdminCompanyLookandfeel.actions.option_add_action'] = "Aggiungi azione personalizzata";
$lang['AdminCompanyLookandfeel.navigation.field_subitem'] = "Sottovoce";
$lang['AdminCompanyLookandfeel.navigation.text_link'] = "collegamento";
$lang['AdminCompanyLookandfeel.navigation.no_results_actions'] = "Non sono presenti azioni per questa posizione.";
$lang['AdminCompanyLookandfeel.navigation.text_submit'] = "Salva navigazione";
$lang['AdminCompanyLookandfeel.actions.page_title'] = "Impostazioni > Azienda > Aspetto > Azioni personalizzate";
$lang['AdminCompanyLookandfeel.actions.boxtitle_actions'] = "Azioni personalizzate";
$lang['AdminCompanyLookandfeel.actions.category_nav_staff'] = "Navigazione del personale";
$lang['AdminCompanyLookandfeel.actions.category_nav_client'] = "Navigazione del cliente";
$lang['AdminCompanyLookandfeel.actions.category_nav_public'] = "Navigazione pubblica";
$lang['AdminCompanyLookandfeel.actions.categorylink_addaction'] = "Aggiungi azione";
$lang['AdminCompanyLookandfeel.actions.heading_name'] = "Nome";
$lang['AdminCompanyLookandfeel.actions.heading_url'] = "URL";
$lang['AdminCompanyLookandfeel.actions.heading_options'] = "Opzioni";
$lang['AdminCompanyLookandfeel.actions.no_results'] = "Non sono presenti azioni per questa posizione.";
$lang['AdminCompanyLookandfeel.actions.option_edit'] = "Modificare";
$lang['AdminCompanyLookandfeel.actions.option_delete'] = "Eliminare";
$lang['AdminCompanyLookandfeel.actions.confirm_delete'] = "Sei sicuro di voler eliminare questa azione?";
$lang['AdminCompanyLookandfeel.addaction.page_title'] = "Impostazioni > Azienda > Aspetto > Aggiungi azione";
$lang['AdminCompanyLookandfeel.addaction.boxtitle_addaction'] = "Aggiungi azione";
$lang['AdminCompanyLookandfeel.addaction.field_location'] = "Posizione";
$lang['AdminCompanyLookandfeel.addaction.field_name'] = "Nome";
$lang['AdminCompanyLookandfeel.addaction.field_url'] = "URL di collegamento";
$lang['AdminCompanyLookandfeel.addaction.placeholder_name'] = "Nome del pacchetto";
$lang['AdminCompanyLookandfeel.addaction.placeholder_url'] = "Stato";
$lang['AdminCompanyLookandfeel.addaction.field_addsubmit'] = "Aggiungi azione";
$lang['AdminCompanyLookandfeel.editaction.page_title'] = "Impostazioni > Azienda > Aspetto > Modifica azione";
$lang['AdminCompanyLookandfeel.editaction.boxtitle_editaction'] = "Modifica azione";
$lang['AdminCompanyLookandfeel.editaction.field_location'] = "Posizione";
$lang['AdminCompanyLookandfeel.editaction.field_name'] = "Nome";
$lang['AdminCompanyLookandfeel.editaction.field_url'] = "URL di collegamento";
$lang['AdminCompanyLookandfeel.editaction.placeholder_name'] = "Nome del pacchetto";
$lang['AdminCompanyLookandfeel.editaction.placeholder_url'] = "Stato";
$lang['AdminCompanyLookandfeel.editaction.field_addsubmit'] = "Modifica azione";
$lang['AdminCompanyLookandfeel.layout.text_widget_preview_note'] = "Per motivi di sicurezza l'anteprima di questo widget non è stata generata.";
?>