<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AppController.lang.dir'] = "ltr";
$lang['AppController.!error.unauthorized_access'] = "Non sei autorizzato ad accedere a quella risorsa";
$lang['AppController.modal.text_close'] = "Vicino";
$lang['AppController.tooltip.text'] = "?";
$lang['AppController.structure.text_myinfo'] = "Le mie informazioni";
$lang['AppController.structure.text_settings'] = "Impostazioni";
$lang['AppController.structure.text_logout'] = "Disconnettersi";
$lang['AppController.!error.invalid_csrf'] = "Il token del modulo non è valido.";
$lang['AppController.message.close'] = "x";
$lang['AppController.structure.text_maintenance'] = "La modalità di manutenzione è attualmente abilitata e i client potrebbero non effettuare l'accesso. Clicca qui per cambiare.";
$lang['AppController.structure.text_search_placeholder'] = "%1\$s..."; // %1$s is the search type
$lang['AppController.client_structure.default_title'] = "Il mio conto";
$lang['AppController.client_structure.text_return_to_portal'] = "Ritorna al Portale";
$lang['AppController.client_structure.text_logout'] = "Disconnetti";
$lang['AppController.dates.day_sun'] = "Domenica";
$lang['AppController.dates.day_mon'] = "Lunedì";
$lang['AppController.dates.day_tue'] = "Martedì";
$lang['AppController.dates.day_wed'] = "Mercoledì";
$lang['AppController.dates.day_thu'] = "Giovedì";
$lang['AppController.dates.day_fri'] = "Venerdì";
$lang['AppController.dates.day_sat'] = "Sabato";
$lang['AppController.dates.dayabbr_sun'] = "Sole";
$lang['AppController.dates.dayabbr_mon'] = "Lun";
$lang['AppController.dates.dayabbr_tue'] = "Mar";
$lang['AppController.dates.dayabbr_wed'] = "Mercoledì";
$lang['AppController.dates.dayabbr_thur'] = "Gio";
$lang['AppController.dates.dayabbr_fri'] = "Ven";
$lang['AppController.dates.dayabbr_sat'] = "Sab";
$lang['AppController.dates.month_jan'] = "Gennaio";
$lang['AppController.dates.month_feb'] = "Febbraio";
$lang['AppController.dates.month_mar'] = "Marzo";
$lang['AppController.dates.month_apr'] = "aprile";
$lang['AppController.dates.month_may'] = "Maggio";
$lang['AppController.dates.month_jun'] = "Giugno";
$lang['AppController.dates.month_jul'] = "Luglio";
$lang['AppController.dates.month_aug'] = "agosto";
$lang['AppController.dates.month_sep'] = "settembre";
$lang['AppController.dates.month_oct'] = "ottobre";
$lang['AppController.dates.month_nov'] = "novembre";
$lang['AppController.dates.month_dec'] = "Dicembre";
$lang['AppController.dates.monthabbr_jan'] = "Gen";
$lang['AppController.dates.monthabbr_feb'] = "Febbraio";
$lang['AppController.dates.monthabbr_mar'] = "Marzo";
$lang['AppController.dates.monthabbr_apr'] = "aprile";
$lang['AppController.dates.monthabbr_may'] = "Maggio";
$lang['AppController.dates.monthabbr_jun'] = "giugno";
$lang['AppController.dates.monthabbr_jul'] = "Lug";
$lang['AppController.dates.monthabbr_aug'] = "Agosto";
$lang['AppController.dates.monthabbr_sep'] = "Settembre";
$lang['AppController.dates.monthabbr_oct'] = "ottobre";
$lang['AppController.dates.monthabbr_nov'] = "Novembre";
$lang['AppController.dates.monthabbr_dec'] = "dicembre";
$lang['AppController.!success.license_updated'] = "La tua licenza è stata riconvalidata con successo. Accedere prego.";
$lang['AppController.!success.license_key_updated'] = "La tua chiave di licenza è stata aggiornata correttamente. Si prega di eseguire il login.";
$lang['AppController.select.please'] = "-- Seleziona --";
$lang['AppController.modal.text_confirm'] = "Per favore conferma";
$lang['AppController.client_structure.text_update_account'] = "Gestisci profilo";
$lang['AppController.sreader.dropdown'] = "Attiva/disattiva il menu a discesa";
$lang['AppController.sreader.navigation'] = "Attiva/disattiva navigazione";
$lang['AppController.client_structure.staff_as_client_note'] = "Ritorna al Portale del personale";
$lang['AppController.client_structure.text_login'] = "Login";
$lang['AppController.graphs.control_label.stacked'] = "Impilato";
$lang['AppController.graphs.control_label.stream'] = "Flusso";
$lang['AppController.graphs.control_label.expanded'] = "allargato";
$lang['AppController.graphs.control_label.grouped'] = "Raggruppato";
$lang['AppController.graphs.label.total'] = "Totale";
$lang['AppController.client_structure.text_emails'] = "Cronologia e-mail";
$lang['AppController.client_structure.text_accounts'] = "Conti di pagamento";
$lang['AppController.client_structure.text_contacts'] = "Contatti";
?>