<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Backup.!error.driver.support'] = "Il driver del database non è supportato.";
$lang['Backup.!error.temp_dir.writable'] = "La cartella temp non è modificabile.";
$lang['Backup.frequencies.hour'] = "Ora";
$lang['Backup.frequencies.hours'] = "%1\$s Ore"; // %1$s is the number of hours
$lang['Backup.frequencies.day'] = "Giorno";
$lang['Backup.frequencies.days'] = "%1\$s Giorni"; // %1$s is the number of days
$lang['Backup.!error.amazons3_failed'] = "Il backup di AmazonS3 non è riuscito.";
$lang['Backup.frequencies.never'] = "Mai";
$lang['Backup.!error.ftp_failed'] = "SFTP backup fallito";
?>