<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientContacts.!success.contact_deleted'] = "Il contatto %1\$s %2\$s è stato eliminato con successo!"; // %1$s is the contact's first name, %2$s is the contact's last name
$lang['ClientContacts.!success.contact_updated'] = "Il contatto è stato aggiornato con successo!";
$lang['ClientContacts.!success.contact_added'] = "Il contatto è stato creato con successo!";
$lang['ClientContacts.index.page_title'] = "Cliente #%1\$s Contatti"; // %1$s is the client ID number
$lang['ClientContacts.index.create_contact'] = "Aggiungi contatto";
$lang['ClientContacts.index.boxtitle_contacts'] = "Contatti";
$lang['ClientContacts.index.heading_name'] = "Nome";
$lang['ClientContacts.index.heading_email'] = "E-mail";
$lang['ClientContacts.index.heading_type'] = "Tipo";
$lang['ClientContacts.index.heading_options'] = "Opzioni";
$lang['ClientContacts.index.option_edit'] = "Modificare";
$lang['ClientContacts.index.option_delete'] = "Eliminare";
$lang['ClientContacts.index.confirm_delete'] = "Sei sicuro di voler eliminare questo contatto?";
$lang['ClientContacts.add.page_title'] = "Cliente #%1\$s Aggiungi contatto"; // %1$s is the client ID number
$lang['ClientContacts.add.boxtitle_create'] = "Aggiungi contatto";
$lang['ClientContacts.add.heading_settings'] = "Impostazioni aggiuntive";
$lang['ClientContacts.add.field_contact_type'] = "Tipo di contatto";
$lang['ClientContacts.add.field_addsubmit'] = "Crea Contatto";
$lang['ClientContacts.edit.page_title'] = "Cliente n. %1\$s Modifica contatto"; // %1$s is the client ID number
$lang['ClientContacts.edit.boxtitle_edit'] = "Modifica il contatto";
$lang['ClientContacts.edit.heading_settings'] = "Altre impostazioni";
$lang['ClientContacts.edit.field_contact_type'] = "Tipo di contatto";
$lang['ClientContacts.edit.field_editsubmit'] = "Aggiorna contatto";
$lang['ClientContacts.setcontactview.text_none'] = "Nessuno";
$lang['ClientContacts.contact_info.heading_contact'] = "Informazioni sui contatti";
$lang['ClientContacts.contact_info.field_contact_id'] = "Copia le informazioni di contatto da";
$lang['ClientContacts.contact_info.field_first_name'] = "Nome di battesimo";
$lang['ClientContacts.contact_info.field_last_name'] = "Cognome";
$lang['ClientContacts.contact_info.field_company'] = "Azienda";
$lang['ClientContacts.contact_info.field_address1'] = "Indirizzo 1";
$lang['ClientContacts.contact_info.field_address2'] = "Indirizzo 2";
$lang['ClientContacts.contact_info.field_city'] = "Città";
$lang['ClientContacts.contact_info.field_country'] = "Paese";
$lang['ClientContacts.contact_info.field_state'] = "Provincia";
$lang['ClientContacts.contact_info.field_zip'] = "Zip / Codice postale";
$lang['ClientContacts.contact_info.field_email'] = "E-mail";
$lang['ClientContacts.phone_numbers.heading_phone'] = "Numeri di telefono";
$lang['ClientContacts.phone_numbers.field_phonetype'] = "Tipo";
$lang['ClientContacts.phone_numbers.field_phonelocation'] = "Posizione";
$lang['ClientContacts.phone_numbers.field_phonenumber'] = "Numero";
$lang['ClientContacts.phone_numbers.text_remove'] = "Rimuovi";
$lang['ClientContacts.index.no_results'] = "Non hai contatti. Per aggiungere il tuo primo contatto, fai clic sul pulsante Aggiungi contatto sopra.";
$lang['ClientContacts.!info.no_contacts'] = "Al momento non hai contatti, aggiungi il tuo primo contatto qui sotto.";
$lang['ClientContacts.contact_info.text_select_contact'] = "Puoi selezionare un contatto esistente per precompilare questo modulo.";
$lang['ClientContacts.phone_numbers.field_phoneoptions'] = "Opzioni";
$lang['ClientContacts.phone_numbers.categorylink_number'] = "Aggiungi aggiuntivo";
$lang['ClientContacts.add.heading_contact'] = "Informazioni di contatto";
$lang['ClientContacts.add.heading_authentication'] = "Autenticazione";
$lang['ClientContacts.add.field_enable_login'] = "Abilita accesso";
$lang['ClientContacts.add.field_username'] = "Nome utente";
$lang['ClientContacts.add.field_new_password'] = "Nuova Password";
$lang['ClientContacts.add.field_confirm_password'] = "Conferma password";
$lang['ClientContacts.add.heading_permissions'] = "Autorizzazioni";
$lang['ClientContacts.edit.heading_contact'] = "Informazioni sui contatti";
$lang['ClientContacts.edit.heading_authentication'] = "Autenticazione";
$lang['ClientContacts.edit.field_enable_login'] = "Abilita accesso";
$lang['ClientContacts.edit.field_username'] = "Nome utente";
$lang['ClientContacts.edit.field_new_password'] = "nuova password";
$lang['ClientContacts.edit.field_confirm_password'] = "Conferma password";
$lang['ClientContacts.edit.heading_permissions'] = "Autorizzazioni";
$lang['ClientContacts.tooltip.client_invoices'] = "Visualizza le fatture sulla dashboard, nonché eventuali avvisi di promemoria di pagamento.";
$lang['ClientContacts.tooltip.client_services'] = "Visualizza i servizi sulla dashboard e consenti la loro gestione.";
$lang['ClientContacts.tooltip.client_transactions'] = "Visualizza le transazioni sulla dashboard.";
$lang['ClientContacts.tooltip.client_contacts'] = "Consenti la gestione dei contatti.";
$lang['ClientContacts.tooltip.client_accounts'] = "Consentire la gestione degli account di pagamento.";
$lang['ClientContacts.tooltip._invoice_delivery'] = "Consentire la visualizzazione e la modifica del metodo di consegna della fattura.";
$lang['ClientContacts.tooltip._credits'] = "View the Google Translation";
$lang['ClientContacts.contact_info.field_title'] = "Titolo";
$lang['ClientContacts.tooltip.client_emails'] = "Visualizza un elenco della cronologia delle e-mail.";
$lang['ClientContacts.!info.unverified_email'] = "L'indirizzo email associato a questo contatto non è stato verificato. Un'e-mail di verifica è stata inviata a %1\$s."; // %1$s is the email address to be verified
$lang['ClientContacts.!info.unverified_email_button'] = "Invia nuovamente email di verifica";
$lang['ClientContacts.navigation.nav_contacts'] = "Contatti";
$lang['ClientContacts.navigation.nav_contacts_add'] = "Aggiungi contatto";
$lang['ClientContacts.navigation.nav_return'] = "Ritorna alla dashboard";
?>