<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientVerify.!success.email_verified'] = "Il tuo indirizzo email è stato verificato con successo.";
$lang['ClientVerify.!success.email_sent'] = "Un'e-mail di verifica è stata inviata a %1\$s."; // %1$s is the email address to be verified
$lang['ClientVerify.!error.invalid_token'] = "Il token fornito non è valido o è scaduto.";
?>