<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Clients.!error.client_group_id.exists'] = "ID gruppo client non valido.";
$lang['Clients.!error.client_id.exists'] = "ID cliente non valido.";
$lang['Clients.!error.account_id.exists'] = "ID account non valido.";
$lang['Clients.!error.type.exists'] = "Tipo non valido.";
$lang['Clients.!error.id_format.empty'] = "Nessun formato ID impostato per i client.";
$lang['Clients.!error.id_format.length'] = "Il formato dell'ID per i client non può superare i 64 caratteri.";
$lang['Clients.!error.id_value.valid'] = "Impossibile determinare il valore dell'ID client.";
$lang['Clients.!error.user_id.exists'] = "ID utente non valido.";
$lang['Clients.!error.user_id.unique'] = "L'ID utente client %1\$s è già in uso."; // %1$s is the client user ID number
$lang['Clients.!error.status.format'] = "Stato non valido.";
$lang['Clients.!error.name.empty'] = "Si prega di inserire un nome.";
$lang['Clients.!error.is_lang.format'] = "is_lang deve essere un numero.";
$lang['Clients.!error.type.format'] = "Tipo non valido.";
$lang['Clients.!error.show_client.format'] = "Mostra client deve essere un numero.";
$lang['Clients.!error.encrypted.format'] = "Crittografato deve essere un numero.";
$lang['Clients.!error.staff_id.exists'] = "ID del personale non valido.";
$lang['Clients.!error.title.empty'] = "Si prega di inserire un titolo.";
$lang['Clients.!error.note_id.exists'] = "ID nota non valido.";
$lang['Clients.!error.stickied.format'] = "Sticky deve essere un numero.";
$lang['Clients.!error.stickied.length'] = "La lunghezza dello sticky non può superare 1 carattere.";
$lang['Clients.getCustomFieldTypes.textbox'] = "Casella di testo";
$lang['Clients.getCustomFieldTypes.checkbox'] = "Casella di controllo";
$lang['Clients.getCustomFieldTypes.dropdown'] = "Cadere in picchiata";
$lang['Clients.getCustomFieldTypes.textarea'] = "Area di testo";
$lang['Clients.getStatusTypes.active'] = "Attivo";
$lang['Clients.getStatusTypes.inactive'] = "Inattivo";
$lang['Clients.getStatusTypes.fraud'] = "Frode";
$lang['Clients.customfield.cf2'] = "Campo personalizzato";
$lang['Clients.!error.autodebit.format'] = "Valore addebito non valido";
$lang['Clients.!error.inv_address_to.exists'] = "Si prega di specificare un contatto valido per inviare le fatture.";
$lang['Clients.!error.default_currency.valid'] = "Valuta non valida.";
$lang['Clients.!error.default_currency.editable'] = "La valuta potrebbe non essere aggiornata.";
$lang['Clients.!error.inv_method.valid'] = "Metodo di consegna della fattura non valido.";
$lang['Clients.!error.inv_method.editable'] = "Il metodo di consegna della fattura potrebbe non essere aggiornato.";
$lang['Clients.!error.language.valid'] = "Lingua non valida.";
$lang['Clients.!error.language.editable'] = "La lingua potrebbe non essere aggiornata.";
$lang['Clients.!error.values.format'] = "I valori sono in un formato non valido.";
$lang['Clients.!error.client_field_id.exists'] = "ID campo personalizzato non valido.";
$lang['Clients.!error.client_field_id.matches'] = "Il campo personalizzato non è valido.";
$lang['Clients.!error.package_ids.exists'] = "Almeno uno dei pacchetti forniti non esiste.";
$lang['Clients.!error.client_id.deleteable'] = "Il cliente non può essere eliminato mentre esistono fatture aperte, fatture ricorrenti o servizi attivi/sospesi. Si prega di annullare eventuali fatture aperte, eliminare eventuali fatture ricorrenti e annullare eventuali servizi attivi/sospesi prima di procedere.";
$lang['Clients.!error.regex.valid'] = "L'espressione regolare non è valida.";
$lang['Clients.!error.read_only.format'] = "La sola lettura deve essere un numero.";
$lang['Clients.!error.read_only.length'] = "La lunghezza di sola lettura non può superare 1 carattere.";
$lang['Clients.!error.value.required'] = "%1\$s è in un formato non valido."; // %1$s is the name of the custom field
$lang['Clients.!error.value.valid'] = "%1\$s è impostato su un valore non valido."; // %1$s is the name of the custom field
$lang['Clients.!error.is_lang.length'] = "is_lang non può superare 1 carattere di lunghezza.";
$lang['Clients.!error.show_client.length'] = "Il client Show non può superare 1 carattere di lunghezza.";
$lang['Clients.!error.encrypted.length'] = "La lunghezza crittografata non può superare 1 carattere.";
$lang['Clients.setDebitAccountFailure.note_title'] = "Addebito automatico disabilitato per il conto di pagamento.";
$lang['Clients.setDebitAccountFailure.note_body'] = "Il conto di pagamento %1\$s che termina con x%2\$s è stato disattivato perché ha superato il numero massimo di tentativi di rifiuto."; // %1$s is the payment account type, %2$s is the last four of the payment account
$lang['Clients.!error.receive_email_marketing.valid'] = "A Google translation is currently unavailable.";
$lang['Clients.!error.default.valid'] = "Il valore predefinito non è valido.";
$lang['Clients.!error.title.length'] = "La lunghezza del titolo non può superare i 255 caratteri.";
$lang['Clients.!error.settings[tax_id].valid'] = "Si prega di specificare un codice fiscale/IVA valido.";
?>