<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientPay.!success.payment_processed'] = "Il pagamento per %1\$s è stato elaborato correttamente. Numero di transazione: %2\$s"; // %1$s is the payment amount, %2$s is the transaction number
$lang['ClientPay.!error.invalid_amount'] = "Gli altri importi di pagamento potrebbero non essere negativi.";
$lang['ClientPay.!error.payment_amounts'] = "Seleziona le fatture da pagare o inserisci un altro importo di pagamento.";
$lang['ClientPay.index.page_title'] = "Cliente %1\$s Paga"; // %1$s is the client ID
$lang['ClientPay.index.boxtitle_pay'] = "Fare un pagamento";
$lang['ClientPay.index.field_submit'] = "Continua";
$lang['ClientPay.multipleinvoices.text_amount'] = "Somma da pagare";
$lang['ClientPay.multipleinvoices.text_due'] = "Importo dovuto";
$lang['ClientPay.multipleinvoices.text_invoice'] = "Fattura #";
$lang['ClientPay.multipleinvoices.text_datedue'] = "Data di scadenza";
$lang['ClientPay.multipleinvoices.no_results'] = "Non ci sono fatture in questa valuta.";
$lang['ClientPay.received.page_title'] = "Pagamento cliente %1\$s ricevuto"; // %1$s is the client ID
$lang['ClientPay.received.boxtitle_received'] = "Grazie!";
$lang['ClientPay.received.statement'] = "Il tuo pagamento è in fase di elaborazione.";
$lang['ClientPay.setcontactview.text_none'] = "Nessuno";
$lang['ClientPay.index.field_credit'] = "Altro importo di pagamento";
$lang['ClientPay.method.page_title'] = "Vliente %1\$s Metodo Pagamento"; // %1$s is the client ID
$lang['ClientPay.method.boxtitle_method'] = "Fare un pagamento";
$lang['ClientPay.method.field_useaccount'] = "Utilizza il conto di pagamento";
$lang['ClientPay.method.field_newdetails'] = "Nuovi dettagli di pagamento";
$lang['ClientPay.method.field_paymentaccount'] = "%1\$s %2\$s - %3\$s x%4\$s"; // %1$s is the account first name, %2$s is the account last name, %3$s is the account type (card type or bank account type), %4$s is the last 4 of the account
$lang['ClientPay.method.field_paymentaccount_cc'] = "Conti di carte di credito";
$lang['ClientPay.method.field_paymentaccount_autodebit'] = "(Addebito automatico) %1\$s %2\$s - %3\$s x%4\$s"; // %1$s is the account first name, %2$s is the account last name, %3$s is the account type (card type or bank account type), %4$s is the last 4 of the account
$lang['ClientPay.method.field_paymentaccount_ach'] = "Conti ACH";
$lang['ClientPay.method.field_submit'] = "Rivedi e conferma";
$lang['ClientPay.confirm.page_title'] = "Il cliente %1\$s conferma il pagamento"; // %1$s is the client ID
$lang['ClientPay.confirm.boxtitle_confirm'] = "Conferma il pagamento";
$lang['ClientPay.confirm.payment_details'] = "Dettagli del pagamento";
$lang['ClientPay.confirm.account_exp'] = "scade %1\$s"; // %1$s is the date the credit card expires
$lang['ClientPay.confirm.total'] = "Totale:";
$lang['ClientPay.confirm.field_submit'] = "Inviare pagamento";
$lang['ClientPay.confirm.field_edit'] = "Modifica pagamento";
$lang['ClientPay.confirm.description_invoice'] = "Fattura n.%1\$s"; // %1$s is the invoice number
$lang['ClientPay.confirm.description_invoice_separator'] = ",";
$lang['ClientPay.confirm.description_invoice_number'] = "#%1\$s"; // %1$s is the invoice number
$lang['ClientPay.confirm.description_credit'] = "Credito di pagamento";
$lang['ClientPay.!error.invalid_details'] = "Seleziona un'opzione di pagamento.";
$lang['ClientPay.method.heading_other_payment_options'] = "Altre opzioni di pagamento";
$lang['ClientPay.method.heading_payment_options'] = "Opzioni di pagamento";
$lang['ClientPay.method.no_options'] = "

Non ci sono opzioni di pagamento disponibili.
";
$lang['ClientPay.!success.credit_full_processed'] = "I crediti disponibili sono stati applicati.";
$lang['ClientPay.!success.credit_partial_processed'] = "I crediti disponibili sono stati applicati, ma esiste ancora un saldo. Si prega di completare questa transazione pagando il resto di seguito.";
$lang['ClientPay.method.field_apply_credit'] = "Applica credito (%1\$s disponibile)"; // %1$s is the amount of available credit that may be used
$lang['ClientPay.method.field_credit_submit'] = "Applica credito e continua";
$lang['ClientPay.multipleinvoices.text_edit_amounts'] = "Effettua invece il pagamento parziale";
$lang['ClientPay.method.heading_invoice'] = "Fattura n.%1\$s"; // %1$s is the invoice ID code
$lang['ClientPay.method.invoice_description'] = "Descrizione";
$lang['ClientPay.method.invoice_quantity'] = "Quantità";
$lang['ClientPay.method.invoice_amount'] = "Quantità";
$lang['ClientPay.!error.invoice_voided'] = "Questa fattura è stata annullata e non può essere pagata.";
$lang['ClientPay.received.transaction_id'] = "ID della transazione";
$lang['ClientPay.received.amount'] = "Quantità";
$lang['ClientPay.received.invoices'] = "Fattura #";
$lang['ClientPay.!success.invoice_paid'] = "Questa fattura è stata precedentemente pagata.";
$lang['ClientPay.confirm.account_info_type'] = "%1\$s"; // %1$s is the account type (Credit Card or ACH)
$lang['ClientPay.confirm.account_info'] = "%1\$s (%2\$s) che termina con %3\$s"; // %1$s is the account type (Credit Card or ACH), %2$s is the type (Savings, Checking, MasterCard, etc.) and %3$s is the last 4 digits of the account
$lang['ClientPay.!info.unverified_email'] = "È stato inviato un collegamento all'indirizzo email fornito. Fai clic sul collegamento nell'e-mail per verificare il tuo indirizzo e-mail prima di procedere con il pagamento.";
$lang['ClientPay.!info.unverified_email_button'] = "Invia nuovamente email di verifica";
$lang['ClientPay.received.text_try_again'] = "Riprova";
$lang['ClientPay.!info.ach_verification'] = "Devi verificare questo account prima di poterlo utilizzare per effettuare un pagamento.";
$lang['ClientPay.!info.ach_verification_redirect'] = "Devi verificare questo account prima di poterlo utilizzare per effettuare un pagamento. Questo processo ti reindirizzerà dalla pagina corrente.";
$lang['ClientPay.!error.payment_authorize'] = "Non è stato possibile autorizzare il pagamento per il conto di pagamento selezionato. Seleziona un account diverso o riprova.";
?>