<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientDialog.confirm.text_yes'] = "SÌ";
$lang['ClientDialog.confirm.text_no'] = "NO";
$lang['ClientDialog.password.title'] = "Genera password";
$lang['ClientDialog.password.field_modal_password'] = "Parola d'ordine";
$lang['ClientDialog.password.field_modal_password_copied'] = "Ho copiato questa password in un posto sicuro";
$lang['ClientDialog.password.btn_generate'] = "Genera";
$lang['ClientDialog.password.btn_cancel'] = "Annulla";
$lang['ClientDialog.password.btn_use_password'] = "Usa password";
?>