<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientTransactions.index.page_title'] = "transazioni cliente #%1\$s"; // %1$s is the client ID number
$lang['ClientTransactions.index.boxtitle_transactions'] = "Transazioni";
$lang['ClientTransactions.index.category_approved'] = "Approvato";
$lang['ClientTransactions.index.category_declined'] = "Rifiutato";
$lang['ClientTransactions.index.heading_type'] = "Tipo";
$lang['ClientTransactions.index.heading_amount'] = "Quantità";
$lang['ClientTransactions.index.heading_credited'] = "Accreditato";
$lang['ClientTransactions.index.heading_applied'] = "Applicato";
$lang['ClientTransactions.index.heading_number'] = "Numero";
$lang['ClientTransactions.index.heading_date'] = "Data";
$lang['ClientTransactions.index.no_results'] = "Non hai transazioni %1\$s."; // %1$s is the language for the transaction category type (e.g. Approved, Declined)
$lang['ClientTransactions.applied.heading_invoice'] = "Fattura";
$lang['ClientTransactions.applied.heading_amount'] = "Quantità";
$lang['ClientTransactions.applied.heading_appliedon'] = "Applicato";
$lang['ClientTransactions.applied.no_results'] = "Questa transazione non è stata applicata ad alcuna fattura.";
$lang['ClientTransactions.index.category_pending'] = "In attesa di";
?>