<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientQuotations.!error.password_mismatch'] = "La password non corrisponde alla password di accesso.";
$lang['ClientQuotations.!success.approved_quotation'] = "Il preventivo è stato approvato con successo.";
$lang['ClientQuotations.index.page_title'] = "Cliente #%1\$s Citazioni"; // %1$s is the client ID number
$lang['ClientQuotations.index.category_pending'] = "In attesa di";
$lang['ClientQuotations.index.category_approved'] = "Approvato";
$lang['ClientQuotations.index.category_expired'] = "Scaduto";
$lang['ClientQuotations.index.boxtitle_quotations'] = "Citazioni";
$lang['ClientQuotations.index.heading_quotation'] = "Quotazione #";
$lang['ClientQuotations.index.heading_title'] = "Titolo";
$lang['ClientQuotations.index.heading_subtotal'] = "totale parziale";
$lang['ClientQuotations.index.heading_total'] = "Quantità";
$lang['ClientQuotations.index.heading_date_created'] = "data di creazione";
$lang['ClientQuotations.index.heading_date_expires'] = "La data scade";
$lang['ClientQuotations.index.heading_options'] = "Opzioni";
$lang['ClientQuotations.index.option_view'] = "Visualizzazione";
$lang['ClientQuotations.index.option_approve'] = "Approvare";
$lang['ClientQuotations.index.no_results'] = "Non hai virgolette %1\$s."; // %1$s is the language for the quotation category type
$lang['ClientQuotations.approve.heading_approve'] = "Approvare";
$lang['ClientQuotations.approve.field_password'] = "Accedi Password per approvare";
$lang['ClientQuotations.approve.field_cancel'] = "Annulla, non approvare";
$lang['ClientQuotations.approve.field_submit'] = "Approvare";
$lang['ClientQuotations.invoices.heading_invoice'] = "Fattura #";
$lang['ClientQuotations.invoices.heading_amount'] = "Quantità";
$lang['ClientQuotations.invoices.heading_paid'] = "Pagato";
$lang['ClientQuotations.invoices.heading_date_billed'] = "Data di fatturazione";
$lang['ClientQuotations.invoices.no_results'] = "A questo preventivo non sono associate fatture.";
?>