<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientInvoices.index.page_title'] = "Cliente n. %1\$s fatture"; // %1$s is the client ID number
$lang['ClientInvoices.index.category_open'] = "Aprire";
$lang['ClientInvoices.index.category_closed'] = "Chiuso";
$lang['ClientInvoices.index.categorylink_make_payment'] = "Fare un pagamento";
$lang['ClientInvoices.index.boxtitle_invoices'] = "Fatture";
$lang['ClientInvoices.index.heading_invoice'] = "Fattura #";
$lang['ClientInvoices.index.heading_amount'] = "Quantità";
$lang['ClientInvoices.index.heading_paid'] = "Pagato";
$lang['ClientInvoices.index.heading_due'] = "Dovuto";
$lang['ClientInvoices.index.heading_dateclosed'] = "Data di chiusura";
$lang['ClientInvoices.index.heading_datebilled'] = "Data di fatturazione";
$lang['ClientInvoices.index.heading_datedue'] = "Data di scadenza";
$lang['ClientInvoices.index.heading_options'] = "Opzioni";
$lang['ClientInvoices.index.option_view'] = "Visualizzazione";
$lang['ClientInvoices.index.option_pay'] = "Paga";
$lang['ClientInvoices.index.no_results'] = "Non hai fatture %1\$s."; // %1$s is the language for the invoice category type (e.g. Open, Closed)
$lang['ClientInvoices.applied.heading_paymenttype'] = "Tipo pagamento";
$lang['ClientInvoices.applied.heading_amount'] = "Quantità";
$lang['ClientInvoices.applied.heading_applied'] = "Applicato";
$lang['ClientInvoices.applied.heading_appliedon'] = "Applicato";
$lang['ClientInvoices.applied.no_results'] = "A questa fattura non sono applicate transazioni.";
?>