<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Companies.!error.company_id.in_use'] = "Quella società è attualmente in uso e non può essere eliminata.";
$lang['Companies.!error.company_id.exists'] = "ID società non valido.";
$lang['Companies.!error.name.empty'] = "Inserisci un nome.";
$lang['Companies.!error.name.length'] = "La lunghezza del nome non può superare i 64 caratteri.";
$lang['Companies.!error.hostname.unique'] = "Quel nome host è già stato preso da un'altra società.";
$lang['Companies.!error.phone.length'] = "La lunghezza del telefono non può superare i 64 caratteri.";
$lang['Companies.!error.fax.length'] = "La lunghezza del fax non può superare i 64 caratteri.";
$lang['Companies.!error.private_key_passphrase.valid'] = "La passphrase inserita non è valida.";
$lang['Companies.!error.inv_format.format'] = "Il formato della fattura non può entrare in conflitto con il formato della bozza della fattura.";
$lang['Companies.!error.inv_format.contains'] = "Formato fattura deve contenere {num}.";
$lang['Companies.!error.inv_draft_format.format'] = "Il formato bozza fattura non può essere in conflitto con il formato fattura.";
$lang['Companies.!error.inv_draft_format.contains'] = "Il formato della bozza della fattura deve contenere {num}.";
$lang['Companies.!error.inv_start.number'] = "Il valore iniziale della fattura deve essere un numero.";
$lang['Companies.!error.inv_increment.number'] = "Il valore dell'incremento della fattura deve essere un numero.";
$lang['Companies.!error.inv_pad_size.number'] = "La dimensione del riempimento della fattura deve essere un numero.";
$lang['Companies.!error.inv_pad_str.length'] = "Il carattere di riempimento della fattura deve essere un singolo carattere.";
$lang['Companies.!error.hostname.valid'] = "Inserisci un nome host valido.";
$lang['Companies.!error.hostname.length'] = "Il nome host non può superare i 255 caratteri di lunghezza.";
$lang['Companies.!error.quota.allowed'] = "Non sono disponibili licenze aziendali aggiuntive. Accedi al tuo account su account.blesta.com o contatta l'ufficio vendite per acquistare licenze aziendali aggiuntive.";
$lang['Companies.!error.inv_proforma_format.format'] = "Il formato della fattura pro forma non può entrare in conflitto con il formato della fattura bozza.";
$lang['Companies.!error.inv_proforma_format.contains'] = "Il formato della fattura pro forma deve contenere {num}.";
$lang['Companies.!error.inv_proforma_start.number'] = "Il valore iniziale della fattura pro forma deve essere un numero.";
?>