<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Contacts.!error.client_id.exists'] = "ID cliente non valido.";
$lang['Contacts.!error.user_id.exists'] = "ID utente non valido.";
$lang['Contacts.!error.contact_type.format'] = "Tipo di contatto non valido.";
$lang['Contacts.!error.contact_type_id.format'] = "ID tipo contatto non valido";
$lang['Contacts.!error.first_name.empty'] = "Inserisci un nome.";
$lang['Contacts.!error.last_name.empty'] = "Inserisci un cognome.";
$lang['Contacts.!error.title.length'] = "La lunghezza del titolo non può superare i 64 caratteri.";
$lang['Contacts.!error.company.length'] = "La lunghezza dell'azienda non può superare i 128 caratteri.";
$lang['Contacts.!error.email.format'] = "Indirizzo email non valido.";
$lang['Contacts.!error.state.length'] = "La lunghezza dello stato non può superare i 3 caratteri.";
$lang['Contacts.!error.state.country_exists'] = "Seleziona il Paese che corrisponde allo stato selezionato.";
$lang['Contacts.!error.country.length'] = "La lunghezza del Paese non deve superare i 3 caratteri.";
$lang['Contacts.!error.contact_id.exists'] = "ID contatto non valido.";
$lang['Contacts.!error.number.empty'] = "Inserisci un numero di contatto.";
$lang['Contacts.!error.type.format'] = "Invalid type.";
$lang['Contacts.!error.location.format'] = "Posizione non valida.";
$lang['Contacts.!error.id.exists'] = "ID del numero di contatto non valido.";
$lang['Contacts.!error.company_id.format'] = "ID azienda non valido.";
$lang['Contacts.!error.name.empty'] = "Inserisci un nome.";
$lang['Contacts.!error.is_lang.format'] = "is_lang deve essere un numero.";
$lang['Contacts.!error.is_lang.length'] = "La lunghezza di is_lang non può superare 1 carattere.";
$lang['Contacts.!error.contact_type_id.exists'] = "Non valido ID del tipo di contatto.";
$lang['Contacts.getcontacttypes.primary'] = "Primario";
$lang['Contacts.getcontacttypes.billing'] = "Fatturazione";
$lang['Contacts.getcontacttypes.other'] = "Altro";
$lang['Contacts.getnumbertypes.phone'] = "Telefono";
$lang['Contacts.getnumbertypes.fax'] = "Fax";
$lang['Contacts.getnumberlocations.home'] = "Casa";
$lang['Contacts.getnumberlocations.work'] = "Lavoro";
$lang['Contacts.getnumberlocations.mobile'] = "Mobile";
$lang['Contacts.!error.contact_type.inv_address_to'] = "Le fatture sono impostate per essere indirizzate a questo contatto e devono essere modificate prima di aggiornare questo contatto.";
$lang['Contacts.!error.contact_id.primary'] = "Il contatto primario del cliente non può essere eliminato";
$lang['Contacts.getPermissionOptions.client_invoices'] = "Fatture";
$lang['Contacts.getPermissionOptions.client_services'] = "Servizi";
$lang['Contacts.getPermissionOptions.client_transactions'] = "Transazioni";
$lang['Contacts.getPermissionOptions.client_contacts'] = "Contatti";
$lang['Contacts.getPermissionOptions.client_accounts'] = "Conti di pagamento";
$lang['Contacts.getPermissionOptions._invoice_delivery'] = "Consegna della fattura";
$lang['Contacts.getPermissionOptions._credits'] = "Crediti";
$lang['Contacts.!error.title.empty'] = "Inserisci un titolo.";
$lang['Contacts.!error.company.empty'] = "Inserisci un'azienda.";
$lang['Contacts.!error.city.empty'] = "Inserisci una città.";
$lang['Contacts.!error.state.empty'] = "Please select a state/province.";
$lang['Contacts.!error.country.empty'] = "Per favore seleziona un paese.";
$lang['Contacts.!error.address1.empty'] = "Inserisci la prima riga del tuo indirizzo.";
$lang['Contacts.!error.address2.empty'] = "Inserisci la seconda riga del tuo indirizzo.";
$lang['Contacts.!error.zip.empty'] = "Inserisci un zip/codice postale.";
$lang['Contacts.!error.email.unique'] = "L'indirizzo email è già occupato.";
$lang['Contacts.getPermissionOptions.client_emails'] = "Cronologia e-mail";
$lang['Contacts.!error.phone.required'] = "Inserisci almeno un numero di telefono.";
$lang['Contacts.!error.fax.required'] = "Inserisci almeno un numero di fax.";
?>