<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Countries.!error.alpha2.format'] = "Il codice paese Alpha2 deve essere composto da 2 caratteri alfabetici.";
$lang['Countries.!error.alpha2.in_use'] = "Codice del paese Alfa2, %1\$s, è già in uso."; // %1$s is the alpha2 country code
$lang['Countries.!error.alpha2.exists'] = "Codice alfa2 non valido.";
$lang['Countries.!error.alpha3.format'] = "Il codice paese Alpha3 deve contenere 3 caratteri alfabetici.";
$lang['Countries.!error.alpha3.in_use'] = "codice paese Alpha3, %1\$s è già stato assegnato."; // %1$s is the alpha3 country code
$lang['Countries.!error.name.format'] = "Inserisci un nome.";
?>