<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CouponTerms.!error.coupon_id.exists'] = "Il coupon indicato non esiste.";
$lang['CouponTerms.!error.term.format'] = "Inserisci un termine valido per ciascun periodo.";
$lang['CouponTerms.!error.period.valid'] = "Inserisci un periodo valido.";
$lang['CouponTerms.!error.term_id.exists'] = "La durata della cedola specificata non esiste.";
$lang['CouponTerms.getperiods.day'] = "Giorno";
$lang['CouponTerms.getperiods.week'] = "Settimana";
$lang['CouponTerms.getperiods.month'] = "Mese";
$lang['CouponTerms.getperiods.year'] = "Anno";
$lang['CouponTerms.getperiods.onetime'] = "Una volta";
?>