<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Emails.!error.company_id.exists'] = "ID azienda non valido.";
$lang['Emails.!error.email_signature_id.in_use'] = "Quella firma e-mail è attualmente in uso e non può essere eliminata.";
$lang['Emails.!error.name.empty'] = "Inserisci un nome per la firma.";
$lang['Emails.!error.text.empty'] = "Si prega di inserire una firma di testo normale.";
$lang['Emails.!error.email_signature_id.exists'] = "ID firma email non valido.";
$lang['Emails.!error.email_group_id.exists'] = "ID gruppo email non valido.";
$lang['Emails.!error.lang.empty'] = "Inserisci una lingua.";
$lang['Emails.!error.lang.length'] = "La lunghezza della lingua non può superare i 5 caratteri.";
$lang['Emails.!error.from.format'] = "Per favore inseirsci un indirizzo valido";
$lang['Emails.!error.from_name.empty'] = "Inserisci il nome del mittente.";
$lang['Emails.!error.subject.empty'] = "Per favore inserisci un oggetto.";
$lang['Emails.!error.status.format'] = "Stato non valido.";
$lang['Emails.!error.email_id.exists'] = "ID e-mail non valido.";
$lang['Emails.!error.company_id.unique'] = "L'ID del gruppo e-mail e l'ID dell'azienda per la lingua specificata sono già in uso.";
$lang['Emails.getStatusTypes.active'] = "NO";
$lang['Emails.getStatusTypes.inactive'] = "SÌ";
$lang['Emails.!error.action.exists'] = "L'azione specificata è un'azione del gruppo email non valida.";
$lang['Emails.!error.to_addresses.format'] = "Almeno uno degli indirizzi e-mail forniti non è un indirizzo email valido.";
$lang['Emails.!error.cc_addresses.format'] = "Almeno uno degli indirizzi CC forniti non è un indirizzo email valido.";
$lang['Emails.!error.bcc_addresses.format'] = "Almeno uno degli indirizzi e-mail BCC forniti non è un indirizzo e-mail valido.";
$lang['Emails.!error.attachments.exist'] = "Almeno uno degli allegati non esiste sul file system.";
$lang['Emails.!error.email.failed_to_send'] = "L'invio dell'e-mail non è riuscito a causa di un problema di configurazione.";
$lang['Emails.!error.reply_to.format'] = "Inserisci un indirizzo di risposta valido.";
$lang['Emails.!error.html.parse'] = "Errore di analisi del modello: %1\$s"; // %1$s is the parse error
$lang['Emails.!error.text.parse'] = "Errore di analisi del modello: %1\$s"; // %1$s is the parse error
$lang['Emails.!error.include_attachments'] = "Se includere gli allegati deve essere impostato su 0 o 1.";
$lang['Emails.!error.to_addresses.empty'] = "È necessario fornire almeno un indirizzo A.";
?>