<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Encryption.!error.current_passphrase.empty'] = "Inserisci la passphrase della chiave privata corrente.";
$lang['Encryption.!error.current_passphrase.matches'] = "La parola chiave della chiave privata corrente non è valida.";
$lang['Encryption.!error.private_key_passphrase.empty'] = "Inserisci una nuova passphrase della chiave privata.";
$lang['Encryption.!error.confirm_new_passphrase.matches'] = "La nuova passphrase non corrisponde.";
$lang['Encryption.!error.agree.empty'] = "Devi accettare di aver salvato questa passphrase in un luogo sicuro.";
?>