<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['GatewayManager.!error.company_id.valid'] = "L'ID azienda non è valido.";
$lang['GatewayManager.!error.class.valid'] = "La classe non è valida.";
$lang['GatewayManager.!error.name.valid'] = "Il nome non è valido.";
$lang['GatewayManager.!error.version.valid'] = "La versione non è valida.";
$lang['GatewayManager.!error.currencies[].exists'] = "Almeno una valuta non è accettata da questo gateway.";
$lang['GatewayManager.!error.currencies[].in_use'] = "Almeno una valuta è attualmente utilizzata da un altro gateway.";
?>