<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['GatewayPayments.!error.gateway.exists'] = "Il gateway non esiste o non è abilitato.";
$lang['GatewayPayments.!error.transaction_id.exists'] = "Impossibile trovare la transazione per quel cliente.";
$lang['GatewayPayments.!error.account_id.exists'] = "Impossibile trovare il conto di pagamento per quel cliente.";
$lang['GatewayPayments.!error.contact_id.exists'] = "Impossibile trovare il contatto per quel cliente.";
$lang['GatewayPayments.!error.type.valid'] = "Il tipo di pagamento non è supportato per questo gateway.";
$lang['GatewayPayments.!error.type.instance'] = "Il gateway non supporta i pagamenti in questo modo.";
$lang['GatewayPayments.!error.reference_id.store'] = "Il gateway di pagamento non è riuscito a memorizzare il conto di pagamento.";
$lang['GatewayPayments.!error.reference_id.update'] = "Il gateway di pagamento non è riuscito ad aggiornare il conto di pagamento.";
$lang['GatewayPayments.!error.reference_id.remove'] = "Il gateway di pagamento non è riuscito a rimuovere il conto di pagamento.";
$lang['GatewayPayments.!error.response_status'] = "Il gateway di pagamento ha restituito una risposta inaspettata.";
$lang['GatewayPayments.!error.gateway.declined'] = "Il pagamento è stato rifiutato.";
$lang['GatewayPayments.!error.gateway.error'] = "Il gateway di pagamento ha restituito un errore durante l'elaborazione della richiesta.";
$lang['GatewayPayments.!error.amount.valid'] = "L'importo deve essere maggiore di zero.";
$lang['GatewayPayments.!error.reference_id.verify'] = "Il gateway di pagamento non è riuscito a verificare il conto di pagamento.";
$lang['GatewayPayments.!error.type.invalid'] = "Il tipo di account deve essere \"ach\" o \"cc\".";
?>