<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Invoices.getPricingPeriods.day'] = "Giorno";
$lang['Invoices.getPricingPeriods.week'] = "Settimana";
$lang['Invoices.getPricingPeriods.month'] = "Mese";
$lang['Invoices.getPricingPeriods.year'] = "Anno";
$lang['Invoices.getDeliveryMethods.email'] = "E-mail";
$lang['Invoices.getDeliveryMethods.paper'] = "Carta";
$lang['Invoices.getDeliveryMethods.interfax'] = "InterFax";
$lang['Invoices.getDeliveryMethods.postalmethods'] = "Metodi postali";
$lang['Invoices.!error.invoice_id.exists'] = "ID fattura non valido.";
$lang['Invoices.!error.invoice_recur_id.exists'] = "ID fattura ricorrente non valido.";
$lang['Invoices.!error.method.exists'] = "Devi impostare almeno un metodo di consegna.";
$lang['Invoices.!error.delivery.empty'] = "Si prega di inserire un metodo di invio della fattura.";
$lang['Invoices.!error.delivery.length'] = "La lunghezza del metodo di consegna della fattura non può superare i 32 caratteri.";
$lang['Invoices.!error.id_format.empty'] = "Nessun formato ID impostato per le fatture.";
$lang['Invoices.!error.id_format.length'] = "Il formato ID delle fatture non può superare i 64 caratteri.";
$lang['Invoices.!error.id_value.valid'] = "Impossibile determinare il valore dell'ID fattura.";
$lang['Invoices.!error.id.amount_applied'] = "Le righe, la valuta e lo stato della fattura potrebbero non essere aggiornati perché a questa fattura è già stato applicato un importo.";
$lang['Invoices.!error.client_id.exists'] = "ID cliente non valido.";
$lang['Invoices.!error.date_billed.format'] = "La data di fatturazione è in un formato di data non valido.";
$lang['Invoices.!error.date_due.format'] = "La data di scadenza è in un formato data non valido.";
$lang['Invoices.!error.date_closed.format'] = "La data di chiusura è in un formato data non valido.";
$lang['Invoices.!error.date_autodebit.format'] = "La data di scadenza è in un formato data non valido.";
$lang['Invoices.!error.status.format'] = "Stato non valido.";
$lang['Invoices.!error.currency.length'] = "Il codice della valuta deve essere di 3 caratteri.";
$lang['Invoices.!error.delivery.exists'] = "Il metodo di consegna dato non esiste.";
$lang['Invoices.!error.term.format'] = "Il termine dovrebbe essere un numero.";
$lang['Invoices.!error.term.bounds'] = "Il termine dovrebbe essere tra 1 e 65535";
$lang['Invoices.!error.period.format'] = "Il periodo è invalido.";
$lang['Invoices.!error.duration.format'] = "La durata non é valida";
$lang['Invoices.!error.date_renews.format'] = "La data di rinnovo ricorrente della fattura deve essere un formato di data valido.";
$lang['Invoices.!error.date_last_renewed.format'] = "L'ultima data di rinnovo ricorrente della fattura deve essere un formato di data valido.";
$lang['Invoices.!error.invoice_id.draft'] = "La fattura fornita non è una bozza di fattura e pertanto non può essere eliminata.";
$lang['Invoices.!error.lines[][id].exists'] = "ID elemento non valido.";
$lang['Invoices.!error.lines[][service_id].exists'] = "ID servizio non valido.";
$lang['Invoices.!error.lines[][description].empty'] = "Inserisci una descrizione dell'elemento pubblicitario.";
$lang['Invoices.!error.lines[][qty].format'] = "La quantità dev'essere un numero.";
$lang['Invoices.!error.lines[][qty].minimum'] = "Inserisci una quantità pari o superiore a 1.";
$lang['Invoices.!error.lines[][amount].format'] = "Il costo unitario deve essere un numero.";
$lang['Invoices.!error.lines[][tax].format'] = "L'imposta sull'elemento pubblicitario deve essere \"vero\" o \"falso\"";
$lang['Invoices.!line_item.service_cancel_fee_description'] = "%1\$s - %2\$s Commissione di cancellazione"; // %1$s is the name of the package, %2$s is the name of the service
$lang['Invoices.!line_item.service_setup_fee_description'] = "%1\$s - %2\$s Costi di attivazione"; // %1$s is the name of the package, %2$s is the name of the service
$lang['Invoices.!line_item.coupon_line_item_description_amount'] = "Coupon %1\$s"; // %1$s is the coupon code
$lang['Invoices.!line_item.coupon_line_item_description_percent'] = "Coupon %1\$s - %2\$s%%"; // %1$s is the coupon code, %2$s is the coupon discount percentage, the two percent symbols (%%) must both be used together to display a single percent symbol
$lang['Invoices.!error.date_due.after_billed'] = "La data di scadenza deve essere uguale o successiva alla data di fatturazione.";
$lang['Invoices.!line_item.recurring_renew_description'] = "%1\$s (%2\$s - %3\$s)"; // %1$s is the line item description, %2$s is the invoice's renew date, %3$s is the invoice's next renew date
$lang['Invoices.status.active'] = "Attivo";
$lang['Invoices.status.draft'] = "Bozza";
$lang['Invoices.status.void'] = "Vuoto";
$lang['Invoices.!line_item.service_renew_description'] = "%5\$s%1\$s - %2\$s (%3\$s - %4\$s)"; // %1$s is the name of the package, %2$s is the name of the service, %3$s is the service's renew date, %4$s is the service's next renew date, %5$s is the addon identifier set only for addon services
$lang['Invoices.!line_item.service_prorated_upgrade_description'] = "Upgrade proporzionale da %1\$s a %2\$s - %3\$s (%4\$s - %5\$s)"; // %1$s is the current package name, %2$s is the new package name, %3$s is the service name, %4$s is the current date, %5$s is the service's next renew date
$lang['Invoices.status.proforma'] = "Pro forma";
$lang['Invoices.types.standard'] = "Standard";
$lang['Invoices.types.proforma'] = "Pro-Forma";
$lang['Invoices.!line_item.service_option_renew_description'] = "? %1\$s - %2\$s"; // %1$s is the package option label, %2$s is the service option name
$lang['Invoices.!line_item.service_option_setup_fee_description'] = "↳ %1\$s - %2\$s Commissione di installazione"; // %1$s is the package option label, %2$s is the service option name
$lang['Invoices.!line_item.service_prorated_upgrade_description_onetime'] = "Upgrade proporzionale da %1\$s a %2\$s - %3\$s"; // %1$s is the current package name, %2$s is the new package name, %3$s is the service name
$lang['Invoices.!line_item.prorated_credit'] = "Credito proporzionale";
$lang['Invoices.!note_private.service_cancel_date'] = "Servizio #%1\$s annullato %2\$s."; // %1$s is the service ID, %2$s is the formatted service cancellation date and time
$lang['Invoices.!note_private.removed_lines'] = "Elementi pubblicitari rimossi:";
$lang['Invoices.!note_private.line_item'] = "- %1\$s @ %2\$s: %3\$s"; // %1$s is the line item quantity, %2$s is the unit price, %3$s is the line item description
$lang['Invoices.!error.autodebit.valid'] = "Seleziona se consentire o meno l'addebito automatico per questa fattura.";
$lang['Invoices.!error.invoice_add.failed'] = "Impossibile creare questa fattura. Per favore riprova.";
$lang['Invoices.!line_item.service_option_prorated_upgrade'] = "↳ Aggiornamento proporzionale di %1\$s da %2\$s a %3\$s"; // %1$s is the service option label name, %2$s is the current service option value, %3$s is the new service option value
$lang['Invoices.!line_item.service_option_prorated_upgrade_date'] = "↳ Aggiornamento proporzionale di %1\$s da %2\$s a %3\$s (%4\$s - %5\$s)"; // %1$s is the service option label name, %2$s is the current service option value, %3$s is the new service option value, %4$s is the current date, %5$s is the service's next renew date
$lang['Invoices.!line_item.service_option_prorated_upgrade_onetime'] = "↳ Aggiornamento proporzionale di %1\$s da %2\$s a %3\$s"; // %1$s is the service option label name, %2$s is the current service option value, %3$s is the new service option value
$lang['Invoices.!line_item.service_option_prorated_upgrade_text'] = "↳ Aggiornamento proporzionale di %1\$s"; // %1$s is the service option label name
$lang['Invoices.!line_item.service_option_prorated_upgrade_text_date'] = "↳ Aggiornamento proporzionale di %1\$s (%2\$s - %3\$s)"; // %1$s is the service option label name, %2$s is the current date, %3$s is the service's next renew date
$lang['Invoices.!line_item.service_option_prorated_upgrade_text_onetime'] = "↳ Aggiornamento proporzionale di %1\$s"; // %1$s is the service option label name
$lang['Invoices.!line_item.service_option_prorated_upgrade_qty'] = "↳ Aggiornamento proporzionale di %1\$s da %2\$sx %3\$s a %4\$sx %5\$s"; // %1$s is the service option label name, %2$s is the old service option quantity, %3$s is the current service option value, %4$s is the new service option quantity, %5$s is the new service option value
$lang['Invoices.!line_item.service_option_prorated_upgrade_qty_date'] = "↳ Aggiornamento proporzionale di %1\$s da %2\$sx %3\$s a %4\$sx %5\$s (%6\$s - %7\$s)"; // %1$s is the service option label name, %2$s is the old service option quantity, %3$s is the current service option value, %4$s is the new service option quantity, %5$s is the new service option value, %6$s is the current date, %7$s is the service's next renew date
$lang['Invoices.!line_item.service_option_prorated_upgrade_qty_onetime'] = "↳ Aggiornamento proporzionale di %1\$s da %2\$s x %3\$s a %4\$s x %5\$s"; // %1$s is the service option label name, %2$s is the old service option quantity, %3$s is the current service option value, %4$s is the new service option quantity, %5$s is the new service option value
$lang['Invoices.!line_item.service_option_prorated_addition'] = "↳ Aggiunta proporzionale di %1\$s %2\$s"; // %1$s is the service option label name, %2$s is the service option value
$lang['Invoices.!line_item.service_option_prorated_addition_date'] = "↳ Aggiunta proporzionale di %1\$s %2\$s (%3\$s - %4\$s)"; // %1$s is the service option label name, %2$s is the service option value, %3$s is the current date, %4$s is the service's next renew date
$lang['Invoices.!line_item.service_option_prorated_addition_onetime'] = "↳ Aggiunta proporzionale di %1\$s %2\$s"; // %1$s is the service option label name, %2$s is the service option value
$lang['Invoices.!line_item.service_option_prorated_addition_text'] = "↳ Aggiunta proporzionale di %1\$s"; // %1$s is the service option label name
$lang['Invoices.!line_item.service_option_prorated_addition_text_date'] = "↳ Aggiunta proporzionale di %1\$s (%2\$s - %3\$s)"; // %1$s is the service option label name, %2$s is the current date, %3$s is the service's next renew date
$lang['Invoices.!line_item.service_option_prorated_addition_text_onetime'] = "↳ Aggiunta proporzionale di %1\$s"; // %1$s is the service option label name
$lang['Invoices.!line_item.service_option_prorated_addition_qty'] = "↳ Aggiunta proporzionale di %1\$s %2\$sx %3\$s"; // %1$s is the service option label name, %2$s is the service option quantity, %3$s is the service option value
$lang['Invoices.!line_item.service_option_prorated_addition_qty_date'] = "↳ Somma proporzionale di %1\$s %2\$s x %3\$s (%4\$s - %5\$s)"; // %1$s is the service option label name, %2$s is the service option quantity, %3$s is the service option value, %4$s is the current date, %5$s is the service's next renew date
$lang['Invoices.!line_item.service_option_prorated_addition_qty_onetime'] = "↳ Aggiunta proporzionale di %1\$s %2\$sx %3\$s"; // %1$s is the service option label name, %2$s is the service option quantity, %3$s is the service option value
$lang['Invoices.cache_methods.none'] = "Nessuno";
$lang['Invoices.cache_methods.json'] = "JSON";
$lang['Invoices.cache_methods.json_pdf'] = "View the Google Translation";
$lang['Invoices.!error.domain_renew.failed'] = "I domini possono essere rinnovati solo per un massimo di 10 anni.";
?>