<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Languages.!error.code.valid'] = "La lingua predefinita \"en_us\" non può essere rimossa.";
$lang['Languages.!error.code.format'] = "Il codice non è formattato correttamente.";
$lang['Languages.!error.code.unique'] = "Il codice lingua esiste già per questa azienda.";
$lang['Languages.!error.company_id.format'] = "L'ID dell'azienda sembra non essere valido.";
$lang['Languages.!error.name.format'] = "Il nome della lingua non può essere vuoto.";
?>