<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MerchantGateway.!error.card_number_invalid'] = "Il numero della carta non è valido.";
$lang['MerchantGateway.!error.card_expired'] = "La carta è scaduta.";
$lang['MerchantGateway.!error.routing_number_invalid'] = "Il numero di routing non è valido.";
$lang['MerchantGateway.!error.account_number_invalid'] = "Il numero di conto non è valido.";
$lang['MerchantGateway.!error.duplicate_transaction'] = "È stata rilevata una transazione duplicata.";
$lang['MerchantGateway.!error.card_not_accepted'] = "Non si accettano carte di questo tipo.";
$lang['MerchantGateway.!error.invalid_security_code'] = "Il codice di sicurezza sembra non essere valido.";
$lang['MerchantGateway.!error.address_verification_failed'] = "L'indirizzo sembra non essere valido.";
$lang['MerchantGateway.!error.transaction_not_found'] = "La transazione non è valida o non è più disponibile per l'elaborazione di tale azione.";
$lang['MerchantGateway.!error.general'] = "Si è verificato un errore durante l'elaborazione della richiesta con il gateway.";
$lang['MerchantGateway.!error.unsupported'] = "Il gateway non supporta tale azione.";
?>