<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MessengerManager.!error.company_id.valid'] = "L'ID azienda non è valido.";
$lang['MessengerManager.!error.dir.valid'] = "La directory non è valida.";
$lang['MessengerManager.!error.name.valid'] = "Il nome non è valido.";
$lang['MessengerManager.!error.version.valid'] = "La versione non è valida.";
$lang['MessengerManager.!error.messenger.missing'] = "Nessun messenger è configurato per il tipo indicato.";
?>