<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ModuleTypes.!error.name.valid'] = "Il nome non è valido.";
$lang['ModuleTypes.!error.type_id.valid'] = "L'ID del tipo di modulo non è valido.";
?>