<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ModuleManager.!error.company_id.valid'] = "L'ID azienda non è valido.";
$lang['ModuleManager.!error.class.valid'] = "La classe non è valida.";
$lang['ModuleManager.!error.name.valid'] = "Il nome non è valido.";
$lang['ModuleManager.!error.version.valid'] = "La versione non è valida.";
$lang['ModuleManager.!error.name.empty'] = "È necessario specificare un nome per il gruppo.";
$lang['ModuleManager.!error.module_rows[].valid'] = "Una o più righe specificate non appartengono a questo modulo.";
$lang['ModuleManager.!error.module_row_id.assigned_package'] = "La riga non può essere eliminata perché appartiene a uno o più pacchetti.";
$lang['ModuleManager.!error.module_group_id.assigned_package'] = "Il gruppo non può essere eliminato perché appartiene a uno o più pacchetti.";
$lang['ModuleManager.!error.module_row_id.assigned_service'] = "La riga non può essere eliminata perché appartiene a uno o più servizi.";
$lang['ModuleManager.!error.module_id.assigned_package'] = "Il modulo non può essere disinstallato perché è utilizzato da uno o più pacchetti attivi.";
$lang['ModuleManager.!error.module_id.assigned_service'] = "Il modulo non può essere disinstallato perché utilizzato da uno o più servizi non annullati.";
$lang['ModuleManager.!error.force_limits.valid'] = "Se applicare limiti rigidi deve essere impostato su 0 o 1.";
$lang['ModuleManager.!error.type_id.valid'] = "L'ID del tipo non è valido.";
?>