<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['NonmerchantGateway.!error.invalid'] = "È stata ricevuta una risposta di pagamento non valida o non riconosciuta.";
$lang['NonmerchantGateway.!error.transaction_not_found'] = "La transazione non è valida o non è più disponibile per l'elaborazione di questa azione.";
$lang['NonmerchantGateway.!error.unsupported'] = "Il gateway non supporta tale azione.";
$lang['NonmerchantGateway.!error.general'] = "Si è verificato un errore durante l'elaborazione della richiesta con il gateway.";
?>