<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PackageGroups.!error.type.format'] = "Tipo di gruppo non valido.";
$lang['PackageGroups.!error.company_id.exists'] = "ID azienda non valido.";
$lang['PackageGroups.!error.parents.format'] = "Almeno un ID gruppo principale fornito è un gruppo non standard non disponibile per l'utilizzo come principale.";
$lang['PackageGroups.gettypes.standard'] = "Standard";
$lang['PackageGroups.gettypes.addon'] = "Aggiungi su";
$lang['PackageGroups.!error.allow_upgrades.format'] = "Se i pacchetti all'interno di questo gruppo possono essere aggiornati/declassati deve essere impostato su 1 o 0.";
$lang['PackageGroups.!error.names.format'] = "I nomi dei gruppi di pacchetti sono in un formato non valido.";
$lang['PackageGroups.!error.names.empty_name'] = "Specificare il nome di un gruppo di pacchetti per ciascuna lingua.";
$lang['PackageGroups.!error.names.empty_lang'] = "Specificare un codice lingua del gruppo di pacchetti per ciascun nome.";
$lang['PackageGroups.!error.descriptions.format'] = "Le descrizioni del gruppo di pacchetti sono in un formato non valido.";
$lang['PackageGroups.!error.descriptions.empty_lang'] = "Specificare un codice lingua del gruppo di pacchetti per ciascuna descrizione.";
$lang['PackageGroups.!error.hidden.format'] = "Se questo gruppo deve essere nascosto nell'interfaccia deve essere impostato su 1 o 0.";
?>