<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PackageOptionGroups.!error.company_id.exists'] = "Si prega di specificare un ID aziendale valido.";
$lang['PackageOptionGroups.!error.name.empty'] = "Si prega di specificare un nome di gruppo.";
$lang['PackageOptionGroups.!error.name.length'] = "Il nome del gruppo non può superare i 128 caratteri di lunghezza.";
$lang['PackageOptionGroups.!error.group_id.exists'] = "ID gruppo opzioni pacchetto non valido.";
$lang['PackageOptionGroups.!error.hide_options.valid'] = "Se nascondere le opzioni deve essere impostato su 0 o 1.";
$lang['PackageOptionGroups.!error.hidden.valid'] = "Se nascondere questo gruppo di opzioni deve essere impostato su 0 o 1.";
?>