<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PackageOptionConditionSets.!error.id.exists'] = "L'ID della condizione dell'opzione specificata non esiste";
$lang['PackageOptionConditionSets.!error.option_group_id.exists'] = "L'ID del gruppo di opzioni specificato non esiste";
$lang['PackageOptionConditionSets.!error.option_id.exists'] = "L'ID opzione specificata non esiste";
$lang['PackageOptionConditionSets.!error.option_value_ids.exists'] = "Uno degli ID del valore dell'opzione specificato non esiste";
?>