<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ReportManager.!error.type.valid'] = "Si prega di selezionare un tipo di report valido.";
$lang['ReportManager.!error.format.valid'] = "Seleziona un formato di rapporto valido.";
$lang['ReportManager.!error.temp_dir.writable'] = "La directory temporanea non è scrivibile oppure non è stato possibile scrivervi il report.";
$lang['ReportManager.getformats.csv'] = "CSV";
$lang['ReportManager.!error.name.valid'] = "Il rapporto deve avere un nome.";
$lang['ReportManager.!error.query.empty'] = "La relazione deve avere una query";
$lang['ReportManager.!error.query.valid'] = "È consentita una sola query e deve essere una query SELECT.";
$lang['ReportManager.!error.date_created.format'] = "La data di creazione è un formato non valido.";
$lang['ReportManager.reportfieldtypes.text'] = "Testo";
$lang['ReportManager.reportfieldtypes.select'] = "Selezionare";
$lang['ReportManager.reportfieldtypes.date'] = "Data";
$lang['ReportManager.reportrequiredtypes.no'] = "No";
$lang['ReportManager.reportrequiredtypes.yes'] = "Si";
$lang['ReportManager.reportrequiredtypes.custom'] = "Regex personalizzata";
$lang['ReportManager.getformats.json'] = "JSON";
?>