<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ServiceInvoices.!error.service_id.exists'] = "ID servizio non valido.";
$lang['ServiceInvoices.!error.invoice_id.exists'] = "ID fattura non valido.";
$lang['ServiceInvoices.!error.failed_attempts.format'] = "I tentativi falliti devono essere un numero.";
$lang['ServiceInvoices.!error.maximum_attempts.format'] = "Il numero massimo di tentativi deve essere un numero.";
?>