<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['StaffGroups.!error.staff_group_id.exists'] = "ID gruppo personale non valido.";
$lang['StaffGroups.!error.company_id.exists'] = "Identificativo azienda non valido";
$lang['StaffGroups.!error.name.empty'] = "Inserisci un nome.";
$lang['StaffGroups.!error.name.length'] = "La lunghezza del nome non può superare i 64 caratteri.";
$lang['StaffGroups.!error.no_company_id.exists'] = "Impossibile accedere, non assegnato a nessuna azienda.
";
$lang['StaffGroups.!error.num_staff.zero'] = "Non è stato possibile eliminare il gruppo staff, %1\$s perché attualmente gli sono assegnati membri dello staff."; // %1$s is the staff group name
$lang['StaffGroups.permission_group.clients'] = "Clienti";
$lang['StaffGroups.permission_group.billing'] = "Fatturazione";
$lang['StaffGroups.permission_group.packages'] = "Pacchetti";
$lang['StaffGroups.permission_group.tools'] = "Utensili";
$lang['StaffGroups.permission_group.search'] = "Ricerca";
$lang['StaffGroups.permission_group.settings'] = "Impostazioni";
$lang['StaffGroups.permissions.admin_clients_view'] = "Visualizza cliente";
$lang['StaffGroups.permissions.admin_clients_add'] = "Aggiungi cliente";
$lang['StaffGroups.permissions.admin_clients_edit'] = "Modifica cliente";
$lang['StaffGroups.permissions.admin_clients_invoices'] = "Elenca fatture";
$lang['StaffGroups.permissions.admin_clients_viewinvoice'] = "guarda fattura";
$lang['StaffGroups.permissions.admin_clients_createinvoice'] = "Crea fattura";
$lang['StaffGroups.permissions.admin_clients_editinvoice'] = "Modifica fattura";
$lang['StaffGroups.permissions.admin_clients_editrecurinvoice'] = "Modifica fattura ricorrente";
$lang['StaffGroups.permissions.admin_clients_deleteinvoice'] = "Elimina fattura";
$lang['StaffGroups.permissions.admin_clients_transactions'] = "Lista transazioni";
$lang['StaffGroups.permissions.admin_clients_edittransaction'] = "Modifica transazione";
$lang['StaffGroups.permissions.admin_clients_services'] = "Elenco servizi";
$lang['StaffGroups.permissions.admin_clients_addservice'] = "Aggiungi servizio";
$lang['StaffGroups.permissions.admin_clients_editservice'] = "Modifica Servizio";
$lang['StaffGroups.permissions.admin_clients_deleteservice'] = "Elimina servizio";
$lang['StaffGroups.permissions.admin_clients_addcontact'] = "Aggiungi contatto";
$lang['StaffGroups.permissions.admin_clients_editcontact'] = "Consenti la visualizzazione dei crediti dell'account.";
$lang['StaffGroups.permissions.admin_clients_deletecontact'] = "Elimina contatto";
$lang['StaffGroups.permissions.admin_clients_quickupdate'] = "Aggiornamento rapido";
$lang['StaffGroups.permissions.admin_clients_accounts'] = "Visualizza conti di pagamento";
$lang['StaffGroups.permissions.admin_clients_addccaccount'] = "Aggiungi conto di pagamento con carta di credito";
$lang['StaffGroups.permissions.admin_clients_addachaccount'] = "Aggiungi conto di pagamento ACH";
$lang['StaffGroups.permissions.admin_clients_editccaccount'] = "Modifica conto di pagamento con carta di credito";
$lang['StaffGroups.permissions.admin_clients_editachaccount'] = "Modifica account di pagamento ACH";
$lang['StaffGroups.permissions.admin_clients_deleteccaccount'] = "Elimina il conto di pagamento con carta di credito";
$lang['StaffGroups.permissions.admin_clients_deleteachaccount'] = "Elimina il conto di pagamento ACH";
$lang['StaffGroups.permissions.admin_clients_notes'] = "Visualizza note";
$lang['StaffGroups.permissions.admin_clients_addnote'] = "Aggiungi Nota";
$lang['StaffGroups.permissions.admin_clients_editnote'] = "Modifica Nota";
$lang['StaffGroups.permissions.admin_clients_deletenote'] = "Elimina nota";
$lang['StaffGroups.permissions.admin_clients_packages'] = "Imposta pacchetti";
$lang['StaffGroups.permissions.admin_clients_email'] = "Cliente di posta elettronica";
$lang['StaffGroups.permissions.admin_clients_emails'] = "Visualizza registro posta";
$lang['StaffGroups.permissions.admin_clients_merge'] = "Unisci cliente";
$lang['StaffGroups.permissions.admin_clients_delete'] = "Elimina cliente";
$lang['StaffGroups.permissions.admin_billing_invoices'] = "Elenca fatture";
$lang['StaffGroups.permissions.admin_billing_services'] = "Elenco dei servizi
";
$lang['StaffGroups.permissions.admin_billing_transactions'] = "Elenca transazioni";
$lang['StaffGroups.permissions.admin_tools_convert_currency'] = "Converti valuta";
$lang['StaffGroups.permissions.admin_tools_logs'] = "Registri";
$lang['StaffGroups.permissions.admin_packages_add'] = "Aggiungi pacchetto";
$lang['StaffGroups.permissions.admin_packages_edit'] = "Modifica pacchetto";
$lang['StaffGroups.permissions.admin_packages_groups'] = "Visualizza gruppi di pacchetti";
$lang['StaffGroups.permissions.admin_settings_company'] = "Impostazioni aziendali";
$lang['StaffGroups.permissions.admin_company_general_localization'] = "Localizzazione";
$lang['StaffGroups.permissions.admin_company_general_international'] = "Internazionalizzazione";
$lang['StaffGroups.permissions.admin_company_general_themes'] = "Temi";
$lang['StaffGroups.permissions.admin_company_general_encryption'] = "Crittografia";
$lang['StaffGroups.permissions.admin_company_billing_invoices'] = "Opzioni di fatturazione e addebito";
$lang['StaffGroups.permissions.admin_company_billing_customization'] = "Personalizzazione Fattura";
$lang['StaffGroups.permissions.admin_company_billing_deliverymethods'] = "Consegna della fattura";
$lang['StaffGroups.permissions.admin_company_billing_coupons'] = "Buoni";
$lang['StaffGroups.permissions.admin_company_modules'] = "Moduli";
$lang['StaffGroups.permissions.admin_company_modules_manage'] = "Gestisci modulo";
$lang['StaffGroups.permissions.admin_company_modules_install'] = "Installa il modulo";
$lang['StaffGroups.permissions.admin_company_modules_uninstall'] = "Disinstalla il modulo";
$lang['StaffGroups.permissions.admin_company_modules_upgrade'] = "Modulo di aggiornamento";
$lang['StaffGroups.permissions.admin_company_gateways'] = "Gateway di pagamento";
$lang['StaffGroups.permissions.admin_company_gateways_manage'] = "Gestisci gateway";
$lang['StaffGroups.permissions.admin_company_gateways_install'] = "Installa Gateway";
$lang['StaffGroups.permissions.admin_company_gateways_uninstall'] = "Disinstalla Gateway";
$lang['StaffGroups.permissions.admin_company_gateways_upgrade'] = "Aggiorna Gateway";
$lang['StaffGroups.permissions.admin_company_emails_mail'] = "Impostazioni di posta";
$lang['StaffGroups.permissions.admin_company_emails_templates'] = "Modelli di e-mail";
$lang['StaffGroups.permissions.admin_company_emails_signatures'] = "Firme e-mail";
$lang['StaffGroups.permissions.admin_company_plugins'] = "Plugin";
$lang['StaffGroups.permissions.admin_company_plugins_manage'] = "Gestisci plugin";
$lang['StaffGroups.permissions.admin_company_plugins_install'] = "Installa il plugin";
$lang['StaffGroups.permissions.admin_company_plugins_uninstall'] = "Disinstallare il plug-in";
$lang['StaffGroups.permissions.admin_company_plugins_upgrade'] = "Aggiorna plugin";
$lang['StaffGroups.permissions.admin_company_groups'] = "Gruppi di clienti";
$lang['StaffGroups.permissions.admin_settings_system'] = "Impostazioni di sistema";
$lang['StaffGroups.permissions.admin_system_general_basic'] = "Configurazione di base";
$lang['StaffGroups.permissions.admin_system_general_geoip'] = "Impostazioni GeoIP";
$lang['StaffGroups.permissions.admin_system_general_maintenance'] = "Manutenzione";
$lang['StaffGroups.permissions.admin_system_general_license'] = "Chiave di licenza";
$lang['StaffGroups.permissions.admin_system_automation'] = "

Automazione
";
$lang['StaffGroups.permissions.admin_system_companies'] = "Aziende";
$lang['StaffGroups.permissions.admin_system_staff_manage'] = "Gestisci il personale";
$lang['StaffGroups.permissions.admin_system_staff_groups'] = "Gruppi del personale";
$lang['StaffGroups.permissions.admin_system_api'] = "Accesso API";
$lang['StaffGroups.permissions.admin_system_upgrade'] = "Opzioni di aggiornamento";
$lang['StaffGroups.permissions.admin_system_help'] = "Aiuto";
$lang['StaffGroups.permissions.admin_system_marketplace'] = "Mercato";
$lang['StaffGroups.!error.action.exists'] = "L'azione del gruppo email %1\$s non esiste."; // %1$s is the name of the email group action
$lang['StaffGroups.permission_group.home'] = "Casa";
$lang['StaffGroups.permissions.admin_main_calendar'] = "Calendario";
$lang['StaffGroups.permissions.admin_clients_loginasclient'] = "Login come Cliente";
$lang['StaffGroups.permissions.admin_billing_printqueue'] = "Coda di stampa";
$lang['StaffGroups.permissions.admin_billing_batch'] = "Lotto";
$lang['StaffGroups.permissions.admin_company_general_contacttypes'] = "Tipi di contatto";
$lang['StaffGroups.permissions.admin_company_general_addcontacttype'] = "Aggiungi Tipo Contatto";
$lang['StaffGroups.permissions.admin_company_general_editcontacttype'] = "Modifica Tipo contatto";
$lang['StaffGroups.permissions.admin_company_general_deletecontacttype'] = "Elimina tipo di contatto";
$lang['StaffGroups.permissions.admin_company_general_installlanguage'] = "Installa lingua";
$lang['StaffGroups.permissions.admin_company_general_uninstalllanguage'] = "Disinstallare la lingua";
$lang['StaffGroups.permissions.admin_company_billing_acceptedtypes'] = "Tipi di pagamento accettati";
$lang['StaffGroups.permissions.admin_system_general_paymenttypes'] = "Tipo pagamento";
$lang['StaffGroups.permissions.admin_system_general_addtype'] = "Aggiungi tipo di pagamento";
$lang['StaffGroups.permissions.admin_system_general_edittype'] = "Modifica tipo di pagamento";
$lang['StaffGroups.permissions.admin_system_general_deletetype'] = "Elimina tipo di pagamento";
$lang['StaffGroups.permissions.admin_packages_addgroup'] = "Aggiungere gruppo";
$lang['StaffGroups.permissions.admin_packages_editgroup'] = "Modifica gruppo";
$lang['StaffGroups.permissions.admin_packages_deletegroup'] = "Elimina gruppo";
$lang['StaffGroups.permissions.admin_package_options'] = "Opzioni configurabili";
$lang['StaffGroups.permissions.admin_company_general_addtheme'] = "Aggiungi temi";
$lang['StaffGroups.permissions.admin_company_general_edittheme'] = "Modifica Tema";
$lang['StaffGroups.permissions.admin_company_general_deletetheme'] = "Elimina tema";
$lang['StaffGroups.permissions.admin_company_billing_addcoupon'] = "Aggiungi coupon";
$lang['StaffGroups.permissions.admin_company_billing_editcoupon'] = "Modifica Coupon";
$lang['StaffGroups.permissions.admin_company_billing_deletecoupon'] = "Cancella Coupon";
$lang['StaffGroups.permissions.admin_company_lookandfeel'] = "Guardare e sentire";
$lang['StaffGroups.permissions.admin_company_themes'] = "Temi";
$lang['StaffGroups.permissions.admin_company_taxes'] = "Le tasse";
$lang['StaffGroups.permissions.admin_company_emails_edittemplate'] = "Modifica modello di posta elettronica";
$lang['StaffGroups.permissions.admin_company_emails_addsignature'] = "Aggiungi firma e-mail";
$lang['StaffGroups.permissions.admin_company_emails_editsignature'] = "Modifica firma e-mail";
$lang['StaffGroups.permissions.admin_company_emails_deletesignature'] = "Elimina firma e-mail";
$lang['StaffGroups.permissions.admin_company_currencies'] = "Valute";
$lang['StaffGroups.permissions.admin_system_backup'] = "Backup";
$lang['StaffGroups.permissions.admin_system_staff_add'] = "Aggiungi personale";
$lang['StaffGroups.permissions.admin_system_staff_edit'] = "Modifica personale";
$lang['StaffGroups.permissions.admin_system_staff_status'] = "Stato del personale";
$lang['StaffGroups.permissions.admin_system_staff_addgroup'] = "Aggiungi gruppo di personale";
$lang['StaffGroups.permissions.admin_system_staff_editgroup'] = "Modifica il gruppo del personale";
$lang['StaffGroups.permissions.admin_system_staff_deletegroup'] = "Elimina gruppo di personale";
$lang['StaffGroups.permissions.admin_company_automation'] = "Automazione";
$lang['StaffGroups.permissions.admin_clients_recordpayment'] = "Registra il pagamento";
$lang['StaffGroups.permissions.admin_clients_makepayment'] = "Fare un pagamento";
$lang['StaffGroups.!error.session_lock.valid'] = "Valore non valido specificato per il blocco della sessione.";
$lang['StaffGroups.permissions.admin_clients_service'] = "

Visualizza i totali del servizio
";
$lang['StaffGroups.permissions.admin_reports'] = "Rapporti";
$lang['StaffGroups.permissions.admin_reports_customize'] = "Personalizza i rapporti";
$lang['StaffGroups.permissions.admin_packages_delete'] = "Elimina pacchetto";
$lang['StaffGroups.permissions.admin_company_general_marketing'] = "Marketing";
$lang['StaffGroups.permissions.admin_company_clientoptions_general'] = "Impostazioni generali del cliente";
$lang['StaffGroups.permissions.admin_company_clientoptions_requiredfields'] = "Campi cliente obbligatori";
$lang['StaffGroups.permissions.admin_company_clientoptions_customfields'] = "Campi personalizzati del cliente";
$lang['StaffGroups.permissions.admin_clients_passwordreset'] = "Invia reimpostazione password";
$lang['StaffGroups.permissions.admin_company_plugins_settings'] = "Impostazioni del plugin";
$lang['StaffGroups.permissions.admin_company_billing_notices'] = "Avvisi";
$lang['StaffGroups.permissions.admin_company_general_smartsearch'] = "Ricerca intelligente";
$lang['StaffGroups.permissions.admin_company_general_humanverification'] = "verifica umana";
$lang['StaffGroups.permissions.admin_company_billing_latefees'] = "View the Google Translation";
$lang['StaffGroups.permissions.admin_company_lookandfeel_layout'] = "Disposizione";
$lang['StaffGroups.permissions.admin_company_emails_mailtest'] = "Prova delle impostazioni di posta";
$lang['StaffGroups.permissions.admin_company_messengers'] = "Messaggeri";
$lang['StaffGroups.permissions.admin_company_messengers_manage'] = "Gestisci Messenger";
$lang['StaffGroups.permissions.admin_company_messengers_install'] = "Installa Messenger";
$lang['StaffGroups.permissions.admin_company_messengers_uninstall'] = "Disinstallare Messenger";
$lang['StaffGroups.permissions.admin_company_messengers_upgrade'] = "Aggiorna Messenger";
$lang['StaffGroups.permissions.admin_company_messengers_configuration'] = "Configurazione di Messenger";
$lang['StaffGroups.permissions.admin_company_messengers_templates'] = "Modelli di messaggistica";
$lang['StaffGroups.permissions.admin_company_messengers_edittemplate'] = "Modifica modelli di Messenger";
$lang['StaffGroups.permissions.admin_tools_utilities'] = "Utilità";
$lang['StaffGroups.permissions.admin_company_lookandfeel_actions'] = "Azioni personalizzate";
$lang['StaffGroups.permissions.admin_company_lookandfeel_addaction'] = "Aggiungi azione";
$lang['StaffGroups.permissions.admin_company_lookandfeel_editaction'] = "Modifica azione";
$lang['StaffGroups.permissions.admin_company_lookandfeel_customize'] = "personalizzare";
$lang['StaffGroups.permissions.admin_company_lookandfeel_navigation'] = "Navigazione";
$lang['StaffGroups.permissions.admin_company_feeds'] = "Feed di dati";
$lang['StaffGroups.permissions.admin_tools_renewals'] = "Coda di rinnovo";
?>