<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['States.!error.code.format'] = "Il codice di stato deve essere alfanumerico come definito in ISO 3166-2.";
$lang['States.!error.country_alpha2.format'] = "Paese Alpha2 deve contenere 2 caratteri alfabetici.";
$lang['States.!error.country_alpha2.in_use'] = "Il codice paese alpha2 %1\$s e il codice suddivisione %2\$s sono già in uso."; // %1$s is the alpha2 country code, %2$s is the state code
$lang['States.!error.name.format'] = "Inserisci il nome dello stato.";
?>