<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SystemRequirements.!error.php.minimum'] = "È richiesta la versione PHP %1\$s o successiva. La tua versione: %2\$s."; // %1$s is the minimum version of PHP (i.e. 5.1.3), %2$s is the current version
$lang['SystemRequirements.!warning.mcrypt.recommended'] = "L'estensione mcrypt è consigliata per prestazioni migliori.";
$lang['SystemRequirements.!warning.gmp.recommended'] = "L'estensione gmp è altamente raccomandata per prestazioni migliori.";
$lang['SystemRequirements.!warning.cache_writable.recommended'] = "Per prestazioni migliori assicurati che %1\$s sia scrivibile dal server web."; // %1$s is the absolute path to the cache directory
$lang['SystemRequirements.!warning.imap.recommended'] = "L'estensione imap è necessaria per inviare e ricevere posta tramite SMTP e IMAP.";
$lang['SystemRequirements.!warning.zlib.recommended'] = "L'utilizzo dell'estensione Zlib è vivamente raccomandato per migliorare le prestazioni";
$lang['SystemRequirements.!warning.mbstring.recommended'] = "

L'estensione mbstring è richiesta da alcune caratteristiche opzionali.
";
$lang['SystemRequirements.!warning.libxml.recommended'] = "L'estensione libxml è altamente raccomandata in quanto potrebbe essere necessaria per interfacciarsi con alcuni sistemi.";
$lang['SystemRequirements.!warning.mailparse.recommended'] = "L'estensione mailparse è necessaria per analizzare le e-mail in arrivo.";
$lang['SystemRequirements.!error.config_writable.minimum'] = "Il file di configurazione (%1\$s) e la directory (%2\$s) devono essere scrivibili dal server web."; // %1$s is the absolute path to the config file, %2$s is the absolute path to the config directory
$lang['SystemRequirements.!warning.simplexml.recommended'] = "L'estensione simplexml è altamente raccomandata in quanto potrebbe essere necessaria per interfacciarsi con alcuni sistemi.";
$lang['SystemRequirements.!warning.iconv.recommended'] = "L'estensione iconv è richiesta per la codifica e decodifica di caratteri speciali.";
$lang['SystemRequirements.!error.extension_version.minimum'] = "L'estensione '%1\$s' è obbligatoria. La tua versione: %2\$s."; // %1$s is the name of the extension required. %2$s is the current version
$lang['SystemRequirements.!info.ext-ioncube.minimum'] = "Assicurati di applicare i file di hotfix necessari sovrascrivendo i file Blesta con quelli della directory %1\$s. Altrimenti Blesta non sarà accessibile dopo l'installazione."; // %1$s is the name of the hotfix directory
$lang['SystemRequirements.!error.extension.minimum'] = "L'estensione '%1\$s' è obbligatoria."; // %1$s is the name of the extension required
$lang['SystemRequirements.!warning.gd.recommended'] = "L'estensione gd è consigliata per un migliore supporto delle immagini durante la generazione di PDF e la generazione di captcha interno.";
$lang['SystemRequirements.!warning.soap.recommended'] = "L'estensione soap è necessaria per la gestione automatica delle imposte IVA.";
$lang['SystemRequirements.!error.ext-ioncube-sourceguardian.minimum'] = "È richiesta l'estensione \"SourceGuardian\" o \"ioncube loader\".";
$lang['SystemRequirements.!info.ext-ioncube-sourceguardian.minimum'] = "È richiesta l'estensione \"SourceGuardian\" o \"ioncube loader\". Se usi SourceGuardian assicurati di applicare i file hotfix necessari sovrascrivendo i tuoi file Blesta con quelli della directory hotfix-php8. Altrimenti Blesta non sarà accessibile dopo l'installazione."; // %1$s is the name of the hotfix directory
?>