<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Taxes.!error.company_id.exists'] = "ID azienda non valido.";
$lang['Taxes.!error.level.format'] = "Il livello di imposta deve essere un numero.";
$lang['Taxes.!error.level.length'] = "La lunghezza del livello fiscale non può superare i 2 caratteri.";
$lang['Taxes.!error.name.length'] = "La lunghezza del nome fiscale non può superare i 64 caratteri.";
$lang['Taxes.!error.amount.format'] = "Importo deve essere un numero.";
$lang['Taxes.!error.type.format'] = "Valore non corretto";
$lang['Taxes.!error.status.format'] = "Stato non valido.";
$lang['Taxes.!error.tax_id.exists'] = "Codice fiscale non valido.";
$lang['Taxes.getTaxStatus.active'] = "Attivo";
$lang['Taxes.getTaxStatus.inactive'] = "Inattivo";
$lang['Taxes.getTaxTypes.inclusive'] = "Inclusivo (additivo)";
$lang['Taxes.getTaxTypes.exclusive'] = "Esclusivo";
$lang['Taxes.!error.country.valid'] = "Il paese non è un codice paese ISO 3166-1 valido.";
$lang['Taxes.!error.state.valid'] = "Lo stato non è un codice di suddivisione ISO 3166-2 valido.";
$lang['Taxes.!error.amount.positive'] = "L'importo deve essere positivo.";
$lang['Taxes.getTaxTypes.inclusive_calculated'] = "Inclusivo";
?>