<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Users.!error.username.empty'] = "Inserisci un nome utente.";
$lang['Users.!error.username.unique'] = "Quel nome utente è già stato preso.";
$lang['Users.!error.current_password.matches'] = "Password non valida.";
$lang['Users.!error.new_password.format'] = "Si prega di inserire una password di almeno 6 caratteri di lunghezza.";
$lang['Users.!error.new_password.matches'] = "The passwords do not match.";
$lang['Users.!error.two_factor_mode.format'] = "Modalità a due fattori non valida.";
$lang['Users.!error.username.auth'] = "Nessuna corrispondenza trovata per quella combinazione utente/password.";
$lang['Users.!error.otp.auth'] = "La password monouso inserita non è valida. La lunghezza massima è di 16 caratteri";
$lang['Users.!error.user_id.exists'] = "ID utente non valido.";
$lang['Users.!error.username.attempts'] = "Rilevati troppi tentativi di accesso non riusciti.";
$lang['Users.!error.clients.exist'] = "Impossibile eliminare l'utente perché è presente almeno un client assegnato all'utente.";
$lang['Users.!error.two_factor_key.format'] = "Chiave a due fattori non valida.";
$lang['Users.!error.username.company'] = "Non sei autorizzato ad accedere a questa posizione.";
?>