<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Kassacompleetideal.!error.api_key.empty'] = "Inserisci una chiave API";
$lang['Kassacompleetideal.!error.api_key.valid'] = "La chiave API non è valida";
$lang['Kassacompleetideal.name'] = "iDeal (Kassa Complete)";
$lang['Kassacompleetideal.api_key'] = "Chiave API";
$lang['Kassacompleetideal.tooltip.api_key'] = "Per utilizzare la modalità test, inserisci semplicemente una chiave API da un account di prova";
$lang['Kassacompleetideal.buildprocess.issuer_id'] = "Emittente ideale";
$lang['Kassacompleetideal.buildprocess.submit'] = "Paga con iDeal tramite Kassa Compleet";
$lang['Kassacompleetideal.description'] = "Integrazione di Kassa Compleet utilizzando il tipo di pagamento iDeal";
?>