<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Config.export.id_code'] = "Identificativo cliente";
$lang['Config.export.first_name'] = "Nome";
$lang['Config.export.last_name'] = "Cognome";
$lang['Config.export.company'] = "Azienda";
$lang['Config.export.email'] = "Email";
$lang['Config.export.date_added'] = "Data aggiunta";
$lang['Config.export.package_name'] = "Pacchetto";
$lang['Config.export.service_name'] = "Servizio";
$lang['Config.export.service_date_renews'] = "Rinnova data";
$lang['Config.export.module_name'] = "Modulo";
$lang['Config.export.module_label'] = "Riga del modulo";
?>