<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MassMailerPlugin.name'] = "Mailer di massa";
$lang['MassMailerPlugin.nav_secondary_staff.admin_main'] = "Mailer di massa";
$lang['MassMailerPlugin.permission.admin_main'] = "Elenchi di spedizioni di massa";
$lang['MassMailerPlugin.permission.admin_filter'] = "Filtri per mailing di massa";
$lang['MassMailerPlugin.permission.admin_compose'] = "Mass Mailer Componi e-mail";
$lang['MassMailerPlugin.cron.export_name'] = "Crea esportazione di posta";
$lang['MassMailerPlugin.cron.export_desc'] = "Crea un file CSV per qualsiasi lavoro di mailing di massa in attesa di esportazione.";
$lang['MassMailerPlugin.cron.mass_mail_name'] = "Invia e-mail di massa";
$lang['MassMailerPlugin.cron.mass_mail_desc'] = "Invia e-mail in modo massivo per qualsiasi lavoro di mailing in sospeso.";
$lang['MassMailerPlugin.description'] = "Invia e-mail a più client nel sistema contemporaneamente.";
?>