<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MassMailerEmails.!error.job_id.valid'] = "ID lavoro non valido.";
$lang['MassMailerEmails.!error.job_id.unique'] = "Al lavoro è già assegnata un'e-mail.";
$lang['MassMailerEmails.!error.from_name.empty'] = "Inserisci il nome del mittente.";
$lang['MassMailerEmails.!error.from_address.valid'] = "Inserisci un indirizzo e-mail valido.";
$lang['MassMailerEmails.!error.subject.empty'] = "Inserisci un oggetto.";
$lang['MassMailerEmails.!error.html.empty'] = "Inserisci il contenuto dell'email in formato HTML.";
$lang['MassMailerEmails.!error.log.valid'] = "L'opzione log deve essere impostata su 0 o 1.";
?>