<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.7.1
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['InvoiceCreation.name'] = "Creazione di fatture";
$lang['InvoiceCreation.options.field_start_date'] = "Data inizio";
$lang['InvoiceCreation.options.field_end_date'] = "Data di fine";
$lang['InvoiceCreation.options.field_status'] = "Stato";
$lang['InvoiceCreation.option.any'] = "Qualunque";
$lang['InvoiceCreation.heading.id_code'] = "Fattura #";
$lang['InvoiceCreation.heading.client_id_code'] = "Cliente #";
$lang['InvoiceCreation.heading.subtotal'] = "Subtotale";
$lang['InvoiceCreation.heading.total'] = "Totale";
$lang['InvoiceCreation.heading.paid'] = "Pagato";
$lang['InvoiceCreation.heading.currency'] = "Valuta";
$lang['InvoiceCreation.heading.status'] = "Stato";
$lang['InvoiceCreation.heading.date_billed'] = "Data di fatturazione";
$lang['InvoiceCreation.heading.date_due'] = "Data di scadenza";
$lang['InvoiceCreation.heading.date_closed'] = "Data di chiusura";
?>